### ISSUE TITLE
deprecated tsd@0.6.5

### ISSUE THREAD

**Issue by labrute** [Swiip/generator-gulp-angular#1000]
Hello,

Since few days TSD is deprecated, and replaced by Typings.
https://github.com/typings/typings

Can someone update this dependency ?
There is a migration description on the github project page from tsd to typings.

Thx

**Comment by Swiip** [comment]
We seen this, it's in the todo. Any help appreciated.

**Comment by Swiip** [comment]
Merged: https://github.com/Swiip/generator-gulp-angular/releases/tag/v1.1.0
