### ISSUE TITLE
Awesome-typescript-loader 0.14.x doesn't recompile watched files

### ISSUE THREAD

**Issue by jukka-varis** [Swiip/generator-gulp-angular#1001]
On Windows with generator 1.0.2

When using **gulp serve**, changes to typescript files are not recompiled because current default version of awesome-typescript-loader ~0.14.0 has a bug.

Awesome-typescript-loader need to be updated to 0.15.x or reverted to 0.13.x version to get gulp serve working as designed.

[More info](https://github.com/s-panferov/awesome-typescript-loader/pull/73)

**Comment by Swiip** [comment]
We have to switch to ts-loader which is better now.

**Comment by Swiip** [comment]
Released : https://github.com/Swiip/generator-gulp-angular/releases/tag/v1.1.0
