### ISSUE TITLE
How to add ui-route on existing project?

### ISSUE THREAD

**Issue by donnygunawan93** [Swiip/generator-gulp-angular#1002]
I have generate without ui-route library, and now i need to add, how to add manually?

I have to add them like usually on bower,

thats ok when serve, but when I build, then any issues templateUrl: 'app/componen/myview.html' not found.

whats wrong here?

**Comment by Swiip** [comment]
These kind of problems are usually about path matching. Check the URLs of the template that your app is asking and the one preloaded in the bundle. They have to match exactly including the first "/".

To be able to read your bundle, you can comment the uglify transform.

**Comment by donnygunawan93** [comment]
I found..., that because I was deleted , because I not want to use auto usehref before.
