### ISSUE TITLE
Okay to update dependencies?

### ISSUE THREAD

**Issue by btn0s** [Swiip/generator-gulp-angular#1014]

**Comment by Swiip** [comment]
Please put some effort when creating an issue.

**Comment by btn0s** [comment]
and effort when answering one? sorry I realize that this is not exactly what you wanted to see, but I like the set up you've built a lot and was just trying to get feedback from you on the dependency issue.

**Comment by Swiip** [comment]
Seriously, just a title which could be interpreted in an hundred ways, no description, not read the contributing docs and I'm the rude guy?
