### ISSUE TITLE
Switch from TSD to Typings

### ISSUE THREAD

**Issue by qorsmond** [Swiip/generator-gulp-angular#1015]
Hey, firstly I must say I think this is the best angular generator out there hands down. Thank you for making it available!

I am trying to switch out TSD with Typings(https://github.com/typings/typings) but are not exactly sure how to do it.

What I did for now is added the typings/browser.d.ts file as a reference to the tsd.d.ts file in .tmp and it seems to be working. But looking to improve this, any tips?

**Comment by Swiip** [comment]
Nop sorry, updating from tsd to typings is a task I have yet to do. I don't have tips on how to do it.
