### ISSUE TITLE
gulp build dont merge bower JS and CSS files

### ISSUE THREAD

**Issue by pablorsk** [Swiip/generator-gulp-angular#1017]
Hi!

If I run `gulp dist` gulp generates a index.html in dist folder. But JS and CSS files installed via bower dont concatenate into a only one file, like vendor.js or app.js.

This is my actual result:
```html
    <!-- Page Loader -->
    <div id="pageloader" page-loader></div>

    <!-- build:js(src) scripts/vendor.js -->
    <!-- bower:js -->
    <script src="../bower_components/jquery/dist/jquery.js"></script>
    <script src="../bower_components/angular/angular.js"></script>
    <script src="../bower_components/angular-animate/angular-animate.js"></script>
    <script src="../bower_components/angular-touch/angular-touch.js"></script>
    <script src="../bower_components/angular-sanitize/angular-sanitize.js"></script>
    <!-- endbower -->
    <!-- endbuild -->
```

I need another gulp task? How I need to do for concatenation and minification of JS and CSS files installed via bower?

Regards...

**Comment by igor-yamshchykov** [comment]
Hey, I think the issue is with the .bower.json of the packages that you've installed

For instance if you would like to install Socket.IO with bower you do

` $ bower install socket.io --save`

This way you'll get in bower_components/ folder socket.io/ folder, in this folder take a look at the bower.json file I bet there's no property 

```"main": "socket.io.js" ```

or something.

So the way gulp task is working, it's trying to find the  `main` property in library installed by the bower.

Surely overriding the library `bower.json` file would be a bad idea. So in your project `bower.json` file
that should be in the root of your project go ahead and add there something like this

``` 
"overrides": {
    "socket.io-client": {
      "main": [
        "./socket.io.js"
      ]
    }
  },
```

Under main you should specify path to the lib file.
After that your bower.json file will override the library bower.json prop and I guess I will be imported.
Try it on with you library, it should help, but watch out to put the correct main file path when you override the main.

Hope that helps.

**Comment by pablorsk** [comment]
Thanks a lot for your really dedicated answer.

Overrides work for another values (thanks for the tip) but with main don't. This is my bower.json

```javascript
  "overrides": {
    "bootstrap-sass": {
      "main": [
        "assets/stylesheets/_bootstrap.scss",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.eot",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.svg",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.ttf",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.woff",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.woff2"
      ]
    },
    "animate.css": {
      "main": [
        "./animate.css"
      ]
    },
    "jquery": {
        "main": [
            "dist/jquery.js"
        ]
    },
    "angular": {
        "main": [
            "./angular.js"
        ]
    }
  }
```

Then, I run `gulp build`. But I have a same result:

```html
    <!-- build:js(src) scripts/vendor.js -->
    <!-- bower:js -->
    <script src="../bower_components/jquery/dist/jquery.js"></script>
    <script src="../bower_components/angular/angular.js"></script>
    <script src="../bower_components/angular-animate/angular-animate.js"></script>
    <!-- SOME FILES MORE.... (removed for this example) -->
    <!-- endbower -->
    <!-- endbuild -->

    <!-- build:js({build/serve,build/partials}) scripts/app.js -->
    <!-- inject:js -->
    <script src="app/index.module.js"></script>
    <!-- endinject -->

    <!-- inject:partials -->
    <!-- angular templates will be automatically converted in js and inserted here -->
    <!-- endinject -->
    <!-- endbuild -->
```

Maybe I need review any library, but we are using 55+ bower components... should not, at least, concatenate some bower files?

**Comment by igor-yamshchykov** [comment]
I'm afraid that I don't know a nice solution for injecting 55 bower components, what I'm doing is I'm overriding component main right away after install. So basically one thing I might suggest is to put them once at your bower.json by hard

**Comment by pablorsk** [comment]
Thanks! I solve the problem with your help.

First, I update bower with `sudo npm install -g bower` (1.7.2 now). This version automatically fix main files (I think).
Next, we found problems with `angular-rickshaw`: `Uncaught ReferenceError: d3 is not defined`.

I solve this second problem with your tip. I put this in my bower.json:
```json
  "overrides": {
    "angular-rickshaw": {
        "dependencies": {
          "angular": "~1.2.0",
          "d3": "~3.4.3",
          "rickshaw": "~1.4.6"
        }
    }
  }
```

Thanks again!
