### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by JimTheMan** [Swiip/generator-gulp-angular#1018]
Wow, great job on this guys. I use this generator all the time. It follows all the best practices I like to use in angular. I noticed the wiki was very empty. Is that on purpose? I could put in some more explanation of what gets created if you want me to.

**Comment by Swiip** [comment]
We chose to go for md files in the repo as documentation. The wiki is not used, I could as well close it. If you want to contribute to docs, you can make a  PR
