### ISSUE TITLE
Pull request failed: continuous-integration/travis-ci/pr — The Travis CI build failed

### ISSUE THREAD

**Issue by pablorsk** [Swiip/generator-gulp-angular#1025]
Hi!

I'm trying to contribute to the project, but the [pull request](https://github.com/Swiip/generator-gulp-angular/pull/1024) fails:
```
 continuous-integration/travis-ci/pr — The Travis CI build failed
```
And I just modify a only one file (.md)

How can I fix this?

**Comment by Swiip** [comment]
Hello, it's not your fault, the master is failing right now. Sorry, with the work on FountainJS, we don't have much time for this project.

**Comment by Swiip** [comment]
Tests are fixed
