### ISSUE TITLE
bootstrap_sass_official javascript files not injected with wiredep nor build

### ISSUE THREAD

**Issue by jbaroudi** [Swiip/generator-gulp-angular#103]
Hi, i'm doing gulp wiredep, gulp build tests and bootstrap_sass_official doesn't get injected in index.html

S.O: Windows 7
choosing options: 
 -Angularjs 1.3
 -JQuery2.x
 -$http
 -ngRoute
 -Bootstrap
 -Sass (node)

if i set javascript files manually to the index then my project works (gulp serve) 

any thoughts?

**Comment by artmees** [comment]
how do I add it so that it works automatically with dist ?
using `<script src="../bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.min.js"></script>` doesn't work ?!
