### ISSUE TITLE
Support for Custom Builds of animate.css

### ISSUE THREAD

**Issue by mackelito** [Swiip/generator-gulp-angular#1033]
Animate.css is great animation framework but including all the css might be a bit much when you are only using a few of the animations.

There is already support for custom builds of animate.css and it would be super nice to see some kind of support for that :)

**Comment by Swiip** [comment]
I don't think we want to optimize our template that much. It's not supposed to be kept, just an illustration of what you can do. Most people will simply start by deleting it. So what the point of such an optimization?

**Comment by mackelito** [comment]
Just thought it would be a nice feature since animate.css is there by default.. But not a big deal :)
