### ISSUE TITLE
gulp serve:dist fails with app.js not found

### ISSUE THREAD

**Issue by geoHeil** [Swiip/generator-gulp-angular#1035]
Hi,

a regular `gulp serve` works fine. But after adding some dependencies and some code I try to use `gulp serve:dist` to preview production. The result is the following error:

app.css not found
app.js not found

![server_js_-_devtemplate_-____documents_arbeitenjobben_faktorzehn_2016_devops_devtemplates_microservices_service1evidence__-_intellij_idea__minerva__iu-145_184_1_und_web](https://cloud.githubusercontent.com/assets/1694964/13548373/15084b42-e2ef-11e5-987c-67fda1e0bb2d.jpg)

**Comment by geoHeil** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/issues/941

**Comment by Hosar** [comment]
It's just generating vendor-ab74800f34.js, but not app.js for me.
Any suggestion?

**Comment by Hosar** [comment]
The error was, because Uglify js, does not support ES6. That's why it was not building app.js

**Comment by MRichardson1** [comment]
> The error was, because Uglify js, does not support ES6. That's why it was not building app.js

Can you say how you fixed this?
