### ISSUE TITLE
How can I use dependencies from node_modules?

### ISSUE THREAD

**Issue by TheOpti** [Swiip/generator-gulp-angular#1043]
Suppose I installed front-end library in node_modules (and I want to use all Front-End libraries from that directory). What should I do to inject it into my project?

**Comment by Swiip** [comment]
I don't know a tool like wiredep which can list NPM deps and give me the liste of JS files to inject (I searched for it). So it's not possible to have the same "auto inject" mechanism.

Still, you can publish the node_modules directory in Browsersync (with an alias like the one for bower_components) and add the script tags in the index.html yourself and it should work.

**Comment by jetspeed** [comment]
@Swiip How can I "publish the node_modules directory in Browsersync and add the script tags in the index.html"?, for example, I want to use a npm module https://github.com/kevva/download, which has no bower package, How to configure it ? 
Thanks.

**Comment by Swiip** [comment]
You have to add an alias in browsersync like this one: https://github.com/Swiip/generator-gulp-angular/blob/master/generators/app/templates/gulp/_server.js#L24

**Comment by Hesesses** [comment]
@jetspeed did you ever get this working?

**Comment by harconst** [comment]
@jetspeed  @Hesesses 

Modifying server.js in order to make the routes look like this:
```
routes = {
      '/node_modules/': 'node_modules',
      '/bower_components': 'bower_components'
    };

```
should allow you to reference and inject node modules in your index file, like this:

```
<!-- build:js({.tmp/serve,.tmp/partials,src}) assets/js/app.js -->
        <!-- bower:js -->
        <!-- run `gulp inject` to automatically populate bower script dependencies -->
        <!-- endbower -->
        <script src="../node_modules/your_module/your_module_file.js"></script>
        <!-- inject:js -->
        <!-- js files will be automatically insert here -->
        <!-- endinject -->

        <!-- inject:partials -->
        <!-- angular templates will be automatically converted in js and inserted here -->
        <!-- endinject -->
<!-- endbuild -->
```

A little late to reply, but I just stumbled upon this myself!
Regards
