### ISSUE TITLE
gulp.watch so slow...

### ISSUE THREAD

**Issue by kl09** [Swiip/generator-gulp-angular#1044]
gulp.task('style', function () {
    return gulp.src('style.less')
        .pipe(less({
            paths: [path.join(__dirname, 'less', 'includes')]
        }))
        .pipe(autoprefixer({
            cascade: false
        }))
        .on('error', onError)
        .pipe(gulp.dest('./'));
});
gulp.watch('./**/*.less', ['style', reload]);

[18:15:30] Using gulpfile ~/work/test/gulpfile.js
[18:15:30] Starting 'default'...
[18:16:26] Finished 'default' after 56 s

Why so slow? 56 sec

**Comment by Swiip** [comment]
I'm not maintainer of `gulp` or `gulp-less`, why do you post this here?
