### ISSUE TITLE
Is there any way to change bower_components folder ?

### ISSUE THREAD

**Issue by luckymancvp** [Swiip/generator-gulp-angular#1046]
Thanks for awesome generator but Can you tell me : Is there any way to change bower_components folder ?.

I changed config in `guld/conf.jp` file but It has some errors

**Comment by Swiip** [comment]
You'll have to change several configurations. Right now, I can think of:
- `gulp/conf.js` yes but also...
- `.bowerrc`
- `gulp/serer.js`

Frankly, try a search "bower_components" in your all project.

**Comment by luckymancvp** [comment]
Thank you very much. I searched around, but no success. 

A simple question , because I'm not familiar with gulp ( I'm using grunt ):
- How to disable browerSync and watch file ? because I can refresh brower by my self.


Your angularjs folder structure is awesome. Thank you very much

**Comment by Swiip** [comment]
Browsersync reloads are triggered by commands likes `browserSync.stream()` or `browserSync.reload()` in the gulp files. You should be able to just comment them.

**Comment by luckymancvp** [comment]
Dear @Swiip 

Today I've read all issue, and I can not resolve my problem. Can you tell me how to use `Todo` resources with this angularjs project 

Actually I use loopback for my backend, and It create a service file for angularjs interact with backend. Example of this file is here 

https://github.com/strongloop/loopback-example-angular/blob/master/client/js/services/lb-services.js

I can not inject that file to project to use `Todo` model in `SampleController`. 
I know you created this repo for free , but please help me inject that service file into project

**Comment by luckymancvp** [comment]
I found solution : 

in module file : `function SampleController(SampleData, Todo) {` in controller , and in index.module.js file define lbService .

Thank you !
