### ISSUE TITLE
Modules get transpiled/builded only the first time

### ISSUE THREAD

**Issue by TheNemus** [Swiip/generator-gulp-angular#1050]
Hi,

I just scaffolded my app as described:

Ang: 1.4.x
jQuery:2.x
Angular modules: sanitize, tocuh
Resource handler:  none
Router: UI Router
UI Framework: Bootstrap
UI directives : UI Bootstrap
CSS pre-processor: Sass with Node
JS preprocessor: TypeScript
HTML preprocessor: Jade

SO: W8
npm: 3.8.2
node: 4.4
yeoman: 1.7.7

Then npm install + bower install, then gulp serve and I see my app. From now, **even if I change or delete my ts/html/scss, my browser will reload, but my app is still the same**. The only solution is to stop and restart gulp serve.

If I scaffold with ES6+Babel, everything works fine.

my boilerplate as created by yeoman:
[ts.zip](https://github.com/Swiip/generator-gulp-angular/files/187923/ts.zip)

**Comment by Swiip** [comment]
Dups of #1001. Master fix this, wait for the next release (or change to ts-loader yourself)
