### ISSUE TITLE
Error: [ng:areq] Argument 'ctl' is not a function, got undefined

### ISSUE THREAD

**Issue by blackleafs** [Swiip/generator-gulp-angular#1055]
<div ng-controller="ctl">
<div style="margin-top: 80px">
  search:<input type="text" ng-model="query">
  sort:<select data-ng-model="order">
  <option value="name">name</option>
  <option value="age">age</option>
</select>
</div>
<ul>
  <li ng-repeat="person in persons | filter:query | orderBy:order">
    {{person.name}}<span>,</span>
    {{person.age}}<br>
  </li>
</ul>
</div>
<script>
     angular.module("demo").controller("ctl",["$scope", function ($scope) {
       $scope.persons = [
         {name:"aaa",age:"12"},
         {name:"bbb",age:"18"},
         {name:"ccc",age:"5"},
         {name:"ddd",age:"88"}
       ];
       $scope.order = "name";
     }])

</script>

**Comment by Swiip** [comment]
https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md
