### ISSUE TITLE
How to use angular-mocks in gulp serve?

### ISSUE THREAD

**Issue by RootProgger** [Swiip/generator-gulp-angular#1056]
$~gulp serve doesn't include angular-mocks, in the bower.json ist declared under devDependencies:

`"devDependencies": {
    "angular-mocks": "~1.5.3"
  },`

how can i use this mock or any other mocks like gulp-json-server?

**Comment by Swiip** [comment]
Not sure what you really want. angular-mocks is a testing library and should be in devDeps and not loaded on `gulp serve`.

If, for any reason, you want it as regular dependency (even if it's not recommanded) you have to move it out of devDeps with the regular deps.

**Comment by RootProgger** [comment]
i thought serve was for the dev and serve:dist for prod?
When i develop and use serve i can see the changes in live-reloading, so i think thats for developing...

**Comment by Swiip** [comment]
Yep, it is.

But about bower deps, dev deps are for testing : deps you don't use normally.
