### ISSUE TITLE
New release with TypeScript fixes?

### ISSUE THREAD

**Issue by fdcastel** [Swiip/generator-gulp-angular#1060]
The current release is not generating TypeScript projects correctly anymore (errors with awesome-script-loader).

I saw a lot of improvements and fixes since nov/2015, including the change to ts-loader.

Could you publish a new version with them? 

Alternatively, how could I use the latest version from github? (I'm not very familiar with yeoman and the tools)

**Comment by Swiip** [comment]
You can clone the project and publish it in your local NPM with npm link. But indeed, a new 1.1 release is planned for really soon, perhaps even today. Sorry for the lazy maintenance these days but we're focused on the next version (https://github.com/FountainJS/generator-fountain-webapp)

**Comment by Swiip** [comment]
Done: https://github.com/Swiip/generator-gulp-angular/releases/tag/v1.1.0
