### ISSUE TITLE
Angular 1.5 and PhantomJS

### ISSUE THREAD

**Issue by riyadhalnur** [Swiip/generator-gulp-angular#1061]
Should someone want to use Angular 1.5, the unit tests will break. PhantomJS needs to be upgraded to v2.2.x for the tests to work under 1.5.x.

I'm up for issuing a PR for this but I noticed @Swiip mention that he'd do it. If not, then let me know and I'll make the changes.

**Comment by Swiip** [comment]
It's handled in master, it will be released soon. (https://github.com/Swiip/generator-gulp-angular/commit/be08a9099de01e3f9576297d5b544639af817914)

**Comment by riyadhalnur** [comment]
Ok cool but why use `shim` rather than upgrade PhantomJS itself?

**Comment by Swiip** [comment]
To be honest, I'm afraid of side effects for changing major version of Phantom. Also considering that I want to release quickly and I'm more focused on the next version of the generator.

**Comment by riyadhalnur** [comment]
Ok, I see you point but I've seen no side-effects so far. I upgraded PhantomJS and the Angular version and nothing else.
