### ISSUE TITLE
how do .mock.js files work?

### ISSUE THREAD

**Issue by codeofsumit** [Swiip/generator-gulp-angular#1073]
I'm always writing my tests inside `.spec.js` but I saw that there is support for `.mock.js` files. Is there an example somewhere how that works?

How do I have to provide the data inside the mock file and how do I make it available inside the tests of spec file?

**Comment by Swiip** [comment]
We don't have examples. The concept was simply that as we have tests files inside the src folder, it's important to have the right files pattern to be excluded for testing.
When you write tests, you often have files which are tests utils but no actual tests, often it's mocks object.  So we added this to prepare for these kind of needs. If you don't use it, just remove it and that's all.

**Comment by codeofsumit** [comment]
No no I do want to use them as large mock objects clutter the actual test file.
I just wanted to know how.

Currently I'm just doing a `var myMockObj = {...}` inside the `.mock.js` file.
And `myMockObj` then is available inside `.spec.js` as a global variable.

Hope that's the correct way to use it.

**Comment by Swiip** [comment]
I think it is yes.

**Comment by codeofsumit** [comment]
👍✌️
