### ISSUE TITLE
typings not installed

### ISSUE THREAD

**Issue by gadieichhorn** [Swiip/generator-gulp-angular#1078]
when running a typescript option the typings are not installed

need to run (maybe add that as postinstall node script?)

`
tsd init
`

and then install each lib

`
tsd install -save angular, angular-route, jasmine
`

and then add reference inside the relevant ts and spec.ts files

`/// <reference path="../../typings/tsd.d.ts" />
`

the file name referenced in the index.module is main.d.ts but it is not the default created by tsd init

**Comment by devmark** [comment]
https://github.com/Swiip/generator-gulp-angular/pull/1052

**Comment by johnoscott** [comment]
seems `typings` is used (not `tsd`) so the missing setup is actually :

`typings install`

once I ran this command the typescript compiler worked for me

**Comment by dereklin** [comment]
@johnoscott Thanks.  It works.  Since I am behind a firewall, I also need to add a .typingsrc file and add proxy info.  https://github.com/typings/typings/issues/106
