### ISSUE TITLE
Doesn't compile ES6 module to ES5 automatically

### ISSUE THREAD

**Issue by axetroy** [Swiip/generator-gulp-angular#1084]
I write a npm module in ES6,and didn't compile it to ES5.
and import it in my project
```javascript
// import resource module which write in ES6
import resource from 'resource'
```
and run ``gulp serve`` or ``gulp build``
but I find i won't compile automatically like other js file

so,what something wrong with this?
should I change the gulp task?

**Comment by Swiip** [comment]
Webpack conf exclude node_modules for the Babel loader. I don't think it's a right approach to publish ES6 modules right now, you should precompile it.

**Comment by axetroy** [comment]
@Swiip Thanks
I have resolve it.
