### ISSUE TITLE
How to asynchronous load module?

### ISSUE THREAD

**Issue by axetroy** [Swiip/generator-gulp-angular#1097]
I want load a module like some chart module or others which is no necessary in most of page

because this module is to large and it don't need every page

I don't want to package together to ``app.js`` or ``vendor.js``

so，how can I load it asyn

user  ``require.ensure``  to package a module ``1.index.module.js``

but i found it not work at all

first error is ``webpackJson is not defined`` then  I load this ``webpack common`` module

it work but the ``1.index.module.js`` 's path is wrong,module is not find

then I copy the ``1.index.module.js`` to his parent folder

it should be ``./.tmp/serve/1.index.module.js`` not be ``./tmp/serve/app/1.index.module.js``

it work now but just in serve env not work for build

will not auto inject this module to ``dist`` folder

### so,the question is

1. I have generate the asyn module but can not load it in asyn

1. and it would not copy the asyn module to ``dist`` folder

1. not a clear path relationship when ``serve`` and ``build``

> I am sorry about this , I don't know this is a issue or not

### can provid a asyn load module example ? thanks very much

**Comment by souravmondal93** [comment]
I would suggest you to use [ocLazyLoad](https://oclazyload.readme.io/) plugin. Yo can follow there [docs](https://oclazyload.readme.io/docs) here and make the required changes in your app. Most importantly, you have to update your router file with something like this:

```javascript
$stateProvider.state('index', {
  url: "/", // root route
  views: {
    "lazyLoadView": {
      controller: 'AppCtrl', // This view will use AppCtrl loaded below in the resolve
      templateUrl: 'partials/main.html'
    }
  },
  resolve: { // Any property in resolve should return a promise and is executed before the view is loaded
    loadMyCtrl: ['$ocLazyLoad', function($ocLazyLoad) {
      // you can lazy load files for an existing module
             return $ocLazyLoad.load('js/AppCtrl.js');
    }]
  }
});
```

**Comment by axetroy** [comment]
@souravmondal93 
thanks you for reply

I have resolve this not use the ``$ocLazyLoad``

I use the webpack  ``require.ensure`` api
and create a new gulp task to fixed the chunk path and copy to dist folder

and then load it in ``$stateProvider resolve``

just like 

```javascript
  resolve: {
    asynModule: ['$q',function($q){
        var deferred = $q.defer();
        require.ensure('./asynModule',function(require){
          var _module = require('./asynModule');
          // other actions like register a new controller or component
       });
        return deferred.promise;
    }]
  }
```

by now, everything is ok.
I think it should be imploded into the gulp task
