### ISSUE TITLE
BrowserSync with html5Mode

### ISSUE THREAD

**Issue by jasperblues** [Swiip/generator-gulp-angular#1099]
Hello. I'm a total n00b here. Would someone be able to explain how to get BroswerSync to support html5Mode with ui-router? 

We need the server to redirect requests to /index.html. There's instructions here for various servers, but not for BrowserSync. I tried a few things but it didn't seem to work, so asking here if it is a common task. 

I need html5Mode for my deployed app, and it would be useful to have it turned on also during dev. 

The reason I need it turned on for the deployed app are: 

- The URLs are prettier, and I've made a landing page for an iOS application. (If displays some basic profile info, and redirects if the app is installed). 
- It is for a 'share profile' feature - creating links to a profile. One of the channels could be skype, and it seems skype gets messed up for any URL with a '#' in it.

**Comment by souravmondal93** [comment]
If you can elaborate your problem, then it will be easier for us to understand. Kindly try to include code snippet, if possible, it makes things clear for other users. With the information supplied by you, I think most probably you are missing the base tag at the head part of the index.html file. You can read mode about it [here](https://docs.angularjs.org/guide/$location).
```html
<!doctype html>
<html ng-app="freeBnB">
<head>
    <meta charset="utf-8">
    <title>freeBnB</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <base href="/">

</head>
<body>
<!--[if lt IE 10]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->

<div ui-view></div>

</body>
</html>
```
I have removed the comments from code snippet to reduce the size. Take a look at the base tag in the head part. I think you are missing it in your code.

**Comment by jasperblues** [comment]
@souravmondal9 I'm sorry I didn't provide more info - as a n00b to angular, I wasn't sure what information would be obvious to someone with more experience and is appropriate to share. 

You solved it for me anyway :) I had the base tag there, but it wasn't in the `<head>` section and that seemed to cause problems. 

Thank you.

**Comment by souravmondal93** [comment]
Welcome. Happy to help you and most importantly it solved your problem.
