### ISSUE TITLE
Heroku/Dokku deploy strategy?

### ISSUE THREAD

**Issue by tvararu** [Swiip/generator-gulp-angular#11]
First of all, great work building this. It's the exact seed that I was looking for, and it's really easy to hack additional features into.

Now then, do you have a recommended git-based deployment strategy for an app built on this, to something like Heroku or Dokku?

I was thinking about using the basic node buildpack, and just having it do something along these lines:

``` bash
npm install &&
./node_modules/gulp/bin/gulp.js build &&
cd dist &&
python -m SimpleHTTPServer $PORT
```

It sounds simple enough, but I decided to ask anyway; maybe it's also something that's been done by someone else in a more robust fashion. :monkey:

**Comment by artmees** [comment]
@tvararu could you please post some gist or anything on how to deploy apps to heroku. (cause I'm having troubles doing it :blush: new to frontend development)

**Comment by tvararu** [comment]
@artmees: Heroku themselves have decent guides written on this subject for a number of the languages and frameworks that they support: https://devcenter.heroku.com/start

For the project in which I was using this (https://github.com/tvararu/wallet), I opted instead to just use GitHub Pages hosting by creating a `gh-pages` branch. You can read about this feature here: https://help.github.com/articles/creating-project-pages-manually/

**Comment by artmees** [comment]
you got me wrong, I've been using heroku with rails since ever... except in this new project where the angular app is a standalone API consumer... the problem is that I don't get where is the server that will host it (the angular app)... ex. in every article they combine it with a node server... but I just want heroku to serve these angular assets (which will interact with my rails API)... and I'm new to developing standalone API consumer (in the frontend).

**Comment by tvararu** [comment]
@artmees ah, well you asked about "how to deploy apps to Heroku" which is why I thought you meant in a generic way.

The reason all those tutorials and websites combine the static build with a node server is because Heroku does not automatically provide static site support. Heroku Web dynos will search your project root for a `Procfile`, and then execute the command outlined on the line that starts with `web:`. AFAIK, that's it. Also, port `:80` is rerouted to `127.0.0.1:$PORT`.

Lots of static site projects use `web: python -m SimpleHTTPServer $PORT`, which will run a small python webserver in the current directory using the specified port.

However, single page applications have more finicky needs; you'll likely want HTML5 pushstate support, so that links like `/hello/world` aren't just resolved to a 404 and a dead page but rather redirect to `index.html` so that your fat client application can handle the URL. node + express servers are simple to setup for this purpose.

I hope that helps! I think that it's best to keep this conversation out of this thread to avoid spamming other people with messages, so feel free to drop me an email if you have further questions. I'll gladly answer what I can.
