### ISSUE TITLE
Can use the recipe for font-awesome

### ISSUE THREAD

**Issue by grimaldo** [Swiip/generator-gulp-angular#1109]
Hello there, I hope some one can help me;

I follow the recipe for add font-awesome but I't doesn't works let me explain  the case:

I installed via bower with: bower install components-font-awesome
I add the variable in app/index.scss:

line 7: $fa-font-path: "../../bower_components/components-font-awesome/fonts";
line 36: @import "../../bower_components/components-font-awesome/scss/font-awesome.scss";

But it doesnt inject, can you help me please?

**Comment by mikedidomizio** [comment]
Hey,

I added font-awesome above the // injector and it worked fine

```

@import "../../bower_components/components-font-awesome/scss/font-awesome";

/**
 *  Do not remove the comments below. It's the markers used by gulp-inject to inject
 *  all your sass files automatically
 */
// injector
// endinjector


```

**Comment by grimaldo** [comment]
I finally can use it, the issue was generated because need to save the dependency reference in the file bower.json thank you
