### ISSUE TITLE
how to use jquery  with this

### ISSUE THREAD

**Issue by wwlweihai** [Swiip/generator-gulp-angular#1116]
i use jquery follow
`export class MainController {    constructor() {
       "ngInject";
        this.activate();
    }
    activate() {
        $(function () {
            console.log("load jquery")
        });
    }
}
`
but the error still,

` 10:9   warning  You should use angular.element instead of the jQuery $ object                                angular/angularelement

  10:9   error    "$" is not defined                                                                           no-undef

  11:13  error    You should use the "log" method of the AngularJS Service $log instead of the console object  angular/log

  11:13  error    Unexpected console statement                                                                 no-console`

**Comment by Swiip** [comment]
That's not an error, it's eslint-plugin-angular which tells you to better use angular.element in place of $. You can disable this rule or do what it says.
