### ISSUE TITLE
Unit Tests Should Not Be Included in Production Build

### ISSUE THREAD

**Issue by JimTheMan** [Swiip/generator-gulp-angular#1131]
Hi. Sorry if this is a stupid question, but I just wanted to make sure that the unit tests are not included in the minified files from "gulp build". In terms of developer productivity I am totally with you that putting the spec files right in the app folder is better than having a root level "test" folder, but you don't want these .spec.js files putting double (or more!) the necessary javascript code in the finished project. I'm just wondering feature if this is already in the project. 

I do see in the gulp folder's inject.js file this block of code:

```
var injectScripts = gulp.src([
    path.join(conf.paths.src, '/app/**/*.module.js'),
    path.join(conf.paths.src, '/app/**/*.js'),
    path.join('!' + conf.paths.src, '/app/**/*.spec.js'),
    path.join('!' + conf.paths.src, '/app/**/*.mock.js'),
  ])
```

Can someone please confirm that this is doing what I'm describing in the paragraph above?

**Comment by Swiip** [comment]
We had a bug about this. But you point exactly the configuration which excludes tests from the dist bundle.

**Comment by JimTheMan** [comment]
ok great. Thanks!
