### ISSUE TITLE
Segmentation Fault during styles task

### ISSUE THREAD

**Issue by danprime** [Swiip/generator-gulp-angular#117]
Running Ubuntu 14.04

I get a 'Segmentation Fault' while running the gulp styles task. I was searching on google and found this: http://stackoverflow.com/questions/24397561/sass-task-in-gulp-with-sourcecomments-map-produces-assertion-failed which seems to work so I no longer get a segmentation fault when I  add the following parameters to the styles task in the build.js file:

```javascript
.pipe($.sass({style: 'expanded',
                  sourceMap: 'sass',
                  sourceComments: 'map'}))
```
Original
```javascript
.pipe($.sass({style: 'expanded'}))
```

**Comment by zckrs** [comment]
@danprime Do you use nodeSass or rubySass ? Can you update issue with the lastest version of generator ?

**Comment by zckrs** [comment]
I will close the issue.

Should work with Node Sass.

### Temporarily workaround for Ruby SASS

Add a option `sourcemap=none': true` in `./gulp/styles.js`:


* replace `var sassOptions = {
      style: 'expanded'
    };`
* to `var sassOptions = {
      style: 'expanded',
      'sourcemap=none': true
    };`

**Comment by blended-ideas** [comment]
The solution did not work for me.
However downgrading node-sass to 3.4.2 did the trick.

node: v6.2.2
npm: v3.9.5
gulp-sass: v2.0.4
