### ISSUE TITLE
Move Gulp Templating Logic to separate repository

### ISSUE THREAD

**Issue by srsgores** [Swiip/generator-gulp-angular#163]
I'm pretty sure the logic in [``templates/gulp/_build.js``](https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/gulp/_build.js) belongs in its own repo, just as does the [grunt file editor](https://github.com/SBoudrias/gruntfile-editor).  This would be useful for authors who are interested in customizing a gulp file in a new generator, but are not interested in simply copy-pasting from the source code in this repository, and could also benefit from community updates via NPM.

**Comment by srsgores** [comment]
So is this still in the plans for the future?  I see you've closed this issue...

**Comment by Swiip** [comment]
I written in this thread all my thought on this subject. To sum up, gulpfile code is too complicated to be generated the same way the `gruntfile-editor` works. It could be feasible but my skills in AST manipulations are not enough.

So we keep templating. I just added a small feature to the template engine to be able to indent correctly and make them more readable.
