### ISSUE TITLE
How to control the order less files are injected into index.css

### ISSUE THREAD

**Issue by sswainright** [Swiip/generator-gulp-angular#169]
Is there a way to control the order of the compiled css files are injected?  The injector @import statements get re-written even if I edit the order in index.less

Much Thanks

**Comment by zckrs** [comment]
I think you can use [stream-series](https://github.com/rschmukler/stream-series)

See https://github.com/klei/gulp-inject#multiple-sources-when-order-is-important

**Comment by zckrs** [comment]
ping @sswainright @bhj
