### ISSUE TITLE
gulp error with ruby-sass

### ISSUE THREAD

**Issue by maxehnert** [Swiip/generator-gulp-angular#198]
This is my first time using this generator and I'm getting this error right out of the box. I have not modified any files. When running any gulp task I get a throw error. 
From the command line:
```
gulp-ruby-sass: write vendor.css
      write vendor.css.map

events.js:72
        throw er; // Unhandled 'error' event
              ^
/Users/123/PersonalProjects/angularGeneratorTest/index.css.map:3:1: Unknown word
"version": 3,
"mappings": "AAAA,YAAa;EACX,MAAM,EAAE,OAAO;EACf,UAAU,EAAE,IAAI;EAChB,KAAK,EAAE,IAAI;EACX,OAAO,EAAE,OAAO;;;AAGlB,UAAW;EACT,MAAM,EAAE,KAAK;;AAEb,yBAAe;EACb,KAAK,EAAE,IAAI",
^
"sources": ["../index.scss"],
```

**Comment by zckrs** [comment]
I close the issue. This error is related to https://github.com/sindresorhus/gulp-autoprefixer/issues/20

### Temporarily workaround

Add a option `sourcemap=none': true` in `./gulp/styles.js`:


* replace `var sassOptions = {
      style: 'expanded'
    };`
* to `var sassOptions = {
      style: 'expanded',
      'sourcemap=none': true
    };`

**Comment by zckrs** [comment]
Done see 
https://github.com/Swiip/generator-gulp-angular/commit/b2c512a84a1a6262bec3ad38e0bb82bcaab576ae
