### ISSUE TITLE
Modify `index.html` in build directory

### ISSUE THREAD

**Issue by wb14123** [Swiip/generator-gulp-angular#202]
The current implement generate imports of css and js by modify `index.html` directly, which means change the source code. Why not just generate a modified `index.html` in build directory, so that the change of dependencies will not change `index.html` in the source tree.

**Comment by wb14123** [comment]
Is it possible to copy the files to other places and run the gulp tasks on that files?

**Comment by Swiip** [comment]
I started this feature. It implies several important changes but I think it's cleaner this way.

Wait a little more before I can publish the PR.

**Comment by Swiip** [comment]
The new organization fix this, check out the master or wait for the 0.9.x!

**Comment by wb14123** [comment]
Great!
