### ISSUE TITLE
Add dist path configuration

### ISSUE THREAD

**Issue by ant0ha** [Swiip/generator-gulp-angular#203]
Like this:

gulp/build.js

var distPath = 'dist/';

gulp.task('fonts', function () {
  return gulp.src($.mainBowerFiles())
    .pipe($.filter('**/*.{eot,svg,ttf,woff}'))
    .pipe($.flatten())
    .pipe(gulp.dest(distPath + 'fonts/'));
});

Thanks!

**Comment by zckrs** [comment]
This issue can be closed ?

**Comment by ant0ha** [comment]
Yes, Thank you!
