### ISSUE TITLE
(Re)organize gulp files

### ISSUE THREAD

**Issue by Swiip** [Swiip/generator-gulp-angular#204]
The `build.js` has severely grows in size. In top of that, its name is not semantically correct anymore as the preprocessors and injectors tasks are not used only in the build process.

I think of something like this would be great:
* `build.js` for the actual "optimize" tasks, `html` should also be renamed
* `styles.js` for css preprocessors and injector css
* `scripts.js` for js preprocessors, hinters and injector js
* `markups.js` for html preprocessors and partials

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/217
