### ISSUE TITLE
Index.html are empty after error

### ISSUE THREAD

**Issue by dpocheketa** [Swiip/generator-gulp-angular#205]
When I am running gulp watch and some error happen in my scripts. Sometimes I have this message:
<code>
gulp(1947,0x7fff7bb0d310) malloc: *** error for object 0x103efe5a9: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
</code>

And my index.html and index.scss are cleaned by gulp. While I am not restore files error still happen.
Can someone help me?

**Comment by Swiip** [comment]
Sorry for the delay. The last evolutions implied too much changes in the `index.html`. It append that with several writing at the same time end up with a white file.

I wanted to correct this the right way even if it implies a important change, you can follow this in this PR: #217

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/217

**Comment by dpocheketa** [comment]
Thanks!
