### ISSUE TITLE
Add None choice for html pre-processor question

### ISSUE THREAD

**Issue by marani** [Swiip/generator-gulp-angular#213]
Now it looks like we don't even have a choice for no html pre processor, until I found out that I can unselect. Also I know Jade is good, but should None be default ?

**Comment by zckrs** [comment]
:+1:

**Comment by Swiip** [comment]
It's already in my incoming PR. In fact, I even remove the multiple choice possibility, I think it's really not necessary.

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/217
