### ISSUE TITLE
Angular Material + No router bug

### ISSUE THREAD

**Issue by Swiip** [Swiip/generator-gulp-angular#216]
There is a regexp in the code to add the ng-controller directive when there is no router which fails on the material template.

https://github.com/Swiip/generator-gulp-angular/blob/master/app/src/format.js#L101

**Comment by zckrs** [comment]
@Swiip  can you update this issue. The link is dead.

**Comment by Swiip** [comment]
https://github.com/Swiip/generator-gulp-angular/blob/master/app/src/router.js#L20
