### ISSUE TITLE
--advanced option is not documented

### ISSUE THREAD

**Issue by Toilal** [Swiip/generator-gulp-angular#226]
It may have been already discussed, but do you really think it make sense to add an additionnal `--advanced` option to display additionnal questions ? I find this more confusing than helpful, the advanced question brings features that are quite easy to understand, and just hitting ENTER key makes generators works like usual (like without advanced option).

It's just my personnal mind, just keep it as you want, but anyway if `--advanced` is keeped, it should be added in README and `yo gulp-angular --help`.

**Comment by zckrs** [comment]
Yeah README should be updated. Thx

**Comment by Toilal** [comment]
Why do you close issues before they are fixed ? You seems nervous @zckrs ...

**Comment by zckrs** [comment]
Just a missclick

**Comment by Toilal** [comment]
thx :p
