### ISSUE TITLE
All content from the index.scss and index.html disappears 

### ISSUE THREAD

**Issue by okadesign** [Swiip/generator-gulp-angular#232]
Did not managed to identify when it happens but I got my files ( index.scss and index.html in the src ) complete empty , twice ...
Probably  related with wiredep. Any one with the similar issue ?

**Comment by jstoneky** [comment]
I have seen this issue as well (mainly on index.html) -- i think it happens when I have a syntax error or something. Thankfully I just check it back out, but its definitely a concern. I haven't started looking into it yet.

**Comment by zckrs** [comment]
this issue should be fixes with `master`
@Swiip

**Comment by jstoneky** [comment]
Awesome @zckrs , is there a commit that fixed it so I can just update my stack. I'll re-scaffold once its stable.

**Comment by okadesign** [comment]
great will update my as well, thanks

**Comment by zckrs** [comment]
You should use master or wait v0.9

**Comment by joelim01** [comment]
@Swiip @zckrs 
I believe that this is still happening in the current version. The only warning I am seeing is a syntax error but the entire index.html file has been cleared. Here is a snippet from terminal:

[BS] File changed: .tmp/app/index.css
[11:39:55] Starting 'scripts'...
[11:39:55] Starting 'wiredep'...
[11:39:55] Starting 'injector:css:preprocessor'...
[BS] File changed: src/app/main/main.controller.js
[11:39:55] gulp-inject Nothing to inject into index.scss.

/Users/jlim/angPipeSingle/src/app/main/main.controller.js
  line 6  col 12  Strings must use singlequote.
  line 6  col 23  Strings must use singlequote.
  line 6  col 30  Strings must use singlequote.
  line 7  col 12  Strings must use singlequote.
  line 7  col 23  Strings must use singlequote.
  line 7  col 34  Strings must use singlequote.
  line 8  col 12  Strings must use singlequote.
  line 8  col 23  Strings must use singlequote.
  line 8  col 39  Strings must use singlequote.
  line 9  col 12  Strings must use singlequote.
  line 9  col 23  Strings must use singlequote.
  line 9  col 33  Strings must use singlequote.

  ⚠  12 warnings

[11:39:55] Finished 'wiredep' after 30 ms

**Comment by chhsiao1981** [comment]
@joelim01

There seems no injector:css:preprocessor in master branch.

Instead of npm install, 
you can do git clone and npm link for latest version.

**Comment by zckrs** [comment]
Can I close this issue ?

**Comment by joelim01** [comment]
Thank you. I linked the cloned repo and everything is working for me.

**Comment by vko-online** [comment]
How to solve this? 
I have 
```js
       gulp.task('injector:css:preprocessor', function () {
      return gulp.src('src/app/index.scss')
        .pipe($.inject(gulp.src([
            'src/{app,components}/**/*.scss',
            '!src/app/index.scss',
            '!src/app/vendor.scss' 
          ], {read: false}), {
          transform: function(filePath) {
            filePath = filePath.replace('src/app/', '');
            filePath = filePath.replace('src/components/', '../components/');
            return '@import \'' + filePath + '\';';
          },
          starttag: '// injector',
          endtag: '// endinjector',
          addRootSlash: false
        }))
        .pipe(gulp.dest('src/app/'));
    });
```
What package is `injector:css:preprocessor` ?
Please can someone provide steps to fix this?

**Comment by Pirhoo** [comment]
Same issue here. How can we fix it with an existing application?

Best (awesome generator btw),
Pierre

**Comment by Swiip** [comment]
Check out the new 0.9.x version, this is fixed since.

**Comment by ant0ha** [comment]
How can I fix it in my current project?

**Comment by ant0ha** [comment]
I have solved the problem.
I generated new structure by new version of the generator and then I copied new gulp files to the current project (package.json copied too).
