### ISSUE TITLE
Proxy wants it minified

### ISSUE THREAD

**Issue by Xobb** [Swiip/generator-gulp-angular#233]
Hello, seems like I've found a bug.

When the proxy is enabled for some reason the ```gulp serve``` outputs html that has ```scripts.min.js``` and ```styles.min.css``` includes instead of the original development files. As those files were not built we get 404 and nothing is loaded.

Version: vagrant@vagrant-ubuntu-trusty-64:~$ npm list -g | grep gulp-angular
├─┬ generator-gulp-angular@0.8.1

Whilst the proxy is disabled everything is build and served correctly.

[.yo-rc.json.](https://gist.github.com/Xobb/1fab0857ad4f5af448dd)

Issue:
![screen shot 2015-01-07 at 23 54 44](https://cloud.githubusercontent.com/assets/98631/5654090/b2b1b8ca-96c8-11e4-884f-2996850f644e.png)

Everything ok:
![screen shot 2015-01-07 at 23 53 48](https://cloud.githubusercontent.com/assets/98631/5654077/a3140bfc-96c8-11e4-922d-9d1c11659289.png)

**Comment by Xobb** [comment]
sorry, this was very lame. I've figured that out myself.

**Comment by zckrs** [comment]
Np ^^
