### ISSUE TITLE
Adding connect-modrewrite results in TypeError: object is not a function

### ISSUE THREAD

**Issue by CrankNPlank** [Swiip/generator-gulp-angular#235]
This generator is great! Thanks for all of the hard work on it. I'm trying to add connect-modrewrite to support AngularJS HTML5 mode, and am following the advice in issue #26. I've included connect-modrewrite in gulp/server.js:
```javascript
...
var middleware = require('./proxy');
var modRewrite = require('connect-modrewrite');
...
```

I then added the rewrite rule to the middleware section:
```javascript
  browserSync.instance = browserSync.init(files, {
    startPath: '/',
    server: {
      baseDir: baseDir,
      middleware: [
        middleware,
        modRewrite([
          '!\\.\\w+$ /index.html [L]'
        ])
      ],
      routes: routes
    },
    browser: browser
  });
```

Doing this throws the error `TypeError: object is not a function` in the browser. If I remove `middleware`, all is good in the world again:
```javascript
...
  browserSync.instance = browserSync.init(files, {
    startPath: '/',
    server: {
      baseDir: baseDir,
      middleware: [
        modRewrite([
          '!\\.\\w+$ /index.html [L]'
        ])
      ],
      routes: routes
    },
    browser: browser
  });

}
```

Any help would be much appreciated!

**Comment by marani** [comment]
If it works then is it good or is there any further problem? The proxyMiddleware is intended for interfacing with a backend. In this case, perhaps you could try this:

Add modRewrite into proxyMiddleware
```
function proxyMiddleware(req, res, next) {
  if (/\.(html|css|js|png|jpg|jpeg|gif|ico|xml|rss|txt|eot|svg|ttf|woff)(\?((r|v|rel|rev)=[\-\.\w]*)?)?$/.test(req.url)) {
    next();
  } else {
    modRewrite(['!\\.\\w+$ /index.html [L]'])(req, res, next);
    // proxy.web(req, res);
  }
}
```
and use proxyMiddleware as the only middleware:
```
      middleware: [
        proxyMiddleware
      ]
```

**Comment by CrankNPlank** [comment]
@marani, that'll work. That's what I was hoping to achieve.

Thanks! Closing this issue.

**Comment by gunish** [comment]
this issue is still open, 
I tried adding the modRewriter to proxy but still getting the ```TypeError: object is not a function```

**Comment by masreis** [comment]
Hello!

 

New message, please read <http://estoncamlievler76.com/step.php?a5>

 

ma@marcoreis.net
