### ISSUE TITLE
Final resource paths are not configurable.

### ISSUE THREAD

**Issue by erichiggins** [Swiip/generator-gulp-angular#237]
In my application, I'd like to ensure that my resource paths are absolute instead of relative (prefixed with a root slash). Within the development environment, I can change this by configuring `gulp/inject.js` to use the `addRootPath: true` or setting some `addPrefix` string value.  The problem is that these options are not used when generating the `dist/` output, which lead to a lot of wasted time trying to decipher the [overly-complex build process](https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/gulp/_build.js#L44) in order to try and duplicate my settings.

Ideally, I should be able to define a prefix that points to my CDN domain for the final output, or configure options like the `addRootSlash` to be used in both development and production, depending on my needs. It'd be great if this generator supported those options out of the box.

**Comment by erichiggins** [comment]
Nevermind me. I RTFM for [useref](https://github.com/digisfera/useref) and learned that I can modify the build path in `index.html` to do this, which solves my issue.

**Comment by Swiip** [comment]
:+1:  Sorry for the reactivity :)
