### ISSUE TITLE
HTML Processor parsing errors stops gulp watch

### ISSUE THREAD

**Issue by Toilal** [Swiip/generator-gulp-angular#238]
When running `gulp watch`, it breaks if an underlying task cause an error, forcing user to run `gulp watch` again.

We could use [gulp-plumber](https://github.com/floatdrop/gulp-plumber) with [gulp-watch](https://github.com/floatdrop/gulp-watch) plugin to avoid this. I'll make a PR.

**Comment by Swiip** [comment]
I already had used plumber in the past and it has been removed by the use of an well placed `.on('error'`.

If there is once again breaks in the watch, it's because my refacto should have missed some task which could break and need an "on error"...

**Comment by Toilal** [comment]
Ok i see. I was starting to check read more docs about watch and plumber plugin, but see it didn't really solve the issue ... 

Does this mean i only need to add an error handler in htmlPreprocesso plugin (markups task) ?

**Comment by Swiip** [comment]
We should have an error handler on each task "which could fail" :)

The preprocessors are the first I think of because the developer could always write something wrong...

**Comment by Toilal** [comment]
I've made a PR only for HTML Processor, because it can fail really often :)

It seems gulpjs 4 will include a global error handler, but for now it seems adding an error handler on each pipe that may fail is the only solution ...

**Comment by Swiip** [comment]
Yeah, Gulp 4 will be a little revolution :)
