### ISSUE TITLE
[TypeScript] Use TSD (TypeScript definition manager by DefinitivelyTyped)

### ISSUE THREAD

**Issue by Toilal** [Swiip/generator-gulp-angular#246]
Using bower to retrieve angularJS types definitions seems to be [deprecated](https://github.com/dt-bower/dt-angular/blob/master/README.md). 

[tsd](https://github.com/DefinitelyTyped/tsd) should be used instead. 

I'll try to make a PR, as i'm currently interested to use TypeScript in my own project, but maybe you have more information about this ?

**Comment by Swiip** [comment]
I'm totally noob with TypeScript and I may well not have used the best solution.

Any "more TypeScript" solution is welcome :)
