### ISSUE TITLE
gulp-angular-filesort doesn't work properly with TypeScript

### ISSUE THREAD

**Issue by Toilal** [Swiip/generator-gulp-angular#247]
`gulp-angular-filesort` doesn't work properly with TypeScript generated files. It cause cause loading controllers to fail because their related javascript files are still not loaded.

**Comment by Toilal** [comment]
Forget about that ...

**Comment by Toilal** [comment]
In fact, it's generating the same order as when not using TypeScript, but this order can't work using TypeScript.

I think we should use [gulp-typescript](https://www.npmjs.com/package/gulp-typescript) instead of [gulp-tsc](https://www.npmjs.com/package/gulp-tsc), because :

- It support [gulp-sourcemaps](https://www.npmjs.com/package/gulp-sourcemaps) (see #245)
- It has a [sortOutput](https://www.npmjs.com/package/gulp-typescript#options) option that would help to solve this issue.

**Comment by Swiip** [comment]
I wonder if I did not break this with the refacto. I just remember that I handled file order differently for TS than for other. If it's not the case anymore, I did broke something.

In any case, I felt that my handling of script loading with TypeScript was perhaps improvable.

**Comment by Toilal** [comment]
PR is coming soon, i've found a solution specific to TypeScript.
