### ISSUE TITLE
Serve rest api from different port?

### ISSUE THREAD

**Issue by mackelito** [Swiip/generator-gulp-angular#254]
Hi,
I'm trying to get this generator to fit in our dev workflow but no luck so far.. So I thought I might as you guys for some pointers.

We have a java (based on spring-boot) app running our backend.. spinning on port 8081. I would like to get the gulp features to work tighter together with the backend..

I start by running "spring-boot:run" to start the backend (a rest api). It's set to server the files from /dist path.. and that works "kind of ok" except that "index.css" is missing...

I want to start "gulp serve" so that we can use BrowserSync and watch features.. but also have access to the backend API.

How can I use the proxy to serve requests from http://localhost:8182/rest/xx from the backend on port :8081?

**Comment by Toilal** [comment]
You want `gulp serve` to partially act as a proxy on `/rest/*` ? everything under `/rest/* should be redirected to the Java Web service ?

**Comment by Toilal** [comment]
Did you try with the `gulp/proxy.js` file ?

**Comment by mackelito** [comment]
Yepp I have.. But I just get 404 on the requests.. :/

**Comment by mackelito** [comment]
Damn.. it was my fault.. I set the proxyTarget to the incorrect path.. my bad..

**Comment by Toilal** [comment]
Great ! You have made me discover this `gulp/proxy.js` file from the project, so thanks anyway :)
