### ISSUE TITLE
Can't import files (ES6/Traceur) from certain folder level

### ISSUE THREAD

**Issue by alexpaluzzi** [Swiip/generator-gulp-angular#257]
I'm assuming this is more of a question than an issue, but I've given up.

Assuming the standard scaffold (using ES6 with Traceur).
```
src
  app
    main
      main.controller.js <-- I want to import into here
  assets
  components
  lib
    Foo.js <-- From here
```
I tried every imaginable variation of folder climbing.
`import Foo from '../lib/Foo'; `
Gulp server always says that it can't find it in `/.tmp`. I noticed the `lib` folder (which I created) wasn't being copied over, so I added it to the `scripts` task: `return gulp.src('src/{app,components,lib}/**/*.js')`
I did see now that the folder and file was copying over and Traceur was running through it, but the module loader still couldn't find it when I went to import.

I'm almost certain it's something I'm missing with one of the gulp tasks. If I put `Foo.js` into any folder inside of `app/` it works just fine.

I wager I'm just doing something stupid.

**Comment by Toilal** [comment]
The generator doesn't support the `lib` directory. You should add files in either `src/app` or `src/components` directory.

Maybe an option could be added for additionnal directories ? Or simply add support for this `lib` directory ?

**Comment by Swiip** [comment]
I gave a quick look, it should work like you did. If you stop your serve and relaunch manually, does it work?

I don't see why the scripts task would fail and as you said you see the compiled files, the only problem I see is that you don't watch the new folder (`gulp/watch.js`)

**Comment by Toilal** [comment]
@Swiip how about replacing every `src/{app,components}/` with `src/*/' ?

Maybe i'm wrong, but I don't think there are real differences between those two folders, and it could make those lib and maybe other additional folders just work ?

**Comment by Swiip** [comment]
This will watch over the asset folder but I agree this is does not matter a lot. @zckrs ?

**Comment by alexpaluzzi** [comment]
I'll be happy to investigate further in the AM. I should mention I didn't mean that the task was failing-- it seems to be working great. It's a runtime issue when I start up the gulp server. The right files are being served and for all intents and purposes it should be working. I didn't know if I was missing some off Traceur option.

**Comment by alexpaluzzi** [comment]
When I start the app using `gulp serve`,  I mean.

**Comment by Toilal** [comment]
So maybe it's not related to `lib` directory, but only Traceur option ?

**Comment by alexpaluzzi** [comment]
@toilal was my first thought, but if I put the exported library anywhere inside of `/app` (no matter how deep), I can get to it. 

Thanks for the great work by the way you guys. This is one of best Yeoman generators in my opinion, and I've used a lot of them.

**Comment by Toilal** [comment]
Could you try to make the same test without Traceur option ?

**Comment by Toilal** [comment]
In `gulp/scripts.js` there's also a `/{app,components}` part that should be replaced with `/{app,components,lib}`. 

This gulpfile is responsible of compiling ES6 files to ES5 with Traceur, so it can be the cause of the issue.

**Comment by Swiip** [comment]
You can also try with a directory with another name that lib. This seams silly but I've seen worse :)

**Comment by alexpaluzzi** [comment]
@toilal I did put the lib folder in the relevant tasks when I was trying to work it out. See first post, I'll try again in a few hours with a fresh start. 

@swiip we think alike. That was the last thing I tried before giving up for the day. Like you said, I've seen worse. :) Now that I think of it, I tried "libs" as the alternative. I'll try another in the AM. If both `` ``

**Comment by alexpaluzzi** [comment]
.. If both lib and libs are reserved, I'm going to pull my hair out. 

Sorry for double post. On mobile.

**Comment by zckrs** [comment]
Add a lib directory in gulp process dont respect the defaut guidelines define by Angular Team un best pratices.

But each developer can/should tweak the generated app.

Yeoman's generator help to start a new project and not create a complete application.
We cant coverage all use case :/

**Comment by zckrs** [comment]
But we should write doc recipes

**Comment by alexpaluzzi** [comment]
@zckrs I don't think this is an edge case nor do I think it has anything to do with Angular. I've contributed to Angular and I'm not sure what "default guidelines" you're referencing. Do you mind dropping a source on that anyway? I'd be interested in reading. It's a bit surprising to me and a departure from the hands-off approach.

**Comment by Toilal** [comment]
The guidelines from README, https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub.

**Comment by Toilal** [comment]
But it seems those guidelines have changed ! :x

**Comment by marani** [comment]
I am not really sure why you would add another shared component folder, or you just want to change the name from `components` -> `lib`.
If it is the case, how about making every static directory configurable (rename, multiple level), including: `bower_components`, `app`, `components`?

**Comment by Toilal** [comment]
For me, an additionnal `lib` directory could make sense to add external libraries that are not available in bower.

**Comment by alexpaluzzi** [comment]
@marani a lot of what @Toilal said it accurate. I consider `components` things like elements (Polymer, X-Tag), and even Angular directives or encapsulated controllers/views, like what the generator is doing now. `lib` would be a folder with your own shared libraries.

Convention aside, the question still remains. We can call the folder `pizza` if that's better. Ignoring convention entirely, I still would like to be able to import from where I would like. If we could ignore convention, that would be great. It's largely irrelevant.

**Comment by Swiip** [comment]
We continue keeping track of the question of the app structure there: #272
