### ISSUE TITLE
Navbar css should be defined in component

### ISSUE THREAD

**Issue by Toilal** [Swiip/generator-gulp-angular#258]
Some styles related to navbar are defined in main `src/app/index.css`, but it they should be defined in a `src/components/navbar/navbar.css` file.

**Comment by Swiip** [comment]
true :+1:

**Comment by zckrs** [comment]
:+1: 
One day for the first stable release I wish create a new design

**Comment by zckrs** [comment]
Related to https://github.com/Swiip/generator-gulp-angular/issues/261 see https://github.com/Swiip/generator-gulp-angular/issues/261#issuecomment-81790092
