### ISSUE TITLE
Enable angular html5 mode (history api)

### ISSUE THREAD

**Issue by markstewie** [Swiip/generator-gulp-angular#26]
Love this generator... except I can't get my angular app to work when I enable HTML5 mode... `$locationProvider.html5Mode(true).hashPrefix('!');`

Every path other than the root path gives `Cannot GET /path-name` response as the request isn't going through the index.html file. 

Is this possible with gulp/this generator?

**Comment by gunish** [comment]
+1

**Comment by andreicojea** [comment]
@otaviosoares I think your code returns `index.html` for assets with `?rel=123412341234`, like the styles injected by browser-sync ^_^

**Comment by cgaudreau** [comment]
The following seems to work for me so far. Haven't done much testing though.

```npm install connect-history-api-fallback --save-dev```

```javascript
var proxyMiddleware = require('./proxy');
var historyApiFallback = require('connect-history-api-fallback');

function browserSyncInit(baseDir, files, browser) {
  browser = browser === undefined ? 'default' : browser;

  var routes = null;
  if(baseDir === paths.src || (util.isArray(baseDir) && baseDir.indexOf(paths.src) !== -1)) {
    routes = {
      '/bower_components': 'bower_components'
    };
  }

  browserSync.instance = browserSync.init(files, {
    startPath: '/',
    server: {
      baseDir: baseDir,
      middleware: proxyMiddleware.concat(historyApiFallback),
      routes: routes
    },
    browser: browser
  });
}
```

**Comment by akhileshmohan** [comment]
@clessg I ran the npm install for the api fallback...post that where do I put the rest of the code you mentioned? I'm new to the programming world and would need your help..
