### ISSUE TITLE
Components should be directives

### ISSUE THREAD

**Issue by Toilal** [Swiip/generator-gulp-angular#261]
It may be discussed, but i think component (navbar) should be declared as directive instead of using `ng-include`.

Future is WebComponents, and webcomponents are very near from directive concept in fact.

Could this be included in V1 ? I could make the refactoring.

**Comment by Swiip** [comment]
There is a new orientation towards a components architecture like the WebCompoents and Angular 2 yes.

But, I think we can't go there head first. Do we want to refactor all our basic application following these new guidelines. Doesn't less quick people be disoriented. Should it be an option?

As a tool for others, I think we should consider these implications.

**Comment by Toilal** [comment]
When opening this issue, i didn't mean using WebComponents at all, only refactoring the `ng-include` of navbar template and its related controller into a `yo-navbar` directive.

**Comment by Swiip** [comment]
I prefer not using directives as application components for now. Ideally, it should be a parent route with ui router but it doesn't work with ngRoute. Perhaps when the new router will be ready to use?

**Comment by Swiip** [comment]
I changed my mind on this issue. I still don't want to redesign the app from view / controller to all component.

But still, I don't like ng-include and more important: we need a directive to illustrate a directive with TS, ES6 and unit testing with template loading. So, I think the navbar is the use case for a directive even if it's not perfect.

But not before the 0.10, don't know for the 1.0...

**Comment by jamm** [comment]
disagree, this folder is for services also and they are not directives.

**Comment by vredchenko** [comment]
@Swiip Just generated a project based on this repo, have a use-case for when I'd normally use a directive, but failed to find an ES6 implementation in the generated code. Question: I've come across this: https://github.com/michaelbromley/angular-es6 - is that the recommended way?

**Comment by jamm** [comment]
@vredchenko sorry for answering question I'm not asked about, but I can share much more simple example:

```
'use strict';
//ngInject
function myDirective($http) {
    return {
        restrict: 'AE',
        template: '<div>Example </div>'
    };
}
export default myDirective;
```

**Comment by vredchenko** [comment]
@jamm Splendid, thanks!
