### ISSUE TITLE
Gulp watch breaks on JS syntax error

### ISSUE THREAD

**Issue by Toilal** [Swiip/generator-gulp-angular#262]
When there's an error in a javascript file, gulp watch breaks, because of angularFilesort.

I've tried to add this in `gulp/inject.js`

```js
  .pipe($.angularFilesort())
  .on('error', function(err) {
    $.util.log($.util.colors.red('[Filesort]'), err.message);
  });
```

But it doesn't call the `server` task anyway ...

Removing angularFilesort fix the issue.

EDIT : ok, I found how to really avoid the error to be propagated, i'll make a PR.

```js
  .pipe($.angularFilesort())
  .on('error', function(err) {
    $.util.log($.util.colors.red('[Filesort]'), err.message);
    this.emit('end'); // This is required to avoid the error to be propagated
  });
```

**Comment by Toilal** [comment]
I think it could be fixed in plugin. Related issue : https://github.com/klei/gulp-angular-filesort/issues/19

**Comment by Swiip** [comment]
Waiting for Gulp 4 we have to listen to all possible errors...

I tried to organize a generic solution here https://github.com/Swiip/generator-gulp-angular/commit/230c710b357fbaa023a6570d847b1b207d7e0a4e#diff-2e6ad34bed54ee43674888cab984c475R13

**Comment by Toilal** [comment]
:+1:
