### ISSUE TITLE
templates not being injected

### ISSUE THREAD

**Issue by johnstontrav** [Swiip/generator-gulp-angular#265]
Hey guys,

I have not done a gulp serve:dist for a while, so i thought i'd try one and code produced is broken.  

Its trying to load templates via a GET request (eg. /app/nav/top.html) and returns a 404.  

Does anyone have any ideas?

**Comment by johnstontrav** [comment]
im wondering if my issue is related to this: https://github.com/Swiip/generator-gulp-angular/issues/150

**Comment by johnstontrav** [comment]
Local issue. resolved.

**Comment by creimers** [comment]
I'm experiencing exactly what you are describing. Would you mind sharing how it was a local issue in your case?
