### ISSUE TITLE
bootstrap font not found

### ISSUE THREAD

**Issue by artmees** [Swiip/generator-gulp-angular#266]
Running `gulp serve:dist` on a newly generated app. I get the following errors in the developers console

```
http://localhost:3000/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
Failed to load resource: the server responded with a status of 404 (Not Found)

http://localhost:3000/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by marani** [comment]
It is discussed in #241, it's broken by some recent PR, will be addressed really soon.
To fix, If the app generated without any path configuration, you can change the code around line 160 of `html` task in `gulp/build.js` into `../bower_components.....`, `../fonts` (each goes back 1 level), it will be fine.

**Comment by artmees** [comment]
the current `gulp/build` has this line
```
.pipe($.replace('../bootstrap-sass-official/assets/fonts/bootstrap', 'fonts')) # line 49
```
but I couldn't figure how to edit it to fix the issue... i tried many combinations but had no luck figuring it out.
so what should this line look like ?!

**Comment by marani** [comment]
try 
```
.pipe($.replace('../bower_components/bootstrap-sass-official/assets/fonts/bootstrap', '../fonts'))
```
or it actually equals
```
.pipe($.replace('bower_components/bootstrap-sass-official/assets/fonts/bootstrap', 'fonts'))
```
It's missing the `bower_components` as well.

**Comment by artmees** [comment]
they didn't work...

**Comment by marani** [comment]
Hmm it's strange that font file shouldn't be missing if the rest is already ok. I haven't been updated with the latest version for a while, I am installing it & try to reproduce.

**Comment by artmees** [comment]
here is the .yo-rc if you want to reproduce identical environment like mine

https://gist.github.com/artmees/98e61e8a07cccd3f7df6

**Comment by marani** [comment]
So woff2 is missing in line 73 of `build.js` (`fonts` task). We can add it back:
```   
 .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))
```
Thanks for the report, this will be fixed soon.

**Comment by artmees** [comment]
it didn't work for me... is there a specific `.pipe($.replace('bower_co....` edit for this to work ?
cause it didn't work with the three alternative (mentioned in this issue) ?

**Comment by marani** [comment]
Well there is no error shown in my chrome console, but also no glyphicon shown in the app as well...

**Comment by artmees** [comment]
with just the edit in the font tasks and not the build task ?!

**Comment by marani** [comment]
I edited both font & build task as above.

**Comment by artmees** [comment]
I've made both the changes and it works in neither `gulp serve` nor `gulp serve:dist`, I've deleted the `.tmp` and `dist` folders and tested again but still not working :disappointed:

**Comment by artmees** [comment]
the weird part is that it doesn't show any error when `gulp serve` only when `gulp serve:dist` and it doesn't show the icons in both cases

**Comment by artmees** [comment]
I've included a screen shot after running `gulp serve` the font is found and still not showing (i've included an icon on the button for demo purpose)
![screen shot 2015-01-20 at 1 46 04 am](https://cloud.githubusercontent.com/assets/347712/5809895/be3a7e48-a046-11e4-8187-90efdb42d66b.png)

but `gulp serve:dist` is always returning 404 ?!

**Comment by marani** [comment]
So the font is actually loaded. 
Tracing down the problem for a while, I found out that the all the bootstrap/glyph styles for icon are wrong in css file.
If you inspect the element, add double quote to the icon value, example: `\e021` -> `"\e021"`. For previous versions, the value is correct. I will look deeper into it & see why there is this problem.

For 404 error doing both the replacement in `build.js` solves it for me.

**Comment by marani** [comment]
Okay got it, that's some bug from bootstrap-sass 3.3.2.
See the [epic diff](https://github.com/twbs/bootstrap-sass/compare/v3.3.2...master#diff-5b362282da62fb4a0be7a7dc15edcd9bL38). 
That's some unquote bug, update to 3.3.3 will solve the problem.

**Comment by Swiip** [comment]
Can we just change https://github.com/Swiip/generator-gulp-angular/blob/master/app/prompts.json#L159 with a `~3.3.0` then?

**Comment by zckrs** [comment]
We could try

**Comment by marani** [comment]
Actually due to semver, ~3.3.x is equal to >= 3.3.x && <3.4.0 so any app generated starting from 12 hours ago (which is the release of 3.3.3) will be 3.3.3 instead of 3.3.2 or 3.3.1, so probably no need a PR for second issue.

**Comment by artmees** [comment]
ok this worked but not in production (`gulp serve:dist`) I still get the 404 response for the fonts all the 3 ?! I've tried all the modifications to the `html` task and yet non of them work with production...

**Comment by marani** [comment]
In [this comment](https://github.com/Swiip/generator-gulp-angular/issues/266#issuecomment-70565124) you mentioned that after the modification, there is only one font file missing. With that modification and adding `woff2` to the `fonts` task, it will probably work.

**Comment by Swiip** [comment]
*.woff2 was not copied in the dist process. I think it's quite new. I added this in the PR.

**Comment by artmees** [comment]
yeah I know the comment... and that is what happened without any further modifications in the file it stopped working... and I really wonder why... is it cached somewhere ?! it's weird I know... but I couldn't figure out why it's not working...

what is more weird is that after updating the `bootstrap-sass-official` it's working with `gulp serve` even without modifying the html task (adding bower to the path) ?!

**Comment by Swiip** [comment]
`gulp serve` doesn't deal with the `html` task.

The replace in the `html` task is aimed to change the path of the font from the `bower_components` folder in dev to the fonts folder in `dist`

In my PR, I got the icons both in `serve` and `serve:dist`.

**Comment by artmees** [comment]
I've applied the same changes you did in the PR
```
# gulp/build.js
    .pipe($.replace('/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/', '../fonts/'))

# src/app/vendor.scss
$icon-font-path: "../../bower_components/bootstrap-sass-official/assets/fonts/bootstrap/";
# the @import was not changed but i added it for reference
@import '../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap'; 
```

and It's still failing... the problem is that i don't understand where the fonts should be copied ( and where is the copying process) ? if you could explain those to me... I might be able to debug it myself

**Comment by Swiip** [comment]
Thats not my changes :/ Did you look there ? https://github.com/Swiip/generator-gulp-angular/commit/f5dc53d38ed76748d83624e13d2ce9a77faeddbb

- Dev: `vendor.scss` got a variable which should point on the font path on the dev server. In this dev server, `bower_components` is a special context which points on the right folder. So, the good value is:
```javascript
$icon-font-path: "/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/";
```
Warning, with sass, this variable has to be set before the `@include` statement
- Dist: the `font` task in `build.js` copy the font files from bower to `dist/fonts`. In the `html` task, the `$.replace` operation replace the previous value of `$icon-font-path` for the `fonts` folder where the files are located in the dist folder. So, relatively to the `styles` folder:
```javascript
.pipe($.replace('/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/', '../fonts/'))
```

**Comment by artmees** [comment]
ok I've changed both the `$icon-font-path` and the `html` task `.pipe` and it's not working...
having to look in the `dist/` folder I found that the fonts was copied correctly but `styles/vendor-469e860f.css` contains the following lines
```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.eot');
  src: url('/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2') format('woff2'), url('/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.woff') format('woff'), url('/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf') format('truetype'), url('/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg'); }
```
is the `src: url(...)` correct ?

**Comment by Swiip** [comment]
What i don't understand is that with my PR, I tried with fresh installs and I've got the icon right in every mode...

**Comment by artmees** [comment]
I didn't tried your PR (didn't pull the code and do all the setup needed) instead I've applied the edits to my existing project
the edits are `$icon-font-path`, html task pipe and adding `woff2` to the font filter... that's it, and not working ?!

**Comment by artmees** [comment]
ok it's now working but I had to change `var cssFilter = $.filter('/**/*.css');` which is my edit back to `var cssFilter = $.filter('**/*.css');`

which bring us to issue #268

**Comment by wgorder** [comment]
There was a problem fixed in https://github.com/twbs/bootstrap/commit/767f3c87bc019e04888c82fa222ffae3e89b6f7e
where mainBowerFiles is not finding the woff2 font.

**Comment by kraihn** [comment]
The replace worked for me once I moved it right below the cssFilter.restore call.

```
    .pipe(cssFilter)
    .pipe($.sourcemaps.init())
    .pipe($.minifyCss({ processImport: false }))
    .pipe($.sourcemaps.write('maps'))
    .pipe(cssFilter.restore)
    .pipe($.replace('/bower_components/bootstrap-sass/assets/fonts/bootstrap/', '../fonts/'))
```
