### ISSUE TITLE
The package gulp does not satisfy its siblings' peerDependencies requirements

### ISSUE THREAD

**Issue by babaggeii** [Swiip/generator-gulp-angular#267]
Here's the error I'm getting when running the command `npm install -g generator-gulp-angular`.

npm ERR! peerinvalid The package gulp does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer gulp-angular@0.1.2 wants gulp@~3.6.2

npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-gulp-angular"
npm ERR! cwd /home/andy/dev/angular-scaffold
npm ERR! node -v v0.13.0-pre
npm ERR! npm -v 1.4.21
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/andy/dev/angular-scaffold/npm-debug.log
npm ERR! not ok code 0

**Comment by zckrs** [comment]
Can you retry with `npm remove -g generator-gulp-angular && npm install -g generator-gulp-angular` ?

But you use pre release node version `v0.13.0-pre`and your npm version is outdated

**Comment by babaggeii** [comment]
Thanks, that now works fine.
