### ISSUE TITLE
Support per Feature styling

### ISSUE THREAD

**Issue by artmees** [Swiip/generator-gulp-angular#268]
as shown in the docs, the recommended structure is as follow

```
├──  src/
│   ├──  app/
│   │   ├──  main/
│   │   │   ├──  main.controller.js
│   │   │   ├──  main.controller.spec.js
│   │   │   └──  main.html
│   │   └──  index.js
│   │   └──  index.(css|less|scss)
│   │   └──  vendor.(css|less|scss)
```

but couldn't it be better if there was a support on styling per feature for example the previous structure could be 

```
├──  src/
│   ├──  app/
│   │   ├──  main/
│   │   │   ├──  main.controller.js
│   │   │   ├──  main.controller.spec.js
│   │   │   ├──  main.html
│   │   │   └──  main.(css|less|scss)  <<<<<<<<<<<<<<<<<<<
│   │   └──  index.js
│   │   └──  index.(css|less|scss)
│   │   └──  vendor.(css|less|scss)
```

**Comment by artmees** [comment]
initially I was able to achieve this by editing [this line](https://github.com/Swiip/generator-gulp-angular/blob/d4fbf084eba148d4eda8f80ca4d122d633433dd8/app/templates/gulp/_build.js#L4)

from `var cssFilter = $.filter('**/*.css');` to `var cssFilter = $.filter('/**/*.css');` but it resulted in making the build task unable to properly substitute the fonts path (see #266)

**Comment by Swiip** [comment]
This filter aims to point only the first level.

The mechanism is that there is an injection point in the `index.scss` to automatically `@include` all other scss files.

`html` task should not have to deal with anything else that index and vendor.

**Comment by artmees** [comment]
actually this is now supported by default... ( I don't know how but it just works) :smile:

**Comment by Swiip** [comment]
The `styles` task take your index.scss and add include statements automatically with the `gulp-inject` plugin. There is no temporary files between injection and processing the scss so you can't see it but look at your `gulp/styles.js`.
