### ISSUE TITLE
App Folder Structure

### ISSUE THREAD

**Issue by haohello** [Swiip/generator-gulp-angular#272]
Hi, I am still confused about the folder structure used in this generator, specifically I don't understand what are the differences between src/app and src/components? Hope some of you here can shed some light for me on this issue.

Thanks in advance for your help.

**Comment by hourliert** [comment]
Same confusion here.

Moreover, according to https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub
Components folder should rather be in app folder ?

**Comment by Toilal** [comment]
:+1: 

I think the components directory was in older version of those guidelines, but it has been dropped. It probably didn't make sense.

**Comment by tlvince** [comment]
AFAIK, `app` should hold pages/routes/states and `components` for reusable directives/services/filters.

**Comment by Swiip** [comment]
We're considering removing app folder which confuse everybody and is not anymore (or never has been?) in the guidelines.

**Comment by fubu** [comment]
What's the status of your considerations? I love your generator, but the first thing I do is usually remove the "app" folder - having that in the generator in the first place would be awesome!

**Comment by Swiip** [comment]
To be honest, I convinced we have to remove the app folder... But I don't know if I succeeded to convince @zckrs :)

But it's a big change as all file selector from the gulp files has to be checked so it's not done for now.

**Comment by fubu** [comment]
Since I already changed my gulp files locally, I could provide some code. I just need to know if it's worth the effort or if you have other plans anyway ;)

**Comment by intellix** [comment]
I've created quite a few Angular projects now, switching between app folders and adding component folders blah blah.

It's exactly as @tlvince mentioned. When you're on a page of your site, it's good to have some idea where you need to look for the code. I don't want to re-iterate what he said but +1 for KEEPING the app folder.

**Comment by Swiip** [comment]
Interesting to have another point of view. I think we'll keep it like that for the 1.0...

**Comment by jbaroudi** [comment]
My first project using this incredible generator (like 4 months ago) went with many changes to gulp to make components folder work like a real encapsulation of context elements... My second project (started 1 month ago) almost has no changes to gulp to achieve this, so, if removing the app (or components)  folder is going to make things brake gulp, well i would vote to go for more interesting features like making (s)css to work inside components/navbar folder from scratch. 

thumbs up for the excellent work

**Comment by jbaroudi** [comment]
Scratch that feature, its working, scss/css injected into app/index.scss on gulp build, sorry :tongue:

**Comment by zckrs** [comment]
I create a PR who is result of this discussion. 
Thanks for contributions
Please review this [PR](https://github.com/Swiip/generator-gulp-angular/pull/447).

**Comment by fubu** [comment]
According to the guidelines, there is no intermediate folder below the source root (here: no `src/app/xy`, but `src/xy` directly). Also note that in all examples, `app.(js|css)` and `index.html` are all on the same level (you currently have them in two different folders).

* If you look at the first and the second example, the `sampleapp` (this generator's `src` folder) lives at the same level as `e2e-tests`, and directly includes `app.js`, `index.html` and all that stuff. Also, `components` is a first-level child.
* The third ("more complex") example has the `index.html` on the same level as `app.js`, as well as the `components` folder and the other module folders.
* The fourth example ("public phonegap") additionally shows an additional data-only directory outside of `app`.

So in my opinion, you should merge the current `app` folder *up* into `src, not `components` *down* into `app`. To be clear, here's the layout I have in mind:

```
<root>/
 ├─ e2e/
 ├─ gulp/
 |
 └─ src/
     ├─ assets/
     |   └─ images/
     |       └─ ...
     ├─ components/
     |   ├─ navbar/
     |   |   └─ ...
     |   └─ ...
     ├─ main/
     |   └─ ...
     ├─ index.js
     ├─ index.css
     ├─ index.html
     ├─ vendor.css
     └─ 404.html
```
(Note that `assets` does not comply with the guidelines (neither today nor with the PR), instead the guideline says to put them into either `components` or a seperate directory on the root level. Personally I don't mind keeping it like it is right now.)

Now, I don't see how this structure would impede @intellix in spotting "where to look for the code" (the modules are still in their own folder, even a level higher up). Can you maybe elaborate?

**Comment by zckrs** [comment]
@fubu guidelines show sample app without a complex workflow (no injection, no gulp, no dist folder).

The `app` folder exist to separate the angular logic and the workflow logic. `index.html` is heavy manipulate by Gulp

**Comment by zckrs** [comment]
@fubu There are other examples where `app`, `assets` and `index.html` are on the same level 

https://scotch.io/tutorials/angularjs-best-practices-directory-structure#a-better-structure-and-foundation
https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y141

**Comment by fubu** [comment]
IMHO the workflow-related logic is already seperated (on the root level, see `gulp`, `e2e` and the like next to `src`). The guidelines don't mention them, as they have an obvious place: right next to the source folder. Also, I wouldn't consider `index.html` workflow logic - quite the opposite, and according to the guidelines it should lie next to `index.js`. (If "gulp manipulation" matters for this, why is `index.css` inside `app` then?)

As of the other styleguides: I don't get why "scotch" puts view templates next to the controllers for modules, but doesn't do the same for the "root module" (`app.js` next to `index.html`, because they clearly belong together). JohnPapa's styleguide is nice, but deviates quite a bit from the guidelines, and also primarily states "Make locating your code intuitive, simple and fast." - something this generator already achieves by the organizing-by-module approach, with or without the proposed change.

I personally just don't see the point of having *yet another* subfolder in `src` to put everything in. This split seems rather random to me.

(And don't get me wrong, your generator is still awesome!)

**Comment by zckrs** [comment]
Really I understand your view.
>Why keep a unnecessary folder ?
But I think it is better that way to keep separation between the angular's code and the rest.

**Comment by eseceve** [comment]
I always remove the app folder after generate a new project.

**Comment by fubu** [comment]
> But I think it is better that way to keep separation between the angular's code and the rest.

With your PR there is now only two things seperated from the "angular code": The assets/images and the basic HTML templates (`index.html` and `404.html`).

I already mentioned the assets, but please at least answer me this: `index.html` contains the starting point for the angular app, so why is it seperate from the app code itself? It also probably bootstraps some/most of the basic layout, but yet the styles are defined inside `app`? Why not put those HTML files into `app` as well?

Remember that `app` eventually will contain a lot of other HTML files as well. (And if the risk of putting "index.html" into the templateCache is a concern, then there's a simple glob for that.)

**Comment by zckrs** [comment]
A pull-request to remove `app` would maybe can merged.

**Comment by jamm** [comment]
@tlvince was right...
