### ISSUE TITLE
Typescript debugging (chrome developers tools)

### ISSUE THREAD

**Issue by hourliert** [Swiip/generator-gulp-angular#273]
Hi,

First of all, many thanks for this generator which gather almost everything to start a typescript angular project.

My project has been generated with the following options : 
angular 1.3, jQuery 2, Restangular, UI router, Angular material, SASS (node), Typescript, Jade

I have a problem when I try to serve my project (in debug mode) : everything works, but when I try to debug it in chromium developers tools, I can't see TS files. I only see TS compiled to JS files. This is very annoying and inconvenient. 
SourceMappingUrl comment in JS files doesn't load correctly the TS file. I always get a 404 not found because it considers the absolute path as relative. For example, it tries : 
"http://localhost:3000/Users/thomashourlier/development/jsProjects/v2-co-net-front/app.ts"
In fact "/Users/thomashourlier/development/jsProjects/v2-co-net-front/app.ts" is the absolute filesystem path.

Any solutions to fix this ?
Thanks in advance.

Edit : It seems this problem is caused by a bad file rename. Stock generated project doesn't have this problem.

**Comment by andrea-spotsoftware** [comment]
Is it normal to see js syntax in ts files exposed by chrome dev tools during debugging?
