### ISSUE TITLE
Could you help me to add the gulp-react to a project ? 

### ISSUE THREAD

**Issue by uaKorona** [Swiip/generator-gulp-angular#278]
Hi. 
I use your generator-gulp-angular in my projects and it's awesome! 
Now I want use React and *.jsx templates.
I finded the gulp plugin for React - https://www.npmjs.com/package/gulp-react 
but don't  understand how to add its to my project's configuration. 

I tried to change the "inject.js" follows:
```javascript
 var injectJSX = gulp.src([
    paths.src + '/{app,components}/**/*.jsx'
  ]).pipe(react());
```
 ....  
```javascript 
return gulp.src(paths.src + '/*.html')
    .pipe($.inject(injectStyles, injectOptions))
    .pipe($.inject(injectJSX, injectOptions))
    .pipe($.inject(injectScripts, injectOptions))
    .pipe(wiredep(wiredepOptions))
    .pipe(gulp.dest(paths.tmp + '/serve'));
```
But it doesn't work correctly 
Could you help me ?

**Comment by Toilal** [comment]
You need to create javascript files using `react()` first and write them to a temporary directory, and then inject them with wiredep, you can't do all in a single step.

Create a task to compile JSX to JavaScript ...
```js
gulp.task('jsx', function () {
 return gulp.src([
    paths.src + '/{app,components}/**/*.jsx'
  ]).pipe(react())
 .dist(paths.tmp + '/jsx');
```

And then depend from this task to wiredep generated javascript files in index.html
```js
gulp.task('inject', ['styles', 'jsx'], function () { // Depend on jsx compile task
....
 var injectJSX = gulp.src([
    paths.tmp + '/jsx/**/*.js' // *.js because react() compiles to javascript
  ]).pipe(react());
...
return gulp.src(paths.src + '/*.html')
    .pipe($.inject(injectStyles, injectOptions))
    .pipe($.inject(injectJSX, injectOptions))
    .pipe($.inject(injectScripts, injectOptions))
    .pipe(wiredep(wiredepOptions))
    ...
);
...
```

I didn't try, it may have caveats, but idea is there.

**Comment by uaKorona** [comment]
Oh, thanks a lot! It's that what I wanted
