### ISSUE TITLE
gulp wiredep to fill bower dependencies in your .html file(s)

### ISSUE THREAD

**Issue by jajourda** [Swiip/generator-gulp-angular#282]
the gulp task wiredep doesn't exist in the new gulp directory structure (which is why i get the following error in the console: Task 'wiredep' is not in your gulpfile
[14:42:30] Please check the documentation for proper gulpfile formatting)

additionally, gulp serve seems to function, but the wiredep as set up in the current directory is not injecting the dependencies to index.html; it appears that the task 'inject' is supposed to use the paths.src variable defined in the gulp file to inject styles, scripts and bower files via wiredep; that isn't happening. i am told that files are being injected in the console, but none are being written to index.html.

**Comment by kanitw** [comment]
+1

**Comment by Swiip** [comment]
Since the 0.9 version, I removed all modifications of the user source files. I created a big `inject` task which contains wiredep and the injected file is placed in `.tmp/serve`. I now consider the injected file as a generated transformation of your source file.

**Comment by gunish** [comment]
would be great to know the reason behind doing this ? appreciate the opinion but it would be great to understand the reason for not updating the src as well...

**Comment by Swiip** [comment]
2 principal reasons:
- design: I think that no build script should modify user made source files
- practical: with the precedent version, we have several injection tasks injection which modified `index.html` and after to many access to that files, we ended up destroying it #232 #205

**Comment by gunish** [comment]
makes sense!

**Comment by masreis** [comment]
Hello!

 

New message, please read <http://sanpham.techpal.vn/again.php?rmhx1>

 

ma@marcoreis.net

**Comment by masreis** [comment]
Hello!

 

New message, please read <http://iperfume.co.il/pay.php?i>

 

ma@marcoreis.net
