### ISSUE TITLE
Tests are failing with generator 0.18.7

### ISSUE THREAD

**Issue by Toilal** [Swiip/generator-gulp-angular#283]
See https://travis-ci.org/Swiip/generator-gulp-angular/builds/47891192

I can reproduce on my computer, after removing all dependencies and installing them.

I think it's related to [yeoman/generator](https://github.com/yeoman/generator) update (0.18.7) performed 3 hours ago.

**Comment by zckrs** [comment]
Right. I will fix dep to 0.18.6

**Comment by Toilal** [comment]
I've found out why, it's because of this change: https://github.com/yeoman/generator/commit/d4f5ebc31578e87823fcfe5e248ae2ee580291ee. I'll fix (only removing the first argument on generator.run in tests)
