### ISSUE TITLE
Add clean before build task

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#286]
It would be nice I think if we did a `gulp clean` before executing the gulp build task.  This way removed files get cleaned up etc.  Thoughts?

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/_gulpfile.js#L22

Just use `gulp` instead of `gulp build`

**Comment by wgorder** [comment]
doh thanks :)
