### ISSUE TITLE
How to inject vendor latest libraries

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#287]
So I have a predicament where I am using jade, coffee and less.  I am using a few vendor libraries that are either not available in bower or I had to hack them or use the 'latest'.  These are typically .js and .css files.  What would be the easiest way to inject this into the gulp build process and append them to the vendor stuff?

**Comment by Swiip** [comment]
You can put `<script>` and `<link>` tags in your html file if you put them in the right line. You have to be inside the `<!-- build` comments to be included but outside of the `<!-- bower` or `<!-- inject` not to be override.

**Comment by wgorder** [comment]
Excellent!,  I was hoping you had allowed a way for this.  Great work on this generator, we needed something like this.

**Comment by Swiip** [comment]
Thanks :)

**Comment by masreis** [comment]
Hello!

 

New message, please read <http://neox.tmpl.mk.ua/ladies.php?h8zfl>

 

ma@marcoreis.net

**Comment by masreis** [comment]
Hello!

 

New message, please read <http://oficinacriativa-d.com.br/corner.php?5>

 

ma@marcoreis.net

**Comment by masreis** [comment]
Hello!

 

New message, please read <http://webfactory.webbandit.co.za/lived.php?0izep>

 

ma@marcoreis.net
