### ISSUE TITLE
templateCachHtml.js not being generated.

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#291]
I am using jade.

I found that in my `partials` task the following line needed to be changed from:
`paths.tmp + '{app,components}/**/*.html'`
to
 ` paths.tmp + '/serve/{app,components}/**/*.html'`

Jade is outputting my compiled .html files under an additional serve directory now, so I am no longer picking them up with the former. You don't see it on the sample because when bootstrapping the application with the generator no Jade files are actually created.  Oddly the serve directory must be a new addition as I don't recall this being the case in an earlier version.

**Comment by Toilal** [comment]
:+1:

**Comment by Toilal** [comment]
The problem occurs even without Jade.
