### ISSUE TITLE
angularTemplateCache assumes all partial html files to be cached

### ISSUE THREAD

**Issue by kikoanis** [Swiip/generator-gulp-angular#295]
As of the current version 0.9.1, the template cache will try to minify all partial html files and add them to the angular Template cache. Is that acceptable if you have a large application where you would have a large main app file where all templates are added (downloading such file would be an issue). 

Not sure if we need to let gulp not to add some files to the cache (based on some mid-extension) and rather just minify and copy them with the same origin folder structure.  

Can someone let me know what are the best practices for this matter?

**Comment by Swiip** [comment]
Why doing less even if it's not absolutely needed. And it's better to have it soon before your app grows and you'll really need it. Some optimizations are complicated to handle but this one works smoothly so why not using it?

If you really don't want it, remove the partials task, the inject partials in the html task and add a copy *.html from src to dist...

**Comment by intellix** [comment]
Actually, this is something I felt was missing. In the generator-angular repos there's a longggg thread talking about application structure and one thing mentioned is partials should be named as: `blah.tpl.html`.
Our partials task: `gulp.src(['src/**/*.tpl.html']).pipe(...);`

We have some large templates containing paragraphs of SEO text that I don't feel should be bundled within the app, shouldn't require a deployment and I don't mind it being pulled in dynamically, which are named as: `blah.seo.html` and are added during the copy task.

**Comment by Swiip** [comment]
That's fine with me but too specific to be handled in the generator. Take your gulp files, it should not be too difficult to make what you ask. Just exclude seo files from the current mechanism and add the copy of this files.

**Comment by intellix** [comment]
We are doing as said :)

**Comment by Swiip** [comment]
If you're willing some code snippet here, we can keep it as a recipe.

We're trying to gather recipes in issues and expose them later on the wiki.

**Comment by zckrs** [comment]
@intellix  do you have a code snippet ?

**Comment by intellix** [comment]
I've stripped out the chunk of the process, as what I currently have isn't inline with the latest generator, but think it's straightforward enough to understand how it's done.

1) Blacklist the .seo.html files during partials task
2) Copy the seo files afterwards into dist

```js
gulp.task('partials', function () {
  return gulp.src([
      'src/**/*.html',
      '!src/**/*.seo.html'
    ])
    .pipe(gulp.dest('.tmp/src'))
    .pipe($.size());
});

gulp.task('copy', function () { 
  return gulp.src([
      'src/**/*.seo.html'
    ])
    .pipe(gulp.dest('dist/'));
});

gulp.task('build', [
  'partials',
  'copy'
], function() {
    gulp.start('deploy');
});
```
