### ISSUE TITLE
TemplateCacheJS not being injected into index.html

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#297]
So https://github.com/Swiip/generator-gulp-angular/issues/291 fixed half the problem.  The file is now there but it is still not being injected into index.html in the block where it says it should be e.g. the below is always empty

```
    <!-- inject:partials -->
    <!-- angular templates will be automatically converted in js and inserted here -->
    <!-- endinject -->
    <!-- endbuild -->

```
 so `gulp serve` is attempting to hit the server to request those files and of course coming up with nothing.  I am a bit hazy on how the inject stuff works but I am trying to sort it out now.  Let me know if I am missing something on how this should be working.

**Comment by wgorder** [comment]
Ok so can someone explain this chunk to me from `inject.js`?

```
 var injectOptions = {
    ignorePath: [paths.src, paths.tmp + '/serve'],
    addRootSlash: false
  };

  var wiredepOptions = {
    directory: 'bower_components',
    exclude: [/bootstrap\.js/, /bootstrap\.css/, /bootstrap\.css/, /foundation\.css/, /font-awesome\.css/]
  };

  return gulp.src(paths.src + '/*.html')
    .pipe($.inject(injectStyles, injectOptions))
    .pipe($.inject(injectScripts, injectOptions))
    .pipe(wiredep(wiredepOptions))
    .pipe(gulp.dest(paths.tmp + '/serve'));

```

It looks like to me that we are only injecting from src and ignoring temp (via injectOptions)?  If that is the case with jade we will find nothing as there are only jade files in src all the html are in .tmp...  Am I missing something?

**Comment by wgorder** [comment]
Ok.  So I don't know if it is because I am on a windows machine here (have to test on my mac at home too), but for whatever reason moving the inject stuff for templateCacheHtml.js out of the `html` task in build.js and into `inject.js` with the rest of it, fixed the problem.  I also added a dependency on the `partials` task when doing the inject.

It probably makes sense for all the injection to be done in inject.js anyway rather then having it scattered about.  This still leaves the `gulp serve` task broken of course I really don't use that but it is getting closer.  If someone who knows more about all this wants to jump in and tell me a better way I am all ears.

**Comment by wgorder** [comment]
Ok course moving it seems to have a side affect of breaking gulp watch as well.  Worked around it by adding `html` along with `markup` to the jade watch task.

**Comment by Toilal** [comment]
When running `gulp watch` mode, templates are read directly from `.tmp/serve` without caching them. `templateCache.js` is generated only with running `gulp` for distribution.

**Comment by wgorder** [comment]
Hmm OK.  Well that makes a lot of it more clear.  However I guess what got me going down the wrong path was I did not see it injected even in my distribution index.html (in the dist folder).  Let me back out my changes later and confirm that was not a fluke on my part or and oversight.  If its there I will close this.

**Comment by wgorder** [comment]
Ok you are absolutely correct.  I don't know what happened that it did not work for me before.  Sorry about that.

**Comment by nadavelyashiv** [comment]
Hi, 
I'm sorry, I'm also new to gulp and I just can't figure out this issue.
When I use 'gulp serve:dist' my $templateCache is working well, since it is concatenated to app.js.
But when I use 'gulp serve' (meaning, serving the html from .tmp), I can  see the templateCacheHtml.js file in  /.tmp/partials, but it is not injected where it should be (to my understanding, at starttag ), and therefore my $templateCache has no templates (when I use 'get' function).
if I add it manually to the html file, it works fine.
How can I fix it in the gulp scripts?
Thank you,
Nadav

**Comment by maciej-gurban** [comment]
I'd be interested in an answer as well. Is there an easy fix to populate $templateCache also in when running gulp serve (not :dist)? 

The application might actually depend on $templateCache to be there for some business logic, so at least having an option to cache the templates would make sense. Is there any chance you could suggest a solution to this?
