### ISSUE TITLE
Bower js files not being added in vendor js

### ISSUE THREAD

**Issue by jivalaraza** [Swiip/generator-gulp-angular#300]
I am trying to use flexslider into the project. I installed it with the command "bower instal flexslider --save". But when I try to build the project, it isn't updating vendor.js with source code of flexslider, hence not fulfilling my desire to use it. I'm being able to add it's less file properly. But not the script one. Would you please look into it? Or am I doing something wrong in the way to use bower components in project?

**Comment by drock07** [comment]
I'm having a similar problem except that it's not including angular.js in the vendor.js file, which is breaking everything.

**Comment by drock07** [comment]
I figured out my problem. A js file that was included before angular.js was missing ";" at the end of its module statement. The js file was auth0-lock.js from Auth0 ([auth0/lock](https://github.com/auth0/lock)), and it looks like they might be using browserify, which, when converting the "require" statements into browser-ready javascript, left the final semicolon off. 

Swiip, it's worth noting this if you're planning on incorporating browserify into the generator.

**Comment by Swiip** [comment]
@jivalaraza It depends of your lib and it's bower.json configuration. If script files are not configured, wiredep will not be able to include it. But you always can put the script yourself if you place it outside of ```<!-- bower``` but inside ```<!-- endbuild -->```

@drock07 Browserify is planned but not for soon.

**Comment by zckrs** [comment]
Should be fix with master
