### ISSUE TITLE
Add woff2 to font extentions

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#304]
There is an additional font extension we are not grabbing --  `woff2`
https://github.com/FortAwesome/Font-Awesome/tree/master/fonts

This leads to 404's when font awesome is used since the woff2 font is not copied to dist

**Comment by alexpaluzzi** [comment]
This was added in #298

**Comment by wgorder** [comment]
Not sure how I missed that. Thanks.
