### ISSUE TITLE
gulp wiredep missing

### ISSUE THREAD

**Issue by koraybalci** [Swiip/generator-gulp-angular#308]
It's in the documentation but I cannot see it in repository, neither can I run 'gulp wiredep' in a fresh installation.

**Comment by Toilal** [comment]
The related task is `inject`, see `gulp/inject.js`.

It runs wiredep from `src/index.html` and copy result file to `.tmp/serve/index.html` without modifing source index.html (and polluting your git repository with useless commits).

**Comment by koraybalci** [comment]
Awesome, thanks a lot. Documentation about wiredep was misleading then.

Cheers.
