### ISSUE TITLE
vendor css not injected by wiredep

### ISSUE THREAD

**Issue by zhenyi2697** [Swiip/generator-gulp-angular#312]
In the index.html file, there is a comment who says: 

I noticed that the `wiredep` has been replaced by `inject` task. So this is a little misleading for me.
However, even with `inject` task, vendor css files cannot been injected into the  block using wiredep. (But it works for js files).

Do we need to include vendors css files manually by adding `<style>` or `<link>` tag?

Thanks in advance.

**Comment by Swiip** [comment]
I rename the gulp task recently and not updated the comments sorry.

Wiredep is still there inside the inject task. It will insert all deps found in your bower_components and correctly configured in the bower.json configuration file of the library.

You can check the result in `.tmp/serve/index.html`. If your lib isn't inserted you can manually add them in index.html as long as you're in the build comment but outside of the bower comment.

**Comment by zhenyi2697** [comment]
Thanks for your quick reply !
You are right, I didn't configure it right in the bower.json file. It works now.

Thanks very much for your work on this project. Merci beaucoup et bonne continuation :+1:
