### ISSUE TITLE
How to control the order of injected js files?

### ISSUE THREAD

**Issue by lancevo** [Swiip/generator-gulp-angular#314]
I have some js files need to be loaded before some controllers. Sometimes gulp load these js files, other times after the controllers and it broke the app. Is there a way to control this?

**Comment by Swiip** [comment]
Which options do you use? We use the angular file sort plugin to order files. This should be enough normally.

**Comment by csablons** [comment]
I guess he talk about the $.angularFilesort() in the 'injector:js' task.

**Comment by lancevo** [comment]
Yes it's using angularfilesort that does the injection.

**Comment by Swiip** [comment]
With angularFilesort, you just shouldn't have any problems... It assures Angular's dependencies to be ordered well.

**Comment by csablons** [comment]
In theory maybe, in fact no :)
By example if I write in a file :
`var controllers = angular.module('controllers', []);`
and in another file :
`controllers.controller('MainCtrl', ['$scope', function ($scope){...}]);`

My second file may be inject before my first file.

**Comment by Swiip** [comment]
Ok, I didn't test all use cases of angular sort. Try with a syntax like that:

```javascript
angular.module('controllers', []);
```
```javascript
angular.module('controllers').controller('MainCtrl', function ($scope) {...});
```

It should work better and to be honest, I like way better than using a variable from a file to another.

**Comment by csablons** [comment]
It's what I'm doing now.
I like variables for simplify the visibility... but it's not a big issue :)

**Comment by zckrs** [comment]
@lancevo Do you resolve your issue ?

**Comment by lancevo** [comment]
It resolved my issue. Thanks

**Comment by goncalomarques** [comment]
@lancevo How did you solve it?

**Comment by lancevo** [comment]
Actually I worked around it. Because I don't think there's any filter capable of handling different odd cases. So I excluded the files I want to load in sequence and moved them to another folder. I excluded this folder in gulpfile.js, and manually reference in , so they will get included in the build.

**Comment by goncalomarques** [comment]
Thats a little bit intrusive, but I guess it works for you.. I think my variation of the issue solved itself when I stopped injecting unmet dependencies. angular-filesort must've been misbehaving when so. Probably a good thing to check on later.
