### ISSUE TITLE
Fonts from bower_components do not copy to dist

### ISSUE THREAD

**Issue by volodchenkov** [Swiip/generator-gulp-angular#316]
Hi.
I try to use latest version generator with foundation.
I installed it:
`yo gulp-angular`
I installed foundation-icon-fonts:
`bower install --save foundation-icon-fonts`
and run build:
`gulp fonts && gulp`
but fonts from foundation-icon-fonts do not copy to dist directory.

Can you help me? I think it is bug in generator or in foundation-icon-fonts bower.json file.
I try 3 versions of generator, but it does not work.
Thanks.

**Comment by volodchenkov** [comment]
And you broke gulp wiredep command :(

**Comment by JDiCode** [comment]
Can confirm this!

**Comment by Swiip** [comment]
The wiredep task has been merged in the inject task but it still there.

The font task will copy font listed in the bower.json of any bower dependencies (not only installed but present in the bower_components). It's not the case for your package while it is in bootstrap.

You have to write some additional gulp to copy your fonts.

**Comment by volodchenkov** [comment]
Ok. Thanks.
