### ISSUE TITLE
Add JSCS 

### ISSUE THREAD

**Issue by mohsen1** [Swiip/generator-gulp-angular#317]
It would be nice to have [jscs](https://github.com/jscs-dev/node-jscs) in generated project.

**Comment by Swiip** [comment]
Don't know very well jscs, I was used to relay only on jshint. But it sounds interesting...

**Comment by eseceve** [comment]
http://www.sitepoint.com/comparison-javascript-linting-tools/

**Comment by Swiip** [comment]
Yep, JSCS is one of this tools where I didn't know about 2 month ago and now, I see it everywhere. We'll add support for it, I just don't know when.

**Comment by zckrs** [comment]
Few questions:
* should autofix ?
* which preset use ?
* disable or override rule (like `maximumLineLength`) ?

**Comment by mohsen1** [comment]
I think it should auto-fix. The preset can be selected by user or be the one that is being used for this project.
