### ISSUE TITLE
Add "scripts/test" in package.json

### ISSUE THREAD

**Issue by mohsen1** [Swiip/generator-gulp-angular#318]
In generated package.json there could be a scripts/test command that should run the tests

**Comment by Swiip** [comment]
Yep :)

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/blob/master/app%2Ftemplates%2F_package.json#L5
Already present.

Can we close @mohsen1 ?

**Comment by mohsen1** [comment]
Yes. Thanks!
