### ISSUE TITLE
Debugging in Webstorm?

### ISSUE THREAD

**Issue by jamesdixon** [Swiip/generator-gulp-angular#321]
Hi,

First, excuse my stupidity in advance as this is a new arena to me. I'm using this generator with Typescript and am having issues with Javascript debugging in Webstorm. I first attempted to set up a debug configuration that points to the default 'gulp serve' port of 3000, but I was getting a connection refused error. I then switched to the default Webstorm server and pointed it to the 'dist' directory and had it run 'gulp build' beforehand. The only issue is that it doesn't seem to be able to debug Typescript files because they've been compiled for production and there is no sourcemap. Does anyone have a working configuration they can recommend? I'd really like to be able to use Webstorm's Typescript debugging capabilities in tandem with this fantastic generator.

Best,
James

**Comment by Swiip** [comment]
Currently, the generator handles sourcemaps in development mode but not in the production mode. It's difficult (impossible?) to make sourcemaping works with useref.

**Comment by jamesdixon** [comment]
Thanks. I'm guessing you're not using Webstorm in this configuration?

**Comment by Swiip** [comment]
I don't use webstorm no, sublime or atom. When I debug, I use chrome dev tools. It should be a solution to connect the webstorm debugger with the serve task, but I don't have experience with this...

**Comment by jamesdixon** [comment]
Appreciate the quick reply. If I figure it out, I’ll make sure to post it here for others.

**Comment by mthomson-csi** [comment]
I had to set the following setting in WebStorm to fix the performance issue.  The performance issue wasn't related to the generator or TypeScript compilation.

Disable Any Breakpoint debugging for V8
   - Help->Find Action...
   - Type Registry and enter
   - Uncheck "js.debugger.v8.use.any.debugger"

For debugging TypeScript, enable TypeScript Compiler
   - Settings->Languages & Frameworks->TypeScript
   - Check Enable TypeScript Compiler
   - Use node from nvm install
   - Use tsconfig.json

Here are the settings I used for configuring the debug configuration:
 - Configuration:
    - Type: Node.JS
    - Name: Debug
    - Node Interpreter: /usr/bin/node
    - JavaScript file: /usr/lib/node_modules/gulp/bin/gulp.js
    - Application parameters: serve --color
 - Browser / Live Edit
    - After Launch: Checked
    - Url: http://localhost:3000/
    - with Javascript Debugger: Checked
