### ISSUE TITLE
When there is a less syntax error, `gulp watch` quits

### ISSUE THREAD

**Issue by mohsen1** [Swiip/generator-gulp-angular#322]
I know I'm opening a lot of bugs but having these issues listed here is better that not having them. Maybe I find some time to fix these. 

:smile:

**Comment by Swiip** [comment]
I'll check. This has been fixed but could have been broken. That's why I'm working so hard on testing lately.

**Comment by dts** [comment]
+1, this is happening to me.

**Comment by zckrs** [comment]
https://github.com/floatdrop/gulp-watch/blob/master/docs/readme.md#prevent-pipe-breaking-on-errors

Using gulp-watch + gulp-plumber can be a solution

**Comment by zckrs** [comment]
To avoid adding more deps, use `.on('error', function () {})`
