### ISSUE TITLE
minification problem

### ISSUE THREAD

**Issue by Tallyb** [Swiip/generator-gulp-angular#323]
Hi, 
when running the serve my project runs just fine, but when running serve:dist - the following error occur. 
Seems like minification issue, and it seems to be on angular (???)
anyone has an idea how to start untangling this? 

Error: [$injector:unpr] Unknown provider: eProvider <- e
http://errors.angularjs.org/1.3.11/$injector/unpr?p0=eProvider%20%3C-%20e
    at vendor-6c082ca7.js:31
    at vendor-6c082ca7.js:31
    at Object.r [as get] (vendor-6c082ca7.js:31)
    at vendor-6c082ca7.js:31
    at r (vendor-6c082ca7.js:31)
    at Object.i [as invoke] (vendor-6c082ca7.js:31)
    at request (vendor-6c082ca7.js:99)
    at u (vendor-6c082ca7.js:32)
    at vendor-6c082ca7.js:32
    at p.$eval (vendor-6c082ca7.js:33)

**Comment by Swiip** [comment]
That should have been prevented by ngAnnotate. It clearly failed this time. There is a few cases ngAnnotate could miss an injection, look there: https://github.com/olov/ng-annotate

**Comment by Tallyb** [comment]
wow! that was fast. any tip on how to locate the bad annotation?

**Comment by Swiip** [comment]
Search for any injected function outside of the standard `angular.module(...).service(..., function() {});`

If you use a js preprocessor, the question is more complicated because ngAnnotate can't handle a langage it doesn't understand...

**Comment by Tallyb** [comment]
I do not use a pre processor. I solved it by explicitly annotating everything, and then it could not find my HTMLs. Any idea?

**Comment by wgorder** [comment]
I have found ng-annotate to be undependable so I just make sure all my stuff is annotated explicitly.  This is especially true for ui-router controllers etc.  ng-annotate is supposed to recognize them but never does.  What you can do if you are using angular 1.3 is add ng-strict to your root tag.  Then angular will barf if it encounters anything that is not minification safe.  This way you will know you did not miss anything.

```
<html class="no-js" ng-app="myApp" ng-strict-di="true">
```

There is more than one way to annotate as well.  Sometimes I find using the ..$inject method more convenient than inline annotations.

https://scotch.io/tutorials/declaring-angularjs-modules-for-minification

**Comment by zckrs** [comment]
@Tallyb please do you have a code example when ng-annote failed ?

**Comment by Tallyb** [comment]
I am afraid not. I annotated everything, and now I cannot find the relevant code (also, it was a one off so I am no longer working on this project).

**Comment by zckrs** [comment]
Should be fix with master
