### ISSUE TITLE
Stop manually injecting dependencies in ES6 modules

### ISSUE THREAD

**Issue by mohsen1** [Swiip/generator-gulp-angular#324]
ngAnnotate now supports ES6 DI for Angular.

https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/src/app/main/_main.controller.es6#L13

Although I wasn't able to make it work on my project but according to ng-annotate project it should work!

**Comment by Swiip** [comment]
I made some tests before coming to this. And there is the question of 6to5 or Traceur.

I'll check if there is some news but don't hope too much..

**Comment by zckrs** [comment]
This issue should be fixed in master.
@mohsen1 can you check and close issue if you are ok ?

**Comment by mohsen1** [comment]
My initial project drifted a lot from code generated by gulp-angular. If you've fixed it and you know it then lets close it :smile:
