### ISSUE TITLE
.pipe($.consolidate('hamljs')) throws an error

### ISSUE THREAD

**Issue by 360disrupt** [Swiip/generator-gulp-angular#325]
I always get this error:
`TypeError: Object #<Object> has no method 'hamljs'`
from markups.js line 15 the error is thrown on line 17. 

The $.consolidate function looks like this 
`module.exports = function (engine, data, options) {
	"use strict";

	options = options || {};

	if (!engine) {
		throw new Error("gulp-consolidate: No template engine supplied");
	}

	try {
		if (engine === "hogan") {
			require("hogan.js");
		} else {
			require(engine);
		}
	} catch (e) {
		throw new Error("gulp-consolidate: The template engine \"" + engine + "\" was not found. " +
			"Did you forget to install it?\n\n    npm install --save-dev " + engine);
	}`

there is a node module in the node_modules folder:
hamljs

I also tried to reinstall.

**Comment by 360disrupt** [comment]
The solution is:
1)
 install new package & uninstall old one
`sudo npm install gulp-haml --save --dev && npm unistall hamljs --save --dev`
2)
Change the code in markup.js

gulp.task('markups', function() {
  function renameToHtml(path) {
    path.extname = '.html';
  }

  return gulp.src(paths.src + '/{app,components}/**/*.haml')
      .pipe($.haml({ext: '.html'}))
      .on('error', function handleError(err) {
        console.error(err.toString());
        this.emit('end');
      })
      .pipe(gulp.dest(paths.tmp + '/serve/'));
});

**Comment by zckrs** [comment]
I cant reproduce with master

**Comment by phedinkus** [comment]
I know you changed it in the main gulpfile but it seems other modules depend on hamljs. I get a similar error coming from gulp-consolidate:
```
Error: Cannot find module 'hamljs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Function.exports.haml.render (/Users/kt/Code/beth_bot/generalizer/client/node_modules/gulp-consolidate/node_modules/consolidate/lib/consolidate.js:386:54)
    at /Users/kt/Code/beth_bot/generalizer/client/node_modules/gulp-consolidate/node_modules/consolidate/lib/consolidate.js:146:25
    at /Users/kt/Code/beth_bot/generalizer/client/node_modules/gulp-consolidate/node_modules/consolidate/lib/consolidate.js:99:5
    at fs.js:272:14
    at /Users/kt/Code/beth_bot/generalizer/client/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:104:5
    at /Users/kt/Code/beth_bot/generalizer/client/node_modules/wiredep/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:104:5
```
Any thoughts?

**Comment by Swiip** [comment]
Seems you still have a reference for "haml**js**". You should only have "haml"

**Comment by phedinkus** [comment]
I installed the generator from scratch, changed the main template to the haml syntax and haml extension and ran `gulp serve`. The error comes from a node module required by the generator. I had a hunch that you aren't seeing the error because you have the hamljs module still installed on your system. So I installed it manually with `npm install hamljs` and ran `gulp serve` and the error went away.

**Comment by sb8244** [comment]
I had to npm install hamljs to get this working with a new generated project
