### ISSUE TITLE
jshint is not running

### ISSUE THREAD

**Issue by Tallyb** [Swiip/generator-gulp-angular#326]
{
  "generator-gulp-angular": {
    "props": {
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      },
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "name": "angular-animate",
          "module": "ngAnimate"
        },
        {
          "name": "angular-cookies",
          "module": "ngCookies"
        },
        {
          "name": "angular-touch",
          "module": "ngTouch"
        },
        {
          "name": "angular-sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "name": null,
        "version": null
      },
      "resource": {
        "name": "restangular",
        "version": "~1.4.0",
        "module": "restangular"
      },
      "router": {
        "name": "angular-ui-router",
        "version": "~0.2.13",
        "module": "ui.router"
      },
      "ui": {
        "name": "bootstrap-sass-official",
        "version": "~3.3.1",
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "name": "angular-strap",
        "version": "2.1.x",
        "key": "angular-strap",
        "module": "mgcrea.ngStrap"
      },
      "cssPreprocessor": {
        "key": "less",
        "extension": "less",
        "module": "gulp-less",
        "version": "~1.3.6"
      },
      "jsPreprocessor": {
        "key": "none",
        "extension": "js",
        "srcExtension": "js",
        "module": null,
        "version": null
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html",
        "module": null,
        "version": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      }
    }
  }
}

**Comment by Toilal** [comment]
Will work with #279.

**Comment by Swiip** [comment]
Yep, it's planned to fix this.
