### ISSUE TITLE
Gulp wiredep is missing.

### ISSUE THREAD

**Issue by krzksz** [Swiip/generator-gulp-angular#332]
So I just generated new project and installed new dependencies with Bower but they're not getting properly injected. When running `gulp wiredep` I get error saying that this task is missing and there is no `wiredep.js` file in `gulp` directory. Is this normal behaviour? Did something change that is not noted in readme?

**Comment by Swiip** [comment]
Sorry, the readme is a little outdated, the `wiredep` task had beed merged in a new `inject` task. Look at `gulp/inject.js`.

**Comment by krzksz** [comment]
Oh, I see. I'm almost certain you're missing `bower:css` comment then. It is also worth mentioning that vendor files get injected only to `dist` files in contrast to `grunt-webapp` which puts them into `app/index.html` too.
