### ISSUE TITLE
Sorting files for karma (with Typescript)

### ISSUE THREAD

**Issue by hourliert** [Swiip/generator-gulp-angular#333]
Hi,
Sorting files then inject it work (when using Typescript). But when I try to run test (via gulp test). File order isn't kept. sortOutput.json is totally ignored by this task.

Is it possible to correct this ?
Thanks in advance.

**Comment by Swiip** [comment]
Seems to be messing indeed. Thanks for reporting.

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/433
