### ISSUE TITLE
Application not functioning in serve:dist (Unable to locate html files)

### ISSUE THREAD

**Issue by jpoiri** [Swiip/generator-gulp-angular#334]
Hi there,

I am having a issue when running the optimized version of my application I get a blank screen  on startup. 

When looking at the console I have the following error:

Failed to load resource: the server responded with a status of 404 (Not Found) - Cannot GET /app/get-quote/get-quote.html

When I am run the non-optimized version it works perfectly.

Here's how my application is structured 

![structure](https://cloud.githubusercontent.com/assets/6857740/6107064/9eefa534-b03d-11e4-9853-42028889472a.png)

Here`s how the state provider is defined

      $stateProvider.state('quote', {
        url: '/',
        templateUrl: 'app/get-quote/get-quote.html',
        controller: 'getQuoteCtrl'
      });

      $urlRouterProvider.otherwise('/');

Is there something wrong with how I structured my application? Or there something I need to change in the GULP build to make it work with the optimized version.

Thank you
Justin

**Comment by Tallyb** [comment]
remove the app/ so your path should be 'get-quote/get-quote.html'

**Comment by jpoiri** [comment]
I updated the to 

  $stateProvider.state('quote', {
    url: '/',
    templateUrl: 'get-quote/get-quote.html',
    controller: 'getQuoteCtrl'
  });

However still not finding the file. How its your app structure?

**Comment by Tallyb** [comment]
I have a similar structure. I suggest that you open the generated scripts file (app-some number.js) and search for $templateCache - see if it exists and what paths are shown there. it will look something like: 
function(e){e.put('partialName.html' ,)
Also search in the scripts file to see if your 'partialName.html' is actually included.

**Comment by Swiip** [comment]
Something new? You solve your issue? If not, can you create a smaller minimal project pattern reproducing the problem?

**Comment by jpoiri** [comment]
I resolved the issue it was due to unclosed spam tag
