### ISSUE TITLE
<!--[if lt IE 9 ]> got removed

### ISSUE THREAD

**Issue by jamm** [Swiip/generator-gulp-angular#336]
<!--[if lt IE 9 ]> got removed on "gulp" task.

Very important bug for me, because I can't deploy message for IE8 users to production...
If somebody knows any workarounds - please let me know

**Comment by Swiip** [comment]
Duplicate for #331. The solution is in the other issue. It definitely has to be handled...

**Comment by jamm** [comment]
thanks
