### ISSUE TITLE
Where is the wiredep.js or task defn? I don't see it in 0.9.1 version

### ISSUE THREAD

**Issue by tyagig** [Swiip/generator-gulp-angular#338]
As per the readme, I think the doc needs to be renamed to "gulp inject"??

**Comment by nikolaz111** [comment]
Same is happenning to me

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/issues/332

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/355
