### ISSUE TITLE
How to choose the order of the injected files?

### ISSUE THREAD

**Issue by csablons** [Swiip/generator-gulp-angular#340]
The 'injector:css:preprocessor' task load my partials in the alphabetical order. Sometimes it's broke css because the order have an impact.
Is there an option for force a preferred order?

**Comment by 360disrupt** [comment]
I did this in the styles.js:
```
var series = require('stream-series');
var preInjectFiles1 =  gulp.src([paths.src + '/app/normalize.scss'], {read: false});
var preInjectFiles2 =  gulp.src([paths.src + '/{refills}/**/*.scss'], {read: false});
```
here you can probably apply regex expressions etc.
& later:
```
.pipe($.inject(series(preInjectFiles1, preInjectFiles2, injectFiles), injectOptions))
```
You can group some scripts. Otherwise I would recommend to exclude scripts where the order is important and to add them manually with imports.

I guess s.th.like this may also work:
```
var injectFiles = gulp.src([
    paths.src + '/{app,components}/**/*.scss',
    '!' + paths.src + '/app/_exclude.scss',
    '!' + paths.src + '/app/index.scss',
    '!' + paths.src + '/app/vendor.scss'
  ], { read: false });
```

with adding imports to your files:
```
@import "myFileA_exclude.scss";
```

**Comment by 360disrupt** [comment]
If you want to use variables after the import e.g. import a `_colors.scss` into your `index.scss` than you need to set `read:true`

**Comment by csablons** [comment]
Thanks for your time.
If I understand, in the 2 solutions there is no automatic injection. That's right?
In this case I prefer just disactive the 'injector:css:preprocessor' and put my import myself. It's simple and I control the order.

**Comment by Swiip** [comment]
This was already reported. It actually is a weakness in the principals.

But you should be able to add your own `@import` in your `index.scss` or `vendor.scss` to ensure some injection comes first. I still have to check if the inject plugin import a file a second time or not if you do.

**Comment by adam-beck** [comment]
@Swiip I will try looking into that issue tomorrow and report back. Would this information be something to consider adding to the documentation? I'm only asking because I had this same question.

**Comment by lebster** [comment]
adam-beck does the file get inject 2x? I am also having this issue after upgrading. I was originally using an order version which let me set the order since it updated the /src/index.html instead of .tmp.

**Comment by thik** [comment]
add number prefix as priority to css filename may work

**Comment by zckrs** [comment]
We have v1.0.0-rc1 on NPM.

I think your issue is resolved. Injection task is rewrite since Feb 2015

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
