### ISSUE TITLE
How do I add my custom fonts?

### ISSUE THREAD

**Issue by npearson72** [Swiip/generator-gulp-angular#343]
I placed fonts in /src/assets/fonts/*

When I run gulp serve, they appear. When I build and run gulp serve:dist they can't be found.

Any ideas?

**Comment by deyceg** [comment]
@npearson72 You'll need to make sure you do a correct path replace in build.js e.g.

```
 .pipe(replace('../fonts', 'assets/fonts'))
```

You'll probably find that your .sccs files and compiled .css files are in different locations relative to the fonts directory which is causing the issue.

**Comment by npearson72** [comment]
ReferenceError: replace is not defined

**Comment by deyceg** [comment]
Sorry @npearson72 , you'll need gulp-replace!

**Comment by npearson72** [comment]
Turns out it was $.replace

And thanks, that got me half way there. I also had to modify the fonts task like this:

```
gulp.task('fonts', function () {
  var files = $.mainBowerFiles();
  files.push('src/assets/fonts/**/*');
  return gulp.src(files)
    .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))
    .pipe($.flatten())
    .pipe(gulp.dest('dist/fonts/'));
});
```
Basically had to append my fonts directory to the array the `$.mainBowerFiles()` spits out.

**Comment by deyceg** [comment]
Good stuff! In hindsight I should have just pasted my task, as it had the concat in there :)
