### ISSUE TITLE
upgrade to a new version

### ISSUE THREAD

**Issue by Tallyb** [Swiip/generator-gulp-angular#345]
I have scaffolded a project, and now I want to upgrade the gulp to a newer version. any recommendations?

**Comment by Swiip** [comment]
Upgrade gulp or the generator ?

Lots of people are afraid of this but if you "re"run the generator on an existing directory, it will ask you before any overriding...

**Comment by zckrs** [comment]
ping @Tallyb

**Comment by Tallyb** [comment]
thanks. worked well.
