### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by priithansen** [Swiip/generator-gulp-angular#346]
Hi,

Is there any plans to implement some sort of gulp build based environment variables system?
Would be nice to have some variables adjusted for distribution.

**Comment by Swiip** [comment]
You could have this by using a plugin like gulp-replace but I doubt we support this at the generator level.

**Comment by intellix** [comment]
I'd recommend **gulp-ng-constant**. You can  have a bunch of `config-<environment>.json` files and do something like:

src/app/config-server.json
```js
{
    "ENV": {
        "name": "server",
        "api": {
            "endpoint": "/api"
        }
    }
}
```

src/app/config-production.json
```js
{
    "ENV": {
        "name": "production",
        "api": {
            "endpoint": "https://www.website.com/api"
        }
    }
}
```

gulp/config.js
```js
var gulp = require('gulp');
var fs = require('fs');
var argv = require('yargs').argv;
var ngConstant = require('gulp-ng-constant');

var environment = argv.env || 'server';
var ENV = JSON.parse(fs.readFileSync('./src/app/config-' + environment + '.json', 'utf8')).ENV;

gulp.task('config', function () {
  gulp.src('src/app/config-' + environment + '.json')
    .pipe(ngConstant({
      name: 'config',
      dest: 'config.js'
    }))
    .pipe(gulp.dest('src/app'));
});
```
`gulp --env=production`

Then just attach the config task to run during your build and server tasks. It'll create a `config` module and you can inject the ENV constant into your services.

**Comment by priithansen** [comment]
Thanks for the insight @intellix. angular-ng-constant was one of the options I stumbled upon when searching the internet but wanted to ask around since I'm quite green with gulp. To me it looks like almost every project would benefit from such an option but maybe it's just me. Anyhow will report here if I get some system going.

**Comment by intellix** [comment]
I also think so actually... it's one of the parts of boilerplate that I add to every project. I was working on also having a config-global.json and merging it with the environment specific one... it seems a no-brainer to have the ability to specify configs globally AND per environment for every project! Even if your API is always `/api`, I think it's good not to hardcode that within services etc.

**Comment by priithansen** [comment]
Thank You very much @intellix the code worked beautifully for my needs. Just added the config task to serve and server:dist and everything is running smoothly.

To me it also looks like a good idea to have this functionality but I'm no pro and understand there might be other considerations I have not taken into account with this.

**Comment by girod** [comment]
I also use this solution with a config.js in my /gulp directory and it works fine to manage env variables. It would be a good thing to integrate it in the generator.

Best regards,

**Comment by eseceve** [comment]
+1

**Comment by pedrodelgallego** [comment]
+1

**Comment by scanferla** [comment]
+1

**Comment by vitorreis** [comment]
+1

**Comment by nanocom** [comment]
+1

**Comment by nanocom** [comment]
I would rather be able to declare my conf in JS rather than JSON.

I have 3 environments, dev test and prod, I added 3 files called app/config.[dev|test|prod].js
In my gulpfile.js I added this:

```javascript
var argv = require('yargs').argv;
var env = argv.env || 'dev';
// ...

var envs = ['dev', 'test', 'prod']; // add your envs here
var ignoredEnvs = _.reject(envs, function (env) {
  return env === cliOptions.env;
});

// ...

var options = {
  // ...
  env: env,
  ignoredEnvs: ignoredEnvs,
  // ...
};
```

And I changed the gulp/inject.js file:

```javascript
var injectScripts = [
   options.src + '/{app,components}/**/*.js',
   '!' + options.src + '/{app,components}/**/*.spec.js',
   '!' + options.src + '/{app,components}/**/*.mock.js'
];

injectScripts = injectScripts.concat(_.map(options.ignoredEnvs, function (env) {
  return '!' + options.src + '/app/config.' + env + '.js';
}));
```

Works fine.

**Comment by nanocom** [comment]
any chance that you accept a PR on this @Swiip @zckrs 
(no ng-constant, just plain js files) ?

**Comment by codeofsumit** [comment]
+1

**Comment by silkroad57** [comment]
since gulp-ng-constant abandoned the .dest option meanwhile, angular takes the generated config-xyz.js files generated in alphabetical order, which is not quite what we usually want.

tintellix' gulp/config.js example (thx) above should now read like
...
    gulp.task('config', function () {
    
        gulp.src('src/app/config-' + environment + '.json')
            .pipe(ngConstant({
                name: 'config'
            }))
            .pipe(rename('config.js'))        
            .pipe(gulp.dest('src/app'));
    
   });
...
may be someone else not so deep into gulp like me will save some time.

**Comment by pablorsk** [comment]
+1

**Comment by cm325** [comment]
This recipe is available now - https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/environment-specific-build.md
