### ISSUE TITLE
gulp serve works fine, gulp serve:dist fails with error

### ISSUE THREAD

**Issue by millarde** [Swiip/generator-gulp-angular#347]
Brand new environment setup (Windows 7), node 0.12, npm 2.5.1, current versions (as of a few days ago) of all related dependencies. I generate a new project and take just about the absolute minimum of everything (standard CSS, HTML, JS, no UI framework, no REST resource, no jQuery and only the sanitize module). No visible issues with any of the processing.  **gulp serve** brings up everything fine.

But **gulp serve:dist** and **gulp build** both fail with:

C:\MyDevProjects\new-scaffolded-test\node_modules\gulp-ng-annotate\node_modules\ng-annotate\build\es5\ng-annotate-main.js:330
    target.$methodName = method.name;
                       ^
TypeError: Cannot assign to read only property '$methodName' of false
    at matchRegular (C:\MyDevProjects\new-scaffolded-test\node_modules\gulp-ng-annotate\node_modules\ng-annotate\build\es5\ng-annotate-main.js:330:24)
    at match (C:\MyDevProjects\new-scaffolded-test\node_modules\gulp-ng-annotate\node_modules\ng-annotate\build\es5\ng-annotate-main.js:36:66)
    at traverse.post (C:\MyDevProjects\new-scaffolded-test\node_modules\gulp-ng-annotate\node_modules\ng-annotate\build\es5\ng-annotate-main.js:995:23)
    at visit (C:\MyDevProjects\new-scaffolded-test\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:50:13)
    at visit (C:\MyDevProjects\new-scaffolded-test\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:44:21)
    at visit (C:\MyDevProjects\new-scaffolded-test\node_modules\gulp-ng-annotate\node_modules\ng-annotate\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:41:25)

Searching made it seem like a strict mode issue, so for fun I deleted 'use strict' wherever I found it with same result.

**Comment by Swiip** [comment]
Strange, this seems to be cover by our tests, I have to check...

**Comment by Swiip** [comment]
Got it, `gulp-ng-annotate` in the version we chose fail with Node 0.12 (verified). Just upgrade this plugin and it should works fine.

Keep the issue open to remember to update the version number.

**Comment by millarde** [comment]
hmm, I did `npm update gulp-ng-annotate` and that didn't fix it.

**Comment by Swiip** [comment]
As the plugin version is written in the package.json, the npm update command will not work. You have to delete the line in the package.json or do a npm uninstall first.

**Comment by millarde** [comment]
sorry, my bad. Just removing the line in the package.json (and then attempting an update) didn't work for me. I updated the line in the package.json to the current version and that did allow me to build. Thanks for your work (and your patience).

**Comment by dnlbox** [comment]
@millarde could you run the command ```npm list ng-annotate``` inside your project? The result should be a ng-annotate 0.13.0 inside of gulp-ng-annotate, I guess.

I faced the same problem and this is how I solved it.

Inside of `node_modules/gulp-ng-annotate/package.json`, change the dependency to:
```
"ng-annotate": "~0.15.0",
```

In `node_modules/gulp-ng-annotate/` run the command `npm update`

I don't know if it is the best solution but it is how I fixed the problem of gulp build using yo with 6to5 option.

@Swiip do you think that could be interesting to do a pull request change it? Or you could do it directly to the project? What do you think?

**Comment by Swiip** [comment]
It's already done in master. gulp-ng-annotate to 0.5.2 which brings ng-annotate 0.15.

We're juste a little late to release the new version...

**Comment by cmullix** [comment]
I had this same problem and I fixed it by making sure /* @ngInject */ was placed before every function or a proper $inject statement

**Comment by chandrabezzo** [comment]
I have error when I dist my project, the javascript when I inspect element the error notice is Uncaught TypeError

**Comment by nilsonsrjunior** [comment]
+1

**Comment by gokhandemirtas** [comment]
+1

I've tried updating annotate plugin, didn't help

**Comment by gokhandemirtas** [comment]
http://stackoverflow.com/a/20307918/262866    this worked for me. I've removed the semicolon from some of my IIFE's for some reason and paid the price for it

**Comment by jspizziri** [comment]
@gokhandemirtas.... thank you!!! What a nightmare, finally found the suspect colon.

**Comment by Sasicumaar** [comment]
![image](https://user-images.githubusercontent.com/25055829/37952713-60662116-31be-11e8-8380-24085203eb0c.png)

**Comment by Sasicumaar** [comment]
Uncaught TypeError: (intermediate value)(intermediate value)(...) is not a function
