### ISSUE TITLE
Newb Question on project configuration

### ISSUE THREAD

**Issue by MAustinMMDP** [Swiip/generator-gulp-angular#348]
Hi, 

Just wondering what the reasoning was for dividing up the gulp tasks rather than storing them all in the gulpfile.js?

**Comment by Swiip** [comment]
Because it was simply to big. I hate big files. It allows to orders tasks and purposes.

**Comment by MAustinMMDP** [comment]
Smart move! I wish other projects would do the same.  Although this generator is my go too for new projects :)
