### ISSUE TITLE
Spaces around directives

### ISSUE THREAD

**Issue by NTag** [Swiip/generator-gulp-angular#352]
Hello,

When I use my own directives, like this :
```<my-directive param1="value1"></my-directive> some text <other-directive param1="othervalue"></other-directive>"```
and when I launch gulp build, the spaces before and after "some text" are removed... Am I using directives wrongly? How to correct that problem?

Thanks!

**Comment by Swiip** [comment]
Partials HTML is optimized in the build process by gulp-minifyHtml. I think it could be this plugin which removes your white spaces.

Try to remove it, to find some options or perhaps tu put some `&nbsp;` (yes I know...)

**Comment by NTag** [comment]
Thanks for your response.
I discover the option ```loose``` in https://github.com/Moveo/minimize to keep one whitespace. It solves my problem :-) .
