### ISSUE TITLE
gulp wiredep not found

### ISSUE THREAD

**Issue by matantsu** [Swiip/generator-gulp-angular#353]
I have ran the generator and was delighted from the result , but when i run `gulp wiredep` , I get an error:
`Task 'wiredep' is not in your gulpfile`

**Comment by Swiip** [comment]
Dups of #332

I'm updating the doc in the next pr.

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/355
