### ISSUE TITLE
empty .tmp/serve folder

### ISSUE THREAD

**Issue by Olgagr** [Swiip/generator-gulp-angular#362]
I have a strange problem. Everything was working fine, but I added some incorrect css. When I did gulp build and I get this error:

```
/Users/user/Projects/snapwin-cms/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399
        throw new Error('Please check the validity of the CSS block starting f
```

The ./tmp/serve folder was cleared. Now when I do gulp serve nothing is served as files from src/app and src/components are not copied to .tmp/serve. I tried to run gulp scripts and gulp styles but .tmp/serve has only app/index.css. Files are not copied!

I'm using coffee and sass.

**Comment by genu** [comment]
Also having an issue similar to this, however, I'm able to run `gulp serve`, but when I do `gulp build` I get the error that you mention. What was your issue?

**Comment by genu** [comment]
A temporary workaround is to disable the `$.csso())` plugin.

**Comment by Olgagr** [comment]
@genu In my case it was buggy sass file. I'm using ready-to-use bootstrap theme and it seems like the author made some mistakes in code. I propose you to validate your file.
