### ISSUE TITLE
jQuery installed although I told the generator not to

### ISSUE THREAD

**Issue by mastix** [Swiip/generator-gulp-angular#365]
Hey guys,

when running/configuring the generator I've told it to not use jQuery (in any case). But bootstrap-sass has jQuery as dep, so it's added anyways... :(

So what's the deal with this option then? :)

Regards and thanks very much for this generator,

Sascha

**Comment by Swiip** [comment]
It has already been reported even if I don't find the issue.

We don't add the dep in bower but bower add it anyway because of a transitiv dep from bootstrap. We have to add a bower config for really refuse it.

**Comment by mastix** [comment]
I couldn't find an issue either... so as a workaround I've added it to the wiredeps excludes, let's see if it works. :) Thanks for your help and keep up the good work.

**Comment by Swiip** [comment]
Arg, I hoped there was something like an "exclude" property to put in bower.json but I don't find it :(

Seems that the wiredep exclude is the right solution then...

**Comment by mastix** [comment]
Ok, I've changed it in the *inject.js* (And deleted the jquery folder in bower_components), but it doesn't seem to work:

```javascript
var wiredepOptions = {
    directory: 'bower_components',
    exclude: [/bootstrap-sass-official/, /bootstrap\.css/, /bootstrap\.css/, /foundation\.css/,/jQuery/]
  };
```

Error: 

> stream.js:75
>       throw er; // Unhandled stream error in pipe.
>             ^
> Error: Error: jquery is not installed. Try running `bower install`.
>     at c:\Users\sbs4fe\Development\c26_bgn_startpage\trunk\frontend\node_modules\wiredep\wiredep.js:30:56

Any ideas?

**Comment by Swiip** [comment]
Did you remove jquery from bower_components? It's possible that wiredep look through the directory.

**Comment by zckrs** [comment]
Related to https://github.com/Swiip/generator-gulp-angular/issues/82 ?

**Comment by Swiip** [comment]
This is the one

**Comment by mastix** [comment]
I've removed the dependencies from bootstrap-sass-official and it seems to work now, but that's actually a bad solution since it will be overridden the next time I run bower install! :(

Just changing the wirep exclude patterns did not solve the issue...

**Comment by Swiip** [comment]
Did you try this solution https://github.com/Swiip/generator-gulp-angular/issues/82#issuecomment-67311140 ?

**Comment by mastix** [comment]
Yes, that's what I did... but that's a bad solution. :(

**Comment by Swiip** [comment]
But this will not be lost by a bower install...

**Comment by MAustinMMDP** [comment]
I would also assume that selecting either Angular UI Bootstrap, AngularStrap or Bootstrap with "No JavaScript, just CSS" would mean no dependency on jQuery. Would it be possible to use main-bower-files package by editing the app _bower.json file with custom overrides as shown here: https://www.npmjs.com/package/main-bower-files#overrides-options?

**Comment by jedwards1211** [comment]
Hi Swiip, I tried removing jQuery from bower_components but that didn't help either.  I didn't see the problem with solution #82 either, I just used that.

Thanks for the generator!  I love how much it let me choose which tools I use!

**Comment by jedwards1211** [comment]
I think ultimately Bootstrap should fix this by creating a bootstrap-core subproject that doesn't have any dependencies, and making the bootstrap project depend on that and jQuery, because it's going to become more and more common that people want only the CSS.

**Comment by raphox** [comment]
https://github.com/Swiip/generator-gulp-angular/issues/690#issuecomment-143060296
