### ISSUE TITLE
Shouldn't scripts gulp task exclude *.spec.js files?

### ISSUE THREAD

**Issue by mohsen1** [Swiip/generator-gulp-angular#371]
I'm not sure about this but it seems that scripts task is doing the extra work of processing spec files

https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/gulp/_scripts.js#L25

**Comment by Swiip** [comment]
Even if we don't (yet?) provide tests in the preprocessed langage, it's something that should be possible so we have to compile them...

**Comment by mohsen1** [comment]
It would be nice to split the scripts task int scripts:app and scripts:test then. It open up the possibility of using two different compiled languages for each

**Comment by Swiip** [comment]
Not sure of this. The user should just have to put a file with the extension he want and Gulp process it correctly.

The only optimization I could think of is to prevent recompiling tests script in the server watch to gain a bit of time but it could be a mess for not so much.
