### ISSUE TITLE
Improve "gulp serve" functionality.

### ISSUE THREAD

**Issue by dts** [Swiip/generator-gulp-angular#373]
Developing on gulp-angular projects can be improved a ton, by making JS and CSS compilation/syntax errors visible in the page that you're delivering to the web server.  I have done this by creating a separate development-mode server, which uses the same gulp modules as the development mode gulp script, but does so in a way that is much more fault-tolerant.  Since the development mode is delivering a web app to a web browser, why not make known errors visible in an easy way?  I have not turned this into any meaningful or re-usable npm modules yet, but it is demonstrated in this gist:

https://gist.github.com/dts/f0d5a6dca85ba21bf51e

**Comment by Swiip** [comment]
It's an interesting idea but from the beginning of this generator, we chose to to drop the support of a home maid dev server in favor to Browser Sync which is a dedicated project to target this need.

Following this, I think that it's a really great idea but it has to be submited to them. They'll be able to gives us an entry point to publish the errors we've got.

**Comment by dts** [comment]
Fair enough, but BrowserSync does not appear to be designed to be extensible in any meaningful way, which limits its usefulness for me.

**Comment by Swiip** [comment]
Browser Sync has already entry points for tools like gulp to manually trigger reloading files (even if we still don't use them but that's another question). I really think that they can consider adding a new entry point to send more detailed feedbacks.
