### ISSUE TITLE
Generator interrupts with errors and doesn't finish process

### ISSUE THREAD

**Issue by marcelaulenbacher** [Swiip/generator-gulp-angular#374]
Hi.

I just started using the generator. Regrettably the generator interrupts it's work and can't finish the generation.

Machine set up: Mac OSX, Bower 1.3.12, npm 1.4.28.

The resulting error is:

> ws@0.4.32 install /Users/marcel/workspace/mydocumenta/webpredevel/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm ERR! Error: EACCES, mkdir '/Users/marcel/.npm/sinon/1.10.3'
npm ERR!  { [Error: EACCES, mkdir '/Users/marcel/.npm/sinon/1.10.3']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/marcel/.npm/sinon/1.10.3',
npm ERR!   parent: 'node-sass' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/marcel/workspace/mydocumenta/webpredevel
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /Users/marcel/.npm/sinon/1.10.3
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/Users/marcel/.npm/sinon/1.10.3'
npm ERR! not ok code 0

Thanks in advance for your help.

**Comment by lastday** [comment]
Try running it with sudo.

**Comment by zckrs** [comment]
`npm ERR! Please try running this command again as root/Administrator.`

**Comment by marcelaulenbacher** [comment]
Thank you for the fast replies.

Is it standard to let these scripts run with root permissions? Before I tried this generator, I tried another one and there was no need to run scripts as root.

Isn't there another solution without running the scripts as root?

**Comment by zckrs** [comment]
You don't need root to run any generator. Problem is your nodejs installation.

You can try http://stackoverflow.com/questions/10081293/install-npm-into-home-directory-with-distribution-nodejs-package-ubuntu/13021677#13021677

**Comment by marcelaulenbacher** [comment]
This solved my problems:

`sudo npm cache clean -f` clear you npm cache
`sudo npm install -g n` install "n"
`sudo n stable` upgrade to lastest version
