### ISSUE TITLE
Generic gulp / grunt generator weakness

### ISSUE THREAD

**Issue by adriatic** [Swiip/generator-gulp-angular#376]
I am likely bringing up something that is well known (and not solved AFAIK): the very primitive UI used to define the generator's task:
![image](https://cloud.githubusercontent.com/assets/2712405/6354471/9eae5200-bc1d-11e4-81c5-dbbf2ca5d68f.png)
This 30 years old UI drives the creation of a massive 125 Mbyte collection of data that represents the skeleton of my app. 
I strongly believe that this could be done a lot better. Anyone with the same opinion?

**Comment by zckrs** [comment]
Do you have one proposition or example ? 

125MByte :-O

**Comment by adriatic** [comment]
Of course I do - but before sharing any proposition, I wanted to test current team's interest. Too many times in the past I encountered the team's behavior that borders with the existence of "class hierarchy", combined with resistance to any changes ("we work from the goodness of our hearts, with no compensations and thus no responsibility to the users of our project").
My principal interest is on sharing (via github) the structure, architecture and development patterns of large scale modern applications targeting healthcare), so gulp generators while an appealing concept are not my primary focus to the point of creating my own project.

**Comment by Swiip** [comment]
I'm perfectly happy with the UI. It's a tool for developper not for end user. The dev ui fashion is about minimalism right now, lots of people even come back to vim :). Anyway, we only use the Yeoman API, open an issue to them if you want.

About the weight. It's true it's big. But it represents all the tools you need for a modern web development including a browser (PhantomJS), Selenium, Sass... The target optimized web distribution is the real focus.

**Comment by adriatic** [comment]
It is not clear to me why would you think that I am discussing a tool for the end-user, but that is besides the point that you are perfectly happy with the UI as is. I am not, so I will do something about it eventually. Thanks for sharing your thoughts with me
