### ISSUE TITLE
Generator failed 

### ISSUE THREAD

**Issue by adriatic** [Swiip/generator-gulp-angular#377]
I apologize if this is a repeat.
Running the task

    yo gulp-angular app

defined as 
![image](https://cloud.githubusercontent.com/assets/2712405/6354471/9eae5200-bc1d-11e4-81c5-dbbf2ca5d68f.png)

resulted with `gulp-flatten` error,

![image](https://cloud.githubusercontent.com/assets/2712405/6355564/d73270be-bc24-11e4-839f-62580da0b249.png)

a "deprecated warning"

![image](https://cloud.githubusercontent.com/assets/2712405/6355629/5f7c6b78-bc25-11e4-9dfb-5e959000c67c.png)

and a bunch of python related errors (clearly I was not aware that I need to have python installed on my computer

![image](https://cloud.githubusercontent.com/assets/2712405/6355663/8fbd1116-bc25-11e4-92a7-92fd332e7f5e.png)

**Comment by Swiip** [comment]
All of it are NPM related problems. I suggest you sends your remarks to them. But they are aware of some problems following a recent major update 0.10 -> 0.12 and more focus on finding an agreement with IO.js ^^

About Python, yes, we could have documented that it's a dependency of some of the NPM dependency. In fact, there is also ruby if you use ruby-sass.
