### ISSUE TITLE
Vendor css injection won't work unless user selects a generator-provided CSS library

### ISSUE THREAD

**Issue by xmlilley** [Swiip/generator-gulp-angular#378]
When a user chooses to include Bootstrap or Foundation or another tool supplied by the generator, the following gets added to index.html, so support the wiredep/inject task: 

```
    <!-- build:css({.tmp/serve,src}) styles/vendor.css -->
    <!-- bower:css -->
    <!-- run `gulp wiredep` to automaticaly populate bower styles dependencies -->
    <!-- endbower -->
    <!-- endbuild -->
```
But if you skip those generator-provided options, the comments won't be included. Then, if a user tries to run `gulp wiredep` or `gulp inject`, or just serve the project, nothing will ever happen: the bower CSS dependencies won't be be included. Ideally, the necessary comments would be present by default, and not depend on using one of the sub-generators for a CSS framework.

**Comment by MarioAraque** [comment]
+1
