### ISSUE TITLE
Unboud variable using sass

### ISSUE THREAD

**Issue by kostonstyle** [Swiip/generator-gulp-angular#379]
Hi all,
I have the following problem to implement sass
http://stackoverflow.com/questions/28705826/unboud-variable-using-sass/28717143?noredirect=1#comment45723602_28717143
Thanks

**Comment by zckrs** [comment]
Please we need details.
Read https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md and explain your problem

**Comment by zckrs** [comment]
Use `bower install bootswatch-scss`


And replace `vendor.scss` by:

```
$icon-font-path: "/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/";

@import '../../bower_components/bootswatch-scss/yeti/variables';
@import '../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap';
@import '../../bower_components/bootswatch-scss/yeti/bootswatch';

```
