### ISSUE TITLE
New components' controllers are empty on serve

### ISSUE THREAD

**Issue by sebastialonso** [Swiip/generator-gulp-angular#381]
I'm using the skeleton app that comes with the generator, the one with navbar component and the main folder under the `app` folder

I tried creating another component under `components` folder

~~~
-components
--cats
---cats.controller.coffee
---cats.controller.spec.js
---cats.html
~~~

So inside `cats.controller.coffee`
~~~

angular.module "app", []
  .controller "CatsCtrl", ($scope) ->
    $scope.say = "Meow"
~~~

and inside `index.coffee`

~~~

angular.module "app", [ ... ]
  .config ($routeProvider) ->
    $routeProvider
      .when "/",
        templateUrl: "app/main/main.html"
        controller: "MainCtrl"
      .when "/cats",
        templateUrl: "components/cats/cats.html"
        controller: "CatsCtrl"
~~~

and when I go to `/cats` I get `Error: [ng:areq] Argument 'CatsCtrl' is not a function, got undefined`

The thing is I thought I forgot to require the files in the index, but according to Dev Tools, `gulp serve` is doing that all by itself. So I'm at a loss. Before using the generator this never showed up, so I think I'm misusing  something. Any help would be greatly appreciated.

**Comment by zckrs** [comment]
Can you try with the `return`? 
```
angular.module "app", [ ... ]
  .config ($routeProvider) ->
    $routeProvider
      .when "/",
        templateUrl: "app/main/main.html"
        controller: "MainCtrl"
      .when "/cats",
        templateUrl: "components/cats/cats.html"
        controller: "CatsCtrl"
     return
```

**Comment by sebastialonso** [comment]
Tack så mycket!
