### ISSUE TITLE
Browser Sync is working correctly?

### ISSUE THREAD

**Issue by pashaigood** [Swiip/generator-gulp-angular#384]
Hi!
I`am use less engine. When i change somth:
Firstly, inject css, expectedly.
Secondary, reload whole page, unexpectedly.

This is by design?

**Comment by sebastialonso** [comment]
I'm running with some weird issues too.
Coffee scritpts are not live-reloading, manually deleting `.tmp/serve` seems to work, but only the first time. Then it's chaos

**Comment by eseceve** [comment]
I've the same issue with Stylus

**Comment by Swiip** [comment]
Currently, styles changes triggers the inject task in case of there is a new injection to make. This implies a change on the index.html and then we've got a reload even for styles change.

This is a real problem, I'm working on a solution...
