### ISSUE TITLE
Bootstrap js files not included via wiredep

### ISSUE THREAD

**Issue by Lesac76** [Swiip/generator-gulp-angular#385]
I don't know why gulp-inject.js had the setting to not include bootstrap.js files in the build. Took quit some time to find that this was an issue:
exclude: [/bootstrap\.js/]

My choice when taking this generator for angular was bootstrap so it seems not to make sense to exclude thoses bootstrap files.

Thx for your work on the generator for angular together with gulp.

**Comment by intellix** [comment]
Because bootstrap.js which is included with twbs-bootstrap is the jQuery dependent version. What you're looking for is something like ui-bootstrap or mgcrea.github.io/angular-strap/

**Comment by zckrs** [comment]
:+1: right @intellix
