### ISSUE TITLE
Gulp serve crashes on error with Sass

### ISSUE THREAD

**Issue by jamesbehr** [Swiip/generator-gulp-angular#391]
I couldn't find similar issue, so I'll just make a new one. While this is an error with gulp-sass (See dlmanning/gulp-sass#44), there are some suggestions in those comments that can be applied here. I'd be happy to write a PR for this if it is not an issue specific to me.

**Comment by zckrs** [comment]
You use v0.9.1 ou master ?

**Comment by jamesbehr** [comment]
Yes. Sorry, I forgot to mention that.

**Comment by zckrs** [comment]
Ans you forgot again

**Comment by jamesbehr** [comment]
Your typo confused me. Go ahead and close this, I just tested master and it works fine. Problem only exists in v0.9.1
