### ISSUE TITLE
gulp doesn't build

### ISSUE THREAD

**Issue by jonathanobino** [Swiip/generator-gulp-angular#394]
when I run "gulp" or "gulp build" it returns this http://pastebin.com/yrSmEBLY

and in the dist there are just these files
![schermata 03-2457085 alle 23 01 37](https://cloud.githubusercontent.com/assets/11078822/6473382/46fbe64e-c1f9-11e4-9c22-9c6b8bff34f2.png)

I'm doing something wrong?

**Comment by jonathanobino** [comment]
reinstalled the gulp-ng-annotate seems to have fixed the issue

**Comment by Swiip** [comment]
Dups of #347
