### ISSUE TITLE
TypeScript: .ts files not generated in newly created project

### ISSUE THREAD

**Issue by jamm** [Swiip/generator-gulp-angular#407]
after running yo gulp-angular and selecting TypeScript (because of ng-conf influence, of course), I see in code of main controller:

```ts
/// <reference path="../../.tmp/typings/tsd.d.ts" />

/// <reference path="main/main.controller.ts" />
/// <reference path="../components/navbar/navbar.controller.ts" />
```

I had to read issues to understand that I need to run gulp tsd. Ok, first file now generated. But 2 others - not. So all code highlight doesn't work and ... it's the key feature of TypeScript :)

Please let me know how I can fix it.

**Comment by Swiip** [comment]
The task tsd:install should be in dep of some others like inject. It should have been ran automatically...

**Comment by jamm** [comment]
It runs on first `gulp serve`, so it's maybe not so critical (just not intuitive), but not all files were generated - only 1 of 3.

**Comment by Swiip** [comment]
Yeah, we always test with gulp serve :)

Strange you not got all files, it generate something like 8 files normally...

**Comment by Swiip** [comment]
In the master, the tsd:install task is now launched as a dependency of the scripts task so there are no more mistake possible...
