### ISSUE TITLE
Where to place third-party files (scripts and stylesheets) who are not installed with Bower and benefited from auto-injection feature ?

### ISSUE THREAD

**Issue by henry74** [Swiip/generator-gulp-angular#413]
I'm trying to figure out where to place a 3rd party js library so it's automatically picked up in the gulp build process so I don't have to manually include it in the index.html.  I've installed everything with bower up to this point so haven't had to deal with this until today.  I've tried created an js folder in app/assets but it doesn't get picked up.

Any pointers would be greatly appreciated!

Thanks,
Henry

**Comment by zckrs** [comment]
Henry, 

I will try to help you.

In `index.html` there are 2 types of auto-injected files during `gulp build` and `gulp serve`:
* CSS part
* JS part

#### CSS
They are inserted at end of `head` node by 2 blocks that write 2 files containing all the CSS.
* `<!-- build:css({.tmp/serve,src}) styles/vendor.css -->`: Any bower's vendor stylesheets present in `bower.json` under property `dependencies` (:warning: not devDependencies) **AND** located in `/bower_components/`

* `<!-- build:css({.tmp/serve,src}) styles/app.css -->`: Yours stylesheets who match with any files located into `/src/{app,components}/**/*.{css,scss,less,styl}`


#### JS
They are inserted at end of `body` node by 2 blocks that write 2 files containing all the JS.
* `<!-- build:js(src) scripts/vendor.js -->`: Any bower's vendor scripts present in `bower.json` under property `dependencies` (:warning: not devDependencies) **AND** located in `/bower_components/`

* `<!-- build:js({.tmp/serve,.tmp/partials,src}) scripts/app.js -->`: Yours scripts who match with any files located into `/src/{app,components}/**/*.{js,es6,ts,coffee}`


#### Where to place the third-party files (scripts and stylesheets) who are not installed with bower ?
* *Without* auto-inject feature: you can use any folders except `/src/app/` and `/src/components/` 
* *With* auto-inject feature: you should use `/src/app/` and `/src/components/` 
* **With** auto-inject feature **in custom folder**: you should complete gulp's tasks 

##### Notes: 
* the parsing of javascript files is managed in `/gulp/script.js`
* the parsing of css files is managed in `/gulp/styles.js`
* the injection in `index.html` is managed in `/gulp/inject.js`

**Comment by henry74** [comment]
@zckrs Thanks for the detailed response.  I did figure it out by trial and error and looking through the gulp source files, but thank you very much for responding.  I'm sure this will be helpful to others looking to take advantage of gulp and yeoman.

**Comment by Swiip** [comment]
:+1: this should definitely end up in the wiki!

**Comment by zckrs** [comment]
No problem :smiley: 

Maybe you can create a folder `/src/lib/` and add `{app,components,lib}` in `/gulp/scripts` and `/gulp/styles`

**Comment by zckrs** [comment]
@henry74 I renamed your issue if you are agree

**Comment by henry74** [comment]
Works for me! +1

**Comment by vespertilian** [comment]
@zckrs 

Thanks for your post. I got the app working in development by following your instructions {app,components,lib(loopback in my case)}. However it does not compile properly when I build. Ideally I would like it to be compiled with the vendor scripts. 

Any help would be appreciated. 

Here is my gulp/scripts file
gulp/scripts file

Added {app,components,loopback}

'use strict';

var gulp = require('gulp');

var paths = gulp.paths;

var $ = require('gulp-load-plugins')();

gulp.task('scripts', function () {
  return gulp.src(paths.src + '/{app,components,loopback}/**/*.js')
    .pipe($.jshint())
    .pipe($.jshint.reporter('jshint-stylish'))
    .pipe($['6to5']())
    .on('error', function handleError(err) {
      console.error(err.toString());
      this.emit('end');
    })
    .pipe(gulp.dest(paths.tmp + '/6to5'))
    .pipe($.size())
});

gulp.task('browserify', ['scripts'], function () {
  return gulp.src(paths.tmp + '/6to5/app/index.js', { read: false })
    .pipe($.browserify())
    .on('error', function handleError(err) {
      console.error(err.toString());
      this.emit('end');
    })
    .pipe(gulp.dest(paths.tmp + '/serve/app'))
    .pipe($.size());
});

**Comment by zckrs** [comment]
@vespertilian please
1) Can use mardown for code ?
```
like this
```
2) Can you paste your `.yo-rc.json` ?

**Comment by vespertilian** [comment]
@zckrs 

Sure thing. 

```
{
  "generator-gulp-angular": {
    "props": {
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      },
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "name": "angular-animate",
          "module": "ngAnimate"
        },
        {
          "name": "angular-cookies",
          "module": "ngCookies"
        },
        {
          "name": "angular-touch",
          "module": "ngTouch"
        },
        {
          "name": "angular-sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "name": "jquery",
        "version": "~2.1.1"
      },
      "resource": {
        "name": "angular-resource",
        "module": "ngResource"
      },
      "router": {
        "name": "angular-ui-router",
        "version": "~0.2.13",
        "module": "ui.router"
      },
      "ui": {
        "name": "bootstrap-sass-official",
        "version": "~3.3.1",
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "name": "angular-bootstrap",
        "version": "0.12.x",
        "key": "ui-bootstrap",
        "module": "ui.bootstrap"
      },
      "cssPreprocessor": {
        "key": "ruby-sass",
        "extension": "scss",
        "module": "gulp-ruby-sass",
        "version": "~0.7.1"
      },
      "jsPreprocessor": {
        "key": "6to5",
        "extension": "js",
        "srcExtension": "es6",
        "module": "gulp-6to5",
        "version": "~1.0.2"
      },
      "htmlPreprocessor": {
        "key": "jade",
        "extension": "jade",
        "module": "jade",
        "version": "~1.8.1"
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      }
    }
  }
}
```

Index when using gulp serve

```

    <!-- build:js(src) scripts/vendor.js -->
    <!-- bower:js -->
    <script src="../bower_components/jquery/dist/jquery.js"></script>
    <script src="../bower_components/angular/angular.js"></script>
    <script src="../bower_components/angular-animate/angular-animate.js"></script>
    <script src="../bower_components/angular-cookies/angular-cookies.js"></script>
    <script src="../bower_components/angular-touch/angular-touch.js"></script>
    <script src="../bower_components/angular-sanitize/angular-sanitize.js"></script>
    <script src="../bower_components/angular-resource/angular-resource.js"></script>
    <script src="../bower_components/angular-ui-router/release/angular-ui-router.js"></script>
    <script src="../bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
    <!-- endbower -->
    <!-- endbuild -->
    <script src="../loopback/lb-services.js"></script>

    <!-- build:js({.tmp/serve,.tmp/partials,src}) scripts/app.js -->
    <!-- inject:js -->
    <script src="app/index.js"></script>
    <!-- endinject -->

```


Index when built

```

    <script src="scripts/vendor-7f073926.js"></script>
    <script src="../loopback/lb-services.js"></script>
    <script src="scripts/app-55b6f8be.js"></script>

```

**Comment by vespertilian** [comment]
So the reason I was having trouble was because I chose to use ES6. All the JS in {app, components} was being run through Browserify, my 3rd party non bower module was ES5. 

Final solution 

Use my own inject block like this:

```
    <!-- inject:vendor -->
    <!-- files in the es5 vendor folder will be injected here -->
    <!-- endinject -->

```

Add to Index.html

```
    <!-- build:js(src) scripts/vendor.js -->
    <!-- bower:js -->
    <!-- run `gulp wiredep` to automaticaly populate bower script dependencies -->
    <!-- endbower -->
    <!-- inject:vendor -->
    <!-- files in the es5 vendor folder will be injected here -->
    <!-- endinject -->
    <!-- endbuild -->

    <!-- build:js({.tmp/serve,.tmp/partials,src}) scripts/app.js -->
    <!-- inject:js -->
    <!-- js files will be automaticaly insert here -->
    <!-- endinject -->

    <!-- inject:partials -->
    <!-- angular templates will be automatically converted in js and inserted here -->
    <!-- endinject -->

    <!-- endbuild -->
```

Add inject vendor to gulp/inject.js

```
  var injectVendor = gulp.src([paths.src + '/es5vendor/**/*.js'], {read: false});
  var vendorOptions= {
    starttag: '<!-- inject:vendor -->',
    ignorePath: [paths.src, paths.tmp + '/serve'],
    addRootSlash: false,
  };

  var wiredepOptions = {
    directory: 'bower_components',
    exclude: [/bootstrap-sass-official/, /bootstrap\.css/, /bootstrap\.css/, /foundation\.css/]
  };

  return gulp.src(paths.src + '/*.html')
    .pipe($.inject(injectStyles, injectOptions))
    .pipe($.inject(injectScripts, injectOptions))
    .pipe($.inject(injectVendor, vendorOptions))
    .pipe(wiredep(wiredepOptions))
    .pipe(gulp.dest(paths.tmp + '/serve'));
});

```

**Comment by jaarong** [comment]
I think this is the same issue that I'm having.  I am trying to use Bourbon/Neat for my framework.  It apparently doesn't use a standardized bower configuration so inject isn't working.  I'd rather not pull them into src and instead keep them in bower.  I am, however, fine with importing them files through my scss.  This works locally, but does not work from external IP's.  I'm assuming it has something to do with the directory structure and the location of bower_components basically changing once served.  

Is there information somewhere on how to properly include other frameworks?

**Comment by Awakening-j** [comment]
@zckrs could you show me an configuration of integrating this generator with `amcharts.js' ? I've tried to modify the scripts file, 
> return gulp.src([options.src + '/app/**/*.js', options.src + 'extra-lib/amcharts/amcharts/amcharts.js'])  
but still not work..I can't find amcharts.js in html source

**Comment by jdhiro** [comment]
Much like @vespertilian I'm trying to include the LoopBack API config into my project. Unfortunately it looks like things changed in the latest version of the generator, and his example doesn't work for me. =\

**Comment by jdhiro** [comment]
Actually, I did get it working, I just needed to move my `vendor` folder under the `app` folder. It seems like there should be an easier way out of the box to include these files =) Awesome generator overall though!

**Comment by Awakening-j** [comment]
@jdhiro You create a `vendor` folder under `app`? I need to add some third-part lib too

**Comment by jdhiro** [comment]
@Awakening-j Yup, I created a vendor folder under app, and just followed @vespertilian directions.

**Comment by sdornan** [comment]
Thanks a ton for your solution @vespertilian. It was very helpful.

**Comment by zckrs** [comment]
Recipe exist now https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/managing-third-party-files.md

I close old issue

**Comment by yakuzaaaa** [comment]
After gulp serve only all custom css files are being removed from index.html and main.scss is kept there.
How do I fix this?
