### ISSUE TITLE
Make it possible to run protractor with args

### ISSUE THREAD

**Issue by Olgagr** [Swiip/generator-gulp-angular#414]
It will be great to make it possible to run protractor with args. For example it could be possible to run only one suite:

```
gulp protractor --suite signIn
```

or choose the browser:

```
gulp protractor --browser firefox
```

**Comment by zckrs** [comment]
I am not sure this issue is related to generator.
Maybe the plugin (gulp-protractor)[https://github.com/mllrsohn/gulp-protractor] should parse the cmd line. 

/cc @mllrsohn

@Olgagr alternatively you can use `node_modules/.bin/protractor protractor.conf.js --browser firefox` with a `gulp serve` running in another terminal

**Comment by pdf13** [comment]
I had the same problem and solve then modifying `gulp/e2e-tests.js` to make function **runProtractor()** looks like this:

```javascript
function runProtractor (done) {
    var params = process.argv;
    var args = params.length > 3 ? [params[3], params[4]] : [];

    gulp.src(options.e2e + '/**/*.js')
      .pipe($.protractor.protractor({
        configFile: 'protractor.conf.js',
        args: args
      }))
(
  }
```

This is not error proof, but allow me to make calls to `gulp protractor`, `gulp protractor --suite suiteName`, `gulp protractor:src --someArg someValue`. I hope it can help.

**Comment by zckrs** [comment]
Nice :+1: 
PR appreciate or wait I take time to implement it

**Comment by bondarewicz** [comment]
just ran into similar issue but when running protractor with args using teamcity gulp runner...
```
Usage: protractor [configFile] [options]
configFile defaults to protractor.conf.js
The [options] object will override values from the config file.

Error: more than one config file specified

/.../e2e-tests.js:44
```
throw in 
```
.on('error', function (err) {
   // Make sure failed tests cause gulp to exit non-zero
   throw err;
})
```
I guess we should only be interested in args with `--`, hence replaced:
```
var args = params.length > 3 ? [params[3], params[4]] : [];
```
with 
```
var args = [];
  for (var i = 0; i < params.length; i++) {
    if(params[i].substring(0, 2) == '--') args.push(params[i]);
  }
```
/cc @zckrs @pdf13

**Comment by furnace915** [comment]
var args = process.argv.slice(3) also works
