### ISSUE TITLE
Refacto karma

### ISSUE THREAD

**Issue by zckrs** [Swiip/generator-gulp-angular#415]
TODO: 

* use `karma` instead of `gulp-karma` see https://github.com/karma-runner/gulp-karma and https://github.com/gulpjs/plugins/blob/master/src/blackList.json#L265
* fix `gulp test:auto` for jsPreprocessor. 
* sort files

**Comment by Swiip** [comment]
I worked on that tonight. I don't have a PR to make but I make some breakthroughs I want to share.
- Karma doesn't understand paths like '{app,components}'. It's able to serve the files, but failed to watch them. I replaced with `options.src + '/**/*.js` and it works a lot better
- For ordering the files we face a dilemma:
  - We can list all the files and order them before launching karma. It allows us to order as we want but karma will not be able to detect new files without restarting
  - We can give the regexp of file paths to karma but the sorting will have to be done by karma. It exists a plugin karma-angularfile-sort equivalent to gulp-angularfile-sort but not one for sorting with a json file which is needed for typescript

I would have loved finding a way piloting Karma server and Karma runner separately to be able to use the Gulp watcher to trigger Karma tests from Gulp but I didn't found a way.

**Comment by Swiip** [comment]
Here's what I've got. https://gist.github.com/Swiip/2dbfd47a8fdf95cf23f9

Works fine. A little too much of code to my tastes but didn't found better. Directives tests passes (#207).

Only problem, a file addition will require to relaunch Karma.

Of course, the code has yet to be "templatized" for all options...
