### ISSUE TITLE
Simplify ES6 template a little [improvement]

### ISSUE THREAD

**Issue by jamm** [Swiip/generator-gulp-angular#416]
As this generator follows rule "1 component per file" (and it's a great rule), template for ES6 components can be simplified to:

```js
'use strict';

export default ClassName {
  // @ngInject
  constructor(){
  }
}
```

or, for directives, factories and filters:
```js
'use strict';

// @ngInject
export default FunctionName function(){
}
```

**Comment by storkme** [comment]
@jamm shouldn't that be:

```javascript

// @ngInject
export default function FunctionName() {}

```

?


:+1: for this idea though.

**Comment by Swiip** [comment]
I made some searches on this topic. What you both suggests works with Babel but Traceur doesn't keeps comments so everything fail.

I finally found this notation which is a bit less "clean" but works for both preprocessors : https://github.com/Swiip/generator-gulp-angular/commit/eba7a43d608faad1b1e78fc26ba631b8de5558ac#diff-1b515377e5c1700611c3bd51d48ccb7bR3

I keep separation between element declaration and exports as ans es6 exports of this rule: https://github.com/johnpapa/angular-styleguide#style-y024

**Comment by storkme** [comment]
That's a shame - I hadn't considered traceur support to be honest. It works I suppose :+1:

I'm not sure Y024 is relevant here - aren't the functions essentially 'named' by whatever imports them? Besides that, the function in my little code snippet was named too. (*disclaimer I haven't worked with es6 modules a whole lot, might be missing something*)

**Comment by jamm** [comment]
named functions are really much better for debugging.

**Comment by zckrs** [comment]
In master branch the ES6 templates are rewrite.
