### ISSUE TITLE
ng-strict-di

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#419]
It seems this is useful to determine in development (with useful messages) whether your source is minification safe.  My problem is that in dev mode some 3rd parties choose to use ngAnnotate to supply the annotations rather than writing them explicitly. When I serve those files in their unimified form directly from bower_components I get an error.

 What I am wanting is a build step that runs ng-annotate() on the js before serving them (perhaps write everything to the .tmp directory including bower component js files).  Do you think this is doable?

See this issue
https://github.com/olov/ng-annotate/issues/142

Edit - I suppose ideally the bower library authors would run the ngAnnotate() step before producing their unminified .js file they are referencing in bower main.

**Comment by fubu** [comment]
I'm going the opposite path, injecting `ng-strict-di` only in the production build (which is the basis for my e2e-tests, except they hit the staging backend). For me `ng-strict-di` is more like a last-resort safety measure (until now it never triggered) so I never cared about the readability of the error message anyway. If that's a viable solution for you, this is how I extended the `build` task (with the help of [gulp-dom](https://github.com/trygve-lie/gulp-dom)):

```js
  // ...add this to the other $.filter calls:
  var htmlIndexFile = $.filter('index.html');

  return gulp.src(/*...*/)
    // ...various pipe's, and then just before the HTML minification:
    .pipe(htmlIndexFile)
    .pipe($.dom(function () {
      this.querySelectorAll('html')[0].setAttribute('ng-strict-di', true);
      return this;
    }))
    .pipe(htmlIndexFile.restore())
    // ...and let the minification happen...
```

When incorporating ngAnnotate into the serving pipeline the generated `index.html` should probably enable `ng-strict-di` by default as well.

**Comment by wgorder** [comment]
@fubu 

Thanks for the tip.  I suppose if the e2e coverage is good and you never actually have to figure out what actually caused it to fail (pretty hard to do from the minified error message).  This would work.  I will try your implementation.

I wonder also if what you did here might help me solve by context root problem in #290 .  I could use it to add a prefix to the src urls :) 

Anyway thank you for your response.

**Comment by fubu** [comment]
It's true that this approach only plays well when the e2e coverage is good enough, that's why I want to investigate using `ng-strict-di` in development mode soon. If that works out and @Swiip thinks this would be a good addition to the generator I could probably contribute a PR.

**Comment by wgorder** [comment]
@fubu 

I was just trying your snippet.  I get this error:

```
/Users/billy/Dev/Git-Repos/my-project/my-module/admin/node_modules/gulp-dom/node_modules/jsdom/lib/jsdom/browser/Window.js:39
  this._globalProxy = vm.runInContext("this", this);
                         ^
TypeError: needs a 'context' argument.
```

I saw some references on google about jsdom needing contextify but adding that didnt seem to help.  Did you have any issues like this when you added this?

**Comment by fubu** [comment]
I assume you are using the latest version, 0.4.0? Since `gulp-dom` is a wrapper around [jsdom](https://github.com/tmpvar/jsdom), and jsdom abandoned NodeJS support in favor of io.js support ([changelog](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#400)) you probably want to stick to the 0.3.1 version of `gulp-dom`.

**Comment by wgorder** [comment]
Ahh I see let me try that.. Thanks

**Comment by fubu** [comment]
It seems that [cheerio](https://github.com/cheeriojs/cheerio) is also quite popular and a good fit for the problem at hand. My example code above, using [gulp-cheerio](https://github.com/KenPowers/gulp-cheerio):

```js
  // ...add this to the other $.filter calls:
  var htmlIndexFile = $.filter('index.html');

  return gulp.src(/*...*/)
    // ...various pipe's, and then just before the HTML minification:
    .pipe(htmlIndexFile)
    .pipe($.cheerio(function ($, file) {
      $('html').attr('ng-strict-di', true);
    }))
    .pipe(htmlIndexFile.restore())
    // ...and let the minification happen...
```

**Comment by wgorder** [comment]
This seems less problematic than depending on jsdom. Once again, thanks for the suggestion.

**Comment by zckrs** [comment]
We use https://github.com/olov/ng-annotate and we don't have unimified dist build
This issue is not relative to the generator-gulp-angular.
