### ISSUE TITLE
gulp-serve html templates reverting to original state

### ISSUE THREAD

**Issue by ShMcK** [Swiip/generator-gulp-angular#422]
Quick fix:
```javascript
// gulp/watch.js
gulp.task('watch', ['inject', 'partials'], function() {     <-- add partials
```

**Comment by ShMcK** [comment]
Scratch that, the fix didn't work after auto-reload kicked in.

Templates constantly revert to their first created version. I know, that doesn't sound like it makes any sense, but that's the issue I'm having with `gulp serve`.

For example, I make a page:
```html
<h1>New Page</h1>
```
Then I update the page:
```html
<h1>New Page</h1>
<p>Update</p>
```
On auto-reload, `<p>Update</p>` disappears.

**Comment by ShMcK** [comment]
yo-rc settings:
```javascript
{
  "generator-gulp-angular": {
    "props": {
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      },
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "name": "angular-animate",
          "module": "ngAnimate"
        },
        {
          "name": "angular-touch",
          "module": "ngTouch"
        },
        {
          "name": "angular-sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "name": "jquery",
        "version": "~2.1.1"
      },
      "resource": {
        "name": "angular-resource",
        "module": "ngResource"
      },
      "router": {
        "name": "angular-ui-router",
        "version": "~0.2.13",
        "module": "ui.router"
      },
      "ui": {
        "name": "bootstrap-sass-official",
        "version": "~3.3.1",
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "name": "angular-bootstrap",
        "version": "0.12.x",
        "key": "ui-bootstrap",
        "module": "ui.bootstrap"
      },
      "cssPreprocessor": {
        "key": "node-sass",
        "extension": "scss",
        "module": "gulp-sass",
        "version": "~1.1.0"
      },
      "jsPreprocessor": {
        "key": "6to5",
        "extension": "js",
        "srcExtension": "es6",
        "module": "gulp-6to5",
        "version": "~1.0.2"
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html",
        "module": null,
        "version": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      }
    }
  }
}
```

**Comment by Swiip** [comment]
The partials compilation isn't used during the dev workflow. Only for the dist optimization. It's not about running the partials task.

Do you use the master branch? Because a reload should be triggered in the 0.9 because of this line: https://github.com/Swiip/generator-gulp-angular/blob/v0.9.1/app/templates/gulp/_server.js#L61

But in master, there is a problem. I optimized the reload triggering of BrowserSync and there is no more reloading when an html file is modified.

**Comment by ShMcK** [comment]
Thanks for getting back to me so quickly. I removed the few changes I made to the gulp files, but the problem still persists.

Using version 0.9.1. Also: the `gulp/server.js` file is the same. 

Any other ideas?

**Comment by ShMcK** [comment]
I just saw three different versions of the html loaded in front of me within a few seconds. Very strange. Maybe my computer is haunted by a daemon.

**Comment by ShMcK** [comment]
I tried updating all packages & re-installing, same issue.

To narrow down the phenomenon, what happens is:
1) I make a change to the template, everything works fine for about 5-10 seconds.
2) all bindings break.
3) the change reverts to the original template.

**Comment by Swiip** [comment]
Wow, looks like the daemon lead is the one :)

The only mechanism which should happen is that we configured BrowserSync to watch your html files and reload them when there is a change. It's done in the `gulp/server.js`
