### ISSUE TITLE
[feature request] BrowserSync option for ghostMode: false

### ISSUE THREAD

**Issue by jamm** [Swiip/generator-gulp-angular#425]
Please provide an option to turn off browser-sync.

**Comment by Swiip** [comment]
Why would you that? And what do you mean by turn off?

**Comment by jamm** [comment]
Because I never use synchronization between browsers (when synchronization is turned on, we can't run tests in few browsers simultaneously because of collisions) and now it generates console.error message so tests fails again (because console is not empty and it's one of checks in tests).

Message:
![screenshot 2015-03-17 00 19 01](https://cloud.githubusercontent.com/assets/526352/6676752/4907b520-cc3b-11e4-9245-d91fb1cedc7e.png)

I think it's not bug of your generator so I didn't fill issue.

**Comment by Swiip** [comment]
So you don't want to remove the server, just the browser sync feature of browser sync :)

There is an UI now with browser sync allowing you to stop the action sync. If it's for test purpose you'll need to configure it but I didn't found the right option here: http://www.browsersync.io/docs/options/ But it's strange, it should exist.

About removing browser sync for a manual express server, it's not gonna happen.

**Comment by fubu** [comment]
There is also the [`ghostMode` option](http://www.browsersync.io/docs/options/#option-ghostMode) available to turn off the syncing. Just set `ghostMode: false` in the `BrowserSync.init()` call of the serve task.

**Comment by jamm** [comment]
just add "ghostMode: false" into .init call params 
```
browserSync.instance = browserSync.init({
      startPath: '/',
      ghostMode: false,
      server: server,
      browser: browser
    });
```
I'm [changing it](http://eugenioz.blogspot.com/2014/12/testing-angularjs-app-with-protractor.html) in each app, so if it will be configurable on the start, it will be little bit more handy :) It's, maybe, most low priority feature-request in this list of issues :)

**Comment by Stamy** [comment]
@jamm I have the same error messages as you have on my angularJs application. I get these while I am changing the URL using ui.route method `$state.go()` from controller. Is there any way to stop these errors ? Seems like `ghostMode:false` didn't help.

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue and marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0

**Comment by Boscop** [comment]
Any updates on this?
I also would appreciate a CLI option to turn off ghost mode..
