### ISSUE TITLE
target gulp failed (solved by increasing gulp-ng-annotate version)

### ISSUE THREAD

**Issue by manuel-m** [Swiip/generator-gulp-angular#429]
I have encountered 2 times this error on 2 different projects:
```
... ng-annotate/build/es5/ng-annotate-main.js:330
    target.$methodName = method.name;
```
solved with this patch on package.json
```
-    "gulp-ng-annotate": "~0.3.6",
+    "gulp-ng-annotate": "~0.5.2",
```

**Comment by m1rc0** [comment]
I've encountered a simillar issue: `TypeError: Cannot assign to read only property '$methodName' of false`.

I was also able to solve it with an upgrade of ng-annotate.

**Comment by Swiip** [comment]
Dups of #347
