### ISSUE TITLE
gulp-protractor with phantomjs generates error

### ISSUE THREAD

**Issue by climboid** [Swiip/generator-gulp-angular#430]
I have phantomjs installed globaly.
In my protractor.conf.js file I have
```
capabilities: {
    'browserName': 'phantomjs',
    'phantomjs.binary.path': './node_modules/karma-phantomjs-launcher/node_modules/phantomjs/bin/phantomjs',
    'phantomjs.cli.args': ['--debug=true', '--webdriver', '--webdriver-logfile=webdriver.log', '--webdriver-loglevel=DEBUG']
  },
```
when running
```
gulp protractor
```
I get this error
```
Starting selenium standalone server...
Selenium standalone server started at http://10.11.1.197:61302/wd/hub
[launcher] Error: UnknownError: org.openqa.selenium.browserlaunchers.Proxies
```

Any help solving this is much appreciated
Thank you!

**Comment by climboid** [comment]
Mmmm just realized that the protractor team goes against using phantomJS.
https://github.com/angular/protractor/blob/master/docs/browser-support.md
closing this for now

**Comment by Swiip** [comment]
Yeah, I would love making it works but no. Perhaps with Phantom 2.1?

https://github.com/Swiip/generator-gulp-angular#known-issue

**Comment by climboid** [comment]
Downgrading to 1.3.1 works, just tested it out. But not sure you would want to do that...
https://github.com/angular/protractor/issues/1512
