### ISSUE TITLE
Layout broken with a recent Angular Material Version

### ISSUE THREAD

**Issue by m1rc0** [Swiip/generator-gulp-angular#431]
Sadly, with a recent Angular Material Version (e.g. 0.8) the initial layout is broken.

See ![Recent Angular Material Version](http://i.imgur.com/0TbpMMl.png)

**Comment by Swiip** [comment]
Seams already fixed in master.

![capture d ecran 2015-03-16 a 21 43 16](https://cloud.githubusercontent.com/assets/475895/6676092/96dc9e48-cc25-11e4-8226-01e359c3548f.png)

**Comment by m1rc0** [comment]
Thank you very much. My fault.

**Comment by zckrs** [comment]
No problem, we should release new version
