### ISSUE TITLE
Provide option to use John Papa's style guide

### ISSUE THREAD

**Issue by KamBha** [Swiip/generator-gulp-angular#440]
The style guide provided by John Papa (https://github.com/johnpapa/angular-styleguide) is used by a number of people in the community and based on the fact that the angular team is working with John Papa to support the style guide going forward, it would be nice if the generator supported the standards in the style guide.  Both in the examples provided and in the JSHint files.

**Comment by zckrs** [comment]
I like idea but that can be apply only for Javascript file (not CoffeeScript and TypeScript)

**Comment by Swiip** [comment]
I like the idea of following a good style guide too. And there os good points in this one. But @zckrs knows what I'll argue.

Does this one really good? https://github.com/johnpapa/angular-styleguide#style-y010

Is

```javascript
(function() {
    'use strict';

    angular
        .module('app')
        .factory('logger', logger);

    function logger() { }
})();
```
better than
```javascript
'use strict';

angular
    .module('app')
    .factory('logger', function logger() { });
```

To be honest for me, the future is Babel, so I could let pass some displeasing things in the es5 version if I have to.
