### ISSUE TITLE
Using bower.json overrides, not injecting css files

### ISSUE THREAD

**Issue by robertbaker** [Swiip/generator-gulp-angular#441]
I'm using bower overrides.
.yo-rc.json
        {
          "generator-gulp-angular": {
            "props": {
              "angularVersion": "~1.3.4",
              "angularModules": [
                {
                  "key": "animate",
                  "module": "ngAnimate"
                },
                {
                  "key": "cookies",
                  "module": "ngCookies"
                },
                {
                  "key": "touch",
                  "module": "ngTouch"
                },
                {
                  "key": "sanitize",
                  "module": "ngSanitize"
                }
              ],
              "jQuery": {
                "key": "jquery2"
              },
              "resource": {
                "key": "angular-resource",
                "module": "ngResource"
              },
              "router": {
                "key": "ui-router",
                "module": "ui.router"
              },
              "ui": {
                "key": "angular-material",
                "module": "ngMaterial"
              },
              "cssPreprocessor": {
                "key": "node-sass",
                "extension": "scss"
              },
              "jsPreprocessor": {
                "key": "none",
                "extension": "js",
                "srcExtension": "js"
              },
              "htmlPreprocessor": {
                "key": "none",
                "extension": "html"
              },
              "bootstrapComponents": {
                "name": null,
                "version": null,
                "key": null,
                "module": null
              },
              "foundationComponents": {
                "name": null,
                "version": null,
                "key": null,
                "module": null
              },
              "paths": {
                "src": "src",
                "dist": "dist",
                "e2e": "e2e",
                "tmp": ".tmp"
              }
            }
          }
        }

Generator Version -0.10.0

Motivation for or Use Case - When bower packages don't specify css files in main.

JS is being injected, but SCSS and CSS isn't. I know for SCSS files, they must be imported in the Vendor.SCSS file.

My bower.json overrides:
 "overrides": {
    "owl.carousel": {
      "main": ["dist/assets/owl.carousel.min.css", "dist/assets/owl.theme.default.min.css", "dist/owl.carousel.min.js"]
    },
    "owlcarousel": {
      "main": [
        "owl-carousel/owl.carousel.min.css",
        "owl-carousel/owl.theme.default.min.css",
        "owl-carousel/owl.carousel.min.js"
      ]
    },
    "bootstrap-sass":{
      "main": [
        "assets/stylesheets/_bootstrap.scss",
        "assets/javascripts/bootstrap.js"
      ]
    }
  }

**Comment by zckrs** [comment]
Unreadable issue see https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md#issues

**Comment by Swiip** [comment]
I doubt this an issue for the generator. Our injector use wiredep, has you checked if wiredep support this?

**Comment by zckrs** [comment]
You solve issue ?

**Comment by robertbaker** [comment]
No I didn't, glanced at this issue and thought it was the other one.

**Comment by robertbaker** [comment]
See issue:
https://github.com/taptapship/wiredep/issues/175#issuecomment-89404985

I'll try to find some time to give a repro case.

>Also, I don't believe the inject task is configured to look for SCSS files: >https://github.com/Swiip/generator-gulp-angular/blob/v0.10.0/app/templates/gulp/_inject.js#L59.
>
>Additionally, I used your material-design-icons as a reference, and it doesn't seem to have a file called ./scss/material-design-iconic-font.scss in it, but maybe I was just on a different version.

>If you can confirm this still won't work after pointing wiredep to your SCSS file which has placeholders like shown above, a test case will definitely be appreciated :)

**Comment by robertbaker** [comment]
Updated my proj to 0.11.

Closing until I can repro again.
