### ISSUE TITLE
Issue with CSSO on gulp build

### ISSUE THREAD

**Issue by sak55** [Swiip/generator-gulp-angular#446]
Upon building my app I received this css validity [Error Message](https://github.com/sak55/skedaddle/issues/6) from [CSSO](https://github.com/css/csso).  

I tracked the following issues and ruled out their suggested fixes on this one:
* https://github.com/css/csso/issues/206 
* https://github.com/css/csso/issues/185
* https://github.com/Swiip/generator-gulp-angular/issues/362

The app will build when I comment out CSSO.  But I would like to run this optimization tool.

**Comment by zckrs** [comment]
This is related to generator ? or a bower lib ? 
`Error: Please check the validity of the CSS block starting from the line #5128`
