### ISSUE TITLE
Worth adding coverage to unit tests?

### ISSUE THREAD

**Issue by elliot-a** [Swiip/generator-gulp-angular#451]
Would it be worth adding test coverage generation to the karma.conf.js ? Something simple like this perhaps : https://gist.github.com/elliot-a/871a3e65ea0a209cd296. I find coverage really valuable but unless I missed something it doesn't seem to be an option?

**Comment by Swiip** [comment]
Coverage is interesting and it would be great to ship it as default. But it should not run everytime only on special gulp task. Perhaps you don't see it in a fresh project but the coverage of the generator tests for example really takes time.

**Comment by zckrs** [comment]
In progress https://github.com/Swiip/generator-gulp-angular/pull/598

**Comment by zckrs** [comment]
Done. 
Coverage is enabled for plain Javascript and Coffeescript
