### ISSUE TITLE
Contribution [jscs] [scss] [css analyzers] [others]

### ISSUE THREAD

**Issue by andrenovax** [Swiip/generator-gulp-angular#453]
Hi!

Thanks for the awesome generator!
I've added a few features in my [fork](https://github.com/andrenovax/generator-gulp-angular/commits/master).
If any of them is needed I'll contribute.

utils:
* added css analyzers
* added google pagespeed analyze tasks

build:
* added uncss [removes unused css]

mobile:
* added mobile meta tags to index.html

linters:
* added jscs and scss linters
* added js-lint task for es6

others:
* added root task to move files from src/root to dist/ dir
* added humans.txt, robots.txt, browserconfig.xml to src/root

**Comment by zckrs** [comment]
I like theses features. 
In first you can add a advanced option for UnCss :)

**Comment by robertbaker** [comment]
Add ESLint as an alt for jscs, please merge latest changes from swiip and I'll use your fork to update my existing proj.
