### ISSUE TITLE
browsersync error with freshly created stylus/material project

### ISSUE THREAD

**Issue by ironside** [Swiip/generator-gulp-angular#455]
Creating a project with choices like:

* stylus
* angular material design

running gulp serve results in the following exception spewed on the console:

    :3000/browser-sync/browser-sync-client.2.1.6.js:26 Uncaught TypeError: Cannot read property '2' of undefined

**Comment by zckrs** [comment]
I think this issue is independent of choices selected in generator but how browser-sync is used in `gulp/serve.js`

I have the same error with default choices.

**Comment by Swiip** [comment]
I have this for some time know. Never really investigate it. Perhaps we should try to update to 2.2.x before anything?

**Comment by zckrs** [comment]
I try 2.5.x. Error always present
