### ISSUE TITLE
Unexpected token }

### ISSUE THREAD

**Issue by jsmylnycky** [Swiip/generator-gulp-angular#457]
Hi all,

Really love this generator, and I have been in the process of updating a project to use the latest release.

On a completely brand new project, after completing the initial install and setup, and running 'gulp serve', I get this error: 'Unexpected token }   index.js:149'

It looks like an additional set of characters are being thrown into index.js towards the bottom:

}
/******/ ])

This is the config I ran with:

angular 1.3.x
modules: animate, cookies, touch, sanitize (all of them basically)
jquery: none
resource: ngResource
router: ngRoute
ui: ngMaterial
cssPreprocessor: node-sass
jsPreprocessor: babel
htmlPreprocessor: none
No advanced options were entered.

I'll post back if I can figure out where the issue is exactly, but wanted to bring this to others attention.

Thanks!

**Comment by zckrs** [comment]
If you remove google analytics code in index.html, what happening ?

**Comment by jsmylnycky** [comment]
I removed the ga block, did a clean & serve, and still getting the same issue.

**Comment by zckrs** [comment]
Can you try to add 'scripts' as dep for task 'scripts:watch' in 'gulp/scripts.js' ?

**Comment by jsmylnycky** [comment]
That looks to have cleared it up!

```
gulp.task('scripts:watch', ['scripts'], function (callback) {
    return webpack(true, callback);
  });
```

**Comment by jasonswett** [comment]
I had this same issue. How come `scripts` isn't set as a dep for `scripts-watch` out of the box?

**Comment by jsmylnycky** [comment]
@jasonswett It is now.  It was a bug that they corrected.
