### ISSUE TITLE
Mode cors in gulp build

### ISSUE THREAD

**Issue by brunoksato** [Swiip/generator-gulp-angular#465]
Is possible add mode cors in build gulp:serve ?

**Comment by Swiip** [comment]
What do you want to achieve? If you have cors problems using the gulp serve server targetting a backend on an other URL, it's on your backend you have to configure cors. You can also use the proxy to get around of the problem.

If you really want to handle cors on the dev server (but I don't know why you could want that), you can use a connect middleware like https://www.npmjs.com/package/connect-cors

**Comment by Stibbons** [comment]
I config, the proxy should be used for this case (i do, and it works great!)

**Comment by brunoksato** [comment]
I have problem when using 2 application on localhost with different doors, and I need to use extension of chrome to solve my problem, I would no longer need to use this extension

@Stibbons I will try !

**Comment by jbaroudi** [comment]
@brunoksato as @Swiip says:

I have two Projects now with this (amazing) generator. In one project i use  Microsoft web api 2 CORS support and in the other Laravel 5 and both have their way to achieve this... My point, No setup or install on angularjs had to be made to make it work.

MS WEB API 2 Cors support:

1) Install Web API 2 CORS Support with Nuget in Tools/Nuget Manager and search web api cors
2) add code in App_Start/WebApiConfig.cs

`config.EnableCors(new EnableCorsAttribute("*", "*", "*"));`

*Warning: this is: All request methods from all clients no matter their domain or port.*

Laravel 5 Cors support is out of the box:

1) check if app/Http/kernel.php has 'App\Http\Middleware\CORSPreflight'
2) check App\Http\Middleware\CORSPreflight for the details:

`````php
public function handle($request, Closure $next)
    {
        return $next($request)->header('Access-Control-Allow-Origin', '*')
                        ->header('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE')
                        ->header('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization, X-Requested-With');
    }
````

Hope this helps :)

**Comment by zckrs** [comment]
This issue is a nice feature/enhancement but we (Swiip and me) don't have time to implement this for the moment.
Our first priority is stabilized functionality already present in the generator for the purpose of releasing v1.0.0

For clarity in issues I will close the issue and marks it as "good-but-no-time".
Any good contributions to resolve this matter is appreciated and merged.

Otherwise we will reopen the issue after the v1.0.0
