### ISSUE TITLE
although unit test is setup the test suite is empty...

### ISSUE THREAD

**Issue by bastienJS** [Swiip/generator-gulp-angular#473]
When I start the karma runner the test suite is empty =>

"C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\JetBrains\WebStorm 10.0.1\plugins\js-karma\js_reporter\karma-intellij\lib\intellijRunner.js" --karmaPackageDir=C:\iplanmylessons.client\node_modules\karma --serverPort=9876 --urlRoot=/
Empty test suite.

Process finished with exit code 0

I know that the karma.config.js needs entries in the files property like this:

files: [ 'pathToMyTestFiles.js']

but do newbies know that?

I think that is an improvement, but I do not know wether this is your improvment or you are just forwarding the karma stuff...

I would just expect from a generator tool when I start the application that it loads
and when I run the tests that i runs the tests available.

**Comment by YonatanKra** [comment]
Hi,
I still get this issue with the latest version of the generator.
1) Installed the generator.
2) `yo` it
3) Just run the `karma.conf` in webstorm
4) Get an empty test suite message.
5) `gulp test` works as expected.
Anything that I need to do in order to get this to work in webstorm?

**Comment by Codem3ay** [comment]
Hey @YonatanKra I'm interested if you found a solution for this problem, still getting this empty test suite even if everything is setup correctly
