### ISSUE TITLE
Fail to run test:auto task

### ISSUE THREAD

**Issue by anggiaj** [Swiip/generator-gulp-angular#476]
``` 
.concat(_.pluck(files, 'path'))
          ^
TypeError: Cannot read property 'concat' of undefined
    at /Users/user/foobar/gulp/unit-tests.js:39:11
```

**Comment by busches** [comment]
Note this is only failing for `test:auto`, `test` works just fine. When running `test:auto` `wiredepOptions` has a `stream` key that contains the `index.html` and when passed to `wiredep` it's returning html instead of a JS object.

**Comment by Swiip** [comment]
Yep, I found it. Wiredep mutates the option object you give. This is a strange behavior I have not expected. When you use test:auto, the task dependencies launch wiredep multiple times so the options are broken.

Anyway, I'll submit a PR soon.

**Comment by JamesBender** [comment]
Has this been published? I just updated my generator and created an application, still getting this error.

**Comment by zckrs** [comment]
Nope https://github.com/Swiip/generator-gulp-angular/compare/v0.11.0...master
