### ISSUE TITLE
gulp serve:dist causing 404 loop and subsequent browser crash

### ISSUE THREAD

**Issue by ajkan** [Swiip/generator-gulp-angular#478]
Firstly, Thank you for the wonderful generator. Love the way you have organized the directory structure. Though it needed some convincing to make my team adopt the new structure, everybody loves it now.

WRT the issue, **gulp serve** works perfectly fine. When I do a **gulp serve:dist** , the tasks seem to be completed without issues as seen in the screenshot. 
![gulpservedist](https://cloud.githubusercontent.com/assets/7103901/7051375/caf6089a-dddc-11e4-960f-eced181025d6.png)

However, the browser goes into a 404 loop and subsequently freezes as below. 
If it makes a difference, I have also added a task for loading jsons into the assets/json directory in the build process, which seems to be working fine.
![404loop](https://cloud.githubusercontent.com/assets/7103901/7051376/cb44c926-dddc-11e4-9d4c-fadab7a32409.png)

I did go through the issue list here and it looks similar to the #12 issue, but that seems like it was resolved in subsequent releases.
Any help would be appreciated @Swiip.

**Comment by Swiip** [comment]
Strange, never seen this. Can you give us your options through an export of your .yo-rc.json?

**Comment by ajkan** [comment]
Sure. Here it is.


{
  "generator-gulp-angular": {
    "props": {
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      },
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "name": "angular-animate",
          "module": "ngAnimate"
        },
        {
          "name": "angular-cookies",
          "module": "ngCookies"
        },
        {
          "name": "angular-touch",
          "module": "ngTouch"
        },
        {
          "name": "angular-sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "name": "jquery",
        "version": "~2.1.1"
      },
      "resource": {
        "name": "restangular",
        "version": "~1.4.0",
        "module": "restangular"
      },
      "router": {
        "name": "angular-route",
        "module": "ngRoute"
      },
      "ui": {
        "name": "bootstrap-sass-official",
        "version": "~3.3.1",
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "name": "angular-bootstrap",
        "version": "0.12.x",
        "key": "ui-bootstrap",
        "module": "ui.bootstrap"
      },
      "cssPreprocessor": {
        "key": "node-sass",
        "extension": "scss",
        "module": "gulp-sass",
        "version": "~1.1.0"
      },
      "jsPreprocessor": {
        "key": "none",
        "extension": "js",
        "srcExtension": "js",
        "module": null,
        "version": null
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html",
        "module": null,
        "version": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      }
    }
  }
}

**Comment by zckrs** [comment]
Fixed in master.

**Comment by zckrs** [comment]
:tada: Just released v0.12.0 :tada:
Your issue should be fixed. I close but if you can retry your case with a new fresh install of generator you are welcome. Any feedback would be appreciated (positive comments too ^_^).
