### ISSUE TITLE
WebStorm karma config problems

### ISSUE THREAD

**Issue by Stamy** [Swiip/generator-gulp-angular#481]
I noticed that the final config of karma is generated in gulp and there is no easy way getting it without the changing the gulp files (as far as I know). I was thinking that there should be a way to kind of keep everything in a karma config.

For example there is other yo generator (https://github.com/johnpapa/generator-hottowel) for angular from creator who maintains the famous angular style guide (https://github.com/johnpapa/angular-styleguide). The generator tries to follow angular style guide he wrote:

This is how his generated karma config looks:
```javascript
module.exports = function(config) {
    var gulpConfig = require('./gulp.config')();

    config.set({
        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: './',

        // frameworks to use
        // some available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['mocha', 'chai', 'sinon', 'chai-sinon'],

        // list of files / patterns to load in the browser
        files: gulpConfig.karma.files,

        // list of files to exclude
        exclude: gulpConfig.karma.exclude,

        proxies: {
            '/': 'http://localhost:8888/'
        },

        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: gulpConfig.karma.preprocessors,

        // test results reporter to use
        // possible values: 'dots', 'progress', 'coverage'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress', 'coverage'],

        coverageReporter: {
            dir: gulpConfig.karma.coverage.dir,
            reporters: gulpConfig.karma.coverage.reporters
        },

        // web server port
        port: 9876,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR ||
        // config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,

        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,

        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        //        browsers: ['Chrome', 'ChromeCanary', 'FirefoxAurora', 'Safari', 'PhantomJS'],
        browsers: ['PhantomJS'],

        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: false
    });
};
```

So by doing this way it might be more flexible and it should work with WebStorm karma runner. Or maybe someone know how to start WebStorm with current karma setup ?

**Comment by zckrs** [comment]
Thanks to report.
You can see here https://github.com/Swiip/generator-gulp-angular/pull/469 I have start to apply guideline's of johnpapa
And `generator-hottowell` can be inspiration

**Comment by zckrs** [comment]
Why you didn't use `karma.conf.js` generated with this generator ? 
What you need for Webstorm ?

**Comment by Stamy** [comment]
In order to run karma tester I have to use cmd `gulp test` which runs this method from  `unit-tests.js` file. So you can see that it is generating and including additional files and including and they are missing in `karma.config.js`. So running only one karma file without this command runs karma without no config.

```js
function runTests(singleRun, done) {
    listFiles(function (files) {
        karma.server.start({
            configFile: __dirname + '/../karma.conf.js',
            files: files,
            singleRun: singleRun,
            autoWatch: !singleRun
        }, done);
    });
}
```

**Comment by Stamy** [comment]
Related to: #473.

**Comment by Swiip** [comment]
In the generator, all is centralized in Gulp. We use the file listing and sorting of our gulp plugins to inject the right configuration into karma. We wanted to avoid having duplicate configurations in gulp and karma.conf.

generator-hottowel seems to answers that by calling the code of gulp from the karma conf which is also a Node script. We could look into this solution

**Comment by ajkan** [comment]
@Stamy 
Hi there,
I do have karma and karma coverage configured on webstorm.
Like you mentioned, the files are listed in the karma config file so webstorm can run the tests.
So, wouldn't the problem be resolved if you replace/add the files variable to your karma conf?

I do not use the test task created by this generator as webstorm is already performing it for me.
Is there any particular reason you would want to use both?

Pardon me if I didn't get your problem.

**Comment by Stamy** [comment]
@ajkan The problem that I need to reconfigure it myself. It doesn't work out of the box. It is good that you are smart enough and understand how to configure it yourself. However people are generally lazy some of them do not have the time to find out how to reconfigure it, and they definitely don't want to spend time looking in the code to understand why it is not working which could be spent better. In the dream world you run generator you work on your app and you forget all the test/gulp config. That is the whole idea of the generator to save time and headaches. Anyway if it can cover both cases so why not ? It takes time to understand these things works.

If you don't mind please share how did you configured it yourself. I am curious to see it.

**Comment by ajkan** [comment]
@Stamy 
I get what you mean. It did take some time for me to figure why the tests were not working too.
I do have one of my team mates who uses sublime text and hence has to use the command line. karma start works with this config, gulp test task might not.

In terms of configuring it, this is how my karma conf looks like
'use strict';

module.exports = function(config) {

  config.set({
    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    autoWatch : true,

    frameworks: ['jasmine'],

    files: [
     "path to files"
    ],

    browsers : ['Chrome'],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      '**/*.js': ['coverage']
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress', 'coverage'],

    // optionally, configure the reporter
    coverageReporter: {
      type : 'html',
      dir : 'coverage/'
    },

    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,



    plugins : [
      'karma-chrome-launcher',
        'karma-phantomjs-launcher',
        'karma-coverage',
        'karma-jasmine'
    ]
  });
};

**Comment by Stamy** [comment]
Sorry for not being clear, but I was only interested in files variable. To see your approach, which is not visible here, you add the files manually ?:
```
files: [
 "path to files"
],
```

**Comment by ajkan** [comment]
yup 

src/components/**/*.js 
bower_components/**/*.js

**Comment by Stamy** [comment]
Well if that is what you are using it is not ideal, because `wiredep` should sort out all the bower_components folder javaScripts for you because there a lot of redundant javascript files in there and with your example you are loading everything in there. But thanks for sharing :+1:

**Comment by ajkan** [comment]
Yw. It's actually specific component files like
"bower_components/angular/angular.js",
"bower_components/angular-mocks/angular-mocks.js",
"bower_components/angular-cookies/angular-cookies.js",
"bower_components/angular-touch/angular-touch.js",
"bower_components/angular-bootstrap/ui-bootstrap.js",

The reason was because it kept complaining about those packages when I'd run the tests.
