### ISSUE TITLE
JSHint throwing 'use strict'; errors out of the box

### ISSUE THREAD

**Issue by busches** [Swiip/generator-gulp-angular#482]
Currently the `.jshintrc` file has the following rule `"strict": true` by default. Both `main.controller.js` and `main.controller.spec.js` with throw a rule violation if you run any of the gulp tasks that run `jsHint` out of the box.

I'm not sure if you'd rather turn off the rule or fix the issue.

**Comment by Swiip** [comment]
Both
- https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/src/app/main/_main.controller.js
- https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/src/app/main/_main.controller.spec.js
has global ```'use strict';``` as first statements...

I'm not sure to understand your problem...

**Comment by busches** [comment]
Oops, this is my fault, as I for some reason was missing `globalstrict: true`, so I was seeing `line 1, col 1, Use the function form of "use strict".` 

Thanks helping me find my mistake.
