### ISSUE TITLE
Protractor included in package.json but also from gulp-protractor

### ISSUE THREAD

**Issue by busches** [Swiip/generator-gulp-angular#483]
I see that `protractor` is a devDependency in the `package.json` file, but it's also a dependency for `gulp-protractor` is there a reason to have both? We should be able to remove `protractor` from the `package.json` and let `gulp-protractor` handle it.

If I'm correct that we can remove it, I can submit a PR.

**Comment by Swiip** [comment]
Yes, it seams that's not needed... Thanks
