### ISSUE TITLE
Question: Were would I add a manifest task in the gulp files

### ISSUE THREAD

**Issue by robertbaker** [Swiip/generator-gulp-angular#484]
How could I integrate
https://github.com/hillmanov/gulp-manifest

into the dist builds?

```
(function () {
  'use strict';
  var gulp = require('gulp'),
    path = require('path'),
  $ = require('gulp-load-plugins')();
  module.exports = tasks;

  function tasks(options) {
    gulp.task('manifest', function () {
      return gulp.src(options.dist + /**)
        .pipe($.manifest({
                hash: true,
                preferOnline: true,
                network: ['http://*', 'https://*', '*'],
                filename: 'app.manifest',
                exclude: 'app.manifest'
              }))
        .pipe(gulp.dest(options.dist));
    });
  }
})();

```

**Comment by zckrs** [comment]
In task `html` see `gulp/build.js`

**Comment by dylanlawrence** [comment]
Just wondering if anyone has been able to make this work yet.  I also have a feeling this will become a more requested feature as "offline availability" becomes more popular, as this project seems an ideal fit.

**Comment by mackelito** [comment]
Did you ever get this to work?

**Comment by robertbaker** [comment]
I did but I did it by doing my redoing all the gulp tasks. I broke them down on a per function basis with gulp4. I also used gulp-if and lazy pipes.
