### ISSUE TITLE
gulp tasks parsing index.html

### ISSUE THREAD

**Issue by c0debreaker** [Swiip/generator-gulp-angular#485]
I'm not sure where to post my question since it's not an issue. I don't know if we have a dedicated gulp-angular forum.

I would like to know which gulp task parses index.html since I'm new to gulp. I tried renaming index.html to index.htm and also updated all the html strings that I saw on js files under gulp then ran gulp serve. It didn't work. I was expecting it would find index.htm and it would create it under .tmp/serve but it didn't.

Thanks!

**Comment by shawn-simon** [comment]
just from scanning the code, I think it searches for *.html ... not positive though

**Comment by busches** [comment]
Look at `inject.js` and change the `return` statement there to be `return gulp.src(options.src + '/*.htm')` or even `.*htm*` to handle both. You'll need to make similar changes to `build.js` and `watch.js`.

**Comment by c0debreaker** [comment]
Thanks busches. I'll try it later.

I noticed though that even just by dropping css files under src dir, it will be included in the injection.

**Comment by Swiip** [comment]
The `inject` task centralize all modifications in the index.html. Since a couple of version, we don't modify directly the `src/index.html` anymore in profit of creating a `.tmp/serve/index.html`.

There is 3 injections made in the index.html: bower css deps, bower js deps, src js.

**Comment by c0debreaker** [comment]
Thanks. I noticed that all I have to do is add css or scss file under src and it will be included :)
