### ISSUE TITLE
controllerAs in $stateProvider.state definition

### ISSUE THREAD

**Issue by Olgagr** [Swiip/generator-gulp-angular#488]
I don't know why this is not working. When I use it without the generator it works. My stack is:
- coffescript
- generator version 0.11.0

What I do:

In the generated index.coffee I add:

```
angular.module 'trh', ['ngSanitize', 'ui.router']
  .config ($stateProvider, $urlRouterProvider) ->
    $stateProvider
      .state "home",
        url: "/"
        templateUrl: "app/main/main.html"
        controller: "MainCtrl"
        controllerAs: "vm"

    $urlRouterProvider.otherwise '/'
```

Then I change the main.controller.coffee:

```
    @awesomeThings = []
    angular.forEach @awesomeThings, (awesomeThing) ->
      awesomeThing.rank = Math.random()
```

And in main.html:
```
    <div class="col" ng-repeat="awesomeThing in vm.awesomeThings | orderBy:'rank'">
```

After loading the page I don't see list of awesomeThings. I confused as it should work and hard to believe that generator causes the problem here but maybe somebody has similar problem.

**Comment by zckrs** [comment]
Look JS generated by coffee for main.controler.JS 
 `return angular.foreach('....`  is the problem.

Solution: Add a return in main.controller.coffee like here https://github.com/Swiip/generator-gulp-angular/pull/469/files#diff-4f268673bdbb6bb3632e783b10312b2aR7

**Comment by Olgagr** [comment]
Aha, you're right. Thank you :)
