### ISSUE TITLE
Customize Foundation

### ISSUE THREAD

**Issue by NicoBleh** [Swiip/generator-gulp-angular#489]
Hi,

i try to figure out how to customize the foundation styles.

As i know the way to do it is to change the parameters in _settings.scss

But changing this under "bower_components" does not make sense.

When i try to set a value in like index.css it does not effect the foundation appearance at all.

Am i missing something?

**Comment by scttcper** [comment]
Try editing or importing your variable cutomizations in the vendor.scss file.

**Comment by NicoBleh** [comment]
Tried that:

    /* The import of foundation is made manually because there is still no links of the
    sass version in theit bower.json... */
    @import '../../bower_components/foundation/scss/foundation';

    $body-bg: $black;

    /* Do not remove this comments bellow. It's the markers used by wiredep to inject
    sass dependencies when defined in the bower.json of your dependencies */
    // bower:scss
    // endbower

Nothing changed with the background color.
