### ISSUE TITLE
Since #466, with Stylus,  sample app have no css

### ISSUE THREAD

**Issue by zckrs** [Swiip/generator-gulp-angular#492]
https://github.com/Swiip/generator-gulp-angular/pull/466

Because bower deps missing. 

We can use: 
* Bootstrap - Stylus: https://github.com/maxmx/bootstrap-stylus :warning: wrong main property in their bower.json
* Foundation - Less: not found
* Foundation - Stylus: not found

Maybe use CSS lib as fallback

**Comment by Swiip** [comment]
Ooops, sorry :)

UI frameworks with no native css preprocessor sources should be included as CSS.
