### ISSUE TITLE
Directives with templateUrl can't be tested with "gulp test"

### ISSUE THREAD

**Issue by jamm** [Swiip/generator-gulp-angular#500]
Because templates are not in $templateCache. I see file with templates in .tmp/partials, but it's not being used and directive trying to load template via http (but $httpBackend is mocked in test mode, so it fails).
v0.11.0

**Comment by Swiip** [comment]
`.tmp/partials` are not used to that. But I recently added `karma-ng-html2js-preprocessor` in the karma configuration especially for that. I had tested with a directive at the time...

Keeping an illustration of testing a directive is right now on the table in #493

**Comment by jamm** [comment]
@Swiip I've created repo with project, generated by gulp-angular master branch version (installed by `npm install -g git+https://github.com/Swiip/generator-gulp-angular.git`)

https://github.com/jamm/gulp-angular-directive-test-demo

You can clone it, `npm install`, and try to run `gulp test` to see request to template.

**Comment by Swiip** [comment]
Found :)

karma-ng-html2js-preprocessor is configured with the name of the angular module (in karma.conf.js). It's wrong in your repo so the template is not "preloaded". I tried to correct it and the test pass.

**Comment by jamm** [comment]
Confirm, all works fine :) Thank you.
If it's possible, please use name of module user entered in generation step. I thought it's some internal "mocking" module.

**Comment by Swiip** [comment]
WoW, but you're right, it's not templatized :)

https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/_karma.conf.js#L54

**Comment by stewones** [comment]
+1 here, it seems directives with templateUrl not using the plugin html2js on `gulp test`. 
```
{
  "generator-gulp-angular": {
    "version": "0.11.0",
    "props": {
      "angularVersion": "~1.3.15",
      "angularModules": [],
      "jQuery": {
        "key": "none"
      },
      "resource": {
        "key": "none",
        "module": null
      },
      "router": {
        "key": "none",
        "module": null
      },
      "ui": {
        "key": "none",
        "module": null
      },
      "cssPreprocessor": {
        "key": "none",
        "extension": "css"
      },
      "jsPreprocessor": {
        "key": "none",
        "extension": "js",
        "srcExtension": "js"
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html"
      },
      "bootstrapComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      }
    }
  }
}
```

**Comment by stewones** [comment]
according by this [sample](https://github.com/vojtajina/ng-directive-testing/blob/master/karma.conf.js), i realized that i need to append the html templates in karma.conf
here i solve this way

```js
 return wiredep(wiredepOptions).js
    .concat([
      path.join(conf.paths.src, '/app/**/*.module.js'),
      path.join(conf.paths.src, '/app/**/*.js'),
      path.join(conf.paths.src, '/**/*.spec.js'),
      path.join(conf.paths.src, '/**/*.mock.js'),
      path.join(conf.paths.src, '/**/*.html') //adding templates        
    ]);
```

i can make a PR if it is right

**Comment by zckrs** [comment]
Can you open a new issue ?

**Comment by stewones** [comment]
@zckrs #546

**Comment by dereklin** [comment]
I can't figure this out yet.  In your git demo example, you have 
```
    var srcFiles = [
      options.tmp + '/serve/app/index.js'
    ].concat(specFiles.map(function(file) {
      return '!' + file;
    }));

```
In the actual gulp-angular tool, it's:
```
    var srcFiles = [
      options.src + '/app/**/*.js'
    ].concat(specFiles.map(function(file) {
      return '!' + file;
    }));
```

Am I using the old version?...
