### ISSUE TITLE
directory structure in dist

### ISSUE THREAD

**Issue by gimox** [Swiip/generator-gulp-angular#502]
in dist folder i have all app folder structure without file, is a bug?

**Comment by Swiip** [comment]
This is the whole point. In the dist folder, scripts are concatenated. Check at https://www.npmjs.com/package/gulp-useref which is the main plugin which do that.

**Comment by robertbaker** [comment]
In the dist folder you still have dist/app/** which has nothing but empty folders. I think the dist/app/** should be removed after the dist build completes.

**Comment by gimox** [comment]
yes, i can remove, or add a middleware in build to delete entire folder.

i don't know if this is my misconfiguration or something wrong.

**Comment by Swiip** [comment]
I confirm that there is an `app` folder in `dist` which should not be there if you don't have any static assets.

**Comment by chriskolenko** [comment]
I changed the other function inside the gulp/build.js file

    gulp.task('other', function () {
        return gulp.src([
          options.src + '/**/*',
          '!' + options.src + '/**/*.{html,css,js,scss,hbs}',
          '!' + options.src + '/{app,app/**}'
        ])
          .pipe(gulp.dest(options.dist + '/'));
      });

**Comment by Swiip** [comment]
That does the trick. I don't see a clean way to do it for everybody. I want to keep possibility that people put "other" files in the app.

**Comment by chriskolenko** [comment]
@Swiip That makes perfect sense. Would be great if there was a clean way to exclude empty folders with recursively checking sub folders etc.

**Comment by Swiip** [comment]
Yeah, I've searched for that, but without writing some sort of specific gulp plugin, I didn't find a simple way to do that.

I think it's because we add the directory then remove the content with the second (and negative) rule. But knowing that doesn't make it easier...

**Comment by sercba** [comment]
+1
