### ISSUE TITLE
fonts with no bower install

### ISSUE THREAD

**Issue by Tallyb** [Swiip/generator-gulp-angular#505]
Hi, 
Is there a way to add fonts that do not have bower install? 
I can place them under assets. what else?

**Comment by Swiip** [comment]
You can, it sill simply be considered as any asset and be copied in the dist folder.

The font/bower/replace mechanism is only used by font in bower deps because we can't place the font in dist in the same path than in dev because we don't release the bower_dependencies folder.

**Comment by Tallyb** [comment]
Not sure I get it, I might be missing something. 
I added under assets/fonts/myFonts folder. 
It contains the font files (woff, svg, eot...). This folder also contains the font-face declaration in a css file which are pointing to the same folder. 
How do I use them during development (serve/watch)?

**Comment by Swiip** [comment]
Ok, I think you just have to look at your `gulp/inject.js`, the inject styles are searched in `app/**/*.css` and so it will not inject a css placed in the asset folder.

You can resolve this by putting the css in the app folder (changing the relative path to the font files) or change the inject styles filter to look into the asset folder.

**Comment by Tallyb** [comment]
Thank you ! you are really great and helpful. 
I will try the first solution, probably, as I do not want to mess with the gulp files (to support future updates). 
Is it worth a PR for supporting user fonts from assets folder?

**Comment by Swiip** [comment]
Don't know it's borderline. Injection should not look into assets folder. But it's not a silly situation to have a css with fonts. Should we update the file selector for everyone for this exception or not? I really don't know.
