### ISSUE TITLE
If I put components directory in the same parent directory with app,how to modify gulp files

### ISSUE THREAD

**Issue by huguangju** [Swiip/generator-gulp-angular#518]
If I put "components" directory in the same parent directory with "app", like:
```
src
  — app
  — assets
  — components
  — less
```
see: [http://www.artandlogic.com/blog/2013/05/ive-been-doing-it-wrong-part-1-of-3/](http://www.artandlogic.com/blog/2013/05/ive-been-doing-it-wrong-part-1-of-3/)

I am modified blow gulp files:
but run with ``` gulp serve ``` is ok, run with ```  gulp serve:dist ``` will report error:
``` html
Failed to load resource: the server responded with a status of 404 (Not Found)  

http://localhost:3000/components/navbar/navbar.html 
```

**build.js**
```javascript
gulp.task('partials', ['markups'], function () {
    return gulp.src([
      options.src + '/app/**/*.html',
      options.tmp + '/serve/app/**/*.html',
      options.src + '/components/**/*.html',
      options.tmp + '/serve/components/**/*.html'
    ])
```
**inject.js**
```javascript
var injectScripts = gulp.src([
      options.src + '/app/**/*.js',
      options.src + '/components/**/*.js',
      '!' + options.src + '/app/**/*.spec.js',
      '!' + options.src + '/app/**/*.mock.js'
    ])
```
**script.js**
```javascript
gulp.task('scripts', function () {
    return gulp.src([
      options.src + '/app/**/*.js',
      options.src + '/components/**/*.js'
    ])
```
**watch.js**
```javascript
 gulp.watch([
      options.src + '/app/**/*.js',
      options.src + '/components/**/*.js'
    ], function(event) {
```
**index.html**
```html
<div ng-include="'components/navbar/navbar.html'"></div>
```

**Comment by robertbaker** [comment]
If you go back a few commits, you will see what this generator used to have components as a parent directory.

However, there are good reasons for having everything reside in app, including components.

Your components are most likely tied and related to your app anyway, why have it in a top directory?

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/pull/447 can be help you if you really need a `components` folder outside `app`
