### ISSUE TITLE
Issues with Node v0.12.x?

### ISSUE THREAD

**Issue by milkshoes** [Swiip/generator-gulp-angular#519]
Wasn't sure if i was the only one having issues running this with the latest Node version 0.12.x? I'm on Windows 8 and previous versions of Node seemed to work, but since I've upgraded my Node version to 0.12 this generator no longer works for me. Thoughts? Thanks for your time and patience!

**Comment by robertbaker** [comment]
I'm running the latest node and latest NPM (with the latest packages npm needs)
You need npm-check-updates installed.

Node 12.2 has a slightly broken NPM, I would update it.
This assumes Windows x64.
```
@echo on
call npm cache clean -f
cd /d "C:\Program Files\nodejs"
call npm install npm@latest
cd /d "C:\Program Files\nodejs\node_modules\npm"

call npm-check-updates -u
cd /d "C:\Program Files\nodejs\node_modules\npm"
call npm update
cd /d "C:\Program Files\nodejs\node_modules\npm"
call npm update -g
call npm-check-updates -g
pause

```

**Comment by Swiip** [comment]
There is no issue for the generator on node 0.12. I used it myself for a long time. Have you updated the generator to the last version ? What kind of error do you have ?

(a bit of npm cache clean and npm update could not be wrong too)

**Comment by milkshoes** [comment]
I can in fact verify that using an older version of your generator caused my issues with NodeJS 0.12.2 on Windows 8.1 64bit . Now with that said I had done some heavy modifications to the overarching structure and build mechanisms in place for the older generator i was using. So really I will have some re-factoring to do based on the new stuff, which I think will be fine because it means we will get all the new awesome updates you've provided with your latest generator. Thanks Swiip!

**Comment by nabinkumarn** [comment]
I too was in problem with node when I updated it to 0.12.x. There was problem with node sass. Gulp did not work. After being suffered for couple of hours I installed the older version of node and everything is fine now
