### ISSUE TITLE
Client caching?

### ISSUE THREAD

**Issue by npearson72** [Swiip/generator-gulp-angular#520]
I recently ran my site through an online speed tester, and it gave me this feedback:

````
Leverage browser caching	

The following cacheable resources have a short freshness lifetime. Specify an expiration at least one week in the future for the following resources:

http://my-domain.net/scripts/app-7ea02d19.js (expiration not specified)

````

Is there a way to set the expiration?

Thanks

**Comment by intellix** [comment]
I don't believe this has anything to do with the generator. It's talking about HTTP expiration as is managed by your web server (nginx/apache)

**Comment by Swiip** [comment]
Yeah, I think it's about HTTP expiration headers which is out of our scope.
