### ISSUE TITLE
Bower assets and relative paths when building.

### ISSUE THREAD

**Issue by MinDokan** [Swiip/generator-gulp-angular#521]
I see an issue when using bower components that contains assets.
For example, a css file linking a font.
When building, the font is in /font directory, while the css file is looking into the same directory.

I can't think on a method to solve this.

**Comment by MinDokan** [comment]
Well, I found a solution, at least for my fonts. I don't think I'll have this problem with images for now, in any case. Here is mi snippet.

Using this gulp plugin.
gulp-modify-css-urls
https://www.npmjs.com/package/gulp-modify-css-urls

after
``` 
.pipe($.replace('../../bower_components/bootstrap/fonts/', '../fonts/'))
``` 
I added this pipe.
```
      .pipe(modifyCssUrls({
        modify: function (url, filePath) {
          var arrayUrl = url.split('/');
          var fileName = arrayUrl[arrayUrl.length-1];
          return fileName;
        },
        prepend: '../fonts/'
      })) 
``` 
It may be an awful solution, but hey, it works. We can enhance in the future and make it even faster.
Thoughts?

**Comment by zckrs** [comment]
Do you have a bower package as example ?

**Comment by MinDokan** [comment]
Yes. Two at the moment.
`angular-ui-grid` and `themify-icons` were in conflict.
I assume because of the path been hard coded on the CSS files.

Thanks.

**Comment by Swiip** [comment]
It's a known issue that bower assets linked inside the css are broken in the dist version. It's why you find the manual replace for the bootstrap fonts url.

But I like your gulp plugin. I didn't know about it. It could be better than what we have now.

**Comment by Swiip** [comment]
It's great for CSS links but it's not the whole problem, it can be more resources in the bower. I'm afraid to deliver something to everyone only responding to a part of the problem.

I keep this manually at least without a good PR.
