### ISSUE TITLE
Gulp tasks refactoring

### ISSUE THREAD

**Issue by robertbaker** [Swiip/generator-gulp-angular#522]
Currently it's a bit of a pain to add new functionality to the build process.

For example: I want to integrate gulp-manifest on dist builds.

I would also like to use gulp-replace to replace things depending on a build.

To do this, either I execute these things after the build, then in gulp.src reference the dist folder, etc.

For replacing things, that's not ideal. I want to replace things based on the src for 1 build, but not necessarily for all of them. Since the code is minified and changed, replace based on a build output isn't ideal either.

It would be nice if the gulp tasks were refactored to allow easier extension.

**Comment by zckrs** [comment]
I waiting gulp4 release to start refactoring

**Comment by Swiip** [comment]
Don't really see what you would prefer. The big changes between src and dist are because of gulp-useref but it's too central to imagine replacing it.

You can make replaces in the build stream in the html task after that useref has loaded all the files by using filters...
