### ISSUE TITLE
Question: how to set BabelJS option

### ISSUE THREAD

**Issue by jamm** [Swiip/generator-gulp-angular#524]
I'm trying to use new BabelJS option for IE8 ([ie8safe](https://github.com/babel/babel/issues/1369)), but I don't see in gulp scripts where I can set option. I don't see any "transpile" or "babel" in pipes or tasks. Only in 1 place, but there is no way to set option.
```
loaders: [{ test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'}]
```

**Comment by Swiip** [comment]
You can add option with a query string syntax. Not really sexy but working... I was using the babel runtime lately: 

`{ test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader?optional=runtime' }`

**Comment by jamm** [comment]
Cool, it works! 
`optional=jscript`

**Comment by kondi** [comment]
There is no ie8Safe option, you have to use the `jscript` transformer instead. Add it to your `.babelrc` file:
```javascript
{
	"optional": ["jscript"]
}
```

**Comment by kondi** [comment]
Looks I was few seconds late :)

**Comment by jamm** [comment]
oops, sorry @kondi, I closed issue exactly when you commented.
