### ISSUE TITLE
Sample for helping us Noobz?

### ISSUE THREAD

**Issue by redaikidoka** [Swiip/generator-gulp-angular#526]
I wonder if you'd be willing to post a small project that has used this generator a little bit.
I can bumble along in regular angular doing everything manually, but I find it very challenging with the awesome magic of gulp to figure out in this model where (and how!) I should add new directives and filters, and struggle with including things like chrono and getting it to work.

Maybe there's a little app out there already that someone has toyed with that you could point us towards in the .md file.

Thanks much!

**Comment by Swiip** [comment]
Look at the code from this branch #493. We already work on an extended version of the generated website which illustrate better how to start.

**Comment by redaikidoka** [comment]
Awesome, thank you so much!

On Mon, May 4, 2015 at 7:57 AM, Matthieu Lux <notifications@github.com>
wrote:

> Look at the code from this branch #493
> <https://github.com/Swiip/generator-gulp-angular/pull/493>. We already
> work on an extended version of the generated website which illustrate
> better how to start.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Swiip/generator-gulp-angular/issues/526#issuecomment-98740164>
> .
>



-- 

-=-=-==-=-=-=-==-=-=-=-=-=-=-=-=-=-
Pol Stafford
Storyteller, Writer, Geek, Sensei
