### ISSUE TITLE
dist output directory for fonts, scripts and styles

### ISSUE THREAD

**Issue by chriskolenko** [Swiip/generator-gulp-angular#527]
Is there a way to change the output directory of fonts, scripts and styles? I would like everything to output to the assets folder. 

ie. 
dist/assets/fonts
dist/assets/scripts
dist/assets/styles
dist/assets/images
dist/index.html

**Comment by Swiip** [comment]
In your `index.html` search for the comments starting with `<-- build`. At the end, there is the target file name for the bundle, you can change it there.

Example: 
`<!-- build:css({.tmp/serve,src}) styles/vendor.css -->` ->
`<!-- build:css({.tmp/serve,src}) assets/styles/vendor.css -->`

About images and fonts, you have to change paths in the `gulp/build.js`

**Comment by chriskolenko** [comment]
Perfect, already figured out the "other" task in gulp/build.js
