### ISSUE TITLE
bower missing in package.json

### ISSUE THREAD

**Issue by ufoscout** [Swiip/generator-gulp-angular#528]
Hi all,

the bower dependency is missing in the devDependencies section of the package.json.
I think it should be present with the expected version because, indeed, it is a required dependency to perform a full build in environments where bower is not installed in the global scope.
For example, for a project of mine, the continuous integration server fails the build because it cannot find bower in the node_modules folder.

**Comment by Swiip** [comment]
Was about to argue but in the end, it's handy for ci so why not...
