### ISSUE TITLE
gulp/conf errorHandler emit('end') not work when catched an error

### ISSUE THREAD

**Issue by abbish** [Swiip/generator-gulp-angular#529]
when sass file has some error and ruby-sass can throw the error,  gulp/conf errorHandler has catched the error but it not stop the progress, maybe this.emit('end') is not work in gulp/conf errorHandler.

**Comment by Swiip** [comment]
Did some tests. Gulp ruby-sass does a bit what it wants... The emit('end') works, gulp take back control sooner but the sass compilation continue anyway.

There is an option `stopOnError` on gulp-ruby-sass which breaks the compilation but we don't have any error event. I think keeping the current configuration is better.

**Comment by abbish** [comment]
I found the issue from TeamCity that the gulp-ruby-sass was error when it build sass files, but it not stoped and the TeamCity build progress was successed

**Comment by zckrs** [comment]
Can I closed ? @abbish

**Comment by abbish** [comment]
yes thank u
