### ISSUE TITLE
bower:scss wiredep and import placement

### ISSUE THREAD

**Issue by Oreqizer** [Swiip/generator-gulp-angular#533]
Hi, I encountered problems with **wiredep** and the file structure.
Did:
> yo gulp-angular

Included: sass-libsass, no css framework. Other options are irrelevant.
> bower install susy --save
> bower install normalize.css --save

Now, the first issue is that
> gulp inject/build/serve

don't actually wiredep susy into the *vendor.scss* file. I know I can simply include it there manually, but it is still an issue. I didn't modify the gulpfile or its components in any way whatsoever.

Another thing is, why separate *index.scss* and *vendor.scss*? I had to switch vendor imports to index.scss, otherwise I was unable to work with the imported libraries like Susy. Am I missing something?

**Comment by zckrs** [comment]
:tada: Just released v0.12.0 :tada:
Your issue should be fixed. I close but if you **can retry your case with a new fresh install of generator** you are welcome. Any feedback would be appreciated (positive comments too ^_^).

**Comment by Goodmind** [comment]
I have a same error
