### ISSUE TITLE
Feature: Create a new directory for html partials that will not be injected, and instead fetched at runtime.

### ISSUE THREAD

**Issue by shawn-simon** [Swiip/generator-gulp-angular#536]
It would be great if some of the html templates could be fetched at run time. For example, my site has a lot of static content pages- FAQ, About, How to do x, etc. This will bloat the js file and makes more sense as a quick download. My current thoughts on implementing this for myself are:

1. If an HTML file matches *.page.html - don't include it in the template file. This allows you to organize pages that still might need a controller / css file in a routes or components directory.
2. Also create separate directory app/pages/ that won't include in the template file. This let's my teammates modify files and know they won't be breaking anything. I can also wire up routes to this directory specially.

I could see this adding a bit of complication for new users though... Open to suggestions. I'll be setting this up myself next week when I have more time.

**Comment by zckrs** [comment]
I'm not sure that should be a part of generator. 
The easy way : use a négative glob pattern in your gulp.src.

A recipe would be appreciate.
