### ISSUE TITLE
Issue forking generated project

### ISSUE THREAD

**Issue by qumani-designs** [Swiip/generator-gulp-angular#537]
I searched and did not see an issue so here goes....

I am wondering if I am doing something wrong when pushing a generated project to a repo and trying to pull it down on another machine. Normally, with generators I can push them up to one of my repos, pull it down on another box, run npm install and bower install, and I am good to go. So far with projects from this generator, I am unable to get the project running on another box unless I run the generator all over again and selecting the same config options. I can work around this, but I often work with contributors on projects that are not able to work around this.

I am wondering if someone could explain to me how to push a generated project to a remote in a manner that would make it easy for another person to pull it down and just run npm and bower install and be good to go.

Thanks,
J

**Comment by zckrs** [comment]
I just try your case.
```
$ mkdir testGulpAngular
$ cd testGulpAngular/
$ yo gulp-angular --default
$ echo "# furry-octo-nemesis" >> README.md
$ git init
$ git add .
$ git commit -m "first commit"
$ git remote add origin git@github.com:zckrs/furry-octo-nemesis.git
$ git push -u origin master
$ gulp serve
$ gulp test
$ gulp
$ cd ..
$ git clone git@github.com:zckrs/furry-octo-nemesis.git
$ cd furry-octo-nemesis/
$ npm install && bower install
$ gulp serve
$ gulp test
$ gulp
```

Everything works fine.

@qumani-designs can you try to fetch https://github.com/zckrs/furry-octo-nemesis ?
