### ISSUE TITLE
Provide an option to use Jade templates

### ISSUE THREAD

**Issue by lotsabackscatter** [Swiip/generator-gulp-angular#541]
Jade is a popular HTML templating solution that would be great to include as part of this generator.

**Comment by ChrisAitken** [comment]
There is already jade support. Although when you first run the yeoman generator it gives you html files but you can edit them to be jade and the app will work the same.

**Comment by lotsabackscatter** [comment]
Awesome! Cheers.

**Comment by lellex** [comment]
I converted html files to jade (and change the extension) but it doesn't seem to work.
Is there any option to change ?

**Comment by lellex** [comment]
Ahaa, I just found why it wasn't working, a stupid error !
In case of someone get the same, I used this site to translate my html to jade : http://html2jade.org/
and the result add systematically "body" and "html" on top...

**Comment by valeriosillari** [comment]
could you please attach source code you use for the new index.jade file?
got right now the same issue ... :)
