### ISSUE TITLE
Gulp serve failing on Ubuntu 14.04

### ISSUE THREAD

**Issue by navjinder** [Swiip/generator-gulp-angular#542]
Hi there I am receiving this issue when I am doing gulp serve. The code is not changed it is the default code from the site.

```
Local: http://localhost:3000/
External: http://192.168.0.104:3000/
 ---------------------------------------
UI: http://localhost:3001
UI External: http://192.168.0.104:3001
 ---------------------------------------
[BS] Serving files from: .tmp/serve
[BS] Serving files from: src

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by robertbaker** [comment]
Would be a good idea to update to 15.04 :)

This generator has outdated dependencies, I updated everything to the latest package version and everything works fine. It might fix your issue.

```
npm install -g bower-update npm-check-updates
```

then under your project root run
```
npm-check-updates -g // run npm install -g packagename for stuff outdated
npm-check-updates -u
npm update
bower-update
bower update
```
then run the gulp task that updates the web driver.

**Comment by navjinder** [comment]
Thanks @robertbaker 
You are right the dependencies need to be updated for the tool but my issue was with the browserSync not opening the browser as my files were on an external harddrive (linux). 

The way I solved this was by adding the following code to server.js in the gulp folder i.e. not opening the browser automatically.
```javascript
open:false,
```
Then going to the locahost:port manually it works flawlessly now. 

Thanks a lot fto the whole  team for creating this tool.

**Comment by Swiip** [comment]
Strange problem. Good if you find a workaround, we'll reopen this if there other people have the same issue.

**Comment by kl09** [comment]
Have the same problem..
open:false
helped me
