### ISSUE TITLE
TypeScript definitions are not installed for some packages

### ISSUE THREAD

**Issue by keichi** [Swiip/generator-gulp-angular#544]
`gulp tsd` reads `bower.json` and installs TypeScript definitions for each of the dependencies. However, it relies on the assumption that bower package name and tsd package name are the same.

This is problematic for some packages, for example Angular UI Bootstrap. Its bower package name is `angular-bootstrap`, but the tsd name is `angular-ui-bootstrap`. In this case, TypeScript definitions are not installed.

**Comment by keichi** [comment]
`bower.json`
```json
{
  "name": "foo",
  "version": "0.0.0",
  "dependencies": {
    "angular-animate": "~1.3.4",
    "angular-cookies": "~1.3.4",
    "angular-sanitize": "~1.3.4",
    "angular-resource": "~1.3.4",
    "angular-ui-router": "~0.2.13",
    "bootstrap-sass-official": "~3.3.1",
    "angular-bootstrap": "~0.13.0",
    "angular": "~1.3.4",
    "angular-tree-control": "~0.2.9",
    "angular-i18n": "~1.3.15"
  },
  "devDependencies": {
    "angular-mocks": "~1.3.4"
  },
  "resolutions": {
    "angular": "~1.3.4"
  }
}
```

`tsd.json`
```json
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": ".tmp/typings",
  "bundle": ".tmp/typings/tsd.d.ts",
  "installed": {
    "angular-ui-bootstrap/angular-ui-bootstrap.d.ts": {
      "commit": "7d2f0aa875cc3bc41f3567e3ff99d344df986155"
    }
  }
}
```

**Comment by rabr2ro** [comment]
Common, I'm struggling with this problem for two days and I though that I'm the only one having it. I thought that maybe I'm using the wrong .d.ts file. So, is there a solution for this kind of situations?

**Comment by keichi** [comment]
Since there is no way to acquire the corresponding .d.ts name from the bower module name, you must specify those not working .d.ts packages in `tsd.json`. However, there's another problem that packages in `tsd.json` are ignored by the gulp task. So I added few lines to `gulp/tsd.js` so that packages written in `tsd.json` are installed during the task.

```js
return tsdApi.readConfig()
  .then(function () {
    // begin
    tsdApi.context.config.getInstalled().forEach(function (inst) {
      var def = tsd.Def.getFrom(inst.path);
      query.addNamePattern(def.project + '/' + def.name);
    });
    // end

    return tsdApi.select(query, options);
  })
  .then ...
```

This works well for now. Maybe I should make a PR?

**Comment by rabr2ro** [comment]
Thank you for your quick answer. In the end I found a solution to the problem, too. Maybe is not so elegant as your, but it's working for me. In patched tsd.js too, and I added the following lines when the dependencies array is created, and before doing the query (at line 20-21). I'm new to this development, but I have to recognize that your patch is more elegant. Here is my patch:

var _tsdj = require(path.join(process.cwd(), tsdJson));
for (var key in _tsdj.installed) {
    dependencies.push(new tsd.Def(key).name);
}

I don't know how to make it look like your :(

**Comment by Swiip** [comment]
Nice solution, a PR could be great!

**Comment by zckrs** [comment]
@keichi PR incoming ?

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/756

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
