### ISSUE TITLE
In "dist" mode Angular throws an errors "Failed to instantiate module due it is not available!" But I can see it in vendor.js file.

### ISSUE THREAD

**Issue by AleksMeshkov** [Swiip/generator-gulp-angular#547]
Hello!

This issue only occurs in the "dist" mode. Please have a look what I've got when running my app.

![screenshot 2015-05-19 12 35 47](https://cloud.githubusercontent.com/assets/1904894/7699985/43219070-fe24-11e4-8e4d-f00680c78c1f.png)

At first I thought that  ```a0-angular-storage``` module wasn't compiled and included into the vendor.js file.
But it's there!

![screenshot 2015-05-19 12 43 48](https://cloud.githubusercontent.com/assets/1904894/7700066/c23ab594-fe24-11e4-83ac-89a15e4d4379.png)

Moreover files from the ```assets``` folder (ckeditor.js, bootflat.css) are not found it the dist mode (the first screenshot).

Can you please help me to deal with this problems? 

Thanks!

**Comment by AleksMeshkov** [comment]
I'm staring to suppose that's not the generator-gulp-angular issue. When I remove ```a0-angular-storage``` and ```angular-jwt``` dependencies (from angular.module) it becomes ok.

**Comment by robertbaker** [comment]
It is a generator issue. For some reason the order of files on serve (which works) is not the same as the order they are inserted in the app.js on build (which doesn't)

**Comment by zckrs** [comment]
I think this issue is fixed on master branch
@AleksMeshkov  can you paste your `.yo-rc.json`, `bower.json` ?

**Comment by AleksMeshkov** [comment]
@zckrs no problem! here they are:

https://gist.github.com/AleksMeshkov/12808b3016f274251400
https://gist.github.com/AleksMeshkov/dd5438a4c574b2a7ecef

**Comment by zckrs** [comment]
1) You should save your bowerDep for wiredep https://github.com/taptapship/wiredep#how-it-works 
2) If that not solved, can you try with master version of generator? Otherwise you should wait next release

**Comment by AleksMeshkov** [comment]
@zckrs thanks for the help!

**Comment by zckrs** [comment]
:tada: Just released v0.12.0 :tada:

**Comment by AleksMeshkov** [comment]
@zckrs nice! Btw how shall I properly upgrade my current project?

**Comment by zckrs** [comment]
there is no upgrade provide by yeoman.
You should update the generator by `npm -g install generator-gulp-angular` and rerun `yo gulp-angular` in your current project.

But be careful. Before upgrade I suggest you to create a branch in your project.

This post should help you http://stackoverflow.com/questions/18480316/how-to-upgrade-existing-project-scaffolded-with-yeoman

**Comment by Swiip** [comment]
This link to stackoverflow has to be somwhere in our docs once and for all :)
