### ISSUE TITLE
Why do the build files have random chars after vendor.css etc?

### ISSUE THREAD

**Issue by Vvaltz** [Swiip/generator-gulp-angular#549]
Why would I want this? I'd like them to have the same name always, can I do that? Is it wrong practice or something?

**Comment by zckrs** [comment]
Remove `.pipe($.rev())` in your gulp/build.js

https://www.npmjs.com/package/gulp-rev

**Comment by Vvaltz** [comment]
Oh, it's for revisioning? Okay, thanks alot
