### ISSUE TITLE
Accessing 'bower_components' in .scss files without having to path ../../bower_components/

### ISSUE THREAD

**Issue by milkshoes** [Swiip/generator-gulp-angular#550]
I have a custom bower dependency folder and I want to reference this folder from within my sass files. Now I have this working with the upwards folder pathing / traversal. But it would seem that there's a more efficient way in which I could add a custom paths folder that allows me to reference my imports without all the folder traversals.

So what i currently have in app.scss:
@import "../../bower_components/my-styles/my_styles_main";

What i want to do is:
@import "my_styles_main";

I tried adding custom load paths by doing the below in gulp/styles.js:

module.exports = function(options) {
  gulp.task('styles', function () {
    var sassOptions = {
      includePaths: ['../../bower_components/my-styles/'],
      style: 'expanded'
    };

I've had no luck yet but thought I'd reach out here and see if anyone else might be able to help with this issue.

Thanks so much and as always I'm extremely grateful for your time and patience!

- frankie

**Comment by mpgn** [comment]
It's not `includePaths` but `loadPath` with grunt-contrib-sass

```
module.exports = function(options) {
gulp.task('styles', function () {
var sassOptions = {
      loadPath: [ options.src + '/../bower_components/my-styles/'],
      style: 'expanded'
};
```

**Comment by Swiip** [comment]
Interesting, could be new recipe, thanks.
