### ISSUE TITLE
How to run project

### ISSUE THREAD

**Issue by rosieks** [Swiip/generator-gulp-angular#552]
This generator is pretty nice, but what should I do after running it. How to run application without node? I would like to host that site on my local IIS, but it doesn't work if run it from src/index.html and if I run it from dist HTML is not updated by watch task? How it works?

**Comment by notrab** [comment]
Hi

You'll need to run `gulp serve` to run the application locally. This will open your browser using BrowserSync. This will generally watch the files in your application and automatically refresh when a change is detected.

You may need to modify the watch gulpfile to reflect any additional file types not set out by default.

If you wish to run locally what it will run like compiled, you will want to run `gulp serve:dist`.

When you're happy to upload this to the world wide web and let it free, run `gulp` and then copy your `/dist` folder to an apache, python or node server.

**Comment by zckrs** [comment]
Nice answer @notrab

**Comment by rosieks** [comment]
And is there any way to run that without any server and any without minification/bundling?

**Comment by zckrs** [comment]
You can tweak build task to disable  minfication and concatenation. And open dist/Index.html with your browser
