### ISSUE TITLE
Production Deployment Option

### ISSUE THREAD

**Issue by Lswith** [Swiip/generator-gulp-angular#557]
I would love to be able to build and run the app on a production server rather than having to install all of the development dependencies (including browserSync which can't be installed at the moment). Support for putting gulp and its necessary tasks into actual dependencies and making a task to build and run for production would be very useful.

**Comment by arcdev1** [comment]
I think most people would consider that an anti-pattern. Ideally, you should never build on a production server; builds should happen on a build server and then be pushed automatically to your prod server. This keeps the prod server free of any dev tools, dependencies and raw source code.

**Comment by Lswith** [comment]
Interesting. Heroku and Azure to name a few, both allow you to push your code and have it build and deployed in production. How would you tackle something for these services?

**Comment by Swiip** [comment]
We're not supporting deployment issues. The generator give you the dist folder, you serve it as you want. It's easy to make a script pushing only the dist folder. If you really want a server to serve the static files, a server.js with Express is 5 lines long.

**Comment by raphox** [comment]
Hi, Im using RSYNC+SCP to deploy in my development enviroment.

```sh
rsync -avz -e 'ssh' ./ui/www/ raphaelaraujo@example.com:/home/raphaelaraujo/api.example.com/public
```

Ref: http://askubuntu.com/a/446726
