### ISSUE TITLE
Why generator didn't use IIFE pattern?

### ISSUE THREAD

**Issue by lokeshjain2008** [Swiip/generator-gulp-angular#558]
Thanks for this awesome generator. It does more than my need.
I see the generator generates files that does not use IIFE pattern.
Is there any problem to generate that?

**Comment by lokeshjain2008** [comment]
:+1:

**Comment by zckrs** [comment]
:tada: Just released v0.12.0 :tada:
Your issue should be fixed. I close but if you can retry your case with a new fresh install of generator you are welcome. Any feedback would be appreciated (positive comments too ^_^).
