### ISSUE TITLE
How to split the vendor js files inside the dist/ folder?

### ISSUE THREAD

**Issue by damdoum** [Swiip/generator-gulp-angular#566]
Hello, i'm trying to understand if there is a way to split the js files inside ' dist/ ' folder. 
(generated when: gulp build or gulp serve:dist)

At least only the vendor-*.js file because is becoming to huge and i have some restriction on the server side.

I found in gulp github repository something who may help: [here]
(https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-task-steps-per-folder.md)

but i haven't find a way to apply this example with the default build.js or maybe it's not the file where i should do that?
Any help would be very nice, thanks

**Comment by Swiip** [comment]
Hello, sorry for the late answer. You can tweak your build to achieve that. The target files are defined by the comments in the `index.html`. You'll see `index.js` `vendor.js` in those comments. You can add other comments to split the bundles, the only limit is that wiredep can only inject scripts in one place so you'll have to write script tags yourself and exclude them from wiredep.

**Comment by damdoum** [comment]
Hi thank you for those usefull informations. I understand better now. Any chance to have a trick from you to only slpit the vendor.js file in two or more files?

**Comment by Swiip** [comment]
I don't think we'll ship that in the generator, your need is quite rare to be honest. In addition, I don't see how the vendor file could be automatically splitted...

**Comment by damdoum** [comment]
I understand and agree the fact that it can be really rare anyway thanks again for your answer and this awesome generator !

**Comment by Swiip** [comment]
Thanks ;)
