### ISSUE TITLE
Support AngularJS 1.4.x

### ISSUE THREAD

**Issue by skrenek** [Swiip/generator-gulp-angular#573]
1.4.0 is released now.  It would be excellent to have it added to the list of supported options in the generator.

**Comment by skrenek** [comment]
Just looked at the HEAD and saw that 1.4.0-rc is in the prompts, so thinking it may just require a tweak and a release?

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/pull/561

**Comment by skrenek** [comment]
Sorry about that.  Weird that I can't get 561 to show up anywhere in an issue search, but can browse to your link.

**Comment by zckrs** [comment]
No problem
