### ISSUE TITLE
How does gulp script choose right library js files to import, for both src and dist

### ISSUE THREAD

**Issue by Awakening-j** [Swiip/generator-gulp-angular#576]
As there are lots of js files in some bower_components, and different library have different folder structure, so how does our gulp script picked up the right js files for both src and dist.

If we look into bower_components, we will see some libraries may define folder name 'dist' or 'release', and some may include pieces of src-js files.

So how can I make sure the vendor.js is correct if I add some other library?

**Comment by zckrs** [comment]
`wiredep` do the work https://github.com/taptapship/wiredep

Bowers dep should present in your dependecie's bower.json. And the bower.json of dep/lib should have a main pprt

**Comment by Awakening-j** [comment]
@zckrs So the `wiredep` plugin to some manual things to collect the correct javascripts? I don't think without a standard bower folder structure, program can pick up all the correct files.

**Comment by Swiip** [comment]
Bower install each lib in its `bower_components`. After that every lib has its own `bower.json` which define which files to include and it could be one `js` file, severals, `css`, `scss`... This feature is actually how wiredep can knows and something that people using npm for frontend can't have.

**Comment by Awakening-j** [comment]
Thanks very much

**Comment by idanb11** [comment]
Hi @Swiip , Great generator, Thanks.

One question about your last comment concerning how wiredep define which files to include:
If I use a library like this one- https://github.com/splunk/splunk-sdk-javascript (which doesn't have any bower.json file) how can I add it manually to the Gulp building process?

Idanb11.

**Comment by zckrs** [comment]
Do you try https://github.com/taptapship/wiredep/blob/master/readme.md#bower-overrides ?

**Comment by idanb11** [comment]
Thanks
