### ISSUE TITLE
How can use theme ?

### ISSUE THREAD

**Issue by nhduc296** [Swiip/generator-gulp-angular#577]
Hi all,

I want to exclude theme folder and use angular to load theme css file manually.

e.g.

<link ng-href={{getTheme()}}></link>

I know how to exclude theme folder but i don't know how to get theme css file reference in serve mode and dist mode.

**Comment by Swiip** [comment]
What do you exactly mean by including theme. You mean adding a css theme from angular material?

If it's that, you can include your own styles in the index.html as explained here: #413.
