### ISSUE TITLE
Not include all needed js in index.html even file exists in bower_components

### ISSUE THREAD

**Issue by Awakening-j** [Swiip/generator-gulp-angular#578]
I'm using `amCharts-Angular`, and run `bower install amcharts-angular --save` to added in bower_components, but when I build gulp, I find that not all needed js are loaded, according to `amcharts-angular' document, there need three files, 'amcharts', 'serial', 'amChartsDirective', but I only find two in browser source, and missing 'serial' js import in index.html  

so how can i add it ?

**Comment by zckrs** [comment]
https://github.com/arturgspb/bower-amcharts/blob/master/bower.json#L4 
bower-amcharts doesn't include serial.js

**Comment by Swiip** [comment]
Wiredep only inject what is listed in the bower.json of the project. What you need to do to add other files yourself is described here: #413

**Comment by Awakening-j** [comment]
That's so nice of you both

**Comment by zckrs** [comment]
:tada: Just released v0.12.0 :tada:

**Comment by Awakening-j** [comment]
@zckrs sounds great!

**Comment by Awakening-j** [comment]
@zckrs I've written a gulp js for module generator with my weak gulp knowledge, so can you refer to it and put a generator plugin in `generator-gulp-angular/gulp/` ?  
https://github.com/Awakening-j/gulp-angular-module-generator
