### ISSUE TITLE
How to set default browser to chrome in gulp serve

### ISSUE THREAD

**Issue by aladine** [Swiip/generator-gulp-angular#58]
I want to change the default browser as Chrome instead of Safari. How I can change it is gulp/server.js:

function browserSyncInit(baseDir, files, browser) {
  browser = browser === undefined ? 'default' : browser;

  browserSync.instance = browserSync.init(files, {
    startPath: '/index.html',
    server: {
      baseDir: baseDir,
      middleware: proxyMiddleware
    },
    browser: browser
  });

}

**Comment by vitr** [comment]
in my case (win7 x64) it was just 'chrome' not 'google chrome'

**Comment by ntimmerman** [comment]
I don't have a gulp/server.js file. I used Yeoman to generate a SharePoint Web Part project.
