### ISSUE TITLE
reving images

### ISSUE THREAD

**Issue by amirtuval** [Swiip/generator-gulp-angular#582]
Hi

I am fairly new to gulp, so I might have missed something obvious.

I've been trying gulp-angular and really impressed with it - many useful features, and very fast.

One thing I was missing was reving (hashing) of images. Other projects, such as generator-angular have that.

I was able to hack together something that seems to work, at least in the simple case, but I would love to get your feedback on it.

I basically created a new project (using "yo gulp-angular") with the advanced option, and selected to use imagemin.
From there, I was able to add hashing to images, save the manifest file, and then use the manifest file in the 'html' task to replace all image occurences.

Here's the new build.js file. For it to work, you need to upgrade gulp-rev-replace to 0.4.1.

'use strict';

var gulp = require('gulp');

var $ = require('gulp-load-plugins')({
  pattern: ['gulp-*', 'main-bower-files', 'uglify-save-license', 'del']
});

module.exports = function(options) {
  gulp.task('partials', function () {
    return gulp.src([
      options.src + '/app/**/*.html',
      options.tmp + '/serve/app/**/*.html'
    ])
      .pipe($.minifyHtml({
        empty: true,
        spare: true,
        quotes: true
      }))
      .pipe($.angularTemplatecache('templateCacheHtml.js', {
        module: 'gulpTest',
        root: 'app'
      }))
      .pipe(gulp.dest(options.tmp + '/partials/'));
  });

  gulp.task('html', ['inject', 'partials', 'images'], function () {
    var partialsInjectFile = gulp.src(options.tmp + '/partials/templateCacheHtml.js', { read: false });
    var partialsInjectOptions = {
      starttag: '',
      ignorePath: options.tmp + '/partials',
      addRootSlash: false
    };

    var htmlFilter = $.filter('*.html');
    var jsFilter = $.filter('**/*.js');
    var cssFilter = $.filter('**/*.css');
    var assets;

    var manifest = gulp.src(options.tmp + "/images-rev-manifest.json");

    return gulp.src(options.tmp + '/serve/*.html')
      .pipe($.inject(partialsInjectFile, partialsInjectOptions))
      .pipe(assets = $.useref.assets())
      .pipe($.revReplace({manifest: manifest}))
      .pipe($.rev())
      .pipe(jsFilter)
      .pipe($.ngAnnotate())
      .pipe($.uglify({ preserveComments: $.uglifySaveLicense })).on('error', options.errorHandler('Uglify'))
      .pipe(jsFilter.restore())
      .pipe(cssFilter)
      .pipe($.csso())
      .pipe(cssFilter.restore())
      .pipe(assets.restore())
      .pipe($.useref())
      .pipe($.revReplace())
      .pipe(htmlFilter)
      .pipe($.minifyHtml({
        empty: true,
        spare: true,
        quotes: true,
        conditionals: true
      }))
      .pipe(htmlFilter.restore())
      .pipe(gulp.dest(options.dist + '/'))
      .pipe($.size({ title: options.dist + '/', showFiles: true }));
  });
  gulp.task('images', function () {
    return gulp.src(options.src + '/assets/images/**/*')
      .pipe($.imagemin({
        optimizationLevel: 3,
        progressive: true,
        interlaced: true
      }))
      .pipe($.rev())
      .pipe(gulp.dest(options.dist + '/assets/images/'))
      .pipe($.rev.manifest('images-rev-manifest.json'))
      .pipe(gulp.dest(options.tmp));

  });

  // Only applies for fonts from bower dependencies
  // Custom fonts are handled by the "other" task
  gulp.task('fonts', function () {
    return gulp.src($.mainBowerFiles())
      .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))
      .pipe($.flatten())
      .pipe(gulp.dest(options.dist + '/fonts/'));
  });

  gulp.task('other', function () {
    return gulp.src([
      options.src + '/**/*',
      '!' + options.src + '/**/*.{html,css,js,scss,jpg,png,gif,svg}'
    ])
      .pipe(gulp.dest(options.dist + '/'));
  });

  gulp.task('clean', function (done) {
    $.del([options.dist + '/', options.tmp + '/'], done);
  });

  gulp.task('build', ['html', 'fonts', 'other']);
};

**Comment by zckrs** [comment]
This issue is fixed in last version v0.12.0.
Please next time embed your code in gist or code block
