### ISSUE TITLE
Varsion 0.11.0 - I can't choose Angular 1.4.0

### ISSUE THREAD

**Issue by Olgagr** [Swiip/generator-gulp-angular#583]
I've updated generator to the newest version (0.11.0). When I generate a new project, I don't see option to choose Angular 1.4.0 version. I only see:

```
? Which version of Angular do you want? (Use arrow keys)
❯ 1.3.x (latest) 
  1.2.x (legacy 2013-11-08) 
```

**Comment by zckrs** [comment]
We don't have released a new version.
You can:
* wait for next release
* contribute for a fastest release
* Clone the master branch and use `npm link`

**Comment by mackelito** [comment]
Just a question.. (I'm not that familiar with yeoman)..
If I download master where should I extract the files? and do I then run npm link from the same folder?

**Comment by Swiip** [comment]
extract the files anywere and use npm link in the folder. It will make a sym link in the right location pointing to your current directory
