### ISSUE TITLE
Just curiosity

### ISSUE THREAD

**Issue by equero** [Swiip/generator-gulp-angular#587]
Why you call 'index.js' to the router? ¿

**Comment by zckrs** [comment]
? Can you precise ? Maybe  https://gitter.im/Swiip/generator-gulp-angular is right place for this type of question.

**Comment by equero** [comment]
Normally, the router file, always is called 'router.js' but you call him index.js.... WHY?

**Comment by zckrs** [comment]
In v0.11.0 the `index.js` should contains module def, `.config` and `.run` statement.
Router configuration is a `.config`.

In master version we split `index.js` in multiples files

**Comment by equero** [comment]
Ok thanks for helping me guys, i'm using your generator to my start up
