### ISSUE TITLE
Where to add stripDebug() for app.js in dist folder

### ISSUE THREAD

**Issue by Awakening-j** [Swiip/generator-gulp-angular#588]
I want to remove all `console.log` in dist app.js, I've install the `gulp-strip-debug`, But could anyone tell me where to add it ?

**Comment by Swiip** [comment]
The optimization process is in the html task in gulp/build.js. You should add your plugin in the big pipe of the html task inside the jsFilter `.pipe(jsFilter)` -> `.pipe(jsFilter.restore())`.

**Comment by Awakening-j** [comment]
@Swiip Thanks!
