### ISSUE TITLE
tsd:install runs multiple times

### ISSUE THREAD

**Issue by robertbaker** [Swiip/generator-gulp-angular#600]
Because tsd:install is attached to the scripts tasks, it is ran multiple times during serve:dist and serve and again on any script changes.

I don't see the point of running it during script changes since bower packages are added when you aren't running a task.

**Comment by Swiip** [comment]
Sorry for the delay. I think you're right, we should be able to put it at the inject time and not script...

**Comment by Swiip** [comment]
Nop, just looked. If we put the tsd:install in dependency of the inject task, it's executed in paralel of scripts and it fails...

In fact, tsd:install runs too many times but not doing this breaks the order.

**Comment by robertbaker** [comment]
I think removing tsd:install from the build process all together would be better. You have to manually run tsd if you don't have the definitions or you need to update it, but the defs don't change that often.

Or maybe just run before serve or build.

**Comment by Swiip** [comment]
Or why not at a npm postinstall? That are interesting leads...

**Comment by robertbaker** [comment]
Bower/NPM post install works for me.

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
