### ISSUE TITLE
How can I deploy into heroku?

### ISSUE THREAD

**Issue by j4ml3t** [Swiip/generator-gulp-angular#602]
I have tried different ways, such creating an Express server:
    var express  = require('express');
    var app      = express();                     
    var morgan = require('morgan');             
    app.use(express.static(__dirname + '/dist'));                
    app.use(morgan('dev'));                                         
    app.listen(8080);
    console.log("App listening on port 8080");

but I get a 'Cannot GET /' error from server. The server starts but nothing is deployed.
And I don't know how to make gulp serve the app on heroku.
Any idea?

**Comment by Grandiz** [comment]
i am not sure you realy need heroku for this purpose. just run gulp build, it will collect and compress all js, css to /dist directory, and that's all. you can deploy to s3 or other hosting

**Comment by Swiip** [comment]
This is out of scope. The generator create a frontend project with no built-in server. The server feature in the generator is about development process only.

If you want to put a project generated by the generator on Heroku, you have to make your website, launch `gulp` to optimize and take away the dist directory.

You have to bring your own server, it could be an Express wich point on that directory if you want. But we can't make support of your backend or your deployment process.
