### ISSUE TITLE
Support JSPM/System.js

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#604]
Since we have ES6 support and browserify etc is already on the menu. I would like to suggest JSPM and system.js

http://jspm.io/
https://github.com/systemjs/systemjs

A simple angular jspm example
https://github.com/jackfranklin/jspm-es6-angular-example

**Comment by Swiip** [comment]
I digged into JSPM recently. We think about an option like "script injection": None, Webpack, Browserify, JSPM. But not before the 1.0

**Comment by wgorder** [comment]
@Swiip 

Thanks for looking at it.  When I use this generator to generate an ES6 project the first thing I do is rip out Webpack (which appears to already be implemented) and replace it with this.   If you are interested later let me know I can put together a PR.

**Comment by Swiip** [comment]
You replace Webpack by JSPM? Arf, I really don't get JSPM. Why use a aweful config.js when you can have CommonJS all the way?
But to be honest, I often remove Bower for NPM these days, it completes the "CommonJS all the way" statement. But removing Bower is to a step to big right now.

**Comment by wgorder** [comment]
Yeah I remove bower too. JSPM handles that, and supports git, bower, npm endpoints etc. I have never had the need to touch config.js, it seems to handle whatever it needs transparently.

**Comment by Swiip** [comment]
Yep, but comparing package.json and a JSPM config.js always makes me sad even if "it's always transparent". But who knows, it's my tastes, we'll see what tech stays...

Anyway, the generator should not make the choice and offer both.

**Comment by wgorder** [comment]
@Swiip sorry I am late to responding.  Yes people should be able to make their own choices.

That said that transparent config that makes you sad does a pretty good job at handling circular and transitive dependencies that the others struggle with.

As for the future I think we know where its going (es6).  I prefer the idea of a polyfil that I can remove later.

Here is an additional read.
https://gist.github.com/OliverJAsh/bcc676e381a06dbb3be0

**Comment by wgorder** [comment]
Oh and if you get bored and want to mess around with it further,  I used this as a starting point.
https://github.com/angular-class/NG6-starter/tree/jspm

**Comment by anishbenji** [comment]
It might be worth looking at StealJS as well, which is based off of SystemJS.
http://stealjs.com/docs/StealJS.why.html
