### ISSUE TITLE
jade to html

### ISSUE THREAD

**Issue by jolugama** [Swiip/generator-gulp-angular#605]
when i create a file jade it's not create a file html.

**Comment by hippiemine** [comment]
you should use [gulp-jade](http://localhost:8180/?subDomain=jialei)

**Comment by valeriosillari** [comment]
got same problem here, I don't get it.

for what I see reading the issues, I not need gulp-jade, it should be already supported.

when i installed the app i choose the option for jade language.
yeoman create a jade task automatically into the gulp file for markup.

so at this point I am assuming just to change the extensions of a .html file into .jade and write code in jade lang (in my unique jade file i just set one heading with hello world for testing)

but jade is not compiled.

so: change file extension e code of the file is or isn't enough?

I know it could be a dummy question, but I am newbie with all the yeoman node gulp stuff ... :)

**Comment by Swiip** [comment]
Should work out of the box. gulp-consolidate with jade is used in place of gulp-jade. We have a limitation thought, watcher misses new files in a folder, try stoping serve and relaunch it.

**Comment by valeriosillari** [comment]
started a new testing project, works just changing file extension and restarting server.
it seems I made a mess on my project ... now i will check my project.
thanks :)
