### ISSUE TITLE
Multiple rebuilds for a single change

### ISSUE THREAD

**Issue by perchi** [Swiip/generator-gulp-angular#607]
Hi all,

It seems that it is something wrong with watch/serve functionality, because when i made a change in a only one JS file the applications starts rebuilding and rebuilding ...

For example when I run the task "gulp watch" and added just a one comment in js file, i got 6 rebuilds:
[23:33:02] all files 7.87 kB
[23:33:02] Finished 'scripts' after 242 ms
[23:33:02] Starting 'scripts'...
[23:33:03] all files 7.87 kB
[23:33:03] Finished 'scripts' after 232 ms
[23:33:03] Starting 'scripts'...
[23:33:03] all files 7.87 kB
[23:33:03] Finished 'scripts' after 219 ms
[23:33:03] Starting 'scripts'...
[23:33:03] all files 7.87 kB
[23:33:03] Finished 'scripts' after 197 ms
[23:33:03] Starting 'scripts'...
[23:33:04] all files 7.87 kB
[23:33:04] Finished 'scripts' after 543 ms
[23:33:04] Starting 'scripts'...
[23:33:04] all files 7.87 kB
[23:33:04] Finished 'scripts' after 188 ms

For example when I run the task "gulp serve" and i added a one comment, then i got 2-3 rebuilds:
[23:39:44] Starting 'scripts'...
[BS] 11 files changed (index.config.js, index.constants.js, index.module.js, ind
ex.route.js, index.run.js, main.controller.js, main.controller.spec.js, githubCo
ntributor.service.js, malarkey.directive.js, navbar.directive.js, webDevTec.serv
ice.js)
[23:39:44] all files 7.86 kB
[23:39:44] Finished 'scripts' after 480 ms
[23:39:44] Starting 'scripts'...
[BS] 11 files changed (index.config.js, index.constants.js, index.module.js, ind
ex.route.js, index.run.js, main.controller.js, main.controller.spec.js, githubCo
ntributor.service.js, malarkey.directive.js, navbar.directive.js, webDevTec.serv
ice.js)
[23:39:45] all files 7.86 kB
[23:39:45] Finished 'scripts' after 373 ms

Does anyone have a similar problem? Tnx! ;)

**Comment by zckrs** [comment]
What version node ? generator? Can you paste .yo-rc.json ?

**Comment by perchi** [comment]
$ node -v
v0.12.4

$ npm -v
2.10.1

OS: Windows 7

{
  "generator-gulp-angular": {
    "version": "0.11.0",
    "props": {
      "angularVersion": "~1.4.0",
      "angularModules": [
        {
          "key": "animate",
          "module": "ngAnimate"
        },
        {
          "key": "touch",
          "module": "ngTouch"
        },
        {
          "key": "sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "key": "jquery2"
      },
      "resource": {
        "key": "none",
        "module": null
      },
      "router": {
        "key": "ui-router",
        "module": "ui.router"
      },
      "ui": {
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "key": "ui-bootstrap",
        "module": "ui.bootstrap"
      },
      "cssPreprocessor": {
        "key": "less",
        "extension": "less"
      },
      "jsPreprocessor": {
        "key": "none",
        "extension": "js",
        "srcExtension": "js"
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html"
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      }
    }
  }
}

**Comment by perchi** [comment]
I figoured out that the problem is in "/gulp/scripts.js" file:

```javascript
    .pipe(gulp.dest(path.join(conf.paths.src, '/app/')));
```

There should be "tmp" folder instead of "src":

```javascript
    .pipe(gulp.dest(path.join(conf.paths.tmp, '/app/')));
```
