### ISSUE TITLE
Run bower install with npm "postinstall" phase

### ISSUE THREAD

**Issue by mjeanroy** [Swiip/generator-gulp-angular#608]
In my projects, I like to bind npm "postinstall" phase with bower: I don't have to manually run bower after an npm install (and it makes my life easier ;) ).
Would you like a PR for this or do you have any rejection?

**Comment by zckrs** [comment]
No :-/
Bower is already launch after scaffolding.
Postinstall should be used compilation or install relative to node_modules.

You can use `npm install && bower install` or `npm i && boxer i` or a bash alias

**Comment by mjeanroy** [comment]
Ok, no worries, it was just a simple suggestion, I already have tons of aliases, one more, one less... (and I probably already have this one).

The biggest advantages of this solution is that you don't need to have bower globally installed (and when you can't install what you want, except npm, this is great).

Anyway, I close this issue, and many thanks for your job ;)
