### ISSUE TITLE
vendor-:hash.js not being generated

### ISSUE THREAD

**Issue by rosscdh** [Swiip/generator-gulp-angular#610]
Hey there, thanks for the great build system.

Im running 

```
  "generator-gulp-angular": {
    "version": "0.11.0",
```

and for some very weird reason when I build the dist does some weird things

1. app-f1bcf660.js is generated but vendors-f1bcf660.js is NOT genereated
2. the build html outputs vendors.js and the contents of vendors.js is the index.html contents

Any thoughts/help would be appreciated here.

**Comment by zckrs** [comment]
How do you install the generator ? via NPM ?

**Comment by rosscdh** [comment]
ok seems that I did not upgrade the index.html to the new 0.11.0 layout (was built using an older version)

copied the new index.html and all seems to work well again.

was exhibiting by including index.html as the vendor.css and vendor.js.. causing angular to be included multiple times.

Fairly straight forward; but would really help to have something about that in the version release notes?

Thanks for the great generator. Might I suggest including ng-constant by default? as this helps a great deal with dealing with multiple environments.
