### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jbonigomes** [Swiip/generator-gulp-angular#613]
Hi Everyone, great generator, I was wondering if anyone has any examples to share of apps built using this generator. I am most interested in examples to follow in terms of structure and so on, anything would help. I stumbled upon @vredchenko repo and it looks really neat:

https://github.com/vredchenko/symphony-candidate-interview-reporter

Thanks

**Comment by zckrs** [comment]
We just release a new version. Maybe you should check

**Comment by jbonigomes** [comment]
Thanks @zckrs I will be sure to check it, again, some sample apps would still be really beneficial

**Comment by jbonigomes** [comment]
In fact, the new generator is awesome, thanks @zckrs 
I'm closing the issue

**Comment by jolugama** [comment]
Thank you for your example. It has been a great help.

**Comment by zckrs** [comment]
You are welcome

**Comment by fuchao2012** [comment]
@zckrs great generator！Just like @jbonigomes said, list some apps use this generator will be great welcome.
