### ISSUE TITLE
gulp test:auto not working

### ISSUE THREAD

**Issue by jolugama** [Swiip/generator-gulp-angular#615]
gulp-angular/gulp/unit-tests.js:39
          .concat(_.pluck(files, 'path'))
          ^
TypeError: Cannot read property 'concat' of undefined

Does anyone happens the same?

**Comment by zckrs** [comment]
Can you paste your .yo-rc.json ???

**Comment by zckrs** [comment]
Today I release v0.12.0 and I have no error

**Comment by jolugama** [comment]
This is my .yo-rc.json. 

{
  "generator-gulp-angular": {
    "version": "0.11.0",
    "props": {
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "key": "animate",
          "module": "ngAnimate"
        },
        {
          "key": "cookies",
          "module": "ngCookies"
        },
        {
          "key": "touch",
          "module": "ngTouch"
        },
        {
          "key": "sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "key": "jquery2"
      },
      "resource": {
        "key": "angular-resource",
        "module": "ngResource"
      },
      "router": {
        "key": "ui-router",
        "module": "ui.router"
      },
      "ui": {
        "key": "angular-material",
        "module": "ngMaterial"
      },
      "cssPreprocessor": {
        "key": "node-sass",
        "extension": "scss"
      },
      "jsPreprocessor": {
        "key": "babel",
        "extension": "js",
        "srcExtension": "es6"
      },
      "htmlPreprocessor": {
        "key": "jade",
        "extension": "jade"
      },
      "bootstrapComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      }
    }
  }
}

**Comment by zckrs** [comment]
Please update the generator.

**Comment by zckrs** [comment]
`npm install -g generator-gulp-angular`

**Comment by jolugama** [comment]
ooh, the vs 0.12 is very different from 0.11. Angular 1.4, the test are in a separate folder. Now I like more.

All right !.  thanks for all

**Comment by zckrs** [comment]
No problem =]

**Comment by jolugama** [comment]
Hi,
I tried the vs 0.12, and I am amazed. It's great test: auto. Everything
works ok. This is the best yeoman generator. Very complete. Thanks for
everything, really.

2015-06-19 2:24 GMT+02:00 Mehdy Dara <notifications@github.com>:
