### ISSUE TITLE
Easy way to stop build dist?

### ISSUE THREAD

**Issue by Awakening-j** [Swiip/generator-gulp-angular#616]
After I added several bower dependencies, my project build very slowly, Anyone knows why?  
I guess if stop build dist, the process will be faster .  
So if it really is, how to stop build dist easily, like a config  
**BTW**, the vender.js is so big, can we divide it into several files, each like 300kb?
![screen shot 2015-06-19 at 10 26 20 am](https://cloud.githubusercontent.com/assets/8085088/8246237/acfd43f2-166d-11e5-818f-418d4a96bbe3.png)

**Comment by zckrs** [comment]
Paste your `.yo-rc.json` in code block or gist

**Comment by Awakening-j** [comment]
@zckrs hi, I don't have this `.yo-rc.json` file, is it in the latest release?

**Comment by Awakening-j** [comment]
@zckrs Hi zckrs, Is there any way to update the gulp project instead of re-generate it ?

**Comment by Awakening-j** [comment]
Sorry, I don't understand `Paste your .yo-rc.json in code block or gist`, I try to comment "dist":dist in "paths", couldn't stop build dist

**Comment by zckrs** [comment]
For support please go to https://gitter.im/Swiip/generator-gulp-angular

Issue tracker is for bug.
