### ISSUE TITLE
The proxy middleware config in gulp/server is wrong

### ISSUE THREAD

**Issue by lordfriend** [Swiip/generator-gulp-angular#620]
When I using the gulp/proxy file to make proxy for some api calls. I modified the last part to following
```javascript
module.exports = function(){
    return [proxyMiddleware];
}
```
I know this is not the suggested format in the comment, but the suggested format `module.exports = [proxyMiddleware]` will break because the following block of the gulpfile.js
```javascript

wrench.readdirSyncRecursive('./gulp').filter(function(file) {
  return (/\.(js|coffee)$/i).test(file);
}).map(function(file) {
  require('./gulp/' + file)(options);
});
```
This code snippet require all files in 'gulp' folder as an function and pass the option in.

So the only way to make the proxy file work is keep the original format as I mentioned above.

But this will not work! So the problem is in the gulp/server file. In **gulp/server** file the middleware is directly used as the `server.middleware` property. this is ok when you use `module.exports= [proxyMiddleware]`. But as we see you can't using that format.

So we need to change the **gulp/server** file. Simply add a function call to middleware require statement.

```javascript
var middleware = require('./proxy')();
```

Then the proxy middleware will work as expected

**Comment by zckrs** [comment]
Can you paste your .yo-rc.json ?

**Comment by Swiip** [comment]
You're right about the problem you described, but the problem doesn't exists any more in the new 0.12 version.

We have simply removed the `proxy.js` for a packaged lib which provide the feature.
