### ISSUE TITLE
sub project

### ISSUE THREAD

**Issue by Grandiz** [Swiip/generator-gulp-angular#623]
Hi. I want to add admin panel to my existring web site generated by this plugin. I want to separate admin.html which will include different bower component and angular modules from main website. Can i do it?

**Comment by Swiip** [comment]
You can have multiple html entry points in the app folder if you copy `index.html` all should work. But if you really want everything separated including the bower deps, I thinks it's not possible, you should better start a different project in a diferent directory.

**Comment by jmls** [comment]
I was just looking at this, and was wondering how others have dealt with it. I have a project (A) , using the generator. Potentially, this project can either be a standalone, or integrated into other projects created using generator-gulp-angular (gga). 

However, my brain is refusing to engage, and I am struggling with the concepts. Is this the right strategy ?

#1 naming of modules etc.  ensure all factories / services etc have unique names for the app (e.g. mainController => fooMainController
#2 create a bower.json file that lists all the important front-end services / file that should be included in the secondary project
#3  add a level to the app folder - app/foo where foo contains components, main, etc folders - this way the templatecache would be caching app/foo/main.html 

the problem that I see with the above is that I would have to go through all the code  (index.route.js for example) and modify accordingly. 

a) is there an option to specify the location of the "app" when generating the project
b) what does everybody else do in this scenario ?

many thanks

**Comment by intellix** [comment]
+1 for starting a new project when you need another entry. Not saying you will, but I always forget that I've updated a dependency for the first entry and broken the second one. Done this many times.

I'm sharing some services, directives etc between them so have split into something like:
  - project-common
  - project-theme
  - project-frontend - requires common + theme
  - project-admin - requires common + theme

**Comment by zckrs** [comment]
Two solutions IMO:
* generate a new external project
* use module in AngularJS

https://github.com/Swiip/generator-gulp-angular/issues/737
