### ISSUE TITLE
ui-bootstrap modal backdrop issue

### ISSUE THREAD

**Issue by nelreina** [Swiip/generator-gulp-angular#628]
After updating gulp-angular to the last version, I got a backdrop issue with current version ui bootstrap modal. I need to set animation to false to get it working properly. 

Any ideas hoe to fix this issue or do I need to go back 1 version ?

**Comment by zckrs** [comment]
I don't think this issue is related to generator.
We have only updated `ui-bootstrap` from `~0.12.0` to `~0.13.0`.

Try to downgrade

**Comment by nelreina** [comment]
Yep that does the trick. I downgrade ui-bootstrap from 0.13.0 to 0.12.0.
