### ISSUE TITLE
this is undefined in RouterConfig class in TypeScript

### ISSUE THREAD

**Issue by pgrm** [Swiip/generator-gulp-angular#629]
Hi, not sure how to report this issue.

I'm using TypeScript pre-processor and wanted to modify the RouterConfig class to make use of methods in order to structure it better. However `this` was undefined in the constructor. I suppose, it is due to the fact, how Angular is calling that class, probably not with `new`. Unfortunately I'm not experienced enough in JavaScript to be 100% sure how things are supposed to work, if they don't.

I've created a [StackOverflow question](http://stackoverflow.com/questions/30978743/how-can-this-be-undefined-in-the-constructor-of-an-angular-config-class) with a detail example:

    class TestConfig {
      constructor() {
        console.log('TestThis =>');
        console.log(this);
        console.log('<= TestThis');
      }
    }
  
    angular.module('todoList', [])
    	.config(TestConfig);

Which logs for me:

    TestThis =>
    undefined
    <= TestThis

I do understand that it's not directly your issue, but I think it's a bit misleading to create it as a class, if it in fact can't be used as one. Or is anything wrong with the code? That might be the case as well, I just couldn't find anything. Controllers and Services work as expected.

Thx for your feedback.

**Comment by zckrs** [comment]
You can look other class like 
https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/src/app/components/githubContributor/_githubContributor.service.ts 

Maybe try to add a `console.log(this)` in this file

**Comment by pgrm** [comment]
Hi, thx - I've created a sample project and added inside the `MainController` constructor

      console.log('controller this:');
      console.log(this);

updated the `RunBlock`:

    export class RunBlock {
      /** @ngInject */
      constructor($log: ng.ILogService) {
        console.log('RunBlock this:');
        console.log(this);
        $log.debug('runBlock end');
      }
    }

updated the `ConfigClass`:

    export class Config {
      /** @ngInject */
      constructor($logProvider: ng.ILogProvider, toastr: Toastr) {
        console.log('Config this:');
        console.log(this);
        // ...
      }
    }

And finally also added the similar code inside the `RouterConfig`:

      console.log('RouterConfig this:');
      console.log(this);

`this` only existed in the `MainController` constructor. Every other constructor was empty. I do understand, that a class is easier to extend, but it is misleading. I'd suggest to either generate them as pure functions, or crate a function (even static one inside the class) which would actually create an instance of the class in order to have the correct behaviour. This way it would be basically a Singleton, just not provided by AngularJS.

**Comment by pgrm** [comment]
Btw, here a [suggestion from Ryan Cavanaugh](http://stackoverflow.com/questions/30978743#30987714) on how to define config classes.

**Comment by zckrs** [comment]
Ryan is right. 
>Config functions aren't classes and shouldn't be written as such.

**Comment by mikesigs** [comment]
I replied to your SO question, but thought I'd add my answer here too. 

It's pretty straightforward really, just export them as functions rather than classes. The constructor parameters become the function's parameters. Also, be sure and use the ngInject attribute on your function (instead of using `$inject = []` syntax).
```
/* @ngInject */
export function Config(
    $logProvider: ng.ILogProvider,
    $httpProvider: ng.IHttpProvider,
    $provide: ng.auto.IProvideService,
    RestangularProvider: restangular.IProvider) { 

    /* ... */
}
```

**Comment by zckrs** [comment]
PR appreciate

**Comment by pgrm** [comment]
@mikesigs yes, I saw your answer and already implemented it, including checking if `@ngInject` works (not that I wouldn't trust you :wink:). Everything is fine, PR would be awesome. I could have a look at it next week, if you won't get to it.

**Comment by mikesigs** [comment]
Great. Glad it worked for you. I'll got right on the PR.

**Comment by mikesigs** [comment]
@zckrs I can't seem to get the mocha tests to run. I'm using Windows. I even tried installing cygwin, but that didn't help. The instructions from the CONTRIBUTING.md don't work. If I run `./node_modules/mocha/bin/_mocha ./test/*.js` it says `'.' is not recognized as an internal or external command, operable program or batch file`. 

I tried running it as `node node_modules/mocha/bin/_mocha test/*.js` but that gives me the following error: 
```
c:\Source\GitHub\generator-gulp-angular\test\mocha.js:6355
      ? process.cwd() + slash
                ^
TypeError: undefined is not a function
    at Object.exports.stackTraceFilter (c:\Source\GitHub\generator-gulp-angular\test\mocha.js:6355:17)
    at Object.<anonymous> (c:\Source\GitHub\generator-gulp-angular\test\mocha.js:4594:25)
    at require (c:\Source\GitHub\generator-gulp-angular\test\mocha.js:11:11)
    at c:\Source\GitHub\generator-gulp-angular\test\mocha.js:45:14
    at Object.<anonymous> (c:\Source\GitHub\generator-gulp-angular\test\mocha.js:1444:18)
    at require (c:\Source\GitHub\generator-gulp-angular\test\mocha.js:11:11)
    at c:\Source\GitHub\generator-gulp-angular\test\mocha.js:6469:28
    at Object.<anonymous> (c:\Source\GitHub\generator-gulp-angular\test\mocha.js:6564:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at c:\Source\GitHub\generator-gulp-angular\node_modules\mocha\lib\mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (c:\Source\GitHub\generator-gulp-angular\node_modules\mocha\lib\mocha.js:189:14)
    at Mocha.run (c:\Source\GitHub\generator-gulp-angular\node_modules\mocha\lib\mocha.js:422:31)
    at Object.<anonymous> (c:\Source\GitHub\generator-gulp-angular\node_modules\mocha\bin\_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Any help getting this working on Windows?

**Comment by zckrs** [comment]
Really you should just push your branch and let Travis run test for you.

Running test of generator in Windows is a pound. You can try to install mocha as global and run `mocha test/`

Windows not recognize `*` or `.` etc

**Comment by pgrm** [comment]
:+1:  thx @mikesigs
