### ISSUE TITLE
Problem setting up Jasny Bootstrap, excluded

### ISSUE THREAD

**Issue by dereklin** [Swiip/generator-gulp-angular#634]
This maybe be related to these issues:
https://github.com/Swiip/generator-gulp-angular/issues/578
https://github.com/Swiip/generator-gulp-angular/issues/531

I am trying to set up Jasny Bootstrap.  

```
"dependencies": {
...
"jasny-bootstrap": "3.1.3"
...
}
```
But the files are not included in the index.html.

Then I found this

```
exports.wiredep = {
  exclude: [/bootstrap.js$/, /bootstrap\.css/],
  directory: 'bower_components'
};
```

What is the history and purpose of excluding bootstrap from wiredep?  And is it ok to remove the exclusion?  What about doing?:

```
exports.wiredep = {
  exclude: [/^bootstrap.js$/, /^bootstrap\.css/],
  directory: 'bower_components'
};

```

**Comment by Swiip** [comment]
If you choose an angular lib for bootstrap, you don't want the the original js to be included.

If you choose a css prepro, you want to include the rich version of the style and not the compile one.

Your changes will not work because it targets links of the files in the lib folder and they do not start with the file name.

**Comment by dereklin** [comment]
@Swiip what changes do you recommend to include jasny-bootstrap in index.html?  Also, the bootstrap files all start with bootstrap: 
![image](https://cloud.githubusercontent.com/assets/2231799/8359078/1398532c-1b19-11e5-8d6b-32f6955ce48f.png)

**Comment by JR-Utily** [comment]
Experiencing same problem here, jasny is not recognized

**Comment by cyberdemon8** [comment]
my older issue #531 is still alive...
@JR-Utily solutions works like a charm (in linux) :smiley:

**Comment by chrisheninger** [comment]
Just came across the same issue with "angular-formly-templates-bootstrap.js" being auto-excluded... @JR-Utily fix is perfect! Thank you JR and Zckrs!
