### ISSUE TITLE
Bootstrap glyphicons omitted for CSS-only builds

### ISSUE THREAD

**Issue by brian428** [Swiip/generator-gulp-angular#637]
If standard CSS is chosen for the build, the Bootstrap glyphicons (from bower_components/bootstrap/dist/fonts) are not included during a build.

I see that _build.js has this conditional on line 92:
```
<% if (props.ui.key === 'bootstrap' && props.cssPreprocessor.extension === 'styl') { -%>
  return gulp.src($.mainBowerFiles().concat('bower_components/bootstrap-stylus/fonts/*'))
<% } else { -%>
  return gulp.src($.mainBowerFiles())
<% } -%>
```

I'm wondering if that just needs to be something like this?
```
<% if (props.ui.key === 'bootstrap') { -%>
  return gulp.src($.mainBowerFiles().concat('bower_components/bootstrap*/**/fonts/*'))
<% } else { -%>
  return gulp.src($.mainBowerFiles())
<% } -%>
```

Either that, or a separate `else if` to explicitly handle bootstrap+css mode?

**Comment by Swiip** [comment]
Nop it's not this. I already seen that the glyphicons stopped working.

Bootstrap recently removed a lot of linked files inside their `bower.json` including the fonts. It already caused another trouble: #622. Perhaps we could use the same strategy: add font path in the bower override...

**Comment by brian428** [comment]
Hmm well that I am less sure of. I actually just started using this generator last week, so I haven't messed with bower overrides. All I know is that in this case, if I change the generated build.js file to mimic what I showed above, the fonts do get included correctly. That said, if there's a "better" way to handle this (via bower override or whatever), I'm all ears! Thanks.

**Comment by Swiip** [comment]
I think we're both right. My point is the original problem but I look too quickly at your solution, it do the trick, I've to look deeper if it's enough generic to be kept in the code.

**Comment by isaacweathers** [comment]
Just my two cents, it is happening with LESS build and BootStrap as well. Looking at work around.

**Comment by jaileleu** [comment]
Hello,

I've made a small workaround to have my fonts working (I'm using less too)
I don't plan to make a PR for that, but here is the code, while waiting for the next release.

```javascript
// fix to hard copy fonts from Bootstrap as they don't include their fonts in their bower.json file
gulp.task('copy-bs-fonts', function(){
  return gulp.src(conf.wiredep.directory+'/bootstrap/fonts/*.{eot,svg,ttf,woff,woff2}')
    .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});

// Only applies for fonts from bower dependencies
// Custom fonts are handled by the "other" task
gulp.task('fonts', ['copy-bs-fonts'], function () {
  return gulp.src($.mainBowerFiles())
    .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))
    .pipe($.flatten())
    .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});
```

**Comment by steeren** [comment]
Hi there.
First I'd like to say, thank you! Your generator is fantastic. 
I also encountered a problem that I guess is related to Bootstrap shifting things around a little (as mentioned some where above).
I generated a project with boostrap and bootstrapUI on ES5 and right now I am only using:
"gulp serve" 
I have noticed 404's where the fonts were not found. Turns out there aren't copied to .tmp/serve so, its no wonder they weren't found. 
JR-Utily kindly supplied some workaround code which I took and placed in inject (changing references from conf.paths.dist to conf.paths.tmp), and adding the fonts task as a dependancy of the inject task. Had to change the font path to /serve/fonts/ too). 

Here's my changes:
```javascript
gulp.task('copy-bs-fonts', function(){
  return gulp.src(conf.wiredep.directory + '/bootstrap/fonts/*.{eot,svg,ttf,woff,woff2}')
    .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/fonts/')));
});

// Only applies for fonts from bower dependencies
// Custom fonts are handled by the "other" task
gulp.task('fonts', ['copy-bs-fonts'], function () {
  return gulp.src($.mainBowerFiles())
    .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))
    .pipe($.flatten())
    .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/fonts/')));
});
```
I am almost certain there is probably a cleaner way of doing this. At a minimum I guess I should have made this one task. I'm not gulp expert at all, so I'm going to assume this is not worth a PR. If it turns out that you would prefer a PR let me know and I'll do that.

**Comment by claboran** [comment]
@steeren Thanks for solution I struggled while building the dist for production. The fonts did not get copied over to dist/fonts. I included also font-awesome. with an extra replacement. So everything is working now. I use font-awesome in conjunction with LESS and is working now as well :-)

Here is my extension:

```javascript
// fix to hard copy fonts from Bootstrap as they don't include their fonts in their bower.json file
gulp.task('copy-bs-fonts', function(){
  return gulp.src(conf.wiredep.directory+'/bootstrap/fonts/*.{eot,svg,ttf,woff,woff2}')
    .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});

// fix to hard copy fonts from font-awesome as they don't include their fonts in their bower.json file
gulp.task('copy-fa-fonts', function(){
  return gulp.src(conf.wiredep.directory+'/font-awesome/fonts/*.{eot,svg,ttf,woff,woff2}')
    .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});

// Only applies for fonts from bower dependencies
// Custom fonts are handled by the "other" task
gulp.task('fonts', ['copy-bs-fonts', 'copy-fa-fonts'],function () {
  return gulp.src($.mainBowerFiles())
    .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))
    .pipe($.flatten())
    .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});

...
  return gulp.src(path.join(conf.paths.tmp, '/serve/*.html'))
...
    .pipe($.replace('../../bower_components/font-awesome/fonts/', '../fonts/'))
...
```

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)

**Comment by dgoncalves1** [comment]
I updated using NPM and tried to install font-awesome again but still the fonts folder doesn't get added in dist.

**Comment by vitorreis** [comment]
Guys thank you for the workarround, I needed a quick solution for this and it helped a lot.

**Comment by dheerajui** [comment]
@JR-Utily that worked like a charm for me. I was using angular material and bootstrap would pick up angular fonts but not glyphicons. Thank you so much!!
