### ISSUE TITLE
Why not use webpack for typescript ?

### ISSUE THREAD

**Issue by mfilotto** [Swiip/generator-gulp-angular#639]
Hi,
I use your template for my project and recently migrated from es6 to typescript.
I wanted to keep using webpack and it's working well.
I was wondering why you decided not to use webpack. 
Thanks for your help

PS : great job thanks :+1:

**Comment by Swiip** [comment]
To be honest, I don't really remember why. I tried a messed with the dependency management of TS.

There is this strange difference between a real deps and a typeing reference with `///` but it would be better to align typescript on webpack.

**Comment by Swiip** [comment]
Just tried a little. Untill Typescript 1.5 is out, it's seams wrong. The module syntax is not standard, the typescript webpack loader doesn't support TS 1.5 easily. I was not able to come up with a satisfying solution.

When TS 1.5 will be out with a standard module notation, I think we'll be able to align TS on Webpack as for ES6.

**Comment by mfilotto** [comment]
TS 1.5 beta with awesome typescript webpack loader work just fine for my code written in ES6 using modules (aka external module for TS)

**Comment by mfilotto** [comment]
#708
