### ISSUE TITLE
creationDate is null in sample

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#640]
I had not generated a new project in awhile.

I generated one with coffee and jade and saw this in the NavBar directive

```
    NavbarController = (moment) ->
      vm = this
      # "vm.creation" is avaible by directive option "bindToController: true"
      vm.relativeDate = moment(vm.creationDate).fromNow()
```

Actually when stepping through with the debugger vm.creationDate is null. Its not null in the main controller and that is called first.  However it is null there.  Since no error is thrown and the relative time still comes back saying 'a few moments ago' people may assume this works but in reality it doesn't.

**Comment by zckrs** [comment]
Juste generate a new project in CoffeScript. `vm.creationDate` is not null

**Comment by wgorder** [comment]
Just generated a new project again. Still null.  See my yo-rc.json below:

You can set a breakpoint on the line I mentioned in the directive or just console.log it by changing it as below:

```

    NavbarController = (moment) ->
      vm = this
      # "vm.creation" is avaible by directive option "bindToController: true"
      vm.relativeDate = moment(vm.creationDate).fromNow()
      console.log(vm.creationDate)
      return

```

If you do this you will see `undefined` printed to the console.

```
{
  "generator-gulp-angular": {
    "version": "0.12.0",
    "props": {
      "angularVersion": "~1.4.0",
      "angularModules": [
        {
          "key": "animate",
          "module": "ngAnimate"
        },
        {
          "key": "cookies",
          "module": "ngCookies"
        },
        {
          "key": "touch",
          "module": "ngTouch"
        },
        {
          "key": "sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "key": "jquery2"
      },
      "resource": {
        "key": "restangular",
        "module": "restangular"
      },
      "router": {
        "key": "ui-router",
        "module": "ui.router"
      },
      "ui": {
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "key": "ui-bootstrap",
        "module": "ui.bootstrap"
      },
      "cssPreprocessor": {
        "key": "less",
        "extension": "less"
      },
      "jsPreprocessor": {
        "key": "coffee",
        "extension": "coffee",
        "srcExtension": "coffee"
      },
      "htmlPreprocessor": {
        "key": "jade",
        "extension": "jade"
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      }
    }
  }
}
```

**Comment by wgorder** [comment]
Also not despite the fact that the generated yo-rc.json says version `version": "0.12.0"` I confirmed that I have the latest version and the package.json for the installed generator-gulp-angular correctly says `version": "0.12.1"`

**Comment by zckrs** [comment]
![capture d ecran 2015-06-30 a 09 20 07](https://cloud.githubusercontent.com/assets/3020368/8425733/3d727350-1f09-11e5-9c02-a0f6d17399b4.png)


I copy/paste your `yo-rc.json` and `NavbarController`

**Comment by wgorder** [comment]
Weird, what could be different?  Are you running on a mac?

**Comment by zckrs** [comment]
Solved :)

In fact I use master version of generator and I recently fix this problem 
https://github.com/Swiip/generator-gulp-angular/compare/v0.12.1...master#diff-86a39a5c5ab2de068f881708b1734e55R4

I will trying to release `v0.12.2` today

**Comment by wgorder** [comment]
Thanks a lot @zckrs  !!

**Comment by msenosiain** [comment]
Hi, How did you solve this? I'm not using any js preporcesssor nad have the same bug.

Thanks

**Comment by benmurden** [comment]
@msenosiain The main difference seems to be in the index.html, where you need to change the `creationDate` attribute on the `acme-navbar` element to `creation-date` so you have the following.

`<acme-navbar creation-date="main.creationDate"></acme-navbar>`

**Comment by msenosiain** [comment]
Oh ok. Thanks

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
