### ISSUE TITLE
Components are not put into dist in the build task

### ISSUE THREAD

**Issue by sergonius** [Swiip/generator-gulp-angular#641]
The build task doesn't put the components I have in src into the dist's components folder, I have to put them there manually later on (which kind of beats the purpose). It does create the folders, but no html files are put there.

**Comment by Swiip** [comment]
What do you call "components"? The js files are in the bundle, the html ones also. So your folder ends up empty but that's ok. In fact we have an issue to remove unused directories but yet, it should work.

**Comment by sergonius** [comment]
the default components folder, where i've put most of my stuff :-(

**Comment by Swiip** [comment]
Yep, it's perfectly normal that in dist, your folder are empty. All is bundled in `index.<hash>.js`

**Comment by sergonius** [comment]
what about html files? ive used ng-include to get some stuff from the components folders.

**Comment by zckrs** [comment]
HTML files are transform in JS files and put into Angular $templateCache service by `gulp-angular-templatecache`

https://github.com/Swiip/generator-gulp-angular/blob/08897c5c88e297bee9ab7571e625f086248a62f4/app/templates/gulp/_build.js#L25

**Comment by sergonius** [comment]
So how would I get a working dist folder by running "gulp build" then? My ng-include has a path to the components folder, meaning things won't get rendered unless I put the components there. Or am I doing something wrong somewhere?

**Comment by Swiip** [comment]
With template cache, the templates are pre-loaded in the Angular cache behind their relative path. It's totally transparent for Angular. Your code will ask for the standard URL and Angular will find it in its cache.

**Comment by sergonius** [comment]
Currently I get error messages (cannot find resourcr) and an empty page, though. Where should I look for the problem?

**Comment by Swiip** [comment]
The path declaration of the templates could be wrong, remove uglify and look at the end of your bundle to look what is generated. The configuration of the path in the gulp plugin is https://github.com/Swiip/generator-gulp-angular/blob/08897c5c88e297bee9ab7571e625f086248a62f4/app/templates/gulp/_build.js#L27, perhaps you have to change it.

**Comment by sergonius** [comment]
Oh, great thanks, I had to change "app" to "/app", surprised nobody else has had an issue.

<3

**Comment by zckrs** [comment]
Before close please pull request

**Comment by Swiip** [comment]
We should test before chosing a PR. This must work on some environment like it is or no inception test would work. But it could be interesting digging why there is a problem here.

**Comment by zckrs** [comment]
@sergonius can you tell us your OS, node version and paste your .yo-rc.json ?

**Comment by sergonius** [comment]
I created my first pull request ever, hope I did that right :-D

What I got:
OSX Yosemite 10.10.3,  node v0.12.4.

.yo-rc.json:
{
  "generator-gulp-angular": {
    "version": "0.11.0",
    "props": {
      "angularVersion": "~1.3.4",
      "angularModules": [
        {
          "key": "animate",
          "module": "ngAnimate"
        },
        {
          "key": "cookies",
          "module": "ngCookies"
        },
        {
          "key": "touch",
          "module": "ngTouch"
        },
        {
          "key": "sanitize",
          "module": "ngSanitize"
        }
      ],
      "jQuery": {
        "key": "none"
      },
      "resource": {
        "key": "angular-resource",
        "module": "ngResource"
      },
      "router": {
        "key": "ui-router",
        "module": "ui.router"
      },
      "ui": {
        "key": "none",
        "module": null
      },
      "cssPreprocessor": {
        "key": "node-sass",
        "extension": "scss"
      },
      "jsPreprocessor": {
        "key": "none",
        "extension": "js",
        "srcExtension": "js"
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html"
      },
      "bootstrapComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      }
    }
  }
}

**Comment by zckrs** [comment]
You use a old version of generator. In last version 0.12.1 I has updated gulp-angular-templatecache

That fix your issue.  No PR needs sorry

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/commit/26ab4ebf39a71690c7af762427dabae1df4d65ae#diff-af782628927c2262dbb848fb6c305b35R11. The commit

**Comment by sergonius** [comment]
Updating the generator didn't work for me.

**Comment by zckrs** [comment]
You should rerun generator after update

**Comment by sergonius** [comment]
I reran the generator after updating and made a new project, replaced the files I had and I still need to change it to "/app"

**Comment by zckrs** [comment]
Can you push the project on a repository ?

**Comment by sergonius** [comment]
I don't have permissions to do that.

**Comment by Swiip** [comment]
Just ran some tests, no idea why it's not working for you without the `/` it should...

**Comment by AhmetCanSolak** [comment]
I have almost the same problem, and I try to change 'app' to '/app', it have not worked for me, too. Do you have any suggestion. After build I can just see my initial screen, but ui-router does not work. I just get Not Found message when I try to use ui-router.

**Comment by andrescuev** [comment]
Hi @Swiip 
I still have the same issue as AhmetCanSolak and sergonius with the ui-router Not Found, adding the "/" to "app" is not working in my case.
Any other solution for this?
