### ISSUE TITLE
`protractor` command is not deterministic

### ISSUE THREAD

**Issue by kudresov** [Swiip/generator-gulp-angular#646]
When you run `gulp protractor` sometimes it runs tests first and then only starts the server, which results in failed tests. Most of time it does in the correct order.. 
It seems that it's to do with the way gulp run tasks (in an asynchronous manner).

**Comment by Swiip** [comment]
You're the first seeing this. Unfortunately we didn't manage to pass protractor tests in the CI but still I run them frequently and never seen this.

What OS, options are you using?

**Comment by e-oz** [comment]
It's so easy to reproduce I even used to run `gulp serve` in separate console as a workaround, because otherwise tests will fail almost always. OS X.

**Comment by zckrs** [comment]
>It's so easy to reproduce

Can you explain @e-oz?

**Comment by Swiip** [comment]
Ran lots of protractor this past few days for the RC and never seen something not deterministic (OSX).

Can you test with the RC version?

**Comment by zckrs** [comment]
ping @e-oz @kudresov

**Comment by zckrs** [comment]
No reply
