### ISSUE TITLE
CSSO is out of date

### ISSUE THREAD

**Issue by wgorder** [Swiip/generator-gulp-angular#651]
I was searching around since I was having some issues with the CSSO stuff and sourcemaps.  Turns out its no longer maintained.  They are promoting clean-css

See here:
https://github.com/css/csso/issues/173#issuecomment-71802159

Is there a reason why we would not do the same with this generator?

Here is the clean-css alternative
https://github.com/jakubpawlowicz/clean-css
https://github.com/murphydanger/gulp-minify-css

**Comment by wgorder** [comment]
By the way, I swapped out CSSO with clean-css and everything works fine, in addition the sourcemaps stuff now works properly which it did not before.

**Comment by Swiip** [comment]
Yep, we have to update this. PR would be nice.
