### ISSUE TITLE
Subgenerators

### ISSUE THREAD

**Issue by juan-manuel-alberro** [Swiip/generator-gulp-angular#652]
Hello,

What do you think about add sub-generators to gulp-angular? Something like

    yo gulp-angular:service myService
    yo gulp-angular:view anotherView
    ...

I think it's very useful, I saw this in another generator. What do you think about this? Pros and cons? 
Thanks!

**Comment by zckrs** [comment]
Duplicate   https://github.com/Swiip/generator-gulp-angular/issues/9
