### ISSUE TITLE
bower install mdi got error

### ISSUE THREAD

**Issue by Gary-Pan** [Swiip/generator-gulp-angular#653]
[Sass] Error in plugin 'gulp-sass'
Message:
    bower_components/mdi/scss/_core.scss
  1:1  Undefined variable: "$mdi-css-prefix".
Details:
    column: 1
    line: 1
    file: /Users/Gary/U3D/bitbucket/mdi/bower_components/mdi/scss/_core.scss
    status: 1
    messageFormatted: bower_components/mdi/scss/_core.scss
  1:1  Undefined variable: "$mdi-css-prefix".

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md

**Comment by rictorres** [comment]
I had the same issue, but the problem lives on MDI's bower.json config.

**Solution**
Add the following to the `overrides` section of your project's bower.json.
```json
"overrides": {
  "mdi": {
    "main": [
      "fonts/*",
      "css/*"
    ]
  }
}
```

Also, check https://github.com/Templarian/MaterialDesign-Webfont/issues/7
