### ISSUE TITLE
Problem with $q es6 angular

### ISSUE THREAD

**Issue by brunoksato** [Swiip/generator-gulp-angular#654]
Class SisService{
        constructor($q){
            'ngInject';
            this.$q = $q;
         }

         get(){
             let deferred = this.$q.defer();
             deferred.resolve();
             return deferred.promise;
         }
      }
     
     export default SisService;

My service is error $q not defined, solution ?

**Comment by e-oz** [comment]
try to put `// @ngInject` before constructor
```
Class SisService{
   // @ngInject
    constructor($q){
        this.$q = $q;
     }

**Comment by BobbieBarker** [comment]
seems like a non starter. I would just use es6 promises.

**Comment by Swiip** [comment]
That should work... Traceur or Babel? Dev or Dist? How do you declare your service in the module?

**Comment by agustin107** [comment]
A solution that worked for me is:
```
Class SisService {
    constructor($q)  {
        'ngInject';
        this.$q = $q;
     }
     get()  {
         let deferred = this.$q.defer();
         deferred.resolve();
         return deferred.promise;
     }
     static sisFactory($q) {
         return new SisService($q);
     }
}

SisService.sisFactory.$inject = ['$q']

angular.module(moduleName, [])
  .factory('sisService', SisService.sisFactory);
```
I hope to help you!!!

P/d: Read [this article](http://www.sitepoint.com/writing-angularjs-apps-using-es6/), is very helpful and is full.
