### ISSUE TITLE
Testing with karma gives Module not available error

### ISSUE THREAD

**Issue by ehteshamkafeel** [Swiip/generator-gulp-angular#655]
While testing I think the Javascript files aren't sorted by Angular File Sort and load in wrong order and gives the following error.

    "Uncaught Error: [$injector:nomod] Module '{someModule}' is not available".

If the files are given in correct order, Karma loads them in correct ordering and doesn't give the above error.

I can fix the issue and issue a pull request.

**Comment by zckrs** [comment]
I think your issue is solved in `master`

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
