### ISSUE TITLE
Generating fails on Windows7 x86

### ISSUE THREAD

**Issue by zhekaus** [Swiip/generator-gulp-angular#656]
I get lots of errors like bellow during of generating the project on Windows7 x86.
It looks like C++ compiler fails to compile projects validation.vcxproj and bufferutil.vcxproj

An example of error:
c:\WebProj\Lab\t\node_modules\socket.io\node_modules\socket.io-client\node_modul
es\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "c:
\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node
-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, до
бавьте параметр "/m".
  bufferutil.cc
c:\WebProj\Lab\t\node_modules\socket.io\node_modules\socket.io-client\node_modu
les\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C2039:
'ThrowException' : is not a member of 'v8' [c:\WebProj\Lab\t\node_modules\socke
t.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\w
s\build\bufferutil.vcxproj]
c:\WebProj\Lab\t\node_modules\socket.io\node_modules\socket.io-client\node_modu
les\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C2039:
'New' : is not a member of 'v8::String' [c:\WebProj\Lab\t\node_modules\socket.i
o\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\b
uild\bufferutil.vcxproj]

**Comment by waylex** [comment]
Facing the same issues on Windows. Python 2.7 and .NET 2.0 are required dependencies. Maybe we could improve this somehow?

**Comment by Swiip** [comment]
Browser Sync need node-gyp which needs .Net and Python.

It's NPM mechanism and responsibility. I can't support all way to NPM usage. Report to BrowserSync or event node-gyp trackers...
