### ISSUE TITLE
Handle CSS source mapping out of the box

### ISSUE THREAD

**Issue by Swiip** [Swiip/generator-gulp-angular#66]
Already works with node-sass.

Problematic with node-ruby-sass: https://github.com/Swiip/generator-gulp-angular/issues/52#issuecomment-57207134

To be done for less.

**Comment by zckrs** [comment]
Done with #398

**Comment by opadilla** [comment]
BTW http requests for css.map files are getting sent to the proxy server when the proxy is enabled.  Adding 'map' to the list of extensions in that regex in proxy.js fixes that.
