### ISSUE TITLE
index.html changes get reloaded one save behind

### ISSUE THREAD

**Issue by slawojstanislawski** [Swiip/generator-gulp-angular#660]
When I introduce changes into .html files placed somewhere under /app folder, right after the save operation the changes are reflected in the browser, live reload works fine. But when I introduce changes to the src/index.html file, the change is reflected in the browser only after saving another (second) change. So live reload is one step behind on changes in the src/index.html file.
I thought changing line 36 in gulp/watch.js from:
```javascript
    gulp.watch(path.join(conf.paths.src, '/app/**/*.html'), function(event) {
```
to:
```javascript
    gulp.watch(path.join(conf.paths.src, '/**/*.html'), function(event) {
```
would help, but it didn't change the behavior.

**Comment by skeenan** [comment]
+1 seeing this behaviour too

**Comment by skeenan** [comment]
Updating everything in `package.json` using the below resolved this for me. Bit of a blunt instrument, but it worked. The problem clearly lay with a specific package, this 'fix'  does not reveal which one sadly. Hope this helps.

    $ npm install -g npm-check-updates
    $ npm-check-updates -u
    $ npm install

**Comment by red0point** [comment]
+1

I think it's because the Inject Task doesn't trigger a browser sync reload, because the styles task does indeed trigger one.

**Comment by Swiip** [comment]
Thanks for reporting, I reproduce it. I have to dig a bit...

**Comment by jesucarr** [comment]
I just tried adding `.pipe(browserSync.reload({ stream: true }))` as the styles task does, but the issue is still there.

I also tried adding `gulp.watch(path.join(conf.paths.tmp, '/serve/*.html'), browserSync.reload);`, so the browser reloads after the inject task, but no luck.I just tried adding `.pipe(browserSync.reload({ stream: true }))` as the styles task does, but the issue is still there.

I also tried adding `gulp.watch(path.join(conf.paths.tmp, '/serve/*.html'), browserSync.reload);`, so the browser reloads after the inject task, but no luck.

**Comment by zckrs** [comment]
Reproduce.

But why edit index.html @slawojstanislawski  ?

**Comment by skeenan** [comment]
@zckrs this is a ridiculous question. lot's of reasons for doing this.

**Comment by zckrs** [comment]
ok

**Comment by slawojstanislawski** [comment]
Well, why edit, perhaps it is valid to say that one should only edit the templates/files angular puts together into the index.html at runtime, but one can still edit index.html and it causes reload, yet in a way that other files don't, I suppose it won't lead to anything serious, just a bit of confusion and introduction of one more unnecessary change (like a single blank space) to reload to see the change, it's just a user experience matter.
As to why one may edit index.html, there can be many reasons, although I can't think of any very serious example, with exception maybe for a viewport tag changes or introduction of some meta tags, like facebook open graph meta tags - although I didn't test this particular use case, so I'm not sure about the generator's behavior on this one - just off the top of my head.

**Comment by skeenan** [comment]
Other cases would be to use webfonts via a CDN, or adding css classes to the toplevel content div.

**Comment by sqal** [comment]
@jesucarr I think the issue has something to do with that part:

```
gulp.watch(path.join(conf.paths.src, '/app/**/*.html'), function(event) {
    browserSync.reload(event.path);
});
```

I replaced it with:

```
    gulp.watch([
        path.join(conf.paths.tmp, '/serve/*.html'),
        path.join(src, 'app/**/*.html')
    ]).on('change', reload);
```

and now works as expected :) Good luck.
`

**Comment by jesucarr** [comment]
@sqal I just tried your suggestion but it doesn't seem to work for me :(

**Comment by sqal** [comment]
@jesucarr ops ofc I made a mistake in my previous comment, it should be `conf.paths.src` instead of just `src`  because I had this variable declared before. And the same thing goes for `reload` -> `browserSync.reload`. Did you fix these by yourself and it's still not working?

**Comment by jesucarr** [comment]
@sqal yes I did those changes and I also tried with a `/` in front of `app`, but it doesn't fix it. Remember the issue is that it's loading one behind, so if you save twice, it would show as expected. Try doing `gulp serve`, make a change in index, and save just once. Do you have that issue?

**Comment by sqal** [comment]
@jesucarr I understand the issue and my changes solved the issue for me (changes made to index.html are visible after first save). It's weird it's not working for you. But to make sure i just did clean install of generator, did the changes, ans it's still working :).

**Comment by GitAngel** [comment]
The issue looks quite easy. The problem is just in the order of execution of tasks: as soon as you save changes to `index.html` automatic page reload happens, but in parallel there's a task which performs `inject` of static resources.  
And it turns out that refresh is performed before the new `index.html` file is actually built. That's why you are seeing previous version of your file.  
This can be easily verified inside `.tmp/serve/index.html` file.

**Comment by Swiip** [comment]
Perfect, thanks for the analysis and the PR!

**Comment by GitAngel** [comment]
@Swiip, Thank you for your generator, Matthieu. It's a pleasure to help a bit into it's development)
