### ISSUE TITLE
ZeptoJS not included in vendors.js

### ISSUE THREAD

**Issue by dzafel** [Swiip/generator-gulp-angular#663]
I selected ZeptoJS when I was generating new app, then I ran `gulp` but ZeptoJS has not been included in generated vendors JS file in `dist` folder. And there is jQuery included instead. Here are my installation steps:
```sh
yo gulp-angular App --skip-welcome-message --skip-message --advanced

? Which version of Angular do you want? 1.4.0 (stable)
? Which Angular's modules would you want to have? (ngRoute and ngResource will be addressed after) angular-animate.js (enable animation features), angular-cookies.js (handle cookie management), angular-touch.js (for mobile development), angular-sanitize.js (to securely parse and manipulate HTML)
? Would you need jQuery or perhaps Zepto? ZeptoJS 1.1.x (jQuery compatible but very much lighter)
? Would you like to use a REST resource library? Restangular, an alternative service to handles RESTful requests
? Would you like to use a router ? UI Router, flexible routing with nested views
? Which UI framework do you want? None
? Which CSS preprocessor do you want? Less, extends the CSS language, adding features that allow variables, mixins, functions and many other techniques.
? Which JS preprocessor do you want? None, I like to code in standard JavaScript.
? Which html template engine would you want? None, I like to code in standard HTML.
```

and `bower.json`:
```json
{
  "name": "app",
  "version": "0.0.0",
  "dependencies": {
    "angular-animate": "~1.4.0",
    "angular-cookies": "~1.4.0",
    "angular-touch": "~1.4.0",
    "angular-sanitize": "~1.4.0",
    "zeptojs": "~1.1.6",
    "restangular": "~1.5.1",
    "angular-ui-router": "~0.2.15",
    "malarkey": "yuanqing/malarkey#~1.3.0",
    "toastr": "~2.1.1",
    "moment": "~2.10.3",
    "animate.css": "~3.3.0",
    "angular": "~1.4.0"
  },
  "devDependencies": {
    "angular-mocks": "~1.4.0"
  },
  "resolutions": {
    "angular": "~1.4.0"
  }
}
```

**Comment by paddybasi** [comment]
I don't this solely applies to the dist either, even selecting no jquery will always include it. I believe this is probably due to the third party library 'toastr' which has a dependency on jquery. When wiredep is injecting the bower dependencies it is probably resolving to jquery.

It also makes sense though, as toastr is a jquery plugin. I believe a solution would be to remove toastr completely or a suitable replacement.

**Comment by Swiip** [comment]
Yep, you raise a good point, the config with zepto is totally wrong, I'll make a PR...

As a workaround, you have to change "zeptojs" bower dep for "zepto" and exclude jquery (which is in transitive dep) in wiredep in the conf.js file.

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
