### ISSUE TITLE
Semantic UI Support

### ISSUE THREAD

**Issue by pineauk** [Swiip/generator-gulp-angular#664]
*Feature Request*
I am wondering if there has been any thoughts of adding support for semantic-ui because it seems to be one of the most powerful front end ui frameworks available. 
If anyways has attempted this and ran into issues, or would like this feature available as well, just comment below.

**Comment by jackrobertscott** [comment]
+1

**Comment by bsides** [comment]
+1

**Comment by zckrs** [comment]
Any PR in progress?

**Comment by Swiip** [comment]
I downvote Semantic a while ago. I agreed it's quite popular now. So why not with a good PR but not by me in a close future.
