### ISSUE TITLE
Running in production

### ISSUE THREAD

**Issue by Sk1Zy** [Swiip/generator-gulp-angular#665]
I am wondering what the best way would be to running this in production.

We're using PM2 on our servers and i was wondering if i should setup express and run it through express or if i can somehow run the serve:dist task inside PM2. Is the built in gulp server enough or should i set up something proper?

How are you guys running this on your servers?

**Comment by Swiip** [comment]
These tools, Gulp or Browser Sync are dev tools, you shouldn't run them in production.

The process is to use de `build` task to generate a optimized version in the `dist` folder and only deploy this folder on a production server with any HTTP server of your choice. Apache, Nginx, Node...

**Comment by qumani-designs** [comment]
@Swiip - I have been using this generator for quite some time now and love it, thank you for all of the work you put in.

That being said... In the recent updates, I can no longer build a working copy in dist. If I do not use html5mode it is fine, however, no matter what I attempt to do, I cannot get a stable copy running with html5mode that I can refresh. Before, I would use $locationProvide with appropriate `<base href="/">` tag, .htaccess rewriting to /index.html on my server, and use a "middleware", but as far as I can tell those are only for the node instance that is running locally, and it does not get put into the "build":
```
var modRewrite = require('connect-modrewrite');

function browserSyncInit(baseDir, files, browser) {
  browser = browser === undefined ? 'default' : browser;

  browserSync.instance = browserSync.init(files, {
    startPath: '/index.html',
    server: {
      baseDir: baseDir,
      middleware: [
        proxyMiddleware,
        modRewrite([
          '!\\.\\w+$ /index.html [L]'
        ])
      ]
    },
    browser: browser
  });

}
```
also tried another suggestion of:
```
var proxyMiddleware = require('proxy');
var historyApiFallback = require('connect-history-api-fallback');

function browserSyncInit(baseDir, files, browser) {
  browser = browser === undefined ? 'default' : browser;

  var routes = null;
  if(baseDir === paths.src || (util.isArray(baseDir) && baseDir.indexOf(paths.src) !== -1)) {
    routes = {
      '/bower_components': 'bower_components'
    };
  }

  browserSync.instance = browserSync.init(files, {
    startPath: '/index.html',
    server: {
      baseDir: baseDir,
      middleware: proxyMiddleware.concat(historyApiFallback),
      routes: routes
    },
    browser: browser
  });
}
```
Did I miss something along the way here?

**Comment by codeofsumit** [comment]
I'd also like to know whats the best way in this app setup to use the html5 history API.

Normally I'd create an .htaccess that redirects to the root URL where the angular routing kicks in. But I don't think gulp will move .htaccess files to their designated folders (neither tmp, nor dist) while service the app to browsersync.

**Comment by Swiip** [comment]
There is other issues on the subject of html5mode urls. I never really tried it so I don't have feedbacks for you. If someone has tried and could do a PR or a reciped it would be perfect.

Until then, I close this issue because the original subject is not relevant. Report or create issue about html5mode if you have more information.
