### ISSUE TITLE
Bug: Spec files are loaded in the browser

### ISSUE THREAD

**Issue by RomFouq** [Swiip/generator-gulp-angular#666]
Spec files seem to be loaded in the browser and that leads errors to be thrown, like `ReferenceError: inject is not defined`, since Jasmine isn't loaded.

I add spec files in the `app` folder, with the same structure as the base generator, but they don't seem to be excluded in injection. Indeed, I found they are explicitly injected in the html, just by opening the Inspector.
I think this problem comes from these lines: https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/gulp/_inject.js#L37, since I just have these:
```javascript
var injectScripts = gulp.src([
    path.join(conf.paths.src, '/app/**/*.module.js'),
    path.join(conf.paths.src, '/app/**/*.js'),
    path.join(conf.paths.tmp, '/serve/app/**/*.module.js'),
    path.join(conf.paths.tmp, '/serve/app/**/*.js'),
    path.join('!' + conf.paths.src, '/app/**/*.spec.js'),
    path.join('!' + conf.paths.src, '/app/**/*.mock.js')
  ])
```

Note: I use coffee for tests and v0.12.1 of this generator.

**Comment by wgorder** [comment]
I believe this has already been fixed in https://github.com/Swiip/generator-gulp-angular/pull/645

**Comment by Swiip** [comment]
Yep thanks @wgorder fix in master...

**Comment by RomFouq** [comment]
Glad to know that's fixed! Thanks!

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
