### ISSUE TITLE
dot notation for DI fails

### ISSUE THREAD

**Issue by lebsral** [Swiip/generator-gulp-angular#669]
When using the directive from angular-google-places-autocomplete
from
https://github.com/kuhnza/angular-google-places-autocomplete

it fails with the following errors,  (depending on how I do it wrong)
If I do this..
.controller('actnowCtrl', function ($scope, $firebaseArray, [google.places])
gives js lint error
  Expected an identifier and instead saw '['

if I do
.controller('actnowCtrl', function ($scope, $firebaseArray, google.places) {
I get the error
Expected ')' from line 10 instead saw '.'

any hints?

TIA

**Comment by Swiip** [comment]
google.places is the module name, not a service name. Look at the lib doc https://github.com/kuhnza/angular-google-places-autocomplete.

This has nothing to do with the generator, please dig a little before asking.

**Comment by lebsral** [comment]
Matthieu,

Thanks, that was very helpful.

I spent an hour 'digging'  but since I had no idea which direction to dig
in I got no closer to an answer.

After your help I got it in about 10 minutes.

Lars
