### ISSUE TITLE
foundation not injected in bower:css / bower:js

### ISSUE THREAD

**Issue by creimers** [Swiip/generator-gulp-angular#67]
It might be due to my incapability, but:

After running ``yo gulp-angular``, opting for foundation, in the ``index.html`` I don't get 
```
<!-- bower:css -->
<link rel="stylesheet" href="bower_components/foundation/css/foundation.css">
<!-- endbower -->
<!-- endbuild -->
```
as expected. 

```
<!-- bower:css -->
<!-- endbower -->
<!-- endbuild -->
```
remains empty.

Likewise, ``foundation.js`` is not injected.

Is this a bug or am I missing something?

Thanks.

**Comment by zckrs** [comment]
### Workaround if you dont need sourcemap

Replace 
`.pipe($.rubySass(sassOptions)).on('error', options.errorHandler('RubySass'))`
to
`.pipe($.rubySass({'sourcemap=none': true })).on('error', options.errorHandler('RubySass'))`
in
`./gulp/styles.js`

***
@creimers

**Comment by zckrs** [comment]
Done with https://github.com/Swiip/generator-gulp-angular/commit/b2c512a84a1a6262bec3ad38e0bb82bcaab576ae

**Comment by nhduc296** [comment]
I also have the same problem, but with combination of: Bootstrap + Node.js Sty;us

**Comment by vasiliy0s** [comment]
I found in gulp/conf.js next blocking filter:
```js
exports.wiredep = {
  directory: 'bower_components',
  exclude: [/foundation\.js/, /foundation\.css/]

};
```

When correct, all works bench!
