### ISSUE TITLE
Bower dependencie works with gulp serve but not with gulp serve:dist

### ISSUE THREAD

**Issue by antoescu** [Swiip/generator-gulp-angular#673]
Hi, Sorry if I am a little 'noob' in this topic, any help would be really appreciated.

I have a dependency in my bower called flag-icon-css (https://github.com/lipis/flag-icon-css). It just add country flags as vectors. 

When I run gulp serve it works as expected (it adds background-image: url(../flags/4x3/us.svg and the call in chrome's network is http://localhost:3000/bower_components/flag-icon-css/flags/4x3/us.svg). The problem is that when I do gulp serve:dist the 'background-image: url' is the same but the call in chrome's network http://localhost:3000/flags/4x3/us.svg is not valid since I don't have a 'flags' folder in dist. I thought that gulp automatically created a vendor.css (actually it does) with all my bower stuff (inside index.scss between // bower:scss and // endbower). Maybe I am mistaken in this thought or it is a different problem. Thanks for the help!

Edit: If I open the vendor.css I see that the classes have been added to the file, the problem is that the flags don't get added to the dist folder. Is this a problem with gulp, with that framework or with me? I could just add them manually, but I'd like to do it automatically. Also, I want to learn what the problem is to avoid asking again if it happens to me. Thanks again

**Comment by JR-Utily** [comment]
Svg files are not taken into account by default, I think.
But you can easily make a small task that will copy them where you want.
```
gulp.task('build:copy-flags', function(){
  return gulp.src(conf.wiredep.directory+'/flag-icon-css/flags/*')
    .pipe(gulp.dest(path.join(conf.paths.dist, '/flags/')));
});
```
then link this task to your build process

**Comment by antoescu** [comment]
Thanks for pointing it out. I'll do as you said. Good to know svg files work that way
