### ISSUE TITLE
How to change the main.html css using sass

### ISSUE THREAD

**Issue by WangJunru** [Swiip/generator-gulp-angular#676]
![c3b87008-0a14-444d-af44-5d0c9e8cb982](https://cloud.githubusercontent.com/assets/9455827/8766000/939abe26-2e5a-11e5-9ca8-0f11762d676c.png)
I want to change the style of main.html, but i don't want add all sass style in index.scss,so i add main.scss in src/app/main, but it can not work.

**Comment by zckrs** [comment]
Works with the latest version v1.0.0-rc1.

![screenshot from 2015-09-09 15 12 52](https://cloud.githubusercontent.com/assets/3020368/9762675/529634c2-5705-11e5-9d46-da991f158391.png)
