### ISSUE TITLE
Is there has a official way to upgrade  the new version from old version ?

### ISSUE THREAD

**Issue by abbish** [Swiip/generator-gulp-angular#677]
Hi

Is there has a official way to upgrade  the new version from old version ?

**Comment by zckrs** [comment]
This post by @sindresorhus can help you http://stackoverflow.com/questions/18480316/how-to-upgrade-existing-project-scaffolded-with-yeoman

**Comment by Swiip** [comment]
Not released doc: https://github.com/Swiip/generator-gulp-angular/blob/feat-readme/docs/recipes/upgrade-my-current-project.md

**Comment by zckrs** [comment]
Released https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md
