### ISSUE TITLE
gulp serve:dist - include images from 3rd party libraries

### ISSUE THREAD

**Issue by cazacugmihai** [Swiip/generator-gulp-angular#678]
Hi,

I'm using [leaflet](https://github.com/Leaflet/Leaflet) in my app. Executing **gulp serve:dist**, the images from leaflet library are not included in the **dist** folder. 

There are also other libraries having images and the mentioned task skips them.

You can use this in order to reproduce this behavior:

>  mkdir sample-app && cd $_
>  yo gulp-angular sample-app

choose default options then add "leaflet": "~0.7.3" in bower.json

> bower install
>  gulp serve:dist

Thanks,
Mihai

**Comment by cazacugmihai** [comment]
Also, neither fontawesome fonts are not included:

> GET http://172.17.0.6:3000/fonts/fontawesome-webfont.woff2?v=4.4.0 404 (Not Found)

If I start it with "gulp serve", everything is fine.

**Comment by Swiip** [comment]
There is no generic way for us to copy bower library assets. So I'm not surprised it's not working out of the box. You'll be forced to add some Gulp code in the `other` task. (https://github.com/Swiip/generator-gulp-angular/blob/master/docs/how-it-works.md#other)

About the fonts, all you need should be here: https://github.com/Swiip/generator-gulp-angular/blob/master/docs/how-it-works.md#fonts

**Comment by cazacugmihai** [comment]
Ok,  I'll use a custom task in this case. Thanks!
