### ISSUE TITLE
Script injection order

### ISSUE THREAD

**Issue by KarlNewark** [Swiip/generator-gulp-angular#679]
I have jest moved an angular application over to this workflow, the only issue I am having is with file injection order, at the minute the generator is including my controllers, services etc before the file that declares the angular app.

How exactly is the injection order determined? I have read all i can find on the subject and haven't found a clear solution?.

**Comment by bsitruk** [comment]
https://github.com/klei/gulp-angular-filesort does part of the work.
But I'm also interested by the question.

**Comment by MarcLoupias** [comment]
In gulp task inject in inject.js : 

```
var injectScripts = gulp.src([
        path.join(conf.paths.src, '/app/**/*.module.js'),
        path.join(conf.paths.src, '/app/**/*.js'),
        path.join('!' + conf.paths.src, '/app/**/*.spec.js'),
        path.join('!' + conf.paths.src, '/app/**/*.mock.js')
    ])
        .pipe($.angularFilesort()).on('error', conf.errorHandler('AngularFilesort'));
```

**Comment by zckrs** [comment]
As said @MarcLoupias the gulp task 'inject' manage the order by [`gulp-angular-filesort`](https://github.com/klei/gulp-angular-filesort) who should place  the declaration module in first place.

After that the task 'build' use [`gulp-useref`](https://github.com/jonkemp/gulp-useref) to replace build blocks in index.html.

Maybe this recipe can complete my comment. https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/managing-third-party-files.md
