### ISSUE TITLE
Code Coverage with ES6 + Babel?

### ISSUE THREAD

**Issue by jgodi** [Swiip/generator-gulp-angular#681]
Is there an option to get Code Coverage with the ES6 and Babel transpiler?

**Comment by zckrs** [comment]
Coverage over ES6 tranpiler is a probleme related to Istanbul. A expirimental solution is https://github.com/douglasduteil/isparta.

**Comment by zckrs** [comment]
Partially solved.

Actually we have coverage on the files generated by JS preprocessors

**Comment by Swiip** [comment]
As @zckrs said. Partially solved in the 1.0.0-rc1. I don't want to go farther right now.

You should look at isparta for ES6 coverage. But at the generator level it needs a different coverage tool by js preprocessor and I didn't find any for TypeScript so I don't want to go this way.

**Comment by keithkml** [comment]
@Swiip @zckrs I'm a little confused - why has this issue been closed? I tried installing isparta but it seems incompatible with the Gulp build generated by generator-gulp-angular.

**Comment by keithkml** [comment]
(I filed https://github.com/douglasduteil/isparta/issues/70 but have gotten no response)

**Comment by rwwagner90** [comment]
I'm having issues getting code coverage to work with ES6 and Babel as well. I'm using isparta, but it will only instrument `.spec.js` files, it will not pull in controllers, services, etc. I believe this is because there is the single `index.module.js` file that is pulling in all of the controllers, services, etc. How can we expose these files to isparta/istanbul?

**Comment by dlombardi** [comment]
cant we get an answer to this?  We're trying to integrate gulp-babel into the scripts tasks.  this fails in gulp serve:dist.

**Comment by rwwagner90** [comment]
@dlombardi babel is a built in option of generator-gulp-angular. Why add it manually?

**Comment by dlombardi** [comment]
In the case of a large project built without that option enabled.

**Comment by rwwagner90** [comment]
@dlombardi I would suggest running the generator in another folder and looking at the way the gulp tasks are set up for use with babel. I believe it uses webpack and babel-loader rather than gulp-babel.
