### ISSUE TITLE
gulp writing, <% if (imageMin) { -%>, where does this function come from?

### ISSUE THREAD

**Issue by Awakening-j** [Swiip/generator-gulp-angular#684]
I'm learning gulp script, and see `<% if (imageMin) { -%>` in `generator-gulp-angular` project, could anyone tell me where does this feature come from? Sorry for asking lower-level question, but I really want to know it.
BTW, i'm writing my own gulp file generator, I need to generate template dynamically, and insert into *.html, could someone give me some advice? Thank you very much!

**Comment by Swiip** [comment]
What you see is a template syntax from Yeoman in the last major release: https://github.com/yeoman/generator/releases/tag/v0.20.0. It has nothing to do with Gulp.

This mechanism of yeoman templates should allow you to generate files with anything you want.

**Comment by Awakening-j** [comment]
@Swiip Thank you, sorry, i forgot to reply. :)
