### ISSUE TITLE
out of memory less complie

### ISSUE THREAD

**Issue by devmark** [Swiip/generator-gulp-angular#685]
old version is
index.less
vendor.less

new version will get error if i have custom less same as bower package (bootstrap bower)

should separate it?

**Comment by Swiip** [comment]
We merge them because people want to use variables from their libraries into their less code.

If there is out of memories, we'll have to find a way by configuring less or something...

**Comment by zckrs** [comment]
@devmark  issue resolved ? 

If not can you give more details ? a github repo where we can reproduce the problem will be the best

**Comment by devmark** [comment]
issue resolved,finally i injected custom style by myself.
Thanks for reply!
