### ISSUE TITLE
PostCSS option as preprocessor

### ISSUE THREAD

**Issue by intellix** [Swiip/generator-gulp-angular#687]
https://github.com/postcss/postcss
"PostCSS can do the same work as preprocessors like Sass, Less, and Stylus. But PostCSS is modular, 3-30 times faster, and much more powerful."

**Comment by Swiip** [comment]
Didn't know about PostCSS, seams great. But as it's a lot of maintainance to add a CSS prepro, I will not digg deaper anytime soon...

**Comment by Swiip** [comment]
It's became quite popular since then. I could use this tracker as a tech monitoring ^^.

I can't do it myself but a good PR would be accepted.

**Comment by marchdoe** [comment]
@Swiip curious if this issue has changed, be interested in this functionality and could lend a hand if possible.

**Comment by Swiip** [comment]
Still good but no time for me. Our main focus is on [FountainJS](https://github.com/FountainJS/generator-fountain-webapp) right now, sorry if it reduce the quality here.

**Comment by marchdoe** [comment]
@Swiip no worries, totally understand. It is impossible these days to support *.js

I hadn't heard of Fountain before, off to go check it out. Thanks!

**Comment by Swiip** [comment]
As it is still n heavy dev status, we don't communicate much on it. But we'll do when enough stable for a beta. I hope it could be soon.
