### ISSUE TITLE
Wrong file order in index.html - modules are last.

### ISSUE THREAD

**Issue by codeofsumit** [Swiip/generator-gulp-angular#688]
I'm an angularJS beginner and just discovered this awesome generator.

While it has way more functions than I can currently grasp, I'm fighting through it to switch our app development to angular and this generator.

One problem I'm facing right now is when defining new modules and directives like so:

```
(function() {
	'use strict';

        angular.module('cities', []);
	angular.module('cities').directive('citySelect', citySelect);
	
	
	function citySelect() {
		
		var directive = {
			restrict: 'E',
			templateUrl: 'app/components/cities/cities.html',
			scope: {
				
			},
			controller: citySelectController,
			controllerAs: 'vm',
			bindToController: true
		};
		
		return directive;
		
	}
})();
```

If I move `angular.module('cities', []);` in a separate file, I'm getting the error that `Module 'cities' is not available!`.
I guess this is due to minification issues.
I read ngAnnotate is already in action here so how could I fix this issue?

The main app module e.g. `myapp` is available everywhere without issues but I can't seem to figure out why.

Thank you for any help and keep up the good work!

**Comment by codeofsumit** [comment]
after further investigation I found this in `gulp/inject.js`

```
var injectScripts = gulp.src([
    path.join(conf.paths.src, '/app/**/*.module.js'),
    path.join(conf.paths.src, '/app/**/*.js'),
    path.join('!' + conf.paths.src, '/app/**/*.spec.js'),
    path.join('!' + conf.paths.src, '/app/**/*.mock.js')
  ])
```

which means each `xx.module.js` file should be included before all others, right?

This is my structure for said new module:
![image](https://cloud.githubusercontent.com/assets/2399810/8889341/4193d9e8-32d6-11e5-836f-f4ed45178dae.png)

`cities.module.js` includes 
```
angular
        .module('cities', [])
```

And from both, `cities.directive.js` and `cities.service.js` I get `$injector:nomod] Module 'cities' is not available!` when I try to use 

```
angular.module('cities').directive('test', function(test) {
		alert('test')
	});
```

**Comment by Swiip** [comment]
It's not about ngAnnotate which is not used in the dev process (only dist).

It's a problem of file order which is (normally) solved by angularFileSort:
```javascript
 .pipe($.angularFilesort()).on('error', conf.errorHandler('AngularFilesort'));
```

Verify you have this line and check in `.tmp/serve/index.html` the order of your files, the module should have been placed before the directive one...

**Comment by codeofsumit** [comment]
Ah, thank you for the clarification. I do have this line:

```
var injectScripts = gulp.src([
    path.join(conf.paths.src, '/app/**/*.module.js'),
    path.join(conf.paths.src, '/app/**/*.js'),
    path.join('!' + conf.paths.src, '/app/**/*.spec.js'),
    path.join('!' + conf.paths.src, '/app/**/*.mock.js')
  ])
  .pipe($.angularFilesort()).on('error', conf.errorHandler('AngularFilesort'));
```

And just where you said lies the problem:

![image](https://cloud.githubusercontent.com/assets/2399810/8930877/f732c784-3531-11e5-8141-0972d563ef55.png)

`.module` files are inserted last. Any idea how that could happen?

**Comment by Swiip** [comment]
Seems to be a miss from angular file sort. Never seen this before. Your modules are especially put in last which is even stranger....

Can you build isolated project reproducing your problem and publish it on GitHub, it would be perfect for us to test (and for you to be sure it's not something else in your project)

**Comment by codeofsumit** [comment]
Sure thing, there you go:

https://github.com/codeofsumit/angular-test-polygons

**Comment by Swiip** [comment]
I start fearing environmental pb. It works for me:

```
    <!-- inject:js -->
    <script src="app/index.module.js"></script>
    <script src="app/components/webDevTec/webDevTec.service.js"></script>
    <script src="app/components/navbar/navbar.directive.js"></script>
    <script src="app/components/map/map.controller.js"></script>
    <script src="app/components/githubContributor/githubContributor.service.js"></script>
    <script src="app/components/cities/cities.module.js"></script>
    <script src="app/components/cities/cities.service.js"></script>
    <script src="app/components/cities/cities.directive.js"></script>
    <script src="app/main/main.controller.js"></script>
    <script src="app/index.run.js"></script>
    <script src="app/index.route.js"></script>
    <script src="app/index.constants.js"></script>
    <script src="app/index.config.js"></script>
    <!-- endinject -->
```

**Comment by zckrs** [comment]
Works for me too:

`.tmp/serve/index.html`
```
    <!-- inject:js -->
    <script src="app/index.module.js"></script>
    <script src="app/components/webDevTec/webDevTec.service.js"></script>
    <script src="app/components/navbar/navbar.directive.js"></script>
    <script src="app/components/map/map.controller.js"></script>
    <script src="app/components/githubContributor/githubContributor.service.js"></script>
    <script src="app/components/cities/cities.module.js"></script>
    <script src="app/components/cities/cities.service.js"></script>
    <script src="app/components/cities/cities.directive.js"></script>
    <script src="app/main/main.controller.js"></script>
    <script src="app/index.run.js"></script>
    <script src="app/index.route.js"></script>
    <script src="app/index.constants.js"></script>
    <script src="app/index.config.js"></script>
    <!-- endinject -->
```

node 0.12.7
npm 2.11.3

```
$ git clone git@github.com:codeofsumit/angular-test-polygons.git && cd $_
$ npm i && bower i
$ gulp serve
```

**Comment by codeofsumit** [comment]
Seems to be a node caching issue.

after
`sudo npm cache clean -f`

and rerunning `gulp serve`, the files are implemented correctly.

Thank you for confirming guys!

**Comment by joelcdoyle** [comment]
I still have this issue, even after running:
```
sudo npm cache clean -f
```
Any new components I create are added to the top of the script tags. I would definitely re-open this issue.

**Comment by joelcdoyle** [comment]
Hmm. This only happens when I have 1 subfolder in components. When I have multiple folders then it works correctly.

**Comment by Hesesses** [comment]
I had the same problem.

`sudo npm cache clean -f`
fixed the problem
