### ISSUE TITLE
Jquery included even if not selected during install

### ISSUE THREAD

**Issue by mvidailhet** [Swiip/generator-gulp-angular#690]
During install I specified not to install Jquery, but it was added anyway.
It's because Toastr require Jquery.
It would be great to be able not to include both.

**Comment by Swiip** [comment]
It's donwloaded by bower but also injected in your index.html ? It should have been excluded in wiredep conf.

**Comment by mvidailhet** [comment]
You're right, it's downloaded by bower but not injected in my index.html.
It's really minor, but it would have been better if it wasn't downloaded :)

**Comment by Swiip** [comment]
Bower doesn't offer a general exclude option. We would be forced to override conf for every deps in the bower.json, it would really be ugly...

**Comment by mvidailhet** [comment]
I see. Nevermind then, it's not really worth the ugliness :)

Love your generator btw. I'm using it for a Ionic app and it works perfectly!

**Comment by raphox** [comment]
I installed the jQuery after I project generation by 'yo gulp-angle'. Then needed for other dependencies (highcharts.com). For this I changed two files:

```
# .yo-rc.json
...
      "jQuery": {
-        "key": "jqLite"
+        "key": "jquery2"
      },
...
```

```
# gulp/config.js
...
exports.wiredep = {
=  exclude: [/jquery/],
+  exclude: [],
  directory: 'bower_components'
};
...
```

**Comment by busches** [comment]
@raphox not sure if there's a question there or just a comment?

**Comment by raphox** [comment]
It is a sugestion to resolve the problem.
