### ISSUE TITLE
More examples in the default generated application

### ISSUE THREAD

**Issue by edimoldovan** [Swiip/generator-gulp-angular#691]
Hi everyone,

I recently found this repository, which is very nice, but I am missing a few deeper examples of how to structure my further coding. I understand that in the angular world one structure things as he needs, but in the case of a team embracing generator-gulp-angular, there will already be an opinionated way of structuring the projects, so it would be awesome to have other examples in the basic generated app. For instance, a basic abstract route, with a few childs which render content in a ui-view, with the templates, controllers, modules that are needed to run this example and give a guidance for those who are not top notch Angular devs and need examples to be able to get their project going.

Would be happy to start a discussion around this, would also be happy to contribute. Sadly, my knowledge doesn't suffice for a PR, but I would help in any way I can.

Cheers,
Eduárd

**Comment by zckrs** [comment]
I think our example in the basic generated app is already huge.
Continue adding details would risk losing users in excessive complexity.

An alternative might be to list the applications created from the generator via an issue. And put forward in the README.md

**Comment by Swiip** [comment]
We go already further thant some people want and it would be a lot more work to maintain (every example has to be done in js, es6, coffee, scss, less, stylus, bootstrap, material...). So we will not going further but as @zckrs says, we should list public project made with the generator if we found a way to know about them.

**Comment by edimoldovan** [comment]
Pretty disappointing reply, but thanks for the update. Will look into other alternatives then.

**Comment by zckrs** [comment]
Theses link can help you:
* https://github.com/johnpapa/angular-styleguide/blob/master/README.md#modularity
* https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views#abstract-state-usage-examples

And pretty contributions are welcome.
