### ISSUE TITLE
Migration from older version

### ISSUE THREAD

**Issue by amgadfahmi** [Swiip/generator-gulp-angular#698]
First thanks a lot guys for this awesome project, I have been keeping an eye on the changes since i start to use this in my personal project and the changes are huge now, In the newer version there is a lot of extra feature i need and also many bug fixes but the gulp files are completely written in a different way and even the project structure, the question is 
Is there a mature way to migrate from the old version, taking in consideration i have made couple of extra tasks in gulp, bower, packages and even project structure.

**Comment by zckrs** [comment]
This link can help you http://stackoverflow.com/a/18500003

**Comment by amgadfahmi** [comment]
@zckrs thanks buddy, will give it a shot
