### ISSUE TITLE
[question] ionic integration

### ISSUE THREAD

**Issue by sibeliusseraphini** [Swiip/generator-gulp-angular#700]
This generator is awesome.

I would like to know if someone can help me,  integrate ionic and this generator and gulp

**Comment by Swiip** [comment]
I never tried but I know some of the users use it with Ionic. I hope some of these can answer.

**Comment by Telemakhos** [comment]
https://github.com/mwaylabs/generator-m is (partially) based on this generator. You should check it out. It's a nice starting point, but Ionic integration into this generator would be obviously much better =)
