### ISSUE TITLE
Include only the minimum required /// <reference> entries in index.modules.ts

### ISSUE THREAD

**Issue by gavinbarron** [Swiip/generator-gulp-angular#704]
When generating the new project please only include the required file references for the compilation/injection to work correctly.

in the current default generator every .ts file has a reference entry in the index.modules.ts file.
This leads new users to believe that they need to add entries for all files that they add.
Based upon my testing the only reference entries that are required are the following:
```
/// <reference path="../../.tmp/typings/tsd.d.ts" />

/// <reference path="index.config.ts" />
/// <reference path="index.route.ts" />
/// <reference path="index.run.ts" />
```

**Comment by Swiip** [comment]
Thanks for reporting. It's an interesting remark. Actually, I'm looking to integrate TS 1.5 and use ES6 module notation to keep only the typings reference. Your problem should go away at this point...

**Comment by gavinbarron** [comment]
Actually I did just run into more trouble where I had to put the directive references back. 
Perhaps you should pivot to using a tsconfig.json inline with the common code editors?

**Comment by Swiip** [comment]
Look at #708

**Comment by gavinbarron** [comment]
:+1:

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
