### ISSUE TITLE
Adding gulp-iife to defaults

### ISSUE THREAD

**Issue by Telemakhos** [Swiip/generator-gulp-angular#707]
Now that the generator is using John Papa's styleguide, did you consider adding something like [gulp-iife](https://github.com/mariusschulz/gulp-iife) to the default pipeline in order to have cleaner js files? Files look so much better without the typical... 

```
(function() {
"use strict";

    // Your code here

}());
```

Just try it... I think that this repeating task looks like a good candidate for some automation...

**Comment by Swiip** [comment]
Didn't know this plugin and actually never thought of it. Could be great...

**Comment by Telemakhos** [comment]
Cool, you can count this issue as a first vote... hopefully more people will find it useful too

**Comment by Swiip** [comment]
But after a second thought, there is a problem. People who chose no js prepro often want to spare the preprocessing step at development. Having this will force these user to have a preprocessing step.

**Comment by Telemakhos** [comment]
Oh, I see... well, I guess user could activate or deactivate this behaviour during the yeoman generation, and have the option to enable/disable it later in the ``conf.js`` inside the gulp folder? Don't know... it isn't that complicated to configure so maybe we'll set it up ourselves in a per project basis.

**Comment by zckrs** [comment]
Sample app follow angular style guides of John Papa
