### ISSUE TITLE
Is there a way to serve a public_app.js and private_app.js

### ISSUE THREAD

**Issue by AlexGrs** [Swiip/generator-gulp-angular#709]
I'm using your generator to build my frontend app and honestly : it is the best generator I ever used. Really good. 

One question though, my app is composed of a public part (login, password reset etc) and a private part. I would like to split the source code of my app in two parts:
- a public_app.js used to handle the login process / logout process
- a private_app.js only accessible to auth user.

Is there a way with the generator to do something like that ?  

Cheers.

**Comment by zckrs** [comment]
This issue is related to how create auth app with Angular. Many blog post explain how to solve your problem.
