### ISSUE TITLE
configuring proxy in server.js and requesting the proxied response always return 400 status.

### ISSUE THREAD

**Issue by sookinoby** [Swiip/generator-gulp-angular#711]
The browser sync server runs on 3000, so all the assets of angular app is served from port 3000. 
I run a express server on port 10000 which accepts rest calls 

I changed server.js proxy middleware to 
proxyMiddleware('/api', {target: 'http://localhost:10000'});

But when i make a $http.get to http:localhost:3000/api/user, it always return 400.

**Comment by zckrs** [comment]
You use a old version of generator. Please update generator, rerun generator on your project and look inside gulp/server.js https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md

You should see these lines:
```
  /*
   * You can add a proxy to your backend by uncommenting the line below.
   * You just have to configure a context which will we redirected and the target url.
   * Example: $http.get('/users') requests will be automatically proxified.
   *
   * For more details and option, https://github.com/chimurai/http-proxy-middleware/blob/v0.0.5/README.md
   */
  // server.middleware = proxyMiddleware('/users', {target: 'http://jsonplaceholder.typicode.com', proxyHost: 'jsonplaceholder.typicode.com'});
```

If you uncomment `// server.middleware = proxyMiddleware('/users', {target: 'http://jsonplaceholder.typicode.com', proxyHost: 'jsonplaceholder.typicode.com'});` and request http://localhost:3000/users everything should works
