### ISSUE TITLE
Replace toast by angular-toastr

### ISSUE THREAD

**Issue by Toub** [Swiip/generator-gulp-angular#712]
Toast requires on JQuery.

So, what about migrating to https://github.com/Foxandxss/angular-toastr witch has no external dependency?

I just gave a try and it looks good.

TODO: 
* replace bower dependency
* add module dependency in index.module.js
* replace module config in index.config.js
* remove constant in index.constants.js

**Comment by mikesigs** [comment]
This would be a great PR. I too am using angular-toastr in my project.

**Comment by zckrs** [comment]
Done by https://github.com/Swiip/generator-gulp-angular/pull/728
