### ISSUE TITLE
BrowserSync stops injecting after awhile

### ISSUE THREAD

**Issue by aendrew** [Swiip/generator-gulp-angular#713]
I'm sorry that this isn't going to be a very descriptive issue, but for some reason, BrowserSync works fine to begin with, but then stops injecting after awhile. I have no idea why this may be the case, though the console still has `[BS]` implying BrowserSync is noticing the changes and reloading.

It's not fatal by any means, but gosh is it an annoying bug when working to deadline...

*Edit:* One other thing I noticed, `browser-sync-client.2.7.13.js` is stuck in `Pending` mode via Chrome's Network tab whenever BS stops injecting. That would explain a lot — it can't open the websocket and thus can't be informed of changes.

**Comment by aendrew** [comment]
An additional thing I've noticed — it stops serving image files when BS injection dies. It seems like the BS server is leaking memory or something?

**Comment by Swiip** [comment]
Never run into this. It could be because I never keep BS alive long enough though. If it's confirmed, it's a bug for BS, try perhaps to update BS, it evolves quickly and I can't be up to date everytime.

**Comment by aendrew** [comment]
@Swiip Hi, thanks for getting back to me! I didn't see any issues in the BS queue, so was wondering whether it could be the generator's implementation of it. Will give that a shot next time I scaffold out a new app.

**Comment by Swiip** [comment]
The generator use BS quite out of the box, I don't see any option we use which could break it.

**Comment by aendrew** [comment]
@Swiip Yeah, that's what I thought — have looked through the config quite a lot and there's nothing sticking out at me.

Will close this for the moment and try the BS queue, reopening if it is indeed an issue with the generator.

**Comment by Swiip** [comment]
Perfect, thanks
