### ISSUE TITLE
Blank Page after gulp serve:dist

### ISSUE THREAD

**Issue by codeofsumit** [Swiip/generator-gulp-angular#715]
Everything works like a charm with `gulp serve`.
After `gulp serve:dist` the app has the following javascript errors:

```
Uncaught Error: [$injector:nomod] Module 'pmm' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=pmm
vendor-deed703424.js:33 runBlock end
vendor-deed703424.js:33 Error: [$compile:tpload] Failed to load template: app/components/cities/cities.html (HTTP status: 404 Not Found)
http://errors.angularjs.org/1.4.3/$compile/tpload?p0=app%2Fcomponents%2Fcities%2Fcities.html&p1=404&p2=Not%20Found
    at vendor-deed703424.js:32
    at s (vendor-deed703424.js:35)
    at u (vendor-deed703424.js:33)
    at vendor-deed703424.js:33
    at d.$eval (vendor-deed703424.js:35)
    at d.$digest (vendor-deed703424.js:35)
    at d.$apply (vendor-deed703424.js:35)
    at o (vendor-deed703424.js:33)
    at v (vendor-deed703424.js:33)
    at XMLHttpRequest.w.onload (vendor-deed703424.js:33)
```

The modue `pmm` is one module of the app was renamed to `app` later.

`pmm` isn't used anymore in our source files, but strangely it is all over the place inside the files of `dist`

Any idea what could mess up the build? Do you need more information?

**Comment by codeofsumit** [comment]
Ok i found it.
Problem was I generated the app with a name of "pmm". Later I wanted to rename the main module of angular to "app". Did so in every file in `src`. But the generator also used that "pmm" module name inside `gulp/build.js`. I renamed that to "app" as well and now the build works perfectly.

**Comment by danielrvt** [comment]
Where exactly did you changed that? I'm having the same problem...
