### ISSUE TITLE
Google material icons

### ISSUE THREAD

**Issue by damdoum** [Swiip/generator-gulp-angular#716]
Hi, how can i use google material icons? http://google.github.io/material-design-icons/#getting-icons

I am using sass in my project and i don't find a way to use them. 
i tried with bower and npm but nothing.,,
Any help would be really kind.

**Comment by dmastag** [comment]
I have been trying this myself with no Luck.
Ended up adding just adding the below into my index.html.
Any advise on the correct would be appreciated.

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

**Comment by damdoum** [comment]
Hi @dmastag , 
I also tried to add it in index.html but when i try everything in: 
```gulp serve:dist ```  ?
The Icons are not working...

**Comment by dmastag** [comment]
@damdoum what implementation are you using?
I am using the textual_name implementation like this

```html
<md-icon md-font-set="material-icons" class="md-dark"> delete </md-icon>
<!-- or -->
<i class="material-icons md-dark"> delete </i>
```

**Comment by damdoum** [comment]
i tried:
```html
<i class="material-icons md-dark"> delete </i> 
```
Is it working on your side?

**Comment by dmastag** [comment]
It is working on my side.

**Comment by damdoum** [comment]
Ok thank you, i will double check on my side. So it only still how to install them via bower and npm.
Which version of gulp-angular generator are you using?

**Comment by dmastag** [comment]
I am using v0.12.1 and scaffolded on the 3rd of August

**Comment by damdoum** [comment]
Ok thank you @dmastag , i am using an older one but i don't think that is  really related. 
My version is 0.9.1

Sorry for the late answer...
