### ISSUE TITLE
Gulp inject does not work correctly

### ISSUE THREAD

**Issue by sasajib** [Swiip/generator-gulp-angular#717]
I changed tmp config in the `gulp/conf.js` file to 

```javascript
exports.paths = {
  src: 'src',
  dist: 'dist',
  tmp: 'SomeCustomTempFolder',
  e2e: 'e2e'
};
```

`gulp build` does not inject the script correctly in `index.html`

```html
<script src="scripts/app.js"></script>
```

**Comment by Swiip** [comment]
Some paths are duplicated in the `index.html` for the build process because of `gulp-useref`, try updating them.

More info: https://github.com/Swiip/generator-gulp-angular/blob/master/docs/how-it-works.md#useref

**Comment by sasajib** [comment]
ok, thanks. I am closing this.
