### ISSUE TITLE
Inject scss automatic

### ISSUE THREAD

**Issue by brunoksato** [Swiip/generator-gulp-angular#718]
when creating a new SCSS file it automatically not adds to inject, need restart task gulp serve.

+1 for this

**Comment by Swiip** [comment]
Check if it's not this known limitation of Gulp 3 watch described here: https://github.com/Swiip/generator-gulp-angular/blob/master/docs/user-guide.md#file-watching--pre-processing

**Comment by brunoksato** [comment]
Thanks
