### ISSUE TITLE
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!

### ISSUE THREAD

**Issue by NayRia** [Swiip/generator-gulp-angular#719]
Just yestarday got strange errors.  
Simple project. Route:
```javascript
  function routeConfig($stateProvider, $urlRouterProvider) {
    $stateProvider
      .state('home', {
        url: '/home',
        templateUrl: 'app/home/home.html',
        controller: 'HomeController',
        controllerAs: 'home',
        data: {
          requireLogin: true
        }
      })

      .state('main', {
        url: '/main',
        templateUrl: 'app/main/main.html',
        controller: 'MainController',
        controllerAs: 'main',
        data : {
          requireLogin: false
        }
      });

    $urlRouterProvider.otherwise('/home');
  }
```
and in block .run() : 
```javascript
  function runBlock($log, $rootScope, $state) {

    $rootScope.$on('$stateChangeStart', function (event, toState, toParams) {
      if ( toState.data.requireLogin ) {
        event.preventDefault();
        $state.go('main');
      }
    });

    $log.debug('runBlock end');
  }
```
when i started project with gulp serve, i got error:
```javascript
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.4.3/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:68
    at Scope.$digest (angular.js:15721)
    at Scope.$apply (angular.js:15951)
    at bootstrapApply (angular.js:1633)
    at Object.invoke (angular.js:4450)
    at doBootstrap (angular.js:1631)
    at bootstrap (angular.js:1651)
    at angularInit (angular.js:1545)
    at HTMLDocument.<anonymous> (angular.js:28359)
    at fire (jquery.js:3099)(anonymous function) @ angular.js:12330
angular.js:15954 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.4.3/$rootScope/infdig?p0=10&p1=%5B%5D
```
But if i change 
```javascript
 $urlRouterProvider.otherwise('/home');
```
 to 
```javascript
 $urlRouterProvider.otherwise('/');
```
 and 
```javascript
url: '/home',
```
to
```javascript
url: '/',
```
the errors disappeared!
Could anyone explain me why this happens. And how to rid of this error ( i still want to use  $urlRouterProvider.otherwise('/home'); )
P.S.
previously i have never had such errors

**Comment by Swiip** [comment]
Sorry to be rude, but this is an Angular dev question. This type of questions are not fitted in this tracker.

**Comment by NayRia** [comment]
well, maybe i'm wrong, but when i made build, and then run it not with gulp serve:dist, but in simple nodejs server (http-server). This error disappeared. It appears only if i run it with gulp serve:dist. So, it looks like it is not an Angular dev question...

**Comment by chanu** [comment]
I also facing the same problem .... I see "Error: [$rootScope:infdig] http://errors.angularjs.org/1.3.15/$rootScope/infdig?" error in console. Can any one help me ????

**Comment by busches** [comment]
If this is happening out of the box with the generator, please post the `yo-rc.json` file, so it can be reproduced and fixed. If it's from code you added, see Swiip's previous comment: https://github.com/Swiip/generator-gulp-angular/issues/719#issuecomment-132096409

**Comment by NayRia** [comment]
@busches 
https://gist.github.com/NayRia/b0165429a18ef82f4544
