### ISSUE TITLE
server-side generation

### ISSUE THREAD

**Issue by jmls** [Swiip/generator-gulp-angular#720]
is there any support for server-side generation as well as the client-side magic that's happening ?

I want to be able to generate server-side code (i've got gulp serve kinda working by hacking server.js and adding nodemon to start the server side process) - but it feels wrong to have a server folder in the "dist" directory

really what I would like is to generate dist/app and dist/server folders from src/app and src/server

is it possible to configure the generator to do this ?

**Comment by Swiip** [comment]
There is nothing to do that and we're not going in this way. Check another generator like one for node or Express.
