### ISSUE TITLE
Toastr fails to work when jQuery is none

### ISSUE THREAD

**Issue by busches** [Swiip/generator-gulp-angular#723]
If I generate a project with `none` selected for the `jQuery` option, then I get a JavaScript error when clicking the `Splendid Toastr` button on the default template. This is because `jQuery` is purposely being excluded from `wiredep` in `bower.js`. Seeing the comments in issue #690 it looks like this is intentional. My question is do we fix it by:
* Removing the exclusion, so `Toastr` works,
* Switching to `angular-toastr` as mentioned in #712, or
* Remove the `Toastr` code when `none` is selected for `jQuery`

Depending on the resolution, I can likely crank out a PR sometime.

**Comment by Swiip** [comment]
Yep, this is a small fail in conception :)

I think the better is to use `angular-toastr`. A PR would be awesome.

**Comment by zckrs** [comment]
Done by https://github.com/Swiip/generator-gulp-angular/pull/728
