### ISSUE TITLE
plain old css not working

### ISSUE THREAD

**Issue by jmls** [Swiip/generator-gulp-angular#725]
I've got no css preprocessors running, and all I want to do is include a .css file in the gulp:serve or gulp:build - however, all I ever see in app.css is the index.sass instructions

how do I get a css file to be included in the gulp:server etc ? I must be missing something really obvious, so my apologies up front ;)

**Comment by busches** [comment]
You should have lines similiar to the following in your `gulp/styles.js`:

```js
  var injectFiles = gulp.src([
    path.join(conf.paths.src, '/app/**/*.css'),
    path.join('!' + conf.paths.src, '/app/index.css')
  ], { read: false });
```

Those should pickup any `css` file you have nested inside of `/app/`

**Comment by jmls** [comment]
that's the thing - I selected:
"? Which CSS preprocessor do you want? None, only the good old CSS"

but that option does not create gulp/styles.js file ...

**Comment by busches** [comment]
I created a basic no nothing app from the generator. In the `build.js` file there is this line: `var cssFilter = $.filter('**/*.css');` this picks up your `css` files. I added a new `css` file to `app/` and it correctly injected it and served it with `gulp serve`.

If that is not working, please link to your `yo-rc.json` file so the issue can be replicated.

**Comment by zckrs** [comment]
Not reproduce.

All works fine. 
CSS files are injected in index.html by `inject` task

```
var injectStyles = gulp.src([
    path.join(conf.paths.src, '/app/**/*.css')
  ], { read: false });
```

**Comment by spattersongt** [comment]
I'm having the same problem.  

@zckrs my `inject` task has the following line

```javascript
 var injectStyles = gulp.src([
    path.join(conf.paths.tmp, '/serve/app/**/*.css'),
    path.join('!' + conf.paths.tmp, '/serve/app/vendor.css')
  ], { read: false }); ```

Note it's `/serve/app/**/*.css`

**Comment by spattersongt** [comment]
> I created a basic no nothing app from the generator. In the build.js file there is this line: var cssFilter =  $.filter('**/*.css'); this picks up your css files. I added a new css file to app/ and it correctly injected it and served it with gulp serve.

I just repeated the same steps in a fresh directory.  My css in the file `/src/app/test.css` does not get embedded into `index.css`  

Here's my yo-rc

https://gist.github.com/spattersongt/4b5b5fbf274c04bcc607
