### ISSUE TITLE
gulp watch is watching but not building

### ISSUE THREAD

**Issue by tawanda** [Swiip/generator-gulp-angular#726]
i'm running
gulp serve:dist watch

if i edit and html file the watcher writes that there is a change in file but it does not rebuild, it only refreshes the browser

i am using the generated gulp files no mods

**Comment by Swiip** [comment]
`gulp serve:dist`run the optimized version of your app, there is no refresh feature possible, the optimization process is far too long

**Comment by tawanda** [comment]
but if i run even the watch command directly it does not rebuild the file i changed, are you saying this was not implemented

**Comment by Swiip** [comment]
Nop, the watch isn't plugged to trigger the full optimization process. That has never be the intend.

You should be able to write a new task for that if you want even if I think that this is can't be a good workflow, you should have a bit of confidence in the optimization process to be able to develop with de dev mode.

**Comment by tawanda** [comment]
ok, thanks for the feedback

**Comment by tawanda** [comment]
...and thanks for the great work :)
