### ISSUE TITLE
Tests are included in TypeScript build

### ISSUE THREAD

**Issue by busches** [Swiip/generator-gulp-angular#729]
When using TypeScript for the JS compiler, the tests under `/app/**/` are included in the concatenated `js` file, resulting in an error of `describe` is undefined in the console when run. Adding a filter into `scripts.js` to remove anything matching `'!' + path.join(conf.paths.src, '/app/**/*.spec.*')` removes them from the concatenation, but it seems like the specs should have been filtered out sooner.

For reference, the TypeScript test case in inception tests throws this error.

**Comment by Swiip** [comment]
Can you check with #708? It changes a lot of things.

Bu I also discovered with Babel similar problem. I think it will be the case with all Webpack builds. In my private project, I fixed it by creating 2 webpack build: one with tests and one without, I think this will be necessary in the generator...

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)
