### ISSUE TITLE
dist file naming

### ISSUE THREAD

**Issue by jmls** [Swiip/generator-gulp-angular#739]
Is it possible to customise the naming conventions of a gulp dist command ? Rather than app-xxxx.js can it just be app.js ? Same with the vendor files

I would like to see <<appname>>.js|css  and <<appname>>.min.js|css if possible

Just wondering if it were a config option or something that can be changed easily

thanks

**Comment by busches** [comment]
The `-xxxx` part is done by `gulp-rev`, removing the calls to the plugin in your Gulp build scripts will remove it. See their github repo on why it was created: https://github.com/sindresorhus/gulp-rev

**Comment by jmls** [comment]
ah, great! thanks for the help

**Comment by Swiip** [comment]
Thanks @busches. There is also the name of the generated files in `index.html` https://github.com/Swiip/generator-gulp-angular/blob/master/docs/how-it-works.md#useref
