### ISSUE TITLE
gulp serve without live-reload?

### ISSUE THREAD

**Issue by codeofsumit** [Swiip/generator-gulp-angular#742]
Sometimes we just want to edit lots of little things in our application, save each one and reload when we want to take a look at it. Especially true, when a reload fetches multiple APIs and needs 15 seconds to load.

So how can we `gulp serve` with live-reload disabled?

**Comment by Swiip** [comment]
I don't see a really easy way. The BS configuration UI doesn't allow to stop "live reloading", it could be a feature to ask them.

To stop livereload, the only way I see is to comment `browserSync.reload` calls in the gulp scripts.

**Comment by codeofsumit** [comment]
Ok thank you!

**Comment by codeofsumit** [comment]
Turns out, it is possible:

![image](https://cloud.githubusercontent.com/assets/2399810/9653618/eb82a8f4-5224-11e5-9fd8-fa41efc82460.png)

If you click on "disable all", syncing stops. Even if you re-enable each options by hand, it'll not auto-sync.

No idea if that is a bug or just bad UI. In any case, I opened an issue about it here.
https://github.com/BrowserSync/browser-sync/issues/802

**Comment by shakyShane** [comment]
You can also set `codeSync: false` in the Browsersync config
