### ISSUE TITLE
empty flag

### ISSUE THREAD

**Issue by codeofsumit** [Swiip/generator-gulp-angular#747]
Is there an option to create an app using this generator without the boilerplate stuff? Without that toastr, malarkey and all that?

**Comment by Swiip** [comment]
Nop, just delete the files you doesn't want

**Comment by codeofsumit** [comment]
unfortunately that's not as easy as it sounds. Dependencies and usage is sprinkled everywhere and despite our team trying to remove all of it, we weren't able to do so by keeping the build intact.
In places like

`protractor.js`
`e2e/main.po.js`
`e2e/main.spec.js`

we found the boilerplate code used.

By this time my teammate removed everything he found but the build fails now.

We will now generate the app from scratch again, put in version controll and commit every change we do so we can track down which removal will cause the build to fail.

**Comment by codeofsumit** [comment]
We finally made it though ;-)

**Comment by busches** [comment]
Can you walk through what was so tightly coupled? It should be what @Swiip said and if it's not, that's somewhere the generated should be improved.
