### ISSUE TITLE
Why are typescript definitions inside .tmp folder?

### ISSUE THREAD

**Issue by oswaldomilet** [Swiip/generator-gulp-angular#748]
I'm new to this generator and found it awesome. However, I could not find some docs...

Why ts definitions (.d.ts) are installed in .tmp folder? I'm using Visual Studio Code and want to use definitions for intellisense, how can I configure that?

I'm new to Jade too, so I chose it in project creation, but all templates are in HTML, why? Should I change them manually?

Thanks

**Comment by Swiip** [comment]
- https://github.com/Swiip/generator-gulp-angular/tree/master/docs

- ts definitions are not user sources but some kind of generated sources so it has not to be in src. About VSC, never used it, I can't help you

- The Jade option add configuration for compiling jade files but there is no example shipped

**Comment by oswaldomilet** [comment]
- The link you mentioned is the root documentation (still no docs for my questions).

- ts definitions generally are in typings folder after project root folder, so they can be used for tooling (intellisense, autocomplete, linters...)

- Would be nice if the templates come in .jade when selecting jade engine (just a suggestion)

**Comment by oswaldomilet** [comment]
I realized that there is a tsd.json file in project root pointing to .tmp/typings, so it solves the tooling problem.

But I'm getting some Typescript errors because some classes are using angular interfaces like ng.ITimeoutService and ng.ILogProvider that are not exported by angular.d.ts.

**Comment by zckrs** [comment]
https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular.d.ts#L727

They are exported by `angular.d.ts`.

We recently change how TSD is used in project.
https://github.com/Swiip/generator-gulp-angular/pull/756

I think your issue is solved

**Comment by oswaldomilet** [comment]
Thanks
