### ISSUE TITLE
Jade option doesn't create .jade files

### ISSUE THREAD

**Issue by busches** [Swiip/generator-gulp-angular#749]
As described in https://github.com/Swiip/generator-gulp-angular/issues/748, selecting Jade as the html templating option doesn't create `.jade` files, but `.html` files.

This is just to track the issue separately, I should be able to crank out a PR this week to fix it.

**Comment by zckrs** [comment]
We have many template files in https://github.com/Swiip/generator-gulp-angular/tree/master/app/templates/src/app 

Are you ready to duplicate the HTML files in 3 preprocessors and maintain?

**Comment by zckrs** [comment]
>Although when you first run the yeoman generator it gives you html files but you can edit them to be jade and the app will work the same. 

You can convert html files with http://html2jade.org/

**Comment by busches** [comment]
If it's not wanted I won't do it, but I view it the same as all the different flavors of JS files the generator offers. We can update the docs to point to http://html2jade.org/ at the very least though.

**Comment by mattycraig** [comment]
+1!

**Comment by Swiip** [comment]
A bit afraid of generating code (Yep I know, I made a generator) but if it's works well, a PR is welcome.
