### ISSUE TITLE
html5mode woes

### ISSUE THREAD

**Issue by rwwagner90** [Swiip/generator-gulp-angular#750]
I have tried using both normal ngRoute and ui-router, with `$locationProvider.html5mode(true)` and with both, I do not get the correct fallback for IE9 or less. It should be able to automatically insert the `#` when it needs to. It might be browser sync, but not really sure.

**Comment by zckrs** [comment]
Sorry I didn't use IE9 or less

But:
* this stackoverflow post can help you http://stackoverflow.com/questions/22763599/ie-9-not-supporting-locationprovider-html5mode
* since Angular1.3 IE8 support is dropped https://docs.angularjs.org/guide/ie
