### ISSUE TITLE
adding less processor to a plain css project

### ISSUE THREAD

**Issue by jmls** [Swiip/generator-gulp-angular#752]
When I set up a project I selected the plain old css option. Of course, I know have the need to use less, as one of the libs I use (semantic-ui) has a .less file specified in the bower.json file

How can I add this into the build / serve task ? 

I was going to use gulp-less, and the example they give is

```javascript
gulp.task('less', function () {
  return gulp.src('./less/**/*.less')
    .pipe(less({
      paths: [ path.join(__dirname, 'less', 'includes') ]
    }))
    .pipe(gulp.dest('./public/css'));
});
```

however, I don't know where to shove it ;)  I was looking at styles.js and build.js but can't make head nor tail of the gulp code :(

thanks

**Comment by naughtydavid** [comment]
I think it should go to the styles scripts file. 
As its already supported by the generator, i suggest you generate a new project with less and copy the less compiler config from the new styles.js file.

**Comment by Swiip** [comment]
I would have gave you the same advice. Generate a new project with the less option and look how we did it.

**Comment by wangchen** [comment]
@jmls You could try adding the following codes to your `bower.json`, it works for my scss project:
```
  "overrides": {
      "semantic": {
        "main": [
          "src/semantic.less",
          "dist/semantic.js",
          "dist/semantic.css"
        ]
      }
    }
```
