### ISSUE TITLE
directives inserted multiple times in generated index.html

### ISSUE THREAD

**Issue by psvensson** [Swiip/generator-gulp-angular#755]
Hi, I've noticed a problem only when using coffeescript, for some reason. At random times, I get the error;
Error: [$compile:multidir] Multiple directives [acmeNavbar (module: crawler), acmeNavbar (module: crawler)] asking for template on: <acme-navbar creationdate="main.creationDate">

One fo the possible reasons that this can happen is that one loads the same directive definition twice, but I htought it unlikely so looked everywhere else.

However, looking at the generated index.html I found this at the end..  (image attached)
![screenshot-35](https://cloud.githubusercontent.com/assets/39554/9706163/e2d4807c-54dd-11e5-8114-ffe4ec73400c.png)

So clearly the gulp procedure insert the same files several times. Not in the beginning, but when I start adding new custom directives (for instance) this is what happens - when I'm using coffeescript!  Very odd.

**Comment by zckrs** [comment]
Clearly we need more informations

* `.yo-rc.json` ?
* node version ?
* OS ?

**Comment by psvensson** [comment]
Sorry I missed that;

I have no file called .yo-rc.json anywhere.
node version v0.12.7
OS is Linux Mint 17 (Ubuntu)

I have used gulp-angular for several projects and it works very well but every time I select coffeescript this bug appears (I understand now).

**Comment by zckrs** [comment]
Can you execute in folder of project with command line `$ cat .yo-rc.json` ?

What is the version of generator-gulp-angular ? Can you try with the latest version ? 

https://github.com/Swiip/generator-gulp-angular/blob/master/docs%2Frecipes%2Fupgrade-my-current-project.md

**Comment by zckrs** [comment]
@psvensson ping

**Comment by psvensson** [comment]
Hi, sorry for the delay!

I did upgrade the gulp-angular generator to the latest version and I managed to create one custom  component, which did get added and worked fine. Let's close this then.
