### ISSUE TITLE
Bootstrap Sass caret style being removed on build

### ISSUE THREAD

**Issue by mdentinho** [Swiip/generator-gulp-angular#766]
Hello guys!

I'm having an issue with bootstrap sass when building the app after scaffolding a new project with the following `.yo-rc.json`:
```json
{
  "generator-gulp-angular": {
    "version": "0.12.1",
    "props": {
      "angularVersion": "~1.4.0",
      "angularModules": [],
      "jQuery": {
        "key": "none"
      },
      "resource": {
        "key": "angular-resource",
        "module": "ngResource"
      },
      "router": {
        "key": "ui-router",
        "module": "ui.router"
      },
      "ui": {
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "key": "ui-bootstrap",
        "module": "ui.bootstrap"
      },
      "cssPreprocessor": {
        "key": "node-sass",
        "extension": "scss"
      },
      "jsPreprocessor": {
        "key": "none",
        "extension": "js",
        "srcExtension": "js"
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html"
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      }
    }
  }
}
```

Basically, the bootstrap sass source code has these styles definitions for the `.caret` class in `/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_dropdowns.scss:7`:
```scss
.caret {
  display: inline-block;
  width: 0;
  height: 0;
  margin-left: 2px;
  vertical-align: middle;
  border-top:   $caret-width-base dashed;
  border-top:   $caret-width-base solid \9; // IE8
  border-right: $caret-width-base solid transparent;
  border-left:  $caret-width-base solid transparent;
}
```
This caret class is used by the dropdown bootstrap component and the bug can be seen after adding the following example code to any template in the app:
```html
<div dropdown>
  <button class="btn btn-default" type="button" id="dropdownMenu1" dropdown-toggle aria-haspopup="true" aria-expanded="true">
    Dropdown
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</div>
```
If you run `gulp serve` and check the app in any browser, it will look normal:
![screenshot 2015-09-10 12 23 51](https://cloud.githubusercontent.com/assets/210138/9784884/e0f47e20-57b6-11e5-99ca-137ce819e29f.png)

You can also check the rules for `<span class="caret"></span>` you will see that everything seems to be just fine:
![screenshot 2015-09-10 12 20 42](https://cloud.githubusercontent.com/assets/210138/9784831/8a78dabe-57b6-11e5-8705-60c3ac238561.png)

Now if you run `gulp serve:dist` and check the browser, the dropdown's caret is not there anymore:
![screenshot 2015-09-10 12 28 47](https://cloud.githubusercontent.com/assets/210138/9784993/834ebbf4-57b7-11e5-9ece-2e4c5b853f50.png)

You can see that the interface space for it is being preserved and if you check the generated rules you see that one of them is missing:
![screenshot 2015-09-10 12 30 28](https://cloud.githubusercontent.com/assets/210138/9785018/c171d236-57b7-11e5-9768-dfce8c13e078.png)

So, basically, somehow, the `border-top: 4px dashed;` rule is being removed just when the `styles` task is called from the `build` task and not when it's called from the `watch` task.

Please note that the described scenario will also happen if you replace `node-sass` with `ruby-sass` when scaffolding the project, so It's probably not a 3rd party component dependency issue.

I looked in all gulp tasks and couldn't figure it out what this could be, so I think that maybe someone involved in this project's development could find faster where the flaw might be.

Thanks in advance.

**Comment by zckrs** [comment]
New version `v1.0.0-rc1` is avaible.
I try your case with this version and carret is always present.
Can you reinstall generator and retry ?

**Comment by mdentinho** [comment]
Yes, @zckrs, it's working now. Thanks!

Do you know if there's an easy way to update an in progress project?

**Comment by mdentinho** [comment]
Closing, since the issue is not part of the project anymore.

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md

**Comment by mdentinho** [comment]
@zckrs Thanks.
