### ISSUE TITLE
Suggestion: Rename `gulp` folder to `gulp_tasks`

### ISSUE THREAD

**Issue by mdentinho** [Swiip/generator-gulp-angular#767]
Just to avoid any confusion with the actual `gulp` package and following the `bower` and `node` naming practices (`bower_components` and `node_modules`), I would suggest to change the gulp tasks folder name from `/gulp/` to `gulp_tasks/`.

It seems to be a simple update and if approved I can send a PR so i might get into the final 1.0.0 version.

Cheers!

**Comment by Swiip** [comment]
Thanks for the suggestion. I must admit I don't feel it. No big arguments, I just don't want too many long snake case directories. `src`, `gulp` and `e2e` feels right to me.
