### ISSUE TITLE
typings for angular-ui-bootstrap are not automatically loaded

### ISSUE THREAD

**Issue by crimsondr** [Swiip/generator-gulp-angular#769]
Create a new project and choose angular-ui-bootstrap with sass and typescript.  The tsd gulp task does not automatically install the typings for angular-ui-bootstrap.

**Comment by zckrs** [comment]
Task tsd doesn't exist anymore. Update generator.
https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md
