### ISSUE TITLE
Question: is it possible to server gzip file in the test server with Content-Encoding: gzip

### ISSUE THREAD

**Issue by mastermind1981** [Swiip/generator-gulp-angular#772]
Hi,

I want to use some gzipped json files to be served and i want to have the Content-Encoding: gzip header to be added so the browser can ungzip them automatically. 

Is it possible to do that ?

Thanks

**Comment by Swiip** [comment]
You have to check in the options of BrowserSync. I guess you'll have to write a specific middleware.
