### ISSUE TITLE
spec running twice when using test:auto

### ISSUE THREAD

**Issue by 0101adm** [Swiip/generator-gulp-angular#778]
v0.12.1

i have a spec that logs '1' to console.

gulp test -> logs once to console

gulp test:auto -> first run, logs once to console.  edit/save a spec and it logs twice to console.

[gulp test]
![screen shot 2015-09-12 at 12 49 21 pm](https://cloud.githubusercontent.com/assets/5133412/9833244/25c83f68-594d-11e5-9b67-e8396af8c083.png)

[gulp test:auto]
![screen shot 2015-09-12 at 12 50 20 pm](https://cloud.githubusercontent.com/assets/5133412/9833261/81a99110-594d-11e5-90c3-bb701def4060.png)

**Comment by zckrs** [comment]
Can you try with the latest version of generator v1.0.0-rc1 ?

**Comment by 0101adm** [comment]
1.0.0-rc1 is throwing errors.

[gulp serve]
![screen shot 2015-09-15 at 9 11 42 am](https://cloud.githubusercontent.com/assets/5133412/9880726/1876e4e2-5b8a-11e5-9e90-16bfb636c742.png)

[gulp test]
![screen shot 2015-09-15 at 9 12 13 am](https://cloud.githubusercontent.com/assets/5133412/9880732/1fbb4144-5b8a-11e5-9658-df53578f1326.png)
![screen shot 2015-09-15 at 9 12 55 am](https://cloud.githubusercontent.com/assets/5133412/9880733/1fbe50a0-5b8a-11e5-8cd9-6f3c95d2727a.png)

**Comment by zckrs** [comment]
Please we need more consistent informations like `.yo-rc.json`.

Everything works on my side with the master branch of generator on Ubuntu.

![untitled](https://cloud.githubusercontent.com/assets/3020368/9881256/711377b0-5bcf-11e5-9b44-c0195c3e7d19.png)
![untitled2](https://cloud.githubusercontent.com/assets/3020368/9881261/7427fe12-5bcf-11e5-86fe-0c392cb41aef.png)

**Comment by Swiip** [comment]
missing tsd.d.ts, seams like your `tsd install`has fail earlier.

**Comment by 0101adm** [comment]
clean install of generator got rid of the errors.

also, seems to have resolved the bug.
