### ISSUE TITLE
ngInject not injecting services into directive (Babel)

### ISSUE THREAD

**Issue by daniel-takeuchi** [Swiip/generator-gulp-angular#779]
Hi there,

I've generated a gulp-angular project using Babel.
Not sure if this is a design change or not, but I don't seem to be able to inject modules into directives.
The directive loads okay, but none of the dependencies do.
I am able to add a controller into the directive, as a workaround to access the services I need. Is this the correct pattern of doing things now?

```javascript
class MyDirective {
  constructor ($rootScope, MyService) {
    'ngInject';
    // can't access $rootScope or MyService
    let directive = {
      restrict: 'A',
      link(scope, el, attr) {
        // can't access $rootScope or MyService
      }
    };
    return directive;
  }
}
```

Thanks!

**Comment by 0101adm** [comment]
/** @ngInject */

put that above your constructor.  but really, you should create a factory that returns a new instance.

**Comment by daniel-takeuchi** [comment]
I believe the 'ngInject'; is the equivalent of /** @ngInject */ for Babel, is it not? Either way, it did not work for me.
I'm following the pattern from the directive generated by gulp-angular's generated code.

**Comment by 0101adm** [comment]
i believe its where you place it.  it should annotate the constructor.

**Comment by daniel-takeuchi** [comment]
Thanks for the help 0101adm. 
Moving the 'ngInject' above the constructor did not solve the problem, so I decided to follow your suggestion of using a factory instead.

I believe this could be a problem with the default generated code, because I was using the same pattern as the example directives provided. Controller and Services had their injections done properly, just not directives.

Anyway, thanks again!

**Comment by Swiip** [comment]
`'ngInject'` and `/** @ngInject */` should works the same https://github.com/olov/ng-annotate#explicit-annotations-with-nginject

We used the string version because Traceur is unable to preserve comments :/

**Comment by zckrs** [comment]
@daniel-takeuchi ES6 + AngularJS are tricky especially for directive.

http://www.michaelbromley.co.uk/blog/350/exploring-es6-classes-in-angularjs-1-x 

This article explain why and how to resolve problem.

**Comment by Swiip** [comment]
I tested, 'ngInject' and /** @ngInject */ works both. But the current way of defining directives don't. My PR correct this.

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/791
