### ISSUE TITLE
unexpected GET when dealing with svg files

### ISSUE THREAD

**Issue by 0101adm** [Swiip/generator-gulp-angular#780]
getting...

Error: Unexpected request: GET assets/iconsets/action-icons.svg

anyone recommend a way to cache svg files like partials are cached?

**Comment by Swiip** [comment]
Need more information. Gulp serve, serve:dist? I don't see any reason why BrowserSync will refuse to serve .svg requests. Never heard of a ng-svg2js, it could not work as partials are loaded in angular though `$templateCache` but svg are just images serverd by the browser...

**Comment by 0101adm** [comment]
this is using gulp test or gulp test:auto.

my svg icons are loaded at config.

```javascript
module com.myapp {
	'use strict';
	export class Config {
		/** @ngInject */
		constructor($logProvider: angular.ILogProvider,
						$mdIconProvider: angular.material.IIconProvider,
						$mdThemingProvider: angular.material.IThemingProvider
						CONSTANT: any) {

			$mdThemingProvider
				.theme('default')
				.primaryPalette('cyan')
				.accentPalette('orange')
				.warnPalette('red');

			_.each(CONSTANT.iconsets, (iconset: any) => {
				$mdIconProvider.iconSet(iconset.name, iconset.path, 24);
			});
		}
	}
}
```

i can dump the templatecache and see that there are corresponding keys for each svg iconset.

i have to use the below assertion for every icon set (there are 17 sets) and then the test will pass.

```javascript
$httpBackend.when('GET','assets/iconsets/action-icons.svg').respond('ok');
```

**Comment by 0101adm** [comment]
id like gulp to take all svg's and account for the request just like html partials.

**Comment by Swiip** [comment]
Ok, I see know, it's about material design and its icon provider. Sorry, I think it's beyond the support of the generator, ask Angular Material perhaps?
