### ISSUE TITLE
phantomJS limitation?

### ISSUE THREAD

**Issue by 0101adm** [Swiip/generator-gulp-angular#782]
using JQLite.

cannot get the height of an element.  also cannot scroll an element w/ overflow.

has anyone implemented either successfully?

should dimensional testing be left for protractor?

**Comment by busches** [comment]
These questions should be directed to JQLite or protractor, not the generator.

**Comment by zckrs** [comment]
:+1: @busches 
We are not mainteners of JQLite or PhantomJS.

You could try with https://github.com/karma-runner/karma-chrome-launcher
