### ISSUE TITLE
stricter .jshintrc directives - latedef - poor style to depend on hoisting

### ISSUE THREAD

**Issue by isrd1** [Swiip/generator-gulp-angular#788]
I think jshint should be stricter and definitely include at least these:
    "strict": true,
    "bitwise": true,
    "curly": true,
    "eqeqeq": true,
    "latedef": false,
    "noarg": true,
    "undef": true,
    "unused": true,
Which causes errors because the code is full of function declarations after the function has been referenced.  I think to depend on default language behaviour, specifically function hoisting, is poor style.  I've rewritten all the code to define vars for the functions prior to their use and the code is still very readable, no inline anonymous functions, but no jshint errors or warnings.  Could this code style and jshint setting not be adopted?

**Comment by zckrs** [comment]
We have migrated to ESLint.

https://github.com/Swiip/generator-gulp-angular/pull/705
