### ISSUE TITLE
functions declared before use bad style?

### ISSUE THREAD

**Issue by isrd1** [Swiip/generator-gulp-angular#789]
I put this issue about making jshint settings stricter, but really the issue isn't which linter you use, zckrs closed the issue prematurely because you've changed to eslint, the issue is really that using functions before declaring them could be improved.

I think to depend on default language behaviour, specifically function hoisting, is poor style. I've rewritten all the code to define vars for the functions prior to their use and the code is still very readable, no inline anonymous functions. Could this code style and appropriate linter settings not be adopted?

**Comment by zckrs** [comment]
We apply John Papa style guides 
https://github.com/johnpapa/angular-styleguide#style-y033

**Comment by isrd1** [comment]
Yes, but that doesn't make that aspect good.  Have a look at Todd Mott's style guide who Papa references, he also disagrees on this point and he puts the function declarations before their use: https://github.com/toddmotto/angularjs-styleguide

Surely if you use any linter references a variable or function before it's declaration is something to be avoided.  That internally JS hoists function declarations is neither here nor there, depending on a language default is asking for trouble in the long term.  

Todd Motto's guide shows code that is equally readable but, at least in this respect, won't lead to error.

If I do a pull and re-write to that standard is that any use to anyone?

Rob

**Comment by Swiip** [comment]
To be honest ES5 style-guides are dead, we're in the era of ES6 now :)

Sorry for non productive post, it's late!

**Comment by Swiip** [comment]
For a better response, there is no guidelines everyone agree with. Personally, I don't like IFEE.

To be as neutral as possible, we simply chose the most popular one and follow it. The point of the generator is not to be another guideline reference.

If the base code is not as you like, change it. It's what I do every time I start a project with the generator.

**Comment by isrd1** [comment]
Yes, I have changed my code I just wondered if a change and choice in the generator was worth having for those other people who like to pass linters without issue and also prefer 'declaration before use'  
I'll have to find out how to change my own local copy to use that as my generator -haven't delved deeply enough yet, yours is the first generator I've liked.

**Comment by zckrs** [comment]
Thank you
