### ISSUE TITLE
404 fetching images during tests

### ISSUE THREAD

**Issue by 0101adm** [Swiip/generator-gulp-angular#790]
image fetches are returning 404's while running tests.

does it serve assets from .tmp/serve/assets?  

![screen shot 2015-09-15 at 9 33 04 am](https://cloud.githubusercontent.com/assets/5133412/9881439/19bfa070-5b8d-11e5-8ac8-10704027eace.png)

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md#issues
