### ISSUE TITLE
Add sub-generator AngularJS

### ISSUE THREAD

**Issue by zckrs** [Swiip/generator-gulp-angular#793]
Our generator should provide  sub-generator for AngularJS.
That depends on option select to create project ie `.yo-rc.json`.
And must apply [John' Papa styles guides](https://github.com/johnpapa/angular-styleguide#table-of-contents) when possible.
- [ ] Generator code should be inside a folder `generators` to match the philosophy of composability Yeoman like [generator-node](https://github.com/yeoman/generator-node)
- [ ] Create a first sub-generator `gulp-angular:factory` who used in main generator to create "githubContributor" and "webDevTec"

**Comment by DaAwesomeP** [comment]
+1

**Comment by ansumanshah** [comment]
+1

**Comment by benkroeger** [comment]
+1

**Comment by elouazzany** [comment]
+1
check [this sub-generator](https://github.com/elouazzany/generator-gulp-angular-sub) and give me your feedback

**Comment by seyDoggy** [comment]
@elouazzany I like the structure of your templates is more in-line with those of @doronsever's sub-generator. I'd be glad to help you extend it more.

**Comment by klovelovely** [comment]
+1

**Comment by GregaVrbancic** [comment]
+1

**Comment by omri79** [comment]
+1

**Comment by prbaron** [comment]
What about [plop](https://www.npmjs.com/package/plop) ?

**Comment by zckrs** [comment]
Why use plop when we use Yeoman ?

**Comment by prbaron** [comment]
the main advantage I see compared to a sub generator is that you do not need to remember all the command lines because it is interactive. Otherwise, it does the same things.

**Comment by zckrs** [comment]
https://github.com/yeoman/yo/releases/tag/v1.8.0 

interactive too ^^

**Comment by zckrs** [comment]
For interested people [the next iterations of generator-gulp-angular](https://github.com/FountainJS/generator-fountain-angular1) have many sub-generators for AngularJS.

You can view list in this [tweet}(https://mobile.twitter.com/YeomanFountain/status/740937434930810880).
