### ISSUE TITLE
Google map

### ISSUE THREAD

**Issue by srdjanprpa** [Swiip/generator-gulp-angular#796]
Hi all,

I need help with goolge map, i don't know where to put this line of code
<script type="text/javascript" src="http://maps.google.com/maps/api/js?&v=3.8&sensor=false"></script>

On gulp serve map work, but on dist folder. It does not works.

**Comment by Swiip** [comment]
Please put a minimum effort when filling an issue. https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md#issues

Options, which lib exactly, how do you included it ?

**Comment by zckrs** [comment]
@srdjanprpa can you provide more details please ?

I'm not sure this issue is related to generator.

**Comment by Swiip** [comment]
Innactivity
