### ISSUE TITLE
Adding new file does not add it to watchers

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [Swiip/generator-gulp-angular#800]
Hey!

If I add new `stylus.styl` file, it is not added automatically to the scope of watchers.

Sorry if it is known issue.

**Comment by zckrs** [comment]
> The generator uses the file watching from Gulp 3 which is known to have some limitations. For example a new directory or the creation of the first file in a directory will be missed. Please try to stop your watch process and relaunch it before asking for help.       

https://github.com/Swiip/generator-gulp-angular/blob/master/docs/user-guide.md#file-watching--pre-processing

**Comment by AlexanderTserkovniy** [comment]
Thanks, will it be somehow fixed in the future? I saw you are planning more fixes/features when Gulp4 is ready, will you consider this as what has to be?

Also, have you considered of using [nodemon](http://nodemon.io/)? As I know it is done exactly for such cases.

**Comment by zckrs** [comment]
Yeah when we migrate to Gulp4 this issue should be solve.
In fact Gulp4 will use a new library for watching files. (https://github.com/gulpjs/gulp/issues/1247).

At this time you can use [gulp-watch plugin](https://github.com/floatdrop/gulp-watch) who use the same library: [chokidar](https://github.com/paulmillr/chokidar)

**Comment by AlexanderTserkovniy** [comment]
Thanks a lot!

**Comment by zckrs** [comment]
Np
