### ISSUE TITLE
Jade + Karma + ES6 (gulp test fails)

### ISSUE THREAD

**Issue by lunatik-210** [Swiip/generator-gulp-angular#802]
Please can you reconsider the ticket #731, I commented there about evolution of the problem

**Comment by Swiip** [comment]
Yep, you're right, sorry for the delay. If the problem is still not fixed, we have to reopen that.

**Comment by Swiip** [comment]
I get it, the principle of keeping html2js and keeping jade inside gulp is possible but the current conf is not correct.

I added searching inside `.tmp` for html files but html2js needs also the stripprefx parameter. PR incoming.

**Comment by Swiip** [comment]
released !
