### ISSUE TITLE
Images in dist are not revisioned

### ISSUE THREAD

**Issue by ereze** [Swiip/generator-gulp-angular#803]
Hi, 

Why are the images in the final dist folder are not revision-ed with content hash? 
How can I add this?

Thanks,
Erez

**Comment by Swiip** [comment]
JS & CSS files inclusions are easy to locates (only in index.html). For images, we can't be sure : html, ng-src, css... Adding revision is not only about renaming the file but also renaming the link so we can't do it. Not in a generic way at least.

You can imagine using Compass and "only in scss image links" for example.
