### ISSUE TITLE
build routes file by inject

### ISSUE THREAD

**Issue by jmls** [Swiip/generator-gulp-angular#805]
at the moment, the index.route.js file is a manually updated file. 

I was wanting to be able to add routes using a generator of some sort, and was thinking of putting the route definition into a json file in the components/xyz folder (where xyz is the name of the component)

what is the best way to go about this ? Using gulp-inject ? or is there another way / utility ?

Has anyone done something like this already ?

**Comment by jmls** [comment]
so, I try something and it works ... for anyone interested, this does the trick for me

```javascript
'use strict';

var path = require('path');
var gulp = require('gulp');
var conf = require('./conf');

var $ = require('gulp-load-plugins')();

var transform =  function (filepath, file) {
  console.log("contents",file.contents.toString('utf8'))
  return file.contents.toString('utf8');
};

gulp.task('injectRoutes', function () {
  var target = gulp.src(path.join(conf.paths.src,'/app/index.route.js'));

  var sources = gulp.src(path.join(conf.paths.src, '/app/**/*.route'));

  return target.pipe($.inject(sources,{transform: transform}))
    .pipe(gulp.dest(path.join(conf.paths.src,'/app')));
});
```
added the following to index.route.js 
```javascript
  <!-- inject:route -->
  <!-- endinject -->      
```
and now any file with an extension of .route is now injected into the index.route.js file

**Comment by XavierLeTohic** [comment]
@jmls please can you explain in details how it work's and where we have to place the code ? Thanks !
