### ISSUE TITLE
Using bower dependencies in index.scss

### ISSUE THREAD

**Issue by hartwm** [Swiip/generator-gulp-angular#807]
For some reason I can't figure out why some bower dependencies can be used in the index.scss file, but others can't?  In particular it I can @extend any bootstrap class within the index file and it compiles, but I can't extend an animate.css class.  Can someone please explain and clarify where I can correct this process?? Thank!

**Comment by Swiip** [comment]
It's all about the bower.json of the dependency. It contains a main property which linked the files. If there is no scss files in this property, wiredep can't do anything.

https://github.com/Swiip/generator-gulp-angular/blob/master/docs/user-guide.md#bower-dependencies
