### ISSUE TITLE
bootstrap application on google callback

### ISSUE THREAD

**Issue by gitsuraj** [Swiip/generator-gulp-angular#809]
currently I am using google visualize for google graphs. The problem is when I navigate to a view it won't go inside google.setOnLoadCallback but if I refresh page it works fine. So is there any way to load entire application inside google.setOnLoadCallback event

**Comment by Swiip** [comment]
There is ways to prevent Angular from bootstraping before Google lib being ready. But I really don't see how this is related to the generator.
