### ISSUE TITLE
Application under sub path

### ISSUE THREAD

**Issue by snikch** [Swiip/generator-gulp-angular#810]
I'm hitting a wall while trying to implement a new app under a sub path. I apologise for bringing this up as an issue, as I don't think it is an issue per se, but I couldn't see any other means of communicating.

I'd like to have my application completely handled under the path `/authorize`, yet I can't for the life of me figure out how to get this working. I understand that I'll need to update the location of the `src` files, and then the various configuration files in the gulp directory, but it feels like I can't quite get the right combination of configuration.

Is it possible to get a helping hand, or some guidance in the right direction?

**Comment by Swiip** [comment]
I have an app deployed under a context right now using the generator. The context or sub path is simply an alias in the HTTP serveur.

In dev, I keep the app in the root context only being very cautious that I have all my links in relative and all is working fine.

But I must admit though, I didn't success to configure browser sync to simulate the context sub path in dev.

**Comment by snikch** [comment]
Thanks for the response. It was the links to bower_components that I was finding hard to configure in dev. I know it's kind of an anti pattern, but I was trying to serve files through my own Go server to provide some consistency with the final URL structure & setup but I think after all this I might just have to try simplifying things a little bit.

Cheers
