### ISSUE TITLE
"bower-like" for npm ?

### ISSUE THREAD

**Issue by jmls** [Swiip/generator-gulp-angular#812]
Does anyone know of a gulp plugin that is similar to bower-main-files, but for node_modules ? More and more client/front-end packages are becoming available for installation via npm, and I would like to be able to use npm in the build process

I know that there is a bower plugin for local file system, but that means having to manually hack the bower.json file, and it doesn't support scopes (@namespace/packagename)

**Comment by gaboesquivel** [comment]
I'd use browserify for javascript and sass @import for css see  [postcss/postcss-import](https://github.com/postcss/postcss-import)

**Comment by jmls** [comment]
yeah, I was looking @ browserify : can it be run in conjunction with wiredep/bower, or is it a complete conversion ? Does gulp-angular support browserify ?

**Comment by gaboesquivel** [comment]
that's not how it works, in both browserify and webpack you get one final javascript file you include in your html. That file is composed of everything you required in your javascript files. You don't need  wiredep.

**Comment by gaboesquivel** [comment]
Checkout http://bit.ly/1Mwo70R OSCON 2014: How Instagram.com Works; Pete Hunt

**Comment by Swiip** [comment]
I perfectly see what you're looking for. I wondered if it was possible to split two options for the generator: dependency management bower/npm and commonjs yes/no which led to considering npm without commonjs.

The anwser is that I never found something like wiredep for npm. Simply everyone which use npm as dependency management also you commonjs and a bundler.
