### ISSUE TITLE
Start new App: problem to serve assets (css and javascript) with gulp

### ISSUE THREAD

**Issue by valeriosillari** [Swiip/generator-gulp-angular#813]
Probably it is a very simple question, but I have not so much experience with Gulp and with Yeoman Generators.

So I install Yeoman, all the dependencies (npm packages), the angular-gulp generator, everything is ok and I see the index page with all the scaffolding files.

I also run gulp and gulp watch to run the assets, no errors.

On my local machine I see the index page, but no css and no javascipts are served / loaded.

I guess I need to run some extra CLI commands or edit the index page commented code, like:

this for css I guess:
```
    <!-- build:css({.tmp/serve,src}) styles/vendor.css -->
    <!-- bower:css -->
    <!-- run `gulp inject` to automatically populate bower styles dependencies -->
    <!-- endbower -->
    <!-- endbuild -->

    <!-- build:css({.tmp/serve,src}) styles/app.css -->
    <!-- inject:css -->
    <!-- css files will be automatically insert here -->
    <!-- endinject -->
    <!-- endbuild -->
```

and this for javascript I guess:
```
    <!-- build:js(src) scripts/vendor.js -->
    <!-- bower:js -->
    <!-- run `gulp inject` to automatically populate bower script dependencies -->
    <!-- endbower -->
    <!-- endbuild -->

    <!-- build:js({.tmp/serve,.tmp/partials}) scripts/app.js -->
    <!-- inject:js -->
    <!-- js files will be automatically insert here -->
    <!-- endinject -->

    <!-- inject:partials -->
    <!-- angular templates will be automatically converted in js and inserted here -->
    <!-- endinject -->
    <!-- endbuild -->
```

any suggestions?

thanks :)

**Comment by dmastag** [comment]
The result of gulp watch will be in the generated .tmp folder.
To see it in action try to run gulp serve

**Comment by valeriosillari** [comment]
yep it seems working. thanks! :)

**Comment by dmastag** [comment]
Sure thing :)
