### ISSUE TITLE
[Question] Cordova integration

### ISSUE THREAD

**Issue by juan-manuel-alberro** [Swiip/generator-gulp-angular#814]
Hi there,

There's some plans in the (near?) future to add Cordova into this generator? 
Adding the possibility to create _natives_ apps using this generator will be awesome ☺

**Comment by busches** [comment]
There are quite a few generators for Cordova/Ionic already - http://yeoman.io/generators/

**Comment by zckrs** [comment]
Actually include Cordova or Ionic in this generator is not planned. 
Sorry @juan-manuel-alberro  but awesome PR are welcome. 

ping @mvidailhet https://github.com/Swiip/generator-gulp-angular/issues/690#issuecomment-125593981

**Comment by mvidailhet** [comment]
The app generated should work as is when included in a cordova project. Just change the "dist" folder to "www" and you're good to go!
