### ISSUE TITLE
generate bower.json

### ISSUE THREAD

**Issue by jmls** [Swiip/generator-gulp-angular#815]
When I build using serve:dist, I want to be able to make the "app" that I am developing a module that can be published to bower - how would I go about creating a bower.json file that has an appropriate "main" property, and also how would I be able to tell the user which app-xxxx to use ?

thanks

**Comment by Swiip** [comment]
Sorry but the build process is absolutely not designed for this type of use. Creating a front end lib has a lot of different needs than an end user app. If you want to adapt it, you'll have quite a bit of changes to do.

To be a bit more precise, I think you should remove the rev thing as having your lib filename changing si not what you want.
