### ISSUE TITLE
Angular binding issue

### ISSUE THREAD

**Issue by zhouhao27** [Swiip/generator-gulp-angular#819]
I'm using parse.com javascript sdk to get data. Here is my controller:

    (function() {
        'use strict';

      angular
        .module('parseCms')
        .controller('BlogController', BlogController);

      /** @ngInject */
      function BlogController() {

      	var vm = this;
        vm.posts = [];

        init();    

        function init() {    	
      		Parse.initialize("xxxxx", "xxxxx");  	
    		  reload();  		
        }

        function reload() {

      		// define Blog object
      		var Post = Parse.Object.extend('Post');

      		var query = new Parse.Query(Post);
      		query.find({
      			success: function(results) {
      				for (var i = 0; i < results.length; i++) {
      		      		var object = results[i];	      		
      		      		var post = {
      		      			"id" : object.id,
      		      			"title" : object.get('title'),
      		      			"content" : object.get('content')	
      		      		};
      		      		vm.posts.push(post);
      		      		console.log(post);
      		    	}							
      			},
      			error: function(error) {
      				console.log(error);
      			}
      		});
        }
      }
    })();

And my html:

        <div class="row">
          <div class="col-sm-8 blog-main">          
            <div class="blog-post" ng-repeat="post in blog.posts">
              <h2 class="blog-post-title">{{post.title}}</h2>
              <div ng-bind-html="post.content"></div>
              {{post.content}}            
            </div>
          </div>
        </div>

The problem is the ng-repeat shows nothing until I reload in Browsersync although the console.log did print the correct value.

By the way, another issue is ng-bind-html doesn't work either. Can anybody tell what's wrong in my code? Thanks

**Comment by dmastag** [comment]
Do you see anything in this line of code?
`
 console.log(post);
`

**Comment by zhouhao27** [comment]
Yes. It shows correct value. But the browser sees nothing.

**Comment by dmastag** [comment]
Could it be that you are calling reload() before Parse has finished initializing?
I usually put the Parse Init in the runblock (index.run.js)
Not sure if that is the problem though

But anyway, do you think this issue has anything to do with this generator?
If you run it in a brand new angular app than it is working as expected?

**Comment by zhouhao27** [comment]
I think it could be related to the generator because I run a similar project in grunt angular without any problem.Maybe related to the auto injection? I got a warning:

> 'Parse' is not defined.

Although Parse did get the correct value for me. 

The strange thing is when I click "Reload All" button in BrowserSync, my browser works correctly. Anyway I'll try your suggestion. Thanks.

**Comment by zhouhao27** [comment]
Sorry, my mistake. My another app is a bit different. The problem has nothing to do with the generator. Please refer to: http://tumba.solutions/blog/angularjs-and-parse
