### ISSUE TITLE
jquery should not be injected in build when using jqLite

### ISSUE THREAD

**Issue by abhishekisnot** [Swiip/generator-gulp-angular#82]
Current Behavior:
1. in new directory - yo gulp-angular
2. answer 'None' to the jquery/zepto prompt -- angular should now work with jqLite
3. answer 'Bootstrap' to the UI framework prompt and 'Sass (Ruby)' to the CSS preprocessor prompt -- this will bring in 'bootstrap-sass-official'
5. run gulp and check &lt;app>/src/index.html and &lt;app>/dist/scripts/vendor-*.js -- jquery is injected in both files.

Expected Behavior:
At Step 5 -- jquery should not be injected in those files -- because I answered 'none' to jquery/zepto prompt.

I guess wiredep should ignore jquery as it does for bootstrap-saas js plugin files.

generator-angular has similar issue - https://github.com/yeoman/generator-angular/issues/538 filed for bootstrap-saas-official package.

**Comment by raphox** [comment]
https://github.com/Swiip/generator-gulp-angular/issues/690#issuecomment-143060296
