### ISSUE TITLE
How to use ocLazyLoad on production? 

### ISSUE THREAD

**Issue by datnq201088** [Swiip/generator-gulp-angular#820]
I want to use `ocLazyLoad`, but I see in production code not split as Webpack. There are only 2 files js. How to use `ocLazyLoad`?

**Comment by Swiip** [comment]
You should look at webpack options http://webpack.github.io/docs/code-splitting.html. But it's not something shipped by default in the generator.

**Comment by datnq201088** [comment]
Thank you
