### ISSUE TITLE
RubySass Error in plugin

### ISSUE THREAD

**Issue by codeofsumit** [Swiip/generator-gulp-angular#821]
No idea what changed but after updating to El Capitan, i get this error when editing a file after `gulp serve`.

```
[16:12:00] [RubySass] Error in plugin 'gulp-ruby-sass'
Message:
    spawn sass ENOENT
Details:
    code: ENOENT
    errno: ENOENT
    syscall: spawn sass
    path: sass
[16:12:00] Finished 'styles' after 56 ms

```

Any idea what might have changed?

**Comment by busches** [comment]
Check out this issue for sass - https://github.com/sass/sass/issues/1768

**Comment by codeofsumit** [comment]
Thank you!
This: `sudo gem install -n /usr/local/bin sass` fixed it.
