### ISSUE TITLE
Build does not load.

### ISSUE THREAD

**Issue by saaqibz** [Swiip/generator-gulp-angular#822]
I created a gulp-angular scaffold using the default options except I selected ES6 babel.
I then ran gulp serve.

It opened up chrome with a blank page. in the developer console I received the following error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to:
Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.7/$injector/strictdi?p0=function(%24provide)
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at Function.annotate [as $$annotate] (http://localhost:3000/bower_components/angular/angular.js:3747:17)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4456:36)
    at runInvokeQueue (http://localhost:3000/bower_components/angular/angular.js:4384:35)
    at http://localhost:3000/bower_components/angular/angular.js:4393:11
    at forEach (http://localhost:3000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4374:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4299:11)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1657:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1678:12)
http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=ng&p1=Error%3A%20%5…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1678%3A12)

Any idea what's going on?

![screen shot 2015-10-01 at 1 31 14 pm](https://cloud.githubusercontent.com/assets/2548078/10230032/bb58e3c8-6840-11e5-9baf-9b99cdd84123.png)

UPDATE:
Strangely enough it works on firefox.

**Comment by 0101adm** [comment]
its because of ng-strict-di on your ng-app element.  i believe i just removed it and will investigate later.

**Comment by Swiip** [comment]
ng-strict-di is active by default (https://docs.angularjs.org/api/ng/directive/ngApp). ng-annotate is present too to resolve this problem but with Babel, you have to put explicit comments `/* @ngInject */` on top or `'ngInject'` inside.

I tested the blank generated project and it's working with Babel so I imagine it's on your code.

**Comment by saaqibz** [comment]
Thanks for investigating. 

@0101adm I think removing strict di works. Read the manual but not sure what it's saying that it does. Does it just make debugging easier and make sure you're using ngAnnotate? I'm probably going to end up removing it anyway because some dependencies seem to give this same error.

@Swiip When I produced this error, I did not add any code I just ran as is 'blank generated project', do you know if there's anything else I should check on my machine to confirm that we have a similar setup? (Running OSX Yosemite / Chrome).  Did you get it to work on chrome?

What's funny is that it works on Firefox just fine. I filed a bug report to google but haven't heard back. Maybe it's something their side.

**Comment by Swiip** [comment]
Could you build such a blank project and publish it on github because I simply not reproduce the problem. All injections are fine for me.

**Comment by saaqibz** [comment]
Hey Matthieu,

Here is the repo you requested: https://github.com/saaqibz/gulp-angular-gen-error
I also compiled a video of how I produced it.
(OSX-Yosemite, 2014 Macbook Pro)

https://youtu.be/yCt5OHEMyg8

**Comment by Swiip** [comment]
oO Your project is fine for me, Chrome & FF on Mac. Still I could see it's not working for you. I don't get what could possibly be different only on your Chrome :/

**Comment by saaqibz** [comment]
Thanks for giving it a look. I think I'll just use the es5 version for now.
