### ISSUE TITLE
UI-router substates and loading css

### ISSUE THREAD

**Issue by rwwagner90** [Swiip/generator-gulp-angular#823]
I have a `groups.list` state, and when I'm in the substate, my index.css will not load, when running `gulp serve`. When I refresh the page, all the styles go away because it cannot find the style.

It tries to append the state to the url for the css: `http://demo.lvh.me/groups/app/index.css `

How do I fix this?

**Comment by rwwagner90** [comment]
It looks like this is the issue: `addRootSlash: false`.

I just made it `addRootSlash: true` and refreshing the page seems to no longer break styles. Is there a reason it was set to false in the first place?

**Comment by Swiip** [comment]
It's seems to be a problem with html5mode, ui router, and css loading. What could we do at the generator level?

**Comment by rwwagner90** [comment]
@Swiip please look at the comment I posted. It works when I change addRootSlash to true. Could you please tell me why it was set to false?

**Comment by zckrs** [comment]
In our sample app we use relative path to get file

**Comment by rwwagner90** [comment]
@Swiip @zckrs it seems like this may be a ui-router and generator issue. The behavior of each needs to line up. UI-router seems to think that prepending state urls to relative paths is what is supposed to happen. I will open an issue on UI-router and check back in here.

**Comment by Swiip** [comment]
Sorry but all of this make any sense to us. Please complete you issues with all needed informations https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md.

At least, tell us if you use html5mode for urls? If not, if there is a `#` in your URL I can't see how ui router could impact your relative paths.

**Comment by rwwagner90** [comment]
We are using html5mode. For example, we have a state `campaigns` and it's trying to load `https://demo.lvh.me/campaigns/bower_components/font-awesome/css/font-awesome.css`. It's incorrectly adding campaigns into the path for the css assets.

**Comment by hardywu** [comment]
@rwwagner90 I found the solution without change any configurations.
taptapship/wiredep#74

**Comment by rwwagner90** [comment]
Ahhh, I had my base href set at the bottom of `<head>`, and moving it to the top does seem to fix the issues. Thanks @hardywu!
