### ISSUE TITLE
ngResource doesn't include in project

### ISSUE THREAD

**Issue by rulir** [Swiip/generator-gulp-angular#825]
I've used "bower install --save angular-resource" and i'ts successfully writes in my "bower.json", but in "index.html" ng-resource doesn't include when I use "gulp build".
In my ".yo-rc.json" was : 
```
      "resource": {
        "key": "none",
        "module": null
      }
```
I've tried to : 
```
      "resource": {
        "key": "angular-resource",
        "module": "ngResource"
      }
```
but nothing happend.

**Comment by Swiip** [comment]
This has nothing to do with `.yo-rc.json`. It should work with `bower install --save`. It's wiredep which should inject the script in your `index.html`.

Run `gulp inject` and check your `.tmp/serve/index.html` to see if the angular resource script is added.
