### ISSUE TITLE
typescript project error

### ISSUE THREAD

**Issue by gimox** [Swiip/generator-gulp-angular#826]
gulp serve not load project with typescript

System: Mac osx 

- angular 1.4
- all angular modules
- sass with node
- $http
- typescript
```
ERROR in ./src/app/index.module.ts
Module build failed: Error: ENOENT: no such file or directory, open '/Users/gx/Development/shout/.tmp/typings/tsd.d.ts'
    at Error (native)
```

without typescript all ok.

**Comment by zckrs** [comment]
You should have error at end of generator. Do you have TSD installed globally ?

**Comment by gimox** [comment]
Yes it a installed globally.
The error appear when i starti the gulp serve. It finish the task with errors and app not Work

**Comment by gimox** [comment]
after some try, uninstalling, removing with npm typescript and tsd, now i have the same error in my two macs:

ERROR in ./src/app/index.module.ts
Module build failed: Error: ENOENT, open '/Users/gimox/Development/tps/.tmp/typings/jquery/jquery.d.ts'
    at Error (native)

**Comment by 0101adm** [comment]
@gimox you'll have to install tsd then run 

tsd install jquery

**Comment by gimox** [comment]
I installed tsd  globally but not work.

**Comment by 0101adm** [comment]
@gimox  try by installing locally.

**Comment by gimox** [comment]
not working, tsd installed locally and globally!

**Comment by gimox** [comment]
create a new project and added jquery as dependency. It work.
I think this is a bug, jquery is in my bower dependency but i don't need it.

**Comment by zckrs** [comment]
Check current open PR before open issue.
https://github.com/Swiip/generator-gulp-angular/pull/824
