### ISSUE TITLE
a root slash is needed in the injected href link

### ISSUE THREAD

**Issue by hardywu** [Swiip/generator-gulp-angular#831]
```html
    <link rel="stylesheet" href="../bower_components/angular-material/angular-material.css" />
    ...
    <link rel="stylesheet" href="app/index.css">
```
need a  root slash
```html
    <link rel="stylesheet" href="/../bower_components/angular-material/angular-material.css" />
    ...
    <link rel="stylesheet" href="/app/index.css">
```

**Comment by zckrs** [comment]
Why ?

**Comment by Swiip** [comment]
In addition, this will fail if you deploy in a sub context. I got the case in a project right now and certainly not want a root slash.

**Comment by hardywu** [comment]
The browser will not be able to find the css files if the accessing address is something like `http://localhost:3000/posts/32`.

**Comment by hardywu** [comment]
Oops. It seems to be a duplicate issue with  #823 .

**Comment by rwwagner90** [comment]
@hardywu I'm having issues with this as well. Please add to the discussion over at #823 :smile:
