### ISSUE TITLE
Typescript : Duplicate identifier 'moment'

### ISSUE THREAD

**Issue by vaubrun13** [Swiip/generator-gulp-angular#833]
After a fresh install of nodejs (v4.1.2) i can't run the generated app with gulp serve, I got the following error 

    [20:14:08] Starting 'scripts'...
    xxxxxxx/.tmp/typings/moment/moment-node.d.ts(6,16): error TS2300: Duplicate identifier 'moment'.
    [20:14:10] [TypeScript] TypeScript error: xxxxx/.tmp/typings/moment/moment-node.d.ts(6,16): error TS2300: Duplicate identifier 'moment'.
    xxxx/.tmp/typings/moment/moment.d.ts(8,13): error TS2300: Duplicate identifier 'moment'.
    [20:14:10] [TypeScript] TypeScript error: xxxx/.tmp/typings/moment/moment.d.ts(8,13): error TS2300: Duplicate identifier 'moment'.
    src/app/index.module.ts(16,13): error TS2300: Duplicate identifier 'moment'.
    [20:14:10] [TypeScript] TypeScript error: src/app/index.module.ts(16,13): error TS2300: Duplicate identifier 'moment'.
    [20:14:10] TypeScript: 3 semantic errors
    [20:14:10] TypeScript: emit succeeded (with errors)
    [20:14:10] Finished 'scripts' after 2.13 s

I am running the v0.12.1 of the generator on an Ubuntu 15.04 pc, my yo-rc.json:

    {
      "generator-gulp-angular": {
        "version": "0.12.1",
        "props": {
          "angularVersion": "~1.4.0",
          "angularModules": [
            {
              "key": "animate",
              "module": "ngAnimate"
            },
            {
              "key": "cookies",
              "module": "ngCookies"
            },
            {
              "key": "touch",
              "module": "ngTouch"
            },
            {
              "key": "sanitize",
              "module": "ngSanitize"
            }
          ],
          "jQuery": {
            "key": "jquery2"
          },
          "resource": {
            "key": "restangular",
            "module": "restangular"
          },
          "router": {
            "key": "ui-router",
            "module": "ui.router"
          },
          "ui": {
            "key": "bootstrap",
            "module": null
          },
          "bootstrapComponents": {
            "key": "ui-bootstrap",
            "module": "ui.bootstrap"
          },
          "cssPreprocessor": {
            "key": "node-sass",
            "extension": "scss"
          },
          "jsPreprocessor": {
            "key": "typescript",
            "extension": "ts",
            "srcExtension": "ts"
          },
          "htmlPreprocessor": {
            "key": "none",
            "extension": "html"
          },
          "foundationComponents": {
            "name": null,
            "version": null,
            "key": null,
            "module": null
          },
          "paths": {
            "src": "src",
            "dist": "dist",
            "e2e": "e2e",
            "tmp": ".tmp"
          }
        }
      }
    }

**Comment by nickroberts** [comment]
The issue started when the `moment-node.d.ts` file in the Definitely Typed repo. If you change the `ref` property to `1.4.1` in `tsd.json` the application will compile correctly. I'm not sure if we should enter an issue in the Definitely Typed repo, or not. This could just be something that is an issue with this generator, as the `moment` bower component, along with the `moment-node` package are both being installed.

`tsd.json`
```
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "1.4.1",
  "path": ".tmp/typings",
  "bundle": ".tmp/typings/tsd.d.ts"
}
```

**Comment by vaubrun13** [comment]
Indeed when changing the ref version it works like a charm

**Comment by NathanWalker** [comment]
This is the most frustrating issue with Typescript... duplicate identifier... urgh.
