### ISSUE TITLE
Watch not catching new SCSS files

### ISSUE THREAD

**Issue by jordond** [Swiip/generator-gulp-angular#838]
Hello,

When I run `gulp watch` and then create a new stylesheet (.scss) and save it, gulp will detect this change and do its thing, and works perfectly.

However when I run `gulp serve` it doesn't detect new stylesheets, but will detect changes to existing stylesheets, which requires me to stop gulp and restart it for it to notice it.

New .html, and .js files are detected, it just seems to be the .scss files.

I have updated to the latest version of this generator, and it still doesn't work.

**Comment by intellix** [comment]
I believe this is a problem with gulp < 4 and will be fixed in gulp 4

**Comment by Swiip** [comment]
Yep, not exactly the same symptoms, but can you check it's not the known problem describe in the warning here: https://github.com/Swiip/generator-gulp-angular/blob/master/docs/user-guide.md#file-watching--pre-processing

**Comment by jordond** [comment]
Oh I didn't see that, I should have looked a bit harder. Thanks!
