### ISSUE TITLE
Failing build with TypeScript on Windows

### ISSUE THREAD

**Issue by lukasholcik** [Swiip/generator-gulp-angular#846]
Hi there,
I created a new project using gulp-angular.

Settings:

    Angular 1.4
    TypeScript
    Bootstrap
    AngularUI
    LESS

And this is the error I'm getting in `gulp scripts`:

    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/components/malarkey/malarkey.directive.ts:1:34
    Cannot find module '../githubContributor/githubContributor.service'.
    
    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/index.module.ts:3:23
    Cannot find module './index.config'.
    
    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/index.module.ts:4:29
    Cannot find module './index.route'.
    
    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/index.module.ts:5:25
    Cannot find module './index.run'.
    
    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/index.module.ts:6:31
    Cannot find module './main/main.controller'.
    
    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/index.module.ts:7:34
    Cannot find module '../app/components/githubContributor/githubContributor.service'.
    
    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/index.module.ts:8:33
    Cannot find module '../app/components/webDevTec/webDevTec.service'.
    
    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/index.module.ts:9:27
    Cannot find module '../app/components/navbar/navbar.directive'.
    
    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/index.module.ts:10:29
    Cannot find module '../app/components/malarkey/malarkey.directive'.
    
    ERROR in [default] c:/devel/my/gulp-sandbox2/src/app/main/main.controller.ts:1:44
    Cannot find module '../components/webDevTec/webDevTec.service'.

This is the version listing from npm:

    gulpSandbox2@0.0.0 c:\devel\my\gulp-sandbox2
    ├── awesome-typescript-loader@0.14.0
    ├── browser-sync@2.9.11
    ├── browser-sync-spa@1.0.3
    ├── chalk@1.1.1
    ├── del@2.0.2
    ├── eslint-plugin-angular@0.12.0
    ├── estraverse@4.1.0
    ├── gulp@3.9.0
    ├── gulp-angular-templatecache@1.8.0
    ├── gulp-autoprefixer@3.0.2
    ├── gulp-eslint@1.0.0
    ├── gulp-filter@3.0.1
    ├── gulp-flatten@0.2.0
    ├── gulp-inject@3.0.0
    ├── gulp-less@3.0.3
    ├── gulp-load-plugins@0.10.0
    ├── gulp-minify-css@1.2.1
    ├── gulp-minify-html@1.0.4
    ├── gulp-protractor@1.0.0
    ├── gulp-rename@1.2.2
    ├── gulp-replace@0.5.4
    ├── gulp-rev@6.0.1
    ├── gulp-rev-replace@0.4.2
    ├── gulp-size@2.0.0
    ├── gulp-sourcemaps@1.6.0
    ├── gulp-uglify@1.4.2
    ├── gulp-useref@1.3.0
    ├── gulp-util@3.0.6
    ├── http-proxy-middleware@0.9.0
    ├── jasmine-core@2.3.4
    ├── karma@0.13.11
    ├── karma-coverage@0.5.2
    ├── karma-jasmine@0.3.6
    ├── karma-ng-html2js-preprocessor@0.2.0
    ├── karma-phantomjs-launcher@0.2.1
    ├── lodash@3.10.1
    ├── main-bower-files@2.9.0
    ├── ng-annotate-loader@0.0.10
    ├── phantomjs@1.9.18
    ├── tsd@0.6.5
    ├── tslint-loader@1.0.2
    ├── typescript@1.6.2
    ├── uglify-save-license@0.4.1
    ├── webpack-stream@2.1.1
    ├── wiredep@2.2.2
    └── wrench@1.5.8

.yo-rc

    {
      "generator-gulp-angular": {
        "version": "1.0.0",
        "props": {
          "angularVersion": "~1.4.2",
          "angularModules": [
            {
              "key": "animate",
              "module": "ngAnimate"
            },
            {
              "key": "cookies",
              "module": "ngCookies"
            },
            {
              "key": "touch",
              "module": "ngTouch"
            },
            {
              "key": "sanitize",
              "module": "ngSanitize"
            },
            {
              "key": "messages",
              "module": "ngMessages"
            },
            {
              "key": "aria",
              "module": "ngAria"
            }
          ],
          "jQuery": {
            "key": "jquery2"
          },
          "resource": {
            "key": "restangular",
            "module": "restangular"
          },
          "router": {
            "key": "ui-router",
            "module": "ui.router"
          },
          "ui": {
            "key": "bootstrap",
            "module": null
          },
          "bootstrapComponents": {
            "key": "ui-bootstrap",
            "module": "ui.bootstrap"
          },
          "cssPreprocessor": {
            "key": "less",
            "extension": "less"
          },
          "jsPreprocessor": {
            "key": "typescript",
            "extension": "ts",
            "srcExtension": "ts"
          },
          "htmlPreprocessor": {
            "key": "noHtmlPrepro",
            "extension": "html"
          },
          "foundationComponents": {
            "name": null,
            "version": null,
            "key": null,
            "module": null
          },
          "paths": {
            "src": "src",
            "dist": "dist",
            "e2e": "e2e",
            "tmp": ".tmp"
          }
        }
      }
    }

Thanks for having a look at this...
Lukas

**Comment by zckrs** [comment]
Windows + Typescript (tsd) I am not sure that works because Windows use `\` instead of `/` for path

**Comment by Swiip** [comment]
That's a shame for a MS tech ^^ (sorry I know, not helpful)

**Comment by lukasholcik** [comment]
So I checked on Linux and it works ... Do you think this is the issue of the awesome-typescript-loader? I have another project (without webpack) and typescript with es6 modules compiles fine using just tsc...

**Comment by mattxo** [comment]
+1

Any workarounds for Windows users?

**Comment by 0101adm** [comment]
yep. typescript@1.5.3 resolves this.

**Comment by lukasholcik** [comment]
So I changed the version to 1.5.3 and it helped for a while.
Then I tried to created a transitive import reference:

    // index.module.ts
    import * as transitive from "./transitive/a";

    // transitive/a.ts
    export * from "./b";

    // transitive/b.ts
    let b = 1;
    export default b;

... and here we go again ...

    ERROR in [default] C:/devel/my/gulp-sandbox2/src/app/transitive/a.ts:1:14 
    Cannot find module './b'.

I'm only having trouble with webpack+typescript, really can't make it work on Windows.

**Comment by 0101adm** [comment]
instead of ./

try a full path 'app/components/mycomponent/transitive/a'

or

'../mycomponent/transtive/a'

**Comment by lukasholcik** [comment]
@0101adm : thanks for advice, but it doesn't work either...

**Comment by 0101adm** [comment]
a.ts should read...

```javascript
import * from './b'
```

**Comment by jbrantly** [comment]
It sounds to me a lot like webpack isn't configured to resolve certain extensions, either `.ts` or maybe `.js`. You should look at your webpack config and make sure `resolve.extensions` is set to something like `['', '.ts', '.js']`. [I noticed by default it doesn't include `.js`.](https://github.com/Swiip/generator-gulp-angular/blob/2b615bdd74f6b2e68f52cd9c675e52797cf76cd8/app/templates/gulp/_scripts.js#L37)

**Comment by lukasholcik** [comment]
@0101adm So doing `import * as b from './b'; export default b;` works here. I expected the direct export to work as I've seen it in angular2 sources (https://github.com/angular/angular/blob/master/modules/angular2/angular2.ts).

@jbrantly: this seems to be fine, but I left this idea of using webpack-stream and currently I'm trying just webpack with your ts-loader and everything is just rainbows and unicorns ... so I hope it will be like this all the time:).

**Comment by mattxo** [comment]
`npm update awesome-typescript-loader` has resolved the issue for me for typescript 1.6

**Comment by lukasholcik** [comment]
@mattxo Yes, I can confirm this. The 0.14.1 update fixed it.
