### ISSUE TITLE
Generated project not actually using ng-annotate

### ISSUE THREAD

**Issue by dstroyrofworlds** [Swiip/generator-gulp-angular#847]
I generated a project and added some jade files and javascript.

When dist'ing the project
```javascript
gulp serve:dist
```
The console gives this error:
> Error: [$injector:unpr] Unknown provider: eProvider <- e

This is because the ng-annotate did not run even though it is included in the package.json.

I see the gulp files do load:
```javascript
var $ = require('gulp-load-plugins')();
```

but cannot see that gulp-ng-annotate is actually used anywhere.

All code I added do have the 
```javascript
'ngInect';
```
annotation added.

Or am I missing something ?

**Comment by dstroyrofworlds** [comment]
Just created a new project with the generator.
The minimization works for the "just" generated project.

Not sure what went wrong in my changes.

**Comment by Swiip** [comment]
You don't mentions your options. With webpack (ES6 & TS), ng-annotate is used as a webpack loader.
