### ISSUE TITLE
Change url and port of gulp serve

### ISSUE THREAD

**Issue by mpgn** [Swiip/generator-gulp-angular#848]
How can i change the default url and port of the commande `gulp serve` ?
```
[BS] [BrowserSync SPA] Running...
[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:3000/
    External: http://10.145.243.244:3000/
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://10.145.243.244:3001
 ----------------------------------------
[BS] Serving files from: .tmp/serve
[BS] Serving files from: src
```
I want to put my custom vhost like http://project.dev:80

**Comment by mkalpana** [comment]
For changing the default url and port you will have to change the `gulp\server.js` file.

The steps to change the default port is mentioned here:

https://github.com/Swiip/generator-gulp-angular/blob/master/docs/how-it-works.md#browser-sync-configuration

For default url, I think you need to remove the server property and add the proxy property in browserSync.init. The details are specified in http://www.browsersync.io/docs/options/#option-proxy

I tried to change the default port and it works. I haven't tried the proxy option though. Let me know how it goes.

**Comment by nanocom** [comment]
the proxy property is not made for that.
for project.dev:80 to redirect to localhost you can just add a line in your /etc/hosts file

**Comment by Swiip** [comment]
As @nanocom said, you can't ask to BrowserSync to serve on a specific url. If you want to address BS with a specific URL you have to touch your `/etc/hosts`. For the port it's different, you have a parameter in BS conf as documented.

**Comment by mpgn** [comment]
thx :)
