### ISSUE TITLE
How to turn off this trash

### ISSUE THREAD

**Issue by e-oz** [Swiip/generator-gulp-angular#852]
How to turn off this crap?
The Step1 controller should follow this pattern: /[A-Z].*Controller$/          angular/controller-name

**Comment by e-oz** [comment]
found: in gulp/scripts.js remove preLoaders line.
really annoying when some trash trying to teach me how to name my files. Go to hell with such recommendations.

**Comment by alfaproject** [comment]
I don't even.

**Comment by e-oz** [comment]
Very useful comment, man. Keep going.

**Comment by Swiip** [comment]
Seriously @e-oz, you crossed a line. Be nicer here please. Fill good issues or just don't.

**Comment by e-oz** [comment]
After release 1.0 this generator turned in a total trash. I spend a lot of
time (including reading of your documentation) to find that
"index.modules.js" is a mandatory file, not optional. And tones of bold red
errors which are just recommendations - it's too much. We have namespaces
so we don't need "Controller" suffix, somebody have "Ctrl" suffix
convention, but you only recommend longest version without option to turn
it off. Too "opinionated" - you, as you say, crossed a line. I deeply
regret I started so many projects with this generator and also regret I
recommended it in my blog articles, G+ and Twitter posts.
I was nice while this generator was nice.

**Comment by Swiip** [comment]
You don't have to be nice only if you like the project. If you don't like it, just stop using it.
