### ISSUE TITLE
No template on production mode

### ISSUE THREAD

**Issue by AlexVKO** [Swiip/generator-gulp-angular#854]
Hi,
I finished my project, but before gulp build, and serve:dist is fired, it display no template... and no errors on chrome console... =S

my set:
Version 1.0
angular 4.1.7
SASS
only html
only javascript

any ideia?

Thank you

**Comment by tiagomelilo** [comment]
AlexVKO, I have this same problem in my project.

Any help?

Thanks!

**Comment by zckrs** [comment]
Post your `.yo-rc.json`

**Comment by Swiip** [comment]
This kind of problem is usually a problem with the relative paths of partials preloaded in angular cache for optimization.

The debugging process is to turn of uglify and look in the bundle the address of the preloaded partials and compare them to the actual partial url needed, you should find a difference.

In the generic case, it works out of the box but if you have a specific server conf it could fail.

Anyway, I close this as we got no details for your problem.
