### ISSUE TITLE
gulp-autoprefixer

### ISSUE THREAD

**Issue by IvanCoronado** [Swiip/generator-gulp-angular#862]
Can we have some css prefixer like https://www.npmjs.com/package/gulp-autoprefixer ?

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/gulp/_styles.js#L65 already done

**Comment by IvanCoronado** [comment]
Sorry, you are right. I was checking "Features included in the gulpfile" in https://github.com/Swiip/generator-gulp-angular/blob/master/docs/usage.md
