### ISSUE TITLE
ReferenceError: asyncCallback is not defined

### ISSUE THREAD

**Issue by dzonatan** [Swiip/generator-gulp-angular#866]
Running **gulp serve:dist** leads to _"ReferenceError: asyncCallback is not defined"_ error.

```
[21:44:12] Finished 'serve:dist' after 34 ms
dns.js:61
    if (asyncCallback.immediately) {
        ^

ReferenceError: asyncCallback is not defined
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:61:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
```

I have no idea how it's related but it only occurs when [semantic](https://github.com/Semantic-Org/Semantic-UI) bower package is installed.
To reproduce:
1. Generate clean project
2. run **bower install semantic --save**
3. run **gulp serve:dist**

Can someone comment on this and give any hints where to investigate more?

**Comment by zckrs** [comment]
I think you should open issue in Semantic-UI repo or/and BrowserSync.

I search file `dns.js` in project but not found

**Comment by zckrs** [comment]
More infos can help.

Node version ? NPM version ? `.yo-rc.json` ?

**Comment by zckrs** [comment]
FYI with NodeJS v4 everything works

**Comment by dzonatan** [comment]
Dunno where was the problem but I don't get it anymore... I think It was related with development environment. Anyway, thank you for your time @zckrs
