### ISSUE TITLE
Get rid off gulp-angular-filesort

### ISSUE THREAD

**Issue by konradhalas** [Swiip/generator-gulp-angular#867]
`gulp-angular-filesort` is not supported from February 2015 - it has many not resolved issues, PR's and forks. I suggest to use something more stable.

In my case I encountered with bug described here - https://github.com/klei/gulp-angular-filesort/issues/30.

According to documentation "(...) to work correctly, each angular file needs to have a uniquely named module and setter syntax (with the brackets), i.e. `angular.module('myModule', [])`.". So "getter" syntax (`angular.module('myModule').service(....)`) is not supported right now.

**Comment by zckrs** [comment]
Do you know a other more stable gulp plugin ?

**Comment by konradhalas** [comment]
TBH, no. I made small research but I didn't find anything :(

**Comment by zckrs** [comment]
If nothing exist to replace this plugin this can be close.
