### ISSUE TITLE
Babel + ES6 Test Coverage

### ISSUE THREAD

**Issue by rwwagner90** [Swiip/generator-gulp-angular#868]
I saw a similar issue related to ES6 coverage, but the problem is not solved, and the issue was closed. Using isparta does allow us to run code coverage reports, but the only files in the report are `*.spec.js` files. I believe this is because we have a single `index.module.js` file, rather than loading each controller, service, etc as a separate entity, that would allow isparta to know that the file exists. Do you have a recommendation for getting this to work?

Relates to https://github.com/Swiip/generator-gulp-angular/issues/681

**Comment by rwwagner90** [comment]
I was able to get this working, for the most part. If you guys would like to work with me on getting an official update to the generator, or at least the guide, let me know.

**Comment by zychj1** [comment]
rwwagner90 could You show Your solution?

**Comment by rwwagner90** [comment]
@zychj1 my solution has several parts, but I will try to list it all here for you.

Firstly, I created a test.js file containing the following:

```js
require('angular');
require('angular-mocks');

var testsContext = require.context('./app', true, /\.spec\.js$/);
testsContext.keys().forEach(testsContext);

var moduleContext = require.context('./app', true, /\.module\.js$/);
moduleContext.keys().forEach(moduleContext);
```

Then I had to install a few npm packages:

`npm install karma-coverage --save-dev`
`npm install karma-webpack --save-dev`
`npm install isparta-loader --save-dev`

Then, I had to update my karma.conf.js to work with webpack and the isparta-loader. I will paste the entire contents of the file below:

```js
'use strict';

var path = require('path');
var conf = require('./gulp/conf');

var _ = require('lodash');
var wiredep = require('wiredep');


function listFiles() {
  var wiredepOptions = _.extend({}, conf.wiredep, {
    dependencies: true,
    devDependencies: true
  });

  return wiredep(wiredepOptions).js
    .concat([
      './node_modules/phantomjs-polyfill/bind-polyfill.js',
      path.join(conf.paths.src, '/ngConstants.js'),
      path.join(conf.paths.src, '/test.js')
    ]);
}

module.exports = function (config) {

  var configuration = {
    files: listFiles(),

    singleRun: true,

    autoWatch: false,

    logLevel: config.LOG_INFO, //config.LOG_DEBUG,

    babelPreprocessor: {
      options: {
        sourceMap: 'inline'
      },
      filename: function (file) {
        return file.originalPath.replace(/\.js$/, '.es5.js');
      },
      sourceFileName: function (file) {
        return file.originalPath;
      }
    },

    coverageReporter: {
      reporters: [
        {type: 'html', dir: 'coverage/'},
        {type: 'text'}
      ]
    },

    frameworks: ['jasmine'],

    hostname: 'demo.lvh.me',

    ngHtml2JsPreprocessor: {
      stripPrefix: 'src/',
      moduleName: 'app'
    },

    browsers: [
      'PhantomJS'//,'Chrome'
    ],

    plugins: [
      'karma-babel-preprocessor',
      'karma-chrome-launcher',
      'karma-coverage',
      'karma-phantomjs-launcher',
      'karma-jasmine',
      'karma-ng-html2js-preprocessor',
      'karma-webpack'
    ],

    preprocessors: {
      'src/**/*.html': ['ng-html2js'],
      'src/**/*.spec.js': ['babel'],
      'src/test.js': ['webpack']
    },

    reporters: ['progress', 'coverage'],

    webpack: {
      module: {
        preLoaders: [
          // transpile all files except testing sources with babel as usual
          {
            test: /\.js$/,
            exclude: [
              'src/app/**/*.spec.js',
              path.resolve('node_modules/')
            ],
            loader: 'isparta'
          }
        ]
      }
    }
  };

  // This block is needed to execute Chrome on Travis
  // If you ever plan to use Chrome and Travis, you can keep it
  // If not, you can safely remove it
  // https://github.com/karma-runner/karma/issues/1144#issuecomment-53633076
  if (configuration.browsers[0] === 'Chrome' && process.env.TRAVIS) {
    configuration.customLaunchers = {
      'chrome-travis-ci': {
        base: 'Chrome',
        flags: ['--no-sandbox']
      }
    };
    configuration.browsers = ['chrome-travis-ci'];
  }

  config.set(configuration);
};

```

Finally, I had to update all instances of:

`beforeEach(module('app')` 

in all of the tests, to be: 

`beforeEach(angular.mock.module('app')`.

**Comment by rwwagner90** [comment]
Would this be something you guys would want to add to the generator itself or should we just document this somewhere? Let me know and I'll be glad to work on a PR.

**Comment by vivascau** [comment]
Thanks a lot @rwwagner90 ! Worked like a charm for me.
For future reference, I had to do a couple of changes **in my specific case**:

1. in `test.js` no need for
    
```
require('angular');
require('angular-mocks');
```

2. pass coverageReporter as an object instead of array of objects:

    `coverageReporter: {type: 'html', dir: 'coverage/'}`

Worth mentioning to people who are trying this solution that the `gulp/unit-tests` task definition overrides the reporters and preprocessors that are being set in karma configuration files so some alterations might be needed there too..

**Comment by vivascau** [comment]
Further to this... 
Add 
```
webpackMiddleware: {
      stats: {
        chunks: false,
      }
    }
```

In karma.conf sibling of `webpack` in order to not log to command line all the assets, combine that with `karma-spec` as a reporter and life will be beautiful.

**Comment by handijk** [comment]
The above works, the only thing i had to add was `path.join(conf.paths.tmp, '/partials/templateCacheHtml.js')`.
It still show spec files in my coverage report though, is there any way to filter these out?

**Comment by tomwetjens** [comment]
Also got it working, thanks! The generated coverage report (html) shows a 100% branch coverage (10 of 10) on a file in my project with "4 branches ignored". But when I import the lcov.info into SonarQube, it says I still have "4 uncovered conditions".
I've inspected the lcov.info file and it has 10/10 branches covered, 14/14 lines covered and 10/10 functions covered, but still SonarQube is saying that I have 4 uncovered branches for this file.
Also the line numbers of the functions in lcov.info do not match with the ES6 original source file. Maybe this is also a cause?

Anyone have an idea?

**Comment by Swiip** [comment]
Hi, sorry for the long delay before answering. I also got it working with the same kind of configurations on my personal project.

The problem is that it's a very different approach of the current karma conf in the project.

Putting things together in the generator and handling TypeScript and Traceur options is complicated, handling pure JS and no webpack is also complicated.

I'm not closed to have this, a PR would be great but doing this correctly could be difficult.

**Comment by rwwagner90** [comment]
@Swiip could we get some additions to the docs then perhaps, rather than changing the generator itself?

**Comment by Swiip** [comment]
We should create recipe from all was said hear! Sure!

**Comment by skeep** [comment]
after bable6 , quite a few changes are necessary, have just made it work expect `navbar` component. will soon post the final findings.

**Comment by skeep** [comment]
Let me take a shot at the updated recipe. This recipe will work for `npm v3+` and `bable 6+`

First we need to install all necessary dependencies. Since automatic peer dependency installation do not happen for `npm 3+` we have install all packages.


### Step 1

```bash
npm install karma-coverage karma-webpack isparta-loader karma-spec-reporter phantomjs-polyfill karma-babel-preprocessor karma-chrome-launcher babel-preset-es2015 --save-dev
```

### Step 2 
Change `karma.conf.js`

```javascript
'use strict';

var path = require('path');
var conf = require('./gulp/conf');

var _ = require('lodash');
var wiredep = require('wiredep');
var babelMoreOptions = {presets: 'es2015'};

var pathSrcHtml = [
  path.join(conf.paths.tmp, '/serve/**/*.html'),
  path.join(conf.paths.src, '/**/*.html')
];


function listFiles() {
  var wiredepOptions = _.extend({}, conf.wiredep, {
    dependencies: true,
    devDependencies: true
  });

  var patterns = wiredep(wiredepOptions).js
    .concat([
      './node_modules/phantomjs-polyfill/bind-polyfill.js',
      path.join(conf.paths.src, '/test.js'),
      path.join(conf.paths.tmp, '/partials/templateCacheHtml.js')
    ])
    .concat(pathSrcHtml);

  var files = patterns.map(function (pattern) {
    return {
      pattern: pattern
    };
  });
  files.push({
    pattern: path.join(conf.paths.src, '/assets/**/*'),
    included: false,
    served: true,
    watched: false
  });
  return files;
}

module.exports = function (config) {

  var configuration = {
    files: listFiles(),

    singleRun: true,

    autoWatch: false,

    ngHtml2JsPreprocessor: {
      stripPrefix: 'src/',
      moduleName: 'oei'
    },

    logLevel: config.LOG_DEBUG,

    babelPreprocessor: {
      options: {
        sourceMap: 'inline'
      },
      filename: function (file) {
        return file.originalPath.replace(/\.js$/, '.es5.js');
      },
      sourceFileName: function (file) {
        return file.originalPath;
      }
    },

    frameworks: ['jasmine'],

    browsers: ['PhantomJS'],

    plugins: [
      'karma-babel-preprocessor',
      'karma-chrome-launcher',
      'karma-phantomjs-launcher',
      'karma-coverage',
      'karma-jasmine',
      'karma-ng-html2js-preprocessor',
      'karma-webpack',
      'karma-spec-reporter'
    ],

    //coverageReporter: {type: 'html', dir: 'coverage/'},
    coverageReporter: {
      // configure the reporter to use isparta for JavaScript coverage
      // Only on { "karma-coverage": "douglasduteil/karma-coverage#next" }
      instrumenters: {isparta: require('isparta')},
      instrumenter: {
        '**/*.js': 'isparta'
      },
      instrumenterOptions: {
        isparta: {babel: babelMoreOptions}
      }
    },

    reporters: ['progress', 'coverage'],

    preprocessors: {
      'src/**/*.html': ['ng-html2js'],
      'src/**/*.spec.js': ['babel'],
      'src/test.js': ['webpack']
    },

    webpack: {
      // *optional* babel options: isparta will use it as well as babel-loader
      babel: {
        presets: ['es2015']
      },
      // *optional* isparta options: istanbul behind isparta will use it
      isparta: {
        embedSource: true,
        noAutoWrap: true,
        // these babel options will be passed only to isparta and not to babel-loader
        babel: {
          presets: ['es2015']
        }
      },
      module: {
        preLoaders: [
          // transpile all files except testing sources with babel as usual
          {
            test: /\.js$/,
            exclude: [
              'src/app/**/*.spec.js',
              path.resolve('node_modules/')
            ],
            loader: 'isparta'
          }
        ]
      },
      webpackMiddleware: {
        stats: {
          chunks: false
        }
      }
    },

    proxies: {
      '/assets/': path.join('/base/', conf.paths.src, '/assets/')
    }
  };

  // This block is needed to execute Chrome on Travis
  // If you ever plan to use Chrome and Travis, you can keep it
  // If not, you can safely remove it
  // https://github.com/karma-runner/karma/issues/1144#issuecomment-53633076
  if (configuration.browsers[0] === 'Chrome' && process.env.TRAVIS) {
    configuration.customLaunchers = {
      'chrome-travis-ci': {
        base: 'Chrome',
        flags: ['--no-sandbox']
      }
    };
    configuration.browsers = ['chrome-travis-ci'];
  }

  config.set(configuration);
};
```

### Step 3
Change `gulp/unit-tests.js`

```javascript
'use strict';

var path = require('path');
var gulp = require('gulp');
var conf = require('./conf');

var karma = require('karma');

function runTests(singleRun, done) {

  var localConfig = {
    configFile: path.join(__dirname, '/../karma.conf.js'),
    singleRun: singleRun,
    autoWatch: !singleRun
  };

  var server = new karma.Server(localConfig, function (failCount) {
    done(failCount ? new Error("Failed " + failCount + " tests.") : null);
  });
  server.start();
}

gulp.task('test', ['scripts:test', 'markups'], function (done) {
  runTests(true, done);
});

gulp.task('test:auto', ['scripts:test-watch'], function (done) {
  runTests(false, done);
});
```

### Step 4

Add `src/test.js`

```javascript
var moduleContext = require.context('./app', true, /\.module\.js$/);
moduleContext.keys().forEach(moduleContext);

var testsContext = require.context('./app', true, /\.spec\.js$/);
testsContext.keys().forEach(testsContext);
```

### Step 5

Run `gulp test`

**Comment by drGrove** [comment]
I just ran through these steps and have a couple of minute changes.

* If you're not using a HTML preprocessor `markups` needs to be replaced with `partials`
* Karma spec reporter is included as a plugin, but not used. See the `karma-spec-reporter` repo for docs if you choose to use it.

I also noticed that the *.spec.js files are being included in coverage on isparta, is there a way to fix this?

**Comment by skeep** [comment]
@drGrove about your comment on spec files getting included, I am aware and till now I have not figured out a way to fix it. Feel free to advice on it if you find a way to fix it, I will update the guide.

**Comment by skeep** [comment]
infact @handijk also mentioned the same.

**Comment by drGrove** [comment]
@skeep also, for `ngHtml2JsPreprocessor`. You currently have oei. Instead could we just pull in the package.json?

```javascript
var pkg = require('package.json')
...
ngHtml2JsPreprocessor: {
      stripPrefix: 'src/',
      moduleName: pkg.name
},
..
```

That way, anyone copy-pasting doesn't have to worry about why all their tests that include HTML suddenly fail. Since by default the package name and module name are the same

**Comment by AlexanderTserkovniy** [comment]
Sorry for disturbing guys, but could you help me? I have been fighting with this unit testing for 3 hours already...
Everything started from that I would like to write tests using ES2015 in my spec.js files and first issue was `Cannot find variable require`, then I went here to this issue and made everything as described by @skeep, but eventually I have got this error:

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: WeakMap
  at /PATH/src/test.js:127
```
(PATH is my path on mac to this file)

Could you help me to fix this?

P.S. I have almost given up...

**Comment by drGrove** [comment]
@AlexanderTserkovniy, can you run
```bash
node -v
```

To use ES6 features without the harmony flag you need to be running at least Node 4. I've been running most of my recent projects using node stable. I recommend using some sort for node version management software. I use `n`. 

```bash
npm install -g n
sudo n stable
# Run this next line in the root of your project
rm -r node_modules && npm install
```

Then your tests should work.

**Comment by AlexanderTserkovniy** [comment]
Hey!

Sure! My node is `v5.4.1`.

And I have tried to remove everything and reinstall, but the same issue here :(

Also I have updated:
```
"babel": "^6.3.26",
"babel-core": "^6.4.5"
```

Some thoughts?

**Comment by drGrove** [comment]
```
"babel-core": "~5.8.25",
"babel-loader": "~5.3.2",
"babel-preset-es2015": "^6.3.13"
```

Is what i'm running

**Comment by AlexanderTserkovniy** [comment]
Set the same as you and the same issue :( I am starting to hate the unit testing setup :(

**Comment by drGrove** [comment]
Can you copy and paste your package.json?

**Comment by AlexanderTserkovniy** [comment]
```
{
  "name": "covers",
  "version": "0.0.0",
  "dependencies": {},
  "scripts": {
    "test": "gulp test"
  },
  "devDependencies": {
    "babel": "^6.3.26",
    "babel-core": "~5.8.25",
    "babel-loader": "~5.3.2",
    "babel-polyfill": "^6.1.19",
    "babel-preset-es2015": "^6.3.13",
    "browser-sync": "~2.7.12",
    "browser-sync-spa": "~1.0.2",
    "chalk": "~1.0.0",
    "concat-stream": "~1.5.0",
    "del": "~1.2.0",
    "gulp": "~3.9.0",
    "gulp-angular-templatecache": "~1.6.0",
    "gulp-autoprefixer": "~2.3.1",
    "gulp-consolidate": "~0.1.2",
    "gulp-csso": "~1.0.0",
    "gulp-filter": "~2.0.2",
    "gulp-flatten": "~0.0.4",
    "gulp-inject": "~1.3.1",
    "gulp-jshint": "~1.11.0",
    "gulp-load-plugins": "~0.10.0",
    "gulp-minify-html": "~1.0.3",
    "gulp-ng-annotate": "~1.0.0",
    "gulp-protractor": "~1.0.0",
    "gulp-rename": "~1.2.2",
    "gulp-replace": "~0.5.3",
    "gulp-rev": "~5.0.0",
    "gulp-rev-replace": "~0.4.2",
    "gulp-size": "~1.2.1",
    "gulp-sourcemaps": "~1.5.2",
    "gulp-stylus": "~2.0.5",
    "gulp-uglify": "~1.2.0",
    "gulp-useref": "~1.2.0",
    "gulp-util": "~3.0.5",
    "gulp-webpack": "~1.5.0",
    "http-proxy-middleware": "~0.0.5",
    "isparta-loader": "^2.0.0",
    "jade": "~1.11.0",
    "jshint-loader": "~0.8.3",
    "jshint-stylish": "~2.0.0",
    "karma": "^0.13.19",
    "karma-babel-preprocessor": "^6.0.1",
    "karma-chrome-launcher": "^0.2.2",
    "karma-coverage": "^0.5.3",
    "karma-jasmine": "~0.3.5",
    "karma-ng-html2js-preprocessor": "~0.1.2",
    "karma-phantomjs-launcher": "~0.2.0",
    "karma-spec-reporter": "0.0.23",
    "karma-webpack": "^1.7.0",
    "lodash": "~3.9.3",
    "main-bower-files": "~2.8.0",
    "merge-stream": "~0.1.7",
    "phantomjs": "^1.9.19",
    "phantomjs-polyfill": "0.0.1",
    "require-dir": "~0.3.0",
    "uglify-save-license": "~0.4.1",
    "webpack": "^1.12.12",
    "wiredep": "~2.2.2",
    "wrench": "~1.5.8"
  },
  "engines": {
    "node": ">=5.0.0"
  }
}
```

**Comment by drGrove** [comment]
Are you using a lot of WeakMaps? Could you try replacing those and see if it fixes it?

**Comment by skeep** [comment]
@drGrove hey thx for catching that. fixing it.

**Comment by skeep** [comment]
BTW I have posted a blog as well, FYI.
https://medium.com/@sumankpaul/test-coverage-report-of-es2015-code-in-gulp-angular-19eeca6efca4#.zb1vhtlap

**Comment by AlexanderTserkovniy** [comment]
@drGrove actually a lot, but I think problem is not in WeakMaps just. As I said there was problem with `require` statement first, I think if I remove all WeakMaps statements then another error would appear, with another ES2015 word. I think it is more generic problem... but I have to fix it, because I need tests :) so I will do my best to find the solution.

**Comment by redskyburning** [comment]
@skeep, I ran through the instruction from your blog post (very nice, thx btw) and everything works great. I did run into the markups vs partials issue the @drGrove mentioned above since i'm not using an html preprocessor, so I would recommend adding that to the final recipe. Otherwise, great work, this will be a great addition once finished.

**Comment by redskyburning** [comment]
One question. After making these changes my output from gulp test got *very* verbose. Resetting the karma log level to 'WARN' helped at lot, but I'm still getting more than I'd like. Any suggestions for how to clean up this:

  [11:24:17] Starting 'test'...
  Hash: 8344a6c0a9b3c44a5636
  Version: webpack 1.12.11
  Time: 4ms
  webpack: bundle is now VALID.
    webpack: bundle is now INVALID.
    Hash: 64fe08bee8ef784583c3
  Version: webpack 1.12.11
  Time: 3584ms
  Asset     Size  Chunks             Chunk Names
  src/test.js  1.22 MB       0  [emitted]  src/test.js
  chunk    {0} src/test.js (src/test.js) 1.21 MB [rendered]
    [0] ./src/test.js 1.52 kB {0} [built]
    [1] ./src/app \.module\.js$ 182 bytes {0} [built]
    [2] ./src/app/index.module.js 13 kB {0} [optional] [built]
    [3] ./src/app/index.config.js 2.19 kB {0} [built]
    [4] ./src/app/index.route.js 6.12 kB {0} [built]
    [5] ./src/app/index.run.js 3.09 kB {0} [built]

**Comment by rgjamkhedkar** [comment]
@skeep very nice solution. Has anybody found a way to exclude .spec files?

**Comment by AlexanderTserkovniy** [comment]
@rgjamkhedkar I have found, but I had to switch to karma 0.13 and other old stuff. Then it started working. Also webpack somehow helped me.

**Comment by AlexanderTserkovniy** [comment]
Here are `package.json` and `karma.conf.js`, which apparently started working.

[Archive.zip](https://github.com/Swiip/generator-gulp-angular/files/177453/Archive.zip)

**Comment by skeep** [comment]
awesome, let me update it accordingly when I get time.

**Comment by skeep** [comment]
@rgjamkhedkar you should try @AlexanderTserkovniy suggestion. One suggestion my coworker gave is to move all tests to a separate test folder, which can work as a interim solution but would defeat the whole module concept.

**Comment by rgjamkhedkar** [comment]
I will try that solution. Otherwise yeah, can move tests to separate folder too.

**Comment by bcg-amitag** [comment]
Hi All, I also facing the problem to generate file wise coverage report. I used @skeep solution and it works fine but I noticed that the *.spec.js files are being included in coverage on isparta, is there a way to fix this? Please suggest any fix for this.

**Comment by skeep** [comment]
@bcg-amitag for now you can move the tests to separate folder. I didn't really found time to fix it right in the config.

**Comment by bcg-amitag** [comment]
@skeep, yes i also tried with the same but facing issues in test.js file since its expect to load unit test specs also. Can you please share me the updated karma.conf.js in case i moves all the test cases under test folder on root. Thanks.

**Comment by rwwagner90** [comment]
Since there are several potential methods for fixing this issue listed here, I am going to close this. Please reopen if work is needed.
