### ISSUE TITLE
Foundation js and css not injected

### ISSUE THREAD

**Issue by Bram77** [Swiip/generator-gulp-angular#878]
I might be completely blind. I've been staring at the code for quite a while but I just can't figure out how I can inject the foundation js and css files. 

I've removed the 'exclude' in grunt/conf.js but that only fixes the injection of the js file since the css file isn't specified in the Foundation bower.json.

In older issues I'm reading about adding foundation @import to the vendor.scss file (I'm using node.js scss), but I don't have a vendor.scss file!

Could someone please point me in the right direction?

**Comment by 0101adm** [comment]
you might have to manually place them in index.html.

**Comment by Bram77** [comment]
I wasn't expecting that, since it's an integral part of the generator. But thank you for clarifying!

**Comment by Swiip** [comment]
If the scss file is specified in the bower.json of Foundation. It should be automatically injected in the index.scss, there is comments in that file to locate the place.

index.scss and vendor.scss have been merged because it causes problem to split the two files.
