### ISSUE TITLE
Bootstrap JS is not included

### ISSUE THREAD

**Issue by alaksandarjesus** [Swiip/generator-gulp-angular#882]
Thanks for saving our time. As i am including jquery i prefer to use bootstrap.js not angular ui-bootstrap on some places. Esp in the navbar menu dropdown.

bootstrap.js is not loaded by default and i included it manually. How can make bootstrap.js loaded by default.

**Comment by ramirescm** [comment]
I have the same problem :(

**Comment by Swiip** [comment]
Did you choose the right options in the generator? The inclusion of the bootstrap.js is prevented (when not needed) by the wiredep exclusion configured in `gulp/conf.js`. By changing this conf, you should be able to auto inject bootstrap.js

**Comment by alaksandarjesus** [comment]
I changed 

exclude:  [/\/bootstrap\.js$/, /\/bootstrap-sass\/.*\.js/, /\/bootstrap\.css/], 
to 

exclude: [],

still no luck in gulp/conf.js

**Comment by Swiip** [comment]
Removing the exclude don't add bootstrap.js in .tmp/serve/index.html after a gulp inject?

If not, check your bower.json to verify you have a dep to bootstrap, and the bower.json of bootstrap in the bower_components folder to check that the bootstrap.js is well in a main property

**Comment by alaksandarjesus** [comment]
I got it. ran bower install bootstrap --save and it worked.

**Comment by igisav** [comment]
Similar issue is #943 

Two steps to do:
1) add a line to your main bower.json as follows:
```
"overrides": {
    "bootstrap-sass": {
      "main": [
        ...
        "assets/javascripts/bootstrap.js",
       ...
      ]
    }
  }
````

2) clear `exports.wiredep.exclude` in gulp/conf.js in order to enable jQuery

**Comment by Martin-Andersen** [comment]
I am having the same problem. the bootstrap bower.json looks fine
`"homepage": "http://getbootstrap.com",
  "license": "MIT",
  "moduleType": "globals",
  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],
`
cleared exports.wiredep.exclude in gulp/conf.js in order to enable jQuery

So why aint it included?
