### ISSUE TITLE
font-awesome not included by default

### ISSUE THREAD

**Issue by alaksandarjesus** [Swiip/generator-gulp-angular#883]
I used bower install font-awesome --save-dev and my font-awesome library is installed. Its not injected by default to the library. 

I even tried changing it from dev-dependencies to dependencies, it not injected.

**Comment by bradleyflood** [comment]
Hey have you read #849 ? Did that help?

**Comment by bradleyflood** [comment]
I just spotted this in the docs: https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/add-fontawesome.md

**Comment by Swiip** [comment]
Documented and no responses...

**Comment by alaksandarjesus** [comment]
I have raised another issue that my build is not working. So I am waiting for a response on that so i could proceed with this.
