### ISSUE TITLE
coffeescript error in index.module.coffee

### ISSUE THREAD

**Issue by alaksandarjesus** [Swiip/generator-gulp-angular#887]
angular.module 'newitpeople', ['ngAnimate', 'ngCookies', 'ngTouch', 'ngSanitize', 'ngMessages', 'ngAria', 'restangular', 'ui.router', 'ui.bootstrap', 'toastr']

The above code fails because of 

index.module.coffee
    line 1  Line exceeds maximum allowed length  Length is 159, max is 150

 1 error

Not sure its builtin error for coffee or within the generator.

**Comment by Swiip** [comment]
Seems that selecting all modules creates a line too long for the coffee lint configuration.

As a workaround, try look at the coffe lint conf or add line breaks.

**Comment by alaksandarjesus** [comment]
I can workaround it with adding another module. Thanks for the time.
