### ISSUE TITLE
Scripts not updating when TypeScript used

### ISSUE THREAD

**Issue by dmitriynosenko** [Swiip/generator-gulp-angular#893]
Hi.
I created a new project using TypeScript.
After run I see message:
> webpack is watching for changes
but once I change any .ts file changes not reflected.
Should I do some additional steps to get it work?

**Comment by dmitriynosenko** [comment]
I added this to watch.js under gulp folder. Seems like all is working but not after auto refresh by browser sync. 
```
gulp.watch(path.join(conf.paths.src, '/app/**/*.ts'), function(event) {
    if(isOnlyChange(event)) {
      gulp.start('scripts');
    } else {
      gulp.start('inject');
    }
  });
```
So maybe I should do other steps?

**Comment by jasteph** [comment]
I'm also having this issue. As a temporary work-around I've switched from using 'awesome-typescript-loader' to 'ts-loader'.

**Comment by dmitriynosenko** [comment]
@jasteph worked for me, but very slow event in empty project.
Seems like there is better solution in #901. 
Thanks everyone!
