### ISSUE TITLE
Additional typescript modules not picked up

### ISSUE THREAD

**Issue by asafper** [Swiip/generator-gulp-angular#894]
Hi,
I tried to add an additional module to the project
but it is not transpiled into the index.module.js file,
resulting in missing module
"Module 'common is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies"

module common {
        angular.module('common',[]);
}

What is the appropriate way to add additional modules ?

Appreciate your help

**Comment by SergiySev** [comment]
add import statement in the index.module.ts, for example:
import '../app/common/file.name.without.ts';
