### ISSUE TITLE
Add scope?

### ISSUE THREAD

**Issue by eigotec** [Swiip/generator-gulp-angular#895]
Hi,

I'm trying to add $scope whilst developing my app. Where is best to put this? I have put it in the controller like I normally do, but this gives errors. I've also seen the modules file and have also added it to the list, but I just get errors saying the module did not load. Any direction would be appreciated. Thanks

**Comment by CarlAmbroselli** [comment]
What is your configuration? 
JavaScript/TypeScript/ES6?

Assuming TypeScript or ES6 you have to put assing it in the constructor:

```
export class Test {

  $scope: ng.IScope;
 
  constructor($scope: ng.IScope) {
    this.$scope = $scope;
  }
```

**Comment by eigotec** [comment]
Thanks for your reply

Using JS.

So i thought it would have been something as simple as 

angular.module([‘$scope’,’$http’],function(scope,http){…}

but i guess its more complicated than that.

Thanks.

**Comment by CarlAmbroselli** [comment]
Scope needs to be injected into the controller, not into the module!

```
angular.module('tutorialApp', [])
 .controller('ArticlesCtrl', function($scope){ 
$scope.article = "Test";
})
```

**Comment by busches** [comment]
This is a basic Angular question and doesn't actually relate the generator itself. I'd recommend reading the [Angular documentation](https://docs.angularjs.org/api) and utilizing the [Angular Google Group](https://groups.google.com/forum/#!forum/angular) for future generic Angular questions.

**Comment by Swiip** [comment]
As @busches says, we can't take angular dev question sorry, refers to the links he gave.
