### ISSUE TITLE
Unit tests running much slower since update

### ISSUE THREAD

**Issue by nanocom** [Swiip/generator-gulp-angular#897]
I just updated my project to use the last gulp config and npm deps, and I noticed my tests run much slower since then (they were executed in less than ~600ms before and now take  ~2.5 seconds). Any ideas on the cause?

**Comment by nanocom** [comment]
The problem doesn't happen all the time...

**Comment by Swiip** [comment]
Do you use `gulp test` or `gulp test:auto`? We added coverage on `gulp test`, it slow down the execution by instrumenting the code. Could be that...

**Comment by nanocom** [comment]
i use both

**Comment by dereklin** [comment]
@Swiip This is not directly related to the topic, but adding the coverage to test:auto can be beneficial, especially for adding tests for legacy apps.  Maybe there can be a new task like test:auto-with-coverage ...

For now, I just comment out the singleRun check:

```
//  if (singleRun) {
    pathSrcJs.forEach(function(path) {
      preprocessors[path] = ['coverage'];
    });
    reporters.push('coverage')
//  }
```

**Comment by nanocom** [comment]
I don't have this issue anymore, the tests run fast again.
