### ISSUE TITLE
Don't update .tmp/serve/app/index.module.js when src/app/index.route.ts change!

### ISSUE THREAD

**Issue by leshin** [Swiip/generator-gulp-angular#900]
I add a new router, but can't access in brower. Only rerun `gulp serve`  to use.

**Comment by leshin** [comment]
Add a new sass file, don't add to `tmp/serve/app/index.css` yet.

**Comment by Swiip** [comment]
Please follow https://github.com/Swiip/generator-gulp-angular/blob/master/CONTRIBUTING.md and a bit more of description would be nice.
