### ISSUE TITLE
Importing css into gulp-angular project

### ISSUE THREAD

**Issue by ObiKerui** [Swiip/generator-gulp-angular#906]
Thanks for creating this generator. 

I need to embed custom sass code into the index.scss file of the gulp-angular project after bootstrap sass but before the changes made by my gulp-angular project. So index.scss  would look like...

----
bootstrap.scss
my custom.scss
my project.scss

-----

When written the custom sass will live in bower_components and be listed as a dependency. 

Index.scss comments say that bower dependencies determine what is injected into index.scss. How does this work exactly? Is this correct....

1) The Styles gulp task looks at each bower_component listed as a dependency and then finds the main block in its bower.json file. 
2) Only if there is a scss file listed in the main block is it injected into Index.scss (css files are ignored).

Is this correct?

**Comment by Swiip** [comment]
Yep, this is correct. The lib we use to do this is https://github.com/taptapship/wiredep.

**Comment by ObiKerui** [comment]
Okay, thanks again!
