### ISSUE TITLE
Index.html triggers reload but changes are not applied

### ISSUE THREAD

**Issue by tscislo** [Swiip/generator-gulp-angular#909]
When I change sth in index.html and launch gulp serve changes are not applied. Tested both on Linux and Windows. To be precise: for example changing page title or adding some external markup.

**Comment by Swiip** [comment]
Seems to me a dup of #660, can you confirm?

**Comment by GitAngel** [comment]
From my point of view it's a duplicate...

**Comment by tscislo** [comment]
Duplicate #660
