### ISSUE TITLE
Allow image minification as an option

### ISSUE THREAD

**Issue by mburbea** [Swiip/generator-gulp-angular#91]
Imagemin has an awful install story for windows users. Especially those running behind corporate proxies. 
Moreover, rarely do I need to minify my image assets. In intranet sites, image size is rarely a concern. To make bootstrapping up projects with this tool much less painful allowing me to say no to the requirement on gulp-imagemin would be absolutely huge.

**Comment by zckrs** [comment]
https://github.com/Swiip/generator-gulp-angular/pull/191 Done
