### ISSUE TITLE
I am using typescript version, How do I use third party js? 

### ISSUE THREAD

**Issue by chojowliu** [Swiip/generator-gulp-angular#910]
I am using typescript version, How do I use third party js? I put it in the index.html page, but that particular js never got picked up. Also is  typescript version come with webpack and es6?

**Comment by Swiip** [comment]
TS option trigger full TS 1.5 code using ES6 modules Webpack and compiled by a typescript loader inside of Webpack.

To install a third party lib, you have to use bower. If you want typings, you have to also use tsd as an external tool.

**Comment by bagusflyer** [comment]
How to use typescript version? Any document about this? Thanks.

**Comment by Swiip** [comment]
@bagusflyer can you explain your question? TS version of what? Of a third party lib? If it's that, I don't know, there is no "only TS library repository" I know of.

**Comment by bagusflyer** [comment]
I knew already. Thanks.
