### ISSUE TITLE
Failed to upgrade generator-gulp-angular

### ISSUE THREAD

**Issue by zhouhao27** [Swiip/generator-gulp-angular#916]
I got the following error when I run **sudo nam i -g generator-gulp-angular**:

> npm WARN EPEERINVALID generator-gulp-angular@1.0.0 requires a peer of yo@>=1.0.0 but none was installed.
> npm ERR! code 1

The version of my yo is the latest 1.5.0. What's could be wrong? Thanks.

**Comment by Swiip** [comment]
This warn is not relevant and the peer dep has been removed in the master. Are you sure the install actually broke?

**Comment by zckrs** [comment]
Already fixed https://github.com/Swiip/generator-gulp-angular/pull/873
Present in the next release
