### ISSUE TITLE
Run without examples

### ISSUE THREAD

**Issue by DaAwesomeP** [Swiip/generator-gulp-angular#917]
Hi,
I use this generator very often now and have really come to love it. It saves *so* much time. However, is it possible to turn off the example code? It was useful when I first started using the generator, but now it's a burden. I'd be happy to implement such a feature if it's not already possible.

Thanks.

**Comment by Swiip** [comment]
Is it so much of a burden to just delete the src folder after generation? It's a really open question, you can have feedbacks on such a process and found some configuration failing. It could be an option but as always, it's a lot of ifs and this needs to have a real value.

**Comment by DaAwesomeP** [comment]
The problem with deleting the `src` folder is that then you lose the structure created there, which is one of the purposes of using such a generator. It would be possible to create a `_blank...` file for each one in the src template folder, but that wouldn't be very efficient. I guess that I'll just have to wait for #793, which will replace the current system of adding in the files.
