### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by 0101adm** [Swiip/generator-gulp-angular#921]
node 5.1.0
npm 3.3.12
yo 1.5.0

cannot install either by npm or using the yo's interface.

am able to install other generators w/o incident.

was using v1.  then updated node/npm before trying to install v1.1.  can anyone else recreate this?

**Comment by 0101adm** [comment]
installing via yo's interface, doesnt show the generator once the install completes...

![screen shot 2015-11-23 at 2 16 49 pm](https://cloud.githubusercontent.com/assets/5133412/11350085/0b9d6a40-91ed-11e5-9c90-bd03f3555f98.png)

**Comment by 0101adm** [comment]
installing via NPM then running yo, doesnt show the generator.

![screen shot 2015-11-23 at 2 18 31 pm](https://cloud.githubusercontent.com/assets/5133412/11350108/269f94e4-91ed-11e5-8b20-e779dfc40058.png)

**Comment by scttcper** [comment]
same as issue #920

**Comment by zckrs** [comment]
Released 1.0.2 who fixed issue
