### ISSUE TITLE
Generator not found by Yeoman

### ISSUE THREAD

**Issue by semeano** [Swiip/generator-gulp-angular#923]
I have two generators installed:
- gulp-angular
- webapp

Webapp appears on yo menu, but not gulp-angular.

https://www.dropbox.com/s/9jca4n41ci126fw/Screenshot%202015-11-24%2011.58.43.png?dl=0

**Comment by zckrs** [comment]
Just release a new version 1.0.2 who should fixed :pray:

**Comment by semeano** [comment]
It is fixed! Thanks a lot! ;)
