### ISSUE TITLE
compiling _xxx.scss file also in src folder

### ISSUE THREAD

**Issue by ansumanshah** [Swiip/generator-gulp-angular#927]
It should only compile xxx.scss files.
Where should we place the _xxx.scss files and import them.
Should I keep the _ files outside the app folder??
Remove the issue if there is already a recipe for this.

**Comment by Swiip** [comment]
I'm not a big user of sass. I'm not sure the current configuration is perfect. The inject will take every scss files whatever there is a _ or not at the beginning.

If it's a common use to have _ on files you want to include, we could just filter the files not to be injected. Or at least, you can do it in your project.

It takes place in this selector: https://github.com/Swiip/generator-gulp-angular/blob/master/generators/app/templates/gulp/_styles.js#L38

**Comment by ansumanshah** [comment]
ohh so i think adding this will work fine for my project??
path.join('!' + conf.paths.src, '/app/**/_*.scss'),

cool thanks !!

**Comment by mnzaki** [comment]
For future reference, remember to leave `_*.scss` files in the watch expression though, or your styles won't rebuild when an `_*.scss` file changes.

also shouldn't this be closed?

**Comment by Swiip** [comment]
This could be closed yes. I keep a recipe label on it to create a reference in the docs. I wonder if it can be a default configuration as it seems that using _ as prefix for scss file is a common use.
