### ISSUE TITLE
too many errors on gulp serve

### ISSUE THREAD

**Issue by mutumarieru** [Swiip/generator-gulp-angular#929]
hi,

is there a way to deactivate the JS LINT on the generator because it seems to generate too many errors.

for each console.log or use of "this" in a Controller, i get an error it's pretty much breaking my development process.

the most blocking error is "mixes tabs and spaces" which occures often because my collaborators don't use the same IDEA as me (mine uses tabs, there's spaces)

**Comment by Swiip** [comment]
I greatly encourage you to fix the real problem, and not muting the linter, like mixing spaces and tabs are really a mess.

Anyway, you can tune the linter in `.eslintrc` (it's eslint, not jslint) choosing the rules you want. Or completely remove it in `gulp/scipts.js` by removing the lines about eslint.

**Comment by mutumarieru** [comment]
well it's not the only problem : mixed spaces and tabs are a little problem can't be overcome everytime when there are differents environnement.

Anyway eslint shouts too many strict errors : console.log use, and the angular on top of it really breaks many things (possibility to use global variables etc)

thanks for the answer

**Comment by gameboyzone** [comment]
@Swiip - Thanks, your suggestion helped.
