### ISSUE TITLE
angular2

### ISSUE THREAD

**Issue by schacki** [Swiip/generator-gulp-angular#938]
Are there any plans to migrate to angular2?

**Comment by Swiip** [comment]
A big refactoring is planned for a v2 which will address Angular2 and React but nothing is will happen in the v1.

**Comment by schacki** [comment]
This sounds great. Do you already have an idea on the timing?

**Comment by Swiip** [comment]
I'm in the middle of prototyping the whole thing with @zckrs. Perhaps some kind of beta in spring?

**Comment by mohsen1** [comment]
React? Then you need to rename this. I've been using this generator a lot lately. Thanks for this, it's great! 
I'm available for beta testing if you need one.

**Comment by zckrs** [comment]
The next awesome version start here 


https://github.com/FountainJS/generator-fountain-webapp/blob/master/README.md

**Comment by dancancro** [comment]
@zckrs Do you want to add the new version to [this](http://www.dancancro.com/compare-app-technologies/)?

**Comment by pablorsk** [comment]
Anyone try use (ng-forward)[https://github.com/ngUpgraders/ng-forward] with this generator? It seems to be an elegant solution to get ready for angular2.
