### ISSUE TITLE
Changes to .ts files not compiled

### ISSUE THREAD

**Issue by craigsh** [Swiip/generator-gulp-angular#940]
I'm a complete newbie at this but have run up the generator to build an app using TypeScript.

I have it up and running using gulp serve and the app opens in my browser. I can make changes to .html files, save and BrowserSync refreshes the page and I see my changes.

But, if I make changes to .ts files and save, BrowserSync refreshes the page but my changes haven't made it.

There's something wrong with the gulp configuration, it would seem, but any hints on how to fix this would be appreciated.

**Comment by busches** [comment]
Are you on Windows? If so see #901 and #893

**Comment by craigsh** [comment]
Yes, on Windows. Thanks for the pointers - I'll look at those - likely they will fix my issue.

**Comment by Swiip** [comment]
That should be fixed with the switch on ts-loader in the last release: https://github.com/Swiip/generator-gulp-angular/releases/tag/v1.1.0
