### ISSUE TITLE
Adapting injected files to django

### ISSUE THREAD

**Issue by mateuo** [Swiip/generator-gulp-angular#944]
Hi,

First of all your tool is awesome .
I'm new using gulp and I try to modify inject.js for adapt the way django framework serves this files. So I need to change the typical src="scripts/vendor-xx.js" and href="styles/vendor-xx.css"  in the dist/index.html and the related files for something like that:
 src='{%static "scripts/vendor-xx.js" %}'
href='{%static "styles/vendor-c2769e81fe.css" %}'

I've tryed modifying the transform in some places in the file like that:
var injectScripts = gulp.src([
    path.join(conf.paths.src, '/app/**/*.module.js'),
    path.join(conf.paths.src, '/app/**/*.js'),
    path.join('!' + conf.paths.src, '/app/**/*.spec.js'),
    path.join('!' + conf.paths.src, '/app/**/*.mock.js'),
    path.join(conf.paths.tmp, '/serve/app/**/*.module.js'),
    path.join(conf.paths.tmp, '/serve/app/**/*.js'),
    path.join('!' + conf.paths.tmp, '/serve/app/**/*.spec.js'),
    path.join('!' + conf.paths.tmp, '/serve/app/**/*.mock.js')
  ],{ read: false}, {
      transform: function (filepath) {

          return '{% static "' + filepath + '" %}';

      }
  })
  .pipe($.angularFilesort()).on('error', conf.errorHandler('AngularFilesort'));
But it's not working.
Thank you for your help

**Comment by mateuo** [comment]
I have find a non elegant solution. 
That is:
Create a file django.js in the gulp directori
the content of this file is:
```javascript
var gulp = require('gulp');
var path = require('path');
var conf = require('./conf');
var replace = require('gulp-replace');

gulp.task('django', function(){
  gulp.src(['dist/index.html'])
    .pipe(replace('src="scripts', 'src="{% static "scripts'))
    .pipe(replace('.js"','.js" %}"'))
    .pipe(replace('href="styles','href="{% static "styles'))
    .pipe(replace('.css"','.css" %}"'))
    .pipe(gulp.dest(path.join(conf.paths.dist, '/')));

});
```
and execute it with "gulp django" this changes the references of static files.
I think this will work

**Comment by Swiip** [comment]
Cool you make this working. I honestly don't see a really better solution. We use plugins like gulp-useref and gulp-revReplace to update the paths, I doubt it's possible de to make them write non valid paths. I think your solution is the best you can do.

**Comment by lahdo** [comment]
This is how you can do that in more clean way:  


```
gulp.task('inject', function () {
    log('Wiring the bower dependencies into the html');
    log('Paths will be save here: ' + config.index);

  var options = {
        read: false,
        addRootSlash: false,
        transform: function (filepath) {
            return '<script src="{% static "' + filepath + '" %}"></script>';
        }
    };

    // Only include stubs if flag is enabled
    var js = args.stubs ? [].concat(config.js, config.stubsjs) : config.js;

    return gulp
        .src(config.index)
        .pipe($.inject(js, options))
        .pipe(gulp.dest(config.django_templates));
});
```
