### ISSUE TITLE
Angular 1.5

### ISSUE THREAD

**Issue by JoshuaAdamYoung** [Swiip/generator-gulp-angular#961]
Is updating the generator to include 1.5 on the table? Or is this generator going to shift directly to 2.0?

**Comment by codeofsumit** [comment]
IMO a 2.0 generator should be a fork of this. The Angular 1.x ecosystem is way to big. Serious production apps will still use 1.x for the time being.

Updating to angular 1.5 should be easy with bower, even if this generator isn't including it by default.

**Comment by busches** [comment]
FYI they are already working on the 2.0 generator - https://github.com/FountainJS/generator-fountain-webapp

**Comment by codeofsumit** [comment]
👍

**Comment by opadilla** [comment]
@codeofsumit , upgrading to angular 1.5 isn't simply a matter of updating with bower if you make use of angular.component, which is the replacement for angular.directive and the main reason for upgrading to angular 1.5.
The current generator, v1.0.2, isn't putting component templates in the template cache in the dist like it does for directives, so when I do a gulp dist none of my angular.components are working.

**Comment by codeofsumit** [comment]
@opadilla I understand. I was thinking more about updating to angular 1.5 via bower in existing projects while still using `.directive` and just enjoy the minor improvements (if there are any) that don't need build changes.
You're right of course.

**Comment by Swiip** [comment]
Angular 1.5 is supported by the new release: https://github.com/Swiip/generator-gulp-angular/releases/tag/v1.1.0.

But it's only the deps, we don't use the component API. The problem is that we support the legacy 1.2 version and we would have to make two version of the code. Any PR this way would be appreciated, until that, we continue like that.

**Comment by busches** [comment]
Wouldn't you be able to include [angular-component](https://www.npmjs.com/package/angular-component) for non 1.5 installations and use that polyfill?

**Comment by Swiip** [comment]
That could be a trick. I'm open to PR like this. But it will not come from me as I'm focused on Fountain
