### ISSUE TITLE
Using gulp angular with Internet explorer 9 and more

### ISSUE THREAD

**Issue by Skahrz** [Swiip/generator-gulp-angular#968]
I m having some trouble using the default config of gulp-angular generator.

I m having an error like the following one :

```
Symbol is undefined
```

It seems that internet explorer isn't able to manage Symbol and I don't know how to face the problem.

Can you help me ?

I use the default configuration given by the generator when installing, no modifications inside of it.

EDIT : here's a piece of my webpack config

```
{
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        presets:['es2015']
      }

```

**Comment by wonsikin** [comment]
1. Install `babel-polyfill`;
2. Import it at the top of your application entry point.

[More information](http://babeljs.io/docs/usage/polyfill/)
