### ISSUE TITLE
Template for UI Modal found in serve but not after build

### ISSUE THREAD

**Issue by m1rc0** [Swiip/generator-gulp-angular#970]
Hi there,

I've a strange problem. I've pointed to a modal's template like the following:
   templateUrl: '/app/subfolder/myModalContent.html',

Now after build I get the following error:
   Error: [$compile:tpload] Failed to load template: /app/subfolder/myModalContent.html (HTTP status:      undefined undefined)

I would be very grateful for any hints.

Thank you very much

**Comment by busches** [comment]
You're missing the period for the html extension.

**Comment by m1rc0** [comment]
It it was so simple. No, the period is there and it works while serving but not after build.

**Comment by m1rc0** [comment]
Solved it...as I said, stupid. ;) 
TemplateUrl should not start with a slash.
templateUrl: 'app/subfolder/myModalContent.html',
