### ISSUE TITLE
Gulp Error

### ISSUE THREAD

**Issue by ebowers** [Swiip/generator-gulp-angular#975]
Hi there,

I just recently downloaded your generator. I ran both the `gulp` & `gulp build` commands and got the error below...

```javascript
[12:37:46] Starting 'html'...
[12:37:47] gulp-inject 1 files into index.html.
[12:37:47] dist/ maps/styles/app-01e1301bfb.css.map 44.96 kB
[12:37:47] dist/ maps/styles/vendor-c2769e81fe.css.map 24.82 kB
[12:37:48] dist/ maps/scripts/app-cff2a5d474.js.map 14.7 kB
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: scripts/vendor-d61af25e2f.js: error: couldn't process source due to parse error
Unexpected token (58791:4)
```

When I ran the `gulp serve` command however, I got a blank BrowserSync page with no content being loaded into it.

Any ideas of what may be going on?

Thanks!

**Comment by busches** [comment]
Looks like one of the bower components has a JS error in it, since the error is being thrown in `vendor.js`

**Comment by ebowers** [comment]
yep, narrowed it down to this plugin fyi.
angular-messages.js
