### ISSUE TITLE
Including processed file

### ISSUE THREAD

**Issue by eshansingh** [Swiip/generator-gulp-angular#985]
When using a preprocessor for any given language (jade, sass, coffeescript, etc). is there a way to reference their corresponding processed files? For example, when I'm configuring my routes, how do I refer to my `.jade` files to load? Or, let's say I have some Sass for my directive, how do I refer to it in a `<link>` tag? I'm sure there's a way to do this, I just can't find it documented.

Thanks for any help!

**Comment by eshansingh** [comment]
According to the user guide, processed files should be included in the same place but with a different file extension. However, when I created a new test project and enabled Jade, and replaced `src/app/main/main.html` with `src/app/main/main.jade`, it didn't work.

**Comment by lokeshjain2008** [comment]
same problem. This should not be that hard. Anyone know how to use `.jade` in the templateUrl string?

**Comment by eshansingh** [comment]
This has been open for 3 months. A lot of other issues are also long overdue. This project is probably dead.

**Comment by lokeshjain2008** [comment]
@eshansingh This is working for me i started project from scratch using `yo gulp-angular`.
said yes for `jade` template. 
used 
`templateUrl: 'app/main/main.html',`
but actual file should be
`app/main/main.jade`.
Hope, this works for you.
