### ISSUE TITLE
The version of Angular Material used is **really** old.

### ISSUE THREAD

**Issue by eshansingh** [Swiip/generator-gulp-angular#987]
The current version of the Angular Material library is `1.0.3`. By default, the `bower.json` generated when Angular Material is included specifies `~0.11.3` as the version. When I updated it manually (by changing and running `bower update`), nothing breaked except some stuff from my own code. So please consider bumping up the version.

**Comment by Phisherman** [comment]
It's not only Angular Material. There are plenty of obsolete versions used.

**Comment by eshansingh** [comment]
Lodash, for example.

**Comment by zckrs** [comment]
Pull request are welcome.

**Comment by eshansingh** [comment]
I'll make one tomorrow.

**Comment by alangunning** [comment]
+1

**Comment by designnotdrum** [comment]
solved by #899
