### ISSUE TITLE
foundation.js not injecting

### ISSUE THREAD

**Issue by crdil** [Swiip/generator-gulp-angular#994]
I've generated a project with Foundation+Angular . The CSS files from Foundation is injected, but the foundation.min.js or foundation.js is not injected, how can I solve this so it will be injected in the right order?

**Comment by Swiip** [comment]
It depends if you chose angular foundation or not. If yes, there should be an exclusion in conf.js for foundation.js as angular foundation replace it. If not, it should be there. Can you give us more input?
