### ISSUE TITLE
Use foundation 6 / foundation-sites

### ISSUE THREAD

**Issue by getglad** [Swiip/generator-gulp-angular#999]
Foundation has moved to https://github.com/zurb/foundation-sites for Foundation 6.

It may be worth updating this project to get the new version.

Also, how can an existing project replace/update Foundation versions?

**Comment by Swiip** [comment]
Yep, the foundation dep should be updated but it could be a lot of work, any help appreciated.

If you want to update the version in your project, just use Bower to update the dep.

**Comment by getglad** [comment]
When I use bower to uninstall foundation and install foundation-sites, foundation-sites does not load. I can add it to the index.html page for now, but not sure why nothing loads in.

Also, I'm happy to help on updating the foundation dep. Can you give me some places to start? Do you mean you need to update the generator/recipes? https://github.com/Swiip/generator-gulp-angular/search?utf8=%E2%9C%93&q=foundation

**Comment by Swiip** [comment]
Thanks to propose your help. Best way to work on this is to update first foundation on your project and make it works. Then try to apply the changes in the different template of the files you changed.

**Comment by getglad** [comment]
Okay - I made a PR that contains the changes I had to make to the template.

https://github.com/getglad/generator-gulp-angular/commit/2eca590f49a514898effc6656a1c6fa7741b7e46

Also need to change the bower reference, they have moved it to `foundation-sites`, but I wasn't entirely sure where you were setting that.

**Comment by Swiip** [comment]
Thanks again, merged now:  https://github.com/Swiip/generator-gulp-angular/releases/tag/v1.1.0

**Comment by getglad** [comment]
NP - this tool has helped me a ton, so if I can help on other Angular / Foundation stuff, just let me know
